CREATE OR REPLACE VIEW R7506V00 (T21_COD_CONT_SOLI, T21_COD_SOLICITANTE, T21_DNI, DENOMINACION, T21_DPTO, T21_DOMICILIO, T21_MUN_MUNI, T21_MUN_PROV, T21_COD_POSTAL)
AS
  select ROW_NUMBER() OVER (PARTITION BY COD_ENTIDAD ORDER BY DNI desc), COD_ENTIDAD, nvl(PREDNI,'')|| DNI || nvl(SUFDNI,''), NOMBRE || ' ' || APEL1 || ' ' || APEL2, '', null, null, null, null from x54japi_solicitantes
  WHERE ESTADO = 'V'