CREATE OR REPLACE VIEW R7505V00 (T19_COD_SOLICITANTE, T19_TIPO_CIF_NIF, T19_CIF_NIF, DENOMINACION, T19_DOMICILIO, T19_MUN_MUNI, T19_MUN_PROV, T19_COD_POSTAL)
AS
   Select CODIGO, TIPO, CIF, DESC_AMP_EU, null, null, null, null
  from  X54JAPI_entidades_solic
  WHERE ESTADO = 'A'