package aa79b.util.common;

import java.io.Serializable;

/**
 *
 * @author grozadilla
 *
 */
public enum TipoAvisoEnum implements Serializable {
	MODIF_CALENDARIO(1), RECHAZADO_EXP(2), REQ_SUBSANACION(3), EXP_PLAZO_REQ(4), ASIGNAR_TAREA(5),
	REASIGNAR_TAREAS(6), ELIMINAR_TAREAS(7), MODIFICAR_DATOS_TAREA(8), ASIGNAR_TAREA_PROVEEDOR(9), DOCUMENTACION_TAREAS(10),
	RECHAZO_ASIGNACION_TAREAS(11), FINALIZACION_TAREAS_DEPENDIENTES(12), NO_CONFORMIDAD_RECHAZADA(13),  REQ_PRESUPUESTO(14),
	REQ_FECHA_ENTREGA(15), REQ_PRESUPUESTO_FECHA_ENTREGA(16), NO_CONFORMIDAD_PROVEEDOR(17),ENTREGA_DOCUMENTOS_FINALES(18),
	ELIMINAR_TAREAS_PROVEEDOR(19), REQUERIMIENTO_REALIZADO(20),REAPERTURA_TAREA(21),REAPERTURA_TAREA_EXTERNA(22),
	FINALIZACION_TAREA_PROVEEDOR(23), MODIFICAR_DATOS_TAREA_EXTERNA(24), ANULADO_EXP(25), ENVIO_ALBARAN(26), APERTURA_OFICIO(27),
	PETICION_AUSENCIA(28), NOTIFICACION_CORRECCION_PROVEEDOR(29), REVISION_DATOS_PAGO(30), AUDITORIA_ENVIADA(31), AUDITORIA_CONFIRMADA(32),
	AUDITORIAS_PENDIENTES_DE_ENVIAR(33), AUDITORIAS_PENDIENTES_DE_CONFIRMAR(34);

	private int value;

	private TipoAvisoEnum(int value) {
		this.value = value;
	}

	public int getValue() {
		return this.value;
	}

}