/*
* Copyright 2024 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/
package com.ejie.x21a.model;

 import java.math.BigDecimal;


/**
 * Areas Model generated by UDA", 22-Nov-2024 09:53:52.
 * @author UDA
 */
 
public class Areas  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  

   private String areaActivaT21;
   private BigDecimal idAreaT21;
   private String idLote3T21;
   private String nombreAreaCastT21;
   private String nombreAreaEuskT21;

 /** 
 * Method 'Areas'.
 */
 public Areas() {
  }

 /** 
 * Method 'Areas'.
 * @param idAreaT21
 *
 */    
 public Areas(BigDecimal idAreaT21) {
	this.idAreaT21 = idAreaT21;
  
 }
 



 /** 
 * Method aa 'Areas'.
 * @param idAreaT21
 * @param areaActivaT21
 * @param idLote3T21
 * @param nombreAreaCastT21
 * @param nombreAreaEuskT21
 *
 */    
 public Areas(BigDecimal idAreaT21, String areaActivaT21, String idLote3T21, String nombreAreaCastT21, String nombreAreaEuskT21) {
	this.idAreaT21 = idAreaT21;
  this.areaActivaT21 = areaActivaT21;
  this.idLote3T21 = idLote3T21;
  this.nombreAreaCastT21 = nombreAreaCastT21;
  this.nombreAreaEuskT21 = nombreAreaEuskT21;
  
 }

 
 	/**
     * Method 'getIdAreaT21'.
     *
     * @return BigDecimal
     */
	
	
	public BigDecimal getIdAreaT21() {
		return this.idAreaT21;
	}
	
	/**
	 * Method 'setIdAreaT21'.
	 *
	 * @param IdAreaT21 BigDecimal
	 * @return
	 */
	
	public void setIdAreaT21(BigDecimal idAreaT21) {
		this.idAreaT21 = idAreaT21;
	}
 
 	/**
     * Method 'getAreaActivaT21'.
     *
     * @return String
     */
	
	
	public String getAreaActivaT21() {
		return this.areaActivaT21;
	}
	
	/**
	 * Method 'setAreaActivaT21'.
	 *
	 * @param AreaActivaT21 String
	 * @return
	 */
	
	public void setAreaActivaT21(String areaActivaT21) {
		this.areaActivaT21 = areaActivaT21;
	}
 
 	/**
     * Method 'getIdLote3T21'.
     *
     * @return String
     */
	
	
	public String getIdLote3T21() {
		return this.idLote3T21;
	}
	
	/**
	 * Method 'setIdLote3T21'.
	 *
	 * @param IdLote3T21 String
	 * @return
	 */
	
	public void setIdLote3T21(String idLote3T21) {
		this.idLote3T21 = idLote3T21;
	}
 
 	/**
     * Method 'getNombreAreaCastT21'.
     *
     * @return String
     */
	
	
	public String getNombreAreaCastT21() {
		return this.nombreAreaCastT21;
	}
	
	/**
	 * Method 'setNombreAreaCastT21'.
	 *
	 * @param NombreAreaCastT21 String
	 * @return
	 */
	
	public void setNombreAreaCastT21(String nombreAreaCastT21) {
		this.nombreAreaCastT21 = nombreAreaCastT21;
	}
 
 	/**
     * Method 'getNombreAreaEuskT21'.
     *
     * @return String
     */
	
	
	public String getNombreAreaEuskT21() {
		return this.nombreAreaEuskT21;
	}
	
	/**
	 * Method 'setNombreAreaEuskT21'.
	 *
	 * @param NombreAreaEuskT21 String
	 * @return
	 */
	
	public void setNombreAreaEuskT21(String nombreAreaEuskT21) {
		this.nombreAreaEuskT21 = nombreAreaEuskT21;
	}
 

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
  
		result.append(" [ idAreaT21: ").append(this.idAreaT21).append(" ]");	
  
		result.append(", [ areaActivaT21: ").append(this.areaActivaT21).append(" ]");	
  
		result.append(", [ idLote3T21: ").append(this.idLote3T21).append(" ]");	
  
		result.append(", [ nombreAreaCastT21: ").append(this.nombreAreaCastT21).append(" ]");	
  
		result.append(", [ nombreAreaEuskT21: ").append(this.nombreAreaEuskT21).append(" ]");	
 
		result.append("}");
		return result.toString();
	}


}
