/*
* Copyright 2012 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/

package com.ejie.x21a.model;


import java.math.BigDecimal;
import java.sql.Clob;
import java.sql.Timestamp;
import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonDeserialize;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.ejie.x38.control.JsonDateDeserializer;
import com.ejie.x38.control.JsonDateSerializer;
import com.ejie.x38.control.JsonDateTimeDeserializer;
import com.ejie.x38.control.JsonDateTimeSerializer;
import com.ejie.x38.control.JsonTimeDeserializer;
import com.ejie.x38.control.JsonTimeSerializer;

/**
 *  * PerfilUsuario generated by UDA, 14-nov-2011 9:41:52.
 * @author UDA
 */

public class PerfilUsuario  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
            private BigDecimal id;
            private Usuario usuario;
            private Localidad localidad;
            private Comarca comarca;
            private Provincia provincia;
            private String userId;
            private String pass;
            private String activo;
            private String tipo;
            private Clob descripcion;
            private Timestamp fechaAlta;
            private Date fechaBaja;
            private Timestamp horaEntrada;

	/** Method 'PerfilUsuario'.
	*
	*/
    public PerfilUsuario() {
    }

    /** Method 'PerfilUsuario'.
    * @param id BigDecimal
    * @param userId String
    * @param pass String
    * @param activo String
    * @param tipo String
    * @param descripcion Clob
    * @param fechaAlta Timestamp
    * @param fechaBaja Date
    * @param horaEntrada Timestamp
    * @param usuario Usuario
    * @param localidad Localidad
    * @param comarca Comarca
    * @param provincia Provincia
    */
   public PerfilUsuario(BigDecimal id, String userId, String pass, String activo, String tipo, Clob descripcion, Timestamp fechaAlta, Date fechaBaja, Timestamp horaEntrada, Usuario usuario, Localidad localidad, Comarca comarca, Provincia provincia) {	

           this.id = id;
           this.usuario = usuario;
           this.localidad = localidad;
           this.comarca = comarca;
           this.provincia = provincia;
           this.userId = userId;
           this.pass = pass;
           this.activo = activo;
           this.tipo = tipo;
           this.descripcion = descripcion;
           this.fechaAlta = fechaAlta;
           this.fechaBaja = fechaBaja;
           this.horaEntrada = horaEntrada;
    }

    /**
	 * Method 'getId'.
	 *
	 * @return BigDecimal
	 */
	
	
	public BigDecimal getId() {
		return this.id;
	}

	/**
	 * Method 'setId'.
	 *
	 * @param id BigDecimal
	 * @return
     */
	
	public void setId(BigDecimal id) {
		this.id = id;
	}
    /**
	 * Method 'getUsuario'.
	 *
	 * @return Usuario
	 */
	public Usuario getUsuario() {
		return this.usuario;
	}

	/**
	 * Method 'setUsuario'.
	 *
	 * @param usuario Usuario
	 * @return
     */
	
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
    /**
	 * Method 'getLocalidad'.
	 *
	 * @return Localidad
	 */
	
	public Localidad getLocalidad() {
		return this.localidad;
	}

	/**
	 * Method 'setLocalidad'.
	 *
	 * @param localidad Localidad
	 * @return
     */
	
	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}
    /**
	 * Method 'getComarca'.
	 *
	 * @return Comarca
	 */
	
	public Comarca getComarca() {
		return this.comarca;
	}

	/**
	 * Method 'setComarca'.
	 *
	 * @param comarca Comarca
	 * @return
     */
	
	public void setComarca(Comarca comarca) {
		this.comarca = comarca;
	}
    /**
	 * Method 'getProvincia'.
	 *
	 * @return Provincia
	 */
	public Provincia getProvincia() {
		return this.provincia;
	}

	/**
	 * Method 'setProvincia'.
	 *
	 * @param provincia Provincia
	 * @return
     */
	
	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}
    /**
	 * Method 'getUserId'.
	 *
	 * @return String
	 */
	
	
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Method 'setUserId'.
	 *
	 * @param userId String
	 * @return
     */
	
	public void setUserId(String userId) {
		this.userId = userId;
	}
    /**
	 * Method 'getPass'.
	 *
	 * @return String
	 */
	
	
	public String getPass() {
		return this.pass;
	}

	/**
	 * Method 'setPass'.
	 *
	 * @param pass String
	 * @return
     */
	
	public void setPass(String pass) {
		this.pass = pass;
	}
    /**
	 * Method 'getActivo'.
	 *
	 * @return String
	 */
	
	
	public String getActivo() {
		return this.activo;
	}

	/**
	 * Method 'setActivo'.
	 *
	 * @param activo String
	 * @return
     */
	
	public void setActivo(String activo) {
		this.activo = activo;
	}
    /**
	 * Method 'getTipo'.
	 *
	 * @return String
	 */
	
	
	public String getTipo() {
		return this.tipo;
	}

	/**
	 * Method 'setTipo'.
	 *
	 * @param tipo String
	 * @return
     */
	
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
    /**
	 * Method 'getDescripcion'.
	 *
	 * @return Clob
	 */
	@JsonIgnore
	public Clob getDescripcion() {
		return this.descripcion;
	}

	/**
	 * Method 'setDescripcion'.
	 *
	 * @param descripcion Clob
	 * @return
     */
	
	public void setDescripcion(Clob descripcion) {
		this.descripcion = descripcion;
	}
    /**
	 * Method 'getFechaAlta'.
	 *
	 * @return Timestamp
	 */
	
	@JsonSerialize(using = JsonDateTimeSerializer.class)
	public Timestamp getFechaAlta() {
		return this.fechaAlta;
	}

	/**
	 * Method 'setFechaAlta'.
	 *
	 * @param fechaAlta Timestamp
	 * @return
     */
	@JsonDeserialize(using = JsonDateTimeDeserializer.class)
	public void setFechaAlta(Timestamp fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
    /**
	 * Method 'getFechaBaja'.
	 *
	 * @return Date
	 */
	
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	/**
	 * Method 'setFechaBaja'.
	 *
	 * @param fechaBaja Date
	 * @return
     */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}
    /**
	 * Method 'getHoraEntrada'.
	 *
	 * @return Timestamp
	 */
	
	@JsonSerialize(using = JsonTimeSerializer.class)
	public Timestamp getHoraEntrada() {
		return this.horaEntrada;
	}

	/**
	 * Method 'setHoraEntrada'.
	 *
	 * @param horaEntrada Timestamp
	 * @return
     */
	@JsonDeserialize(using = JsonTimeDeserializer.class)
	public void setHoraEntrada(Timestamp horaEntrada) {
		this.horaEntrada = horaEntrada;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		result.append(" [ id: ").append(this.id).append(" ]");
		result.append(", [ userId: ").append(this.userId).append(" ]");
		result.append(", [ pass: ").append(this.pass).append(" ]");
		result.append(", [ activo: ").append(this.activo).append(" ]");
		result.append(", [ tipo: ").append(this.tipo).append(" ]");
		result.append(", [ fechaAlta: ").append(this.fechaAlta).append(" ]");
		result.append(", [ fechaBaja: ").append(this.fechaBaja).append(" ]");
		result.append(", [ horaEntrada: ").append(this.horaEntrada).append(" ]");
		result.append("}");
		return result.toString();
	}


}
