package com.ejie.x21a.model;

import org.hdiv.services.SecureIdentifiable;

import com.ejie.x38.serialization.JsonDateDeserializer;
import com.ejie.x38.serialization.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Date;

/**
 * UsuarioJerarquia generated by UDA, 03-oct-2012 10:36:40.
 * @author UDA
 */

public class UsuarioJerarquia implements java.io.Serializable, SecureIdentifiable<String> {

	private static final long serialVersionUID = 1L;
	private String id;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String ejie;
	private Date fechaAlta;
	private Date fechaBaja;
	private String idPadre;
	private String grupo;

	/** 
	 * Method 'UsuarioJerarquia'.
	 */
    public UsuarioJerarquia() {
    }

    /** 
     * Method 'UsuarioJerarquia'.
     * @param id String
     * @param nombre String
     * @param apellido1 String
     * @param apellido2 String
     * @param ejie String
     * @param fechaAlta Date
     * @param fechaBaja Date
     * @param idPadre String
     * @param grupo String
     */
   public UsuarioJerarquia(String id, String nombre, String apellido1, String apellido2, String ejie, Date fechaAlta, Date fechaBaja, String idPadre, String grupo) {	

           this.id = id;
           this.nombre = nombre;
           this.apellido1 = apellido1;
           this.apellido2 = apellido2;
           this.ejie = ejie;
           this.fechaAlta = fechaAlta;
           this.fechaBaja = fechaBaja;
           this.idPadre = idPadre;
           this.grupo = grupo;
    }

    /**
	 * Method 'getId'.
	 *
	 * @return String
	 */
	
	
	public String getId() {
		return this.id;
	}

	/**
	 * Method 'setId'.
	 *
	 * @param id String
	 * @return
     */
	
	public void setId(String id) {
		this.id = id;
	}
    /**
	 * Method 'getNombre'.
	 *
	 * @return String
	 */
	
	
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Method 'setNombre'.
	 *
	 * @param nombre String
	 * @return
     */
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
    /**
	 * Method 'getApellido1'.
	 *
	 * @return String
	 */
	
	
	public String getApellido1() {
		return this.apellido1;
	}

	/**
	 * Method 'setApellido1'.
	 *
	 * @param apellido1 String
	 * @return
     */
	
	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}
    /**
	 * Method 'getApellido2'.
	 *
	 * @return String
	 */
	
	
	public String getApellido2() {
		return this.apellido2;
	}

	/**
	 * Method 'setApellido2'.
	 *
	 * @param apellido2 String
	 * @return
     */
	
	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}
    /**
	 * Method 'getEjie'.
	 *
	 * @return String
	 */
	
	
	public String getEjie() {
		return this.ejie;
	}

	/**
	 * Method 'setEjie'.
	 *
	 * @param ejie String
	 * @return
     */
	
	public void setEjie(String ejie) {
		this.ejie = ejie;
	}
    /**
	 * Method 'getFechaAlta'.
	 *
	 * @return Date
	 */
	
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	/**
	 * Method 'setFechaAlta'.
	 *
	 * @param fechaAlta Date
	 * @return
     */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
    /**
	 * Method 'getFechaBaja'.
	 *
	 * @return Date
	 */
	
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	/**
	 * Method 'setFechaBaja'.
	 *
	 * @param fechaBaja Date
	 * @return
     */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}
    /**
	 * Method 'getIdPadre'.
	 *
	 * @return String
	 */
	
	
	public String getIdPadre() {
		return this.idPadre;
	}

	/**
	 * Method 'setIdPadre'.
	 *
	 * @param idPadre String
	 * @return
     */
	
	public void setIdPadre(String idPadre) {
		this.idPadre = idPadre;
	}

	/**
	 * Method 'getGrupo'.
	 *
	 * @return String
	 */
	
	
	public String getGrupo() {
		return this.grupo;
	}

	/**
	 * Method 'setGrupo'.
	 *
	 * @param grupo String
	 * @return
     */
	
	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}
	
	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		result.append(" [ id: ").append(this.id).append(" ]");
		result.append(", [ nombre: ").append(this.nombre).append(" ]");
		result.append(", [ apellido1: ").append(this.apellido1).append(" ]");
		result.append(", [ apellido2: ").append(this.apellido2).append(" ]");
		result.append(", [ ejie: ").append(this.ejie).append(" ]");
		result.append(", [ fechaAlta: ").append(this.fechaAlta).append(" ]");
		result.append(", [ fechaBaja: ").append(this.fechaBaja).append(" ]");
		result.append(", [ idPadre: ").append(this.idPadre).append(" ]");
		result.append(", [ grupo: ").append(this.grupo).append(" ]");
		result.append("}");
		return result.toString();
	}


}

