package com.ejie.aa79b.service;

import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.dao.AusenciasCalendarioPersonalDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.ObservacionesAusenciasDao;
import com.ejie.aa79b.dao.RegistroAccionesDao;
import com.ejie.aa79b.model.AusenciasCalendarioPersonal;
import com.ejie.aa79b.model.ObservacionesAusencias;
import com.ejie.aa79b.model.PersonalIZO;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.model.Tareas;
import com.ejie.aa79b.utils.Utils;
import com.ejie.aa79b.utils.date.DateFormaterFactory;

/**
 * AusenciasCalendarioPersonalServiceImpl generated by UDA, 17-nov-2017
 * 13:04:12.
 * 
 * @author UDA
 */

@Service(value = "ausenciasCalendarioPersonalService")
public class AusenciasCalendarioPersonalServiceImpl extends GenericoServiceImpl<AusenciasCalendarioPersonal>
		implements AusenciasCalendarioPersonalService {

	private static final String LABEL_DNI = "label.dni";

	@Autowired()
	private AusenciasCalendarioPersonalDao ausenciasCalendarioPersonalDao;
	@Autowired
	private ObservacionesAusenciasDao observacionesAusenciasDao;
	@Autowired()
	private RegistroAccionesDao registroAccionesDao;
	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	@Autowired()
	private TareasService tareasService;

	@Override
	protected GenericoDao<AusenciasCalendarioPersonal> getDao() {
		return this.ausenciasCalendarioPersonalDao;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public AusenciasCalendarioPersonal add(AusenciasCalendarioPersonal ausenciasCalendarioPersonal) {

		AusenciasCalendarioPersonal ausenciasCalendarioPersonalAux = this.ausenciasCalendarioPersonalDao
				.add(ausenciasCalendarioPersonal);
		// insert en el otro dao
		ObservacionesAusencias observacionesAusenciasAux = new ObservacionesAusencias(
				ausenciasCalendarioPersonalAux.getIdAusencia());
		observacionesAusenciasAux.setObservDia076(ausenciasCalendarioPersonalAux.getObservDia());
		this.observacionesAusenciasDao.add(observacionesAusenciasAux);

		// Registro de acciones...
		RegistroAcciones regAusencias = new RegistroAcciones();
		regAusencias.setIdPuntoMenu(Constants.PUNTO_MENU_CALENDARIO_PERSONAL);
		regAusencias.setIdAccion(Constants.ACCION_ALTA);
		Locale locale = new Locale(Constants.LANG_EUSKERA);

		StringBuilder observ = new StringBuilder();
		observ.append(this.msg.getMessage(LABEL_DNI, null, locale)).append(": ")
				.append(ausenciasCalendarioPersonalAux.getDni()).append(" - ");
		observ.append(this.msg.getMessage("mensaje.ausenciaNueva", null, locale)).append(":\n ");

		if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("V")) {
			observ.append(this.msg.getMessage("label.vacaciones", null, locale));
		} else if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("F")) {
			observ.append(this.msg.getMessage("label.formacion", null, locale));
		} else if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("B")) {
			observ.append(this.msg.getMessage("label.baja", null, locale));
		} else if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("O")) {
			observ.append(this.msg.getMessage("label.otros", null, locale));
		}

		observ.append(": ")
				.append(DateFormaterFactory.getInstance().getAa79bDateFormater()
						.parse(ausenciasCalendarioPersonalAux.getFechaDesde()))
				.append(" - ").append(DateFormaterFactory.getInstance().getAa79bDateFormater()
						.parse(ausenciasCalendarioPersonalAux.getFechaHasta()))
				.append(" \n");

		regAusencias.setObserv(observ.toString());
		this.registroAccionesDao.add(regAusencias);

		// solo tareas que no sean de interpretación
		comprobarTareasYEnviarEmails(ausenciasCalendarioPersonal, Constants.DOS);

		return ausenciasCalendarioPersonalAux;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public AusenciasCalendarioPersonal update(AusenciasCalendarioPersonal bean) {
		AusenciasCalendarioPersonal original = this.ausenciasCalendarioPersonalDao.find(bean);

		this.ausenciasCalendarioPersonalDao.update(bean);
		// cargar las obs y id en el otro dao y modificar

		ObservacionesAusencias observacionesAusenciasAux = new ObservacionesAusencias(bean.getIdAusencia());
		observacionesAusenciasAux.setObservDia076(bean.getObservDia());
		this.observacionesAusenciasDao.update(observacionesAusenciasAux);

		RegistroAcciones regAusencias = new RegistroAcciones();
		regAusencias.setIdPuntoMenu(Constants.PUNTO_MENU_CALENDARIO_PERSONAL);
		regAusencias.setIdAccion(Constants.ACCION_MODIFICACION);

		Map<String, String> paramAusencia = new LinkedHashMap<String, String>();
		paramAusencia.put("fechaDesde", "label.fechaDesde");
		paramAusencia.put("fechaHasta", "label.fechaHasta");
		paramAusencia.put("tipoJornada", "label.tipoJornada");

		Locale locale = new Locale(Constants.LANG_EUSKERA);
		String aux = Utils.observacionesRegistro(bean, original, paramAusencia, this.msg, locale);
		if (StringUtils.isNotBlank(aux)) {
			StringBuilder observ = new StringBuilder();
			observ.append(this.msg.getMessage(LABEL_DNI, null, locale)).append(": ").append(original.getDni())
					.append(" - ");
			observ.append(this.msg.getMessage("mensaje.ausenciaModificada", null, locale)).append(":\n ");
			observ.append(aux);
			regAusencias.setObserv(observ.toString());
			this.registroAccionesDao.add(regAusencias);
		}

		// solo tareas que no sean de interpretación
		comprobarTareasYEnviarEmails(bean, Constants.DOS);

		return bean;

	}

	/**
	 * 
	 */
	@Override()
	public void comprobarTareasYEnviarEmails(AusenciasCalendarioPersonal bean, int tipoTarea) {
		if (bean.getNumTareasConflicto() > 0) {
			Tareas tareaFilter = new Tareas();
			PersonalIZO personaAsignada = new PersonalIZO();
			personaAsignada.setDni(bean.getDni());
			tareaFilter.setPersonaAsignada(personaAsignada);
			tareaFilter.setFechaIni(bean.getFechaDesde());
			tareaFilter.setFechaFin(bean.getFechaHasta());
			bean.setRdoEnvioEmails(this.tareasService.enviarEmailsAsignadoresModifCalendario(tareaFilter, tipoTarea));
		}
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public void remove(AusenciasCalendarioPersonal ausenciasCalendarioPersonal) {

		AusenciasCalendarioPersonal ausenciasCalendarioPersonalAux = this.ausenciasCalendarioPersonalDao
				.find(ausenciasCalendarioPersonal);

		// remove en el dao de observaciones
		ObservacionesAusencias observacionesAusenciasAux = new ObservacionesAusencias(
				ausenciasCalendarioPersonalAux.getIdAusencia());
		this.observacionesAusenciasDao.remove(observacionesAusenciasAux);
		this.ausenciasCalendarioPersonalDao.remove(ausenciasCalendarioPersonal);

		// Registro de acciones...
		RegistroAcciones regAusencias = new RegistroAcciones();
		regAusencias.setIdPuntoMenu(Constants.PUNTO_MENU_CALENDARIO_PERSONAL);
		regAusencias.setIdAccion(Constants.ACCION_BORRADO);
		Locale locale = new Locale(Constants.LANG_EUSKERA);

		StringBuilder observ = new StringBuilder();
		observ.append(this.msg.getMessage(LABEL_DNI, null, locale)).append(": ")
				.append(ausenciasCalendarioPersonalAux.getDni()).append(" - ");
		observ.append(this.msg.getMessage("mensaje.ausenciaEliminada", null, locale)).append(":\n ");

		if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("V")) {
			observ.append(this.msg.getMessage("label.vacaciones", null, locale));
		} else if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("F")) {
			observ.append(this.msg.getMessage("label.formacion", null, locale));
		} else if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("B")) {
			observ.append(this.msg.getMessage("label.baja", null, locale));
		} else if (ausenciasCalendarioPersonalAux.getTipoJornada().contentEquals("O")) {
			observ.append(this.msg.getMessage("label.otros", null, locale));
		}

		observ.append(": ")
				.append(DateFormaterFactory.getInstance().getAa79bDateFormater()
						.parse(ausenciasCalendarioPersonalAux.getFechaDesde()))
				.append(" - ").append(DateFormaterFactory.getInstance().getAa79bDateFormater()
						.parse(ausenciasCalendarioPersonalAux.getFechaHasta()))
				.append(" \n");

		regAusencias.setObserv(observ.toString());
		this.registroAccionesDao.add(regAusencias);
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public boolean comprobarRangoAusencias(AusenciasCalendarioPersonal ausenciasCalendarioPersonal) {
		return this.ausenciasCalendarioPersonalDao.comprobarRangoAusencias(ausenciasCalendarioPersonal);
	}

	@Override
	public AusenciasCalendarioPersonal findConObservaciones(AusenciasCalendarioPersonal ausenciasCalendarioPersonal) {

		return this.ausenciasCalendarioPersonalDao.findConObservaciones(ausenciasCalendarioPersonal);
	}

}
