package com.ejie.aa79b.service;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.dao.CalendarioServicioDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.RegistroAccionesDao;
import com.ejie.aa79b.model.CalendarioServicio;
import com.ejie.aa79b.model.FestivosCalendarioServicio;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.utils.Utils;
import com.ejie.aa79b.utils.date.DateFormaterFactory;

/**
 * CalendarioServicioServiceImpl generated by UDA, 16-nov-2017 12:15:13.
 * 
 * @author UDA
 */

@Service(value = "calendarioServicioService")
public class CalendarioServicioServiceImpl extends GenericoServiceImpl<CalendarioServicio>
		implements CalendarioServicioService {

	@Autowired
	private CalendarioServicioDao calendarioServicioDao;
	@Autowired
	private FestivosCalendarioServicioService festivosCalendarioServicioService;
	@Autowired()
	private RegistroAccionesDao registroAccionesDao;
	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	@Override
	protected GenericoDao<CalendarioServicio> getDao() {
		return this.calendarioServicioDao;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public CalendarioServicio update(CalendarioServicio calendarioServicio) {

		CalendarioServicio original = this.find(calendarioServicio);

		CalendarioServicio calendarioServicioAux = this.calendarioServicioDao.update(calendarioServicio);
		calendarioServicioAux.setFestivosCalendarioServicios(calendarioServicio.getFestivosCalendarioServicios());
		// Elimino los festivos anteriores
		FestivosCalendarioServicio filterFestivosCalendarioServicio = new FestivosCalendarioServicio();
		filterFestivosCalendarioServicio.setAnyoCalendario023(calendarioServicioAux.getAnyoCalendario());
		this.festivosCalendarioServicioService.removeTodosPorAnio(filterFestivosCalendarioServicio);
		// Inserto los nuevos
		if (!calendarioServicio.getFestivosCalendarioServicios().isEmpty()) {
			for (FestivosCalendarioServicio festivosCalendarioServicio : calendarioServicio
					.getFestivosCalendarioServicios()) {
				this.festivosCalendarioServicioService.add(festivosCalendarioServicio);
			}
		}

		// Registro de acciones...
		registroAccionesUpdate(calendarioServicio, original);
		return calendarioServicioAux;
	}

	/**
	 * @param calendarioServicio
	 * @param original
	 */
	private void registroAccionesUpdate(CalendarioServicio calendarioServicio, CalendarioServicio original) {
		RegistroAcciones regCalendarioServicio = new RegistroAcciones();
		regCalendarioServicio.setIdPuntoMenu(Constants.PUNTO_MENU_CALENDARIO_SERVICIO);
		regCalendarioServicio.setIdAccion(Constants.ACCION_MODIFICACION);

		Map<String, String> paramTiposRevision = new LinkedHashMap<String, String>();
		paramTiposRevision.put("veranoDesde", "label.veranoDesde");
		paramTiposRevision.put("veranoHasta", "label.veranoHasta");
		Locale locale = new Locale(Constants.LANG_EUSKERA);
		String aux = Utils.observacionesRegistro(calendarioServicio, original, paramTiposRevision, this.msg, locale);

		List<String> listaDiasOriginal = new ArrayList<String>();
		List<String> listaDiasNueva = new ArrayList<String>();
		for (FestivosCalendarioServicio festivosCalendarioServicio : original.getFestivosCalendarioServicios()) {
			listaDiasOriginal.add(DateFormaterFactory.getInstance().getAa79bDateFormater()
					.parse(festivosCalendarioServicio.getDiaCalendario023()));
		}
		for (FestivosCalendarioServicio festivosCalendarioServicio : calendarioServicio
				.getFestivosCalendarioServicios()) {
			listaDiasNueva.add(DateFormaterFactory.getInstance().getAa79bDateFormater()
					.parse(festivosCalendarioServicio.getDiaCalendario023()));
		}
		// Comprobación de los festivos...
		boolean festivosModificados = false;
		String unDia;

		if (!listaDiasNueva.isEmpty()) {
			for (int x = 0; x < calendarioServicio.getFestivosCalendarioServicios().size(); x++) {
				unDia = DateFormaterFactory.getInstance().getAa79bDateFormater()
						.parse(calendarioServicio.getFestivosCalendarioServicios().get(x).getDiaCalendario023());
				if (listaDiasOriginal.contains(unDia)) {
					listaDiasOriginal.remove(unDia);
					listaDiasNueva.remove(unDia);
				}
			}
		}
		if ((!listaDiasOriginal.isEmpty()) || (!listaDiasNueva.isEmpty())) {
			festivosModificados = true;
		}
		guardarRegistroAccionesUpdate(original, regCalendarioServicio, locale, aux, listaDiasOriginal, listaDiasNueva,
				festivosModificados);
	}

	/**
	 * @param original
	 * @param regCalendarioServicio
	 * @param locale
	 * @param aux
	 * @param listaDiasOriginal
	 * @param listaDiasNueva
	 * @param festivosModificados
	 */
	private void guardarRegistroAccionesUpdate(CalendarioServicio original, RegistroAcciones regCalendarioServicio,
			Locale locale, String aux, List<String> listaDiasOriginal, List<String> listaDiasNueva,
			boolean festivosModificados) {
		if (StringUtils.isNotBlank(aux) || festivosModificados) {
			StringBuilder observ = new StringBuilder();
			observ.append(this.msg.getMessage("label.anyo", null, locale)).append(" ")
					.append(original.getAnyoCalendario()).append(" \n");
			if (StringUtils.isNotBlank(aux)) {
				observ.append(aux);
			}
			if (festivosModificados) {
				if (!listaDiasOriginal.isEmpty()) {
					observ.append(this.msg.getMessage("mensaje.festivosEliminados", null, locale));
					observ.append(listaDiasOriginal.toString()).append(" \n");
				}
				if (!listaDiasNueva.isEmpty()) {
					observ.append(this.msg.getMessage("mensaje.festivosAnadidos", null, locale));
					observ.append(listaDiasNueva.toString()).append(" \n");
				}
			}
			regCalendarioServicio.setObserv(observ.toString());
			if (regCalendarioServicio.getObserv().length() > 2000) {
				regCalendarioServicio.setObserv(regCalendarioServicio.getObserv().substring(0, 1999));
			}
			this.registroAccionesDao.add(regCalendarioServicio);
		}
	}

	@Override()
	public CalendarioServicio find(CalendarioServicio calendarioServicio) {

		CalendarioServicio calendarioServicioAux = this.calendarioServicioDao.find(calendarioServicio);

		FestivosCalendarioServicio filterFestivosCalendarioServicio = new FestivosCalendarioServicio();
		filterFestivosCalendarioServicio.setAnyoCalendario023(calendarioServicioAux.getAnyoCalendario());

		calendarioServicioAux.setFestivosCalendarioServicios(
				this.festivosCalendarioServicioService.findAll(filterFestivosCalendarioServicio, null));
		return calendarioServicioAux;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public void procCargaFestivosDefecto(long elAnyo) {
		this.calendarioServicioDao.procCargaFestivosDefecto(elAnyo);
	}

}
