package com.ejie.aa79b.service;

import com.ejie.aa79b.model.CalendarioServicio;

/**
 * CalendarioServicioService generated by UDA, 16-nov-2017 12:15:12.
 * 
 * @author UDA
 */

public interface CalendarioServicioService extends GenericoService<CalendarioServicio> {
	/**
	 * Method 'procCargaFestivosDefecto'.
	 * 
	 * @param elAnyo
	 *            Long
	 */
	void procCargaFestivosDefecto(long elAnyo);

}
