package com.ejie.aa79b.service;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.dao.CalendarioPersonalDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.RegistroAccionesDao;
import com.ejie.aa79b.model.CalendarioPersonal;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.utils.Utils;

/**
 * CalendarioPersonalServiceImpl generated by UDA, 17-nov-2017 12:37:45.
 * @author UDA
 */

@Service(value = "calendarioPersonalService")
public class CalendarioPersonalServiceImpl extends GenericoServiceImpl<CalendarioPersonal> implements CalendarioPersonalService {

    protected static final String DNI = "label.dni";
    
	@Autowired
	private CalendarioPersonalDao calendarioPersonalDao;
	@Autowired()
    private RegistroAccionesDao registroAccionesDao;
    @Autowired()
    private ReloadableResourceBundleMessageSource msg;
	    
    
    
	@Override
    protected GenericoDao<CalendarioPersonal> getDao() {
        return this.calendarioPersonalDao;
    }	
	
	@Override()
    @Transactional(rollbackFor = Throwable.class)
    public CalendarioPersonal add(CalendarioPersonal calendarioPersonal) {
        
        CalendarioPersonal calendarioPersonalAux = this.calendarioPersonalDao.add(calendarioPersonal);

        //Registro de acciones...        
        RegistroAcciones regAusencias = new RegistroAcciones();
        regAusencias.setIdPuntoMenu(Constants.PUNTO_MENU_CALENDARIO_PERSONAL);
        regAusencias.setIdAccion(Constants.ACCION_ALTA);
        Locale locale = new Locale(Constants.LANG_EUSKERA);
        
        StringBuilder observ = new StringBuilder();
        observ.append(this.msg.getMessage(DNI, null, locale)).append(": ").append(calendarioPersonalAux.getDni()).append(" - "); 
        observ.append(this.msg.getMessage("mensaje.calPersonalCreado", null, locale)).append(":\n");                
               
        observ.append(this.msg.getMessage("label.obsvHorario", null, locale)).append(": ").append(calendarioPersonalAux.getObservHorario()).append(" \n"); 
        observ.append(this.msg.getMessage("label.teletrabajador", null, locale)).append(": ");
        observ.append((calendarioPersonalAux.getIndTeletrabajo()!=null)?calendarioPersonalAux.getIndTeletrabajo():"N").append(". ");        
        observ.append(calendarioPersonalAux.getHorasGestionExp()+" ").append(this.msg.getMessage("label.horasGestion", null, locale));
        regAusencias.setObserv(observ.toString());
        this.registroAccionesDao.add(regAusencias);       
        
        return calendarioPersonalAux;
    }
	
	
	
	@Override()
    @Transactional(rollbackFor = Throwable.class)
    public CalendarioPersonal update(CalendarioPersonal bean) {
        CalendarioPersonal original = this.calendarioPersonalDao.find(bean);
        
        this.calendarioPersonalDao.update(bean);
        
      //Registro de acciones...
        if (bean.getIndTeletrabajo() == null){
            bean.setIndTeletrabajo("N");
        }
        RegistroAcciones regCalPersonal = new RegistroAcciones();
        regCalPersonal.setIdPuntoMenu(Constants.PUNTO_MENU_CALENDARIO_PERSONAL);
        regCalPersonal.setIdAccion(Constants.ACCION_MODIFICACION);
        
        Map<String, String> paramCalendarioPersonal = new LinkedHashMap<String, String>();
        paramCalendarioPersonal.put("dni", DNI);
        paramCalendarioPersonal.put("indTeletrabajo", "label.teletrabajador");
        paramCalendarioPersonal.put("observHorario", "label.obsvHorario");
        paramCalendarioPersonal.put("horasGestionExp", "label.horasGestion");
                
        Locale locale = new Locale(Constants.LANG_EUSKERA);
        String aux = Utils.observacionesRegistro(bean, original, paramCalendarioPersonal, this.msg, locale);
        if (StringUtils.isNotBlank(aux)) {
            StringBuilder observ = new StringBuilder();
            observ.append(this.msg.getMessage(DNI, null, locale)).append(": ").append(original.getDni()).append(" \n");
            observ.append(aux);
            regCalPersonal.setObserv(observ.toString());
            this.registroAccionesDao.add(regCalPersonal);
        }
        return bean;
    }
	
}

