package com.ejie.aa79b.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.dao.ClasificacionDocumentosDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.model.ClasificacionDocumentos;

/**
 * ClasificacionDocumentosServiceImpl generated by UDA, 06-feb-2018 8:28:55.
 * 
 * @author UDA
 */

@Service(value = "clasificacionDocumentosService")
public class ClasificacionDocumentosServiceImpl extends GenericoServiceImpl<ClasificacionDocumentos>
		implements ClasificacionDocumentosService {

	@Autowired
	private ClasificacionDocumentosDao clasificacionDocumentosDao;

	@Override
	protected GenericoDao<ClasificacionDocumentos> getDao() {
		return this.clasificacionDocumentosDao;
	}

	/**
	 * Inserts a single row in the ClasificacionDocumentos table.
	 *
	 * @param clasificacionDocumentos
	 *            ClasificacionDocumentos
	 * @return ClasificacionDocumentos
	 */
	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ClasificacionDocumentos add(ClasificacionDocumentos clasificacionDocumentos) {
		return this.clasificacionDocumentosDao.add(clasificacionDocumentos);
	}

	/**
	 * Updates a single row in the ClasificacionDocumentos table.
	 *
	 * @param clasificacionDocumentos
	 *            ClasificacionDocumentos
	 * @return ClasificacionDocumentos
	 */
	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ClasificacionDocumentos update(ClasificacionDocumentos clasificacionDocumentos) {
		return this.clasificacionDocumentosDao.update(clasificacionDocumentos);
	}

	/**
	 * Deletes a single row in the ClasificacionDocumentos table.
	 *
	 * @param clasificacionDocumentos
	 *            ClasificacionDocumentos
	 */
	@Override
	@Transactional(rollbackFor = Throwable.class)
	public void remove(ClasificacionDocumentos clasificacionDocumentos) {
		this.clasificacionDocumentosDao.remove(clasificacionDocumentos);
	}

	@Override()
	@Transactional(readOnly = true)
	public List<ClasificacionDocumentos> findAllSinTrabajo(ClasificacionDocumentos bean) {
		return this.clasificacionDocumentosDao.findAllSinTrabajo(bean);
	}
}
