package com.ejie.aa79b.service;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.dao.ContactoFacturacionExpedienteDao;
import com.ejie.aa79b.dao.ExpedienteDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.RegistroAccionesDao;
import com.ejie.aa79b.dao.SolicitanteDao;
import com.ejie.aa79b.model.ContactoFacturacionExpediente;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.utils.Utils;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * ContactoFacturacionExpedienteServiceImpl generated by UDA, 29-ene-2018
 * 12:17:36.
 * 
 * @author UDA
 */

@Service(value = "contactoFacturacionExpedienteService")
public class ContactoFacturacionExpedienteServiceImpl extends GenericoServiceImpl<ContactoFacturacionExpediente>
		implements ContactoFacturacionExpedienteService {

	private static final String LABPORCENTAJE = "label.porcentajeFactAplica";
	private static final String LABID = "label.id";
	private static final String LABENTASOC = "label.entidadAsociada";
	private static final String LABCONTACTO = "label.contacto";
	private static final String LABNUMEXP = "label.numeroExpediente";

	@Autowired
	private ContactoFacturacionExpedienteDao contactoFacturacionExpedienteDao;
	@Autowired()
	private RegistroAccionesDao registroAccionesDao;
	@Autowired()
	private ReloadableResourceBundleMessageSource msg;
	@Autowired
	private SolicitanteDao solicitanteDao;
	@Autowired()
	private ExpedienteDao expedienteDao;

	@Override
	protected GenericoDao<ContactoFacturacionExpediente> getDao() {
		return this.contactoFacturacionExpedienteDao;
	}

	/**
	 * Inserts a single row in the ContactoFacturacionExpediente table.
	 *
	 * @param contactoFacturacionExpediente
	 *            ContactoFacturacionExpediente
	 * @return ContactoFacturacionExpediente
	 */
	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ContactoFacturacionExpediente add(ContactoFacturacionExpediente contactoFacturacionExpediente) {

		ContactoFacturacionExpediente contactoFacturacionExpedienteAux = this.contactoFacturacionExpedienteDao
				.add(contactoFacturacionExpediente);

		contactoFacturacionExpediente.getContacto().setDni(contactoFacturacionExpediente.getDniContacto058());
		contactoFacturacionExpediente
				.setContacto(this.solicitanteDao.find(contactoFacturacionExpediente.getContacto()));
		this.solicitanteDao.guardarFoto(contactoFacturacionExpediente.getContacto());

		// Registro de acciones...
		RegistroAcciones regAcciones = new RegistroAcciones();
		regAcciones.setIdPuntoMenu(Constants.PUNTO_MENU_TRAMITACION_EXPEDIENTES);
		regAcciones.setIdAccion(Constants.ACCION_ALTA);
		regAcciones.setAnyo(contactoFacturacionExpediente.getAnyo());
		regAcciones.setNumExp(contactoFacturacionExpediente.getNumExp());
		Expediente expediente = new Expediente(contactoFacturacionExpediente.getAnyo(),
				contactoFacturacionExpediente.getNumExp());
		regAcciones.setIdEstadoBitacora(this.expedienteDao.leerIdEstadoBitacora(expediente));
		Locale locale = new Locale(Constants.LANG_EUSKERA);

		StringBuilder observ = new StringBuilder();
		observ.append(this.msg.getMessage(LABNUMEXP, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getAnyo() + "/" + contactoFacturacionExpedienteAux.getNumExp())
				.append("\n ");
		observ.append(this.msg.getMessage("label.facturacionExpediente.creadoContacto", null, locale)).append(" - ");
		observ.append(this.msg.getMessage(LABID, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getId058()).append(": \n");
		observ.append(this.msg.getMessage(LABENTASOC, null, locale)).append(": ");
		observ.append(contactoFacturacionExpedienteAux.getTipoEntidadAsoc058()).append(" ");
		observ.append(contactoFacturacionExpedienteAux.getIdEntidadAsoc058()).append(": \n");
		observ.append(this.msg.getMessage(LABCONTACTO, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getDniContacto058()).append(": \n");
		observ.append(this.msg.getMessage(LABPORCENTAJE, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getPorFactura058()).append(": \n");
		regAcciones.setObserv(observ.toString());
		this.registroAccionesDao.add(regAcciones);

		return contactoFacturacionExpedienteAux;
	}

	/**
	 * Updates a single row in the ContactoFacturacionExpediente table.
	 *
	 * @param contactoFacturacionExpediente
	 *            ContactoFacturacionExpediente
	 * @return ContactoFacturacionExpediente
	 */
	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ContactoFacturacionExpediente update(ContactoFacturacionExpediente contactoFacturacionExpediente) {
		ContactoFacturacionExpediente original = this.contactoFacturacionExpedienteDao
				.find(contactoFacturacionExpediente);
		this.contactoFacturacionExpedienteDao.update(contactoFacturacionExpediente);

		contactoFacturacionExpediente.getContacto().setDni(contactoFacturacionExpediente.getDniContacto058());
		contactoFacturacionExpediente
				.setContacto(this.solicitanteDao.find(contactoFacturacionExpediente.getContacto()));
		this.solicitanteDao.guardarFoto(contactoFacturacionExpediente.getContacto());

		RegistroAcciones regAcciones = new RegistroAcciones();
		regAcciones.setIdPuntoMenu(Constants.PUNTO_MENU_TRAMITACION_EXPEDIENTES);
		regAcciones.setIdAccion(Constants.ACCION_MODIFICACION);
		regAcciones.setAnyo(original.getAnyo());
		regAcciones.setNumExp(original.getNumExp());
		Expediente expediente = new Expediente(original.getAnyo(), original.getNumExp());
		regAcciones.setIdEstadoBitacora(this.expedienteDao.leerIdEstadoBitacora(expediente));

		Map<String, String> paramRegAcciones = new LinkedHashMap<String, String>();
		paramRegAcciones.put("tipoEntidadAsoc058", "label.tipoEntidad");
		paramRegAcciones.put("idEntidadAsoc058", LABENTASOC);
		paramRegAcciones.put("dniContacto058", LABCONTACTO);
		paramRegAcciones.put("porFactura058", LABPORCENTAJE);

		Locale locale = new Locale(Constants.LANG_EUSKERA);
		String aux = Utils.observacionesRegistro(contactoFacturacionExpediente, original, paramRegAcciones, this.msg,
				locale);
		if (StringUtils.isNotBlank(aux)) {
			StringBuilder observ = new StringBuilder();
			observ.append(this.msg.getMessage(LABNUMEXP, null, locale)).append(": ")
					.append(original.getAnyo() + "/" + original.getNumExp()).append("\n ");
			observ.append(this.msg.getMessage(LABID, null, locale)).append(": ").append(original.getId058())
					.append(" - ");
			observ.append(this.msg.getMessage("label.facturacionExpediente.modificadoContacto", null, locale))
					.append(":\n ");
			observ.append(aux);
			regAcciones.setObserv(observ.toString());
			this.registroAccionesDao.add(regAcciones);
		}

		return contactoFacturacionExpediente;
	}

	/**
	 * Deletes a single row in the ContactoFacturacionExpediente table.
	 *
	 * @param contactoFacturacionExpediente
	 *            ContactoFacturacionExpediente
	 */
	@Override
	@Transactional(rollbackFor = Throwable.class)
	public void remove(ContactoFacturacionExpediente contactoFacturacionExpediente) {

		ContactoFacturacionExpediente contactoFacturacionExpedienteAux = this.contactoFacturacionExpedienteDao
				.find(contactoFacturacionExpediente);
		this.contactoFacturacionExpedienteDao.remove(contactoFacturacionExpediente);

		// Registro de acciones...
		RegistroAcciones regAcciones = new RegistroAcciones();
		regAcciones.setIdPuntoMenu(Constants.PUNTO_MENU_TRAMITACION_EXPEDIENTES);
		regAcciones.setIdAccion(Constants.ACCION_BORRADO);
		regAcciones.setAnyo(contactoFacturacionExpedienteAux.getAnyo());
		regAcciones.setNumExp(contactoFacturacionExpedienteAux.getNumExp());
		Expediente expediente = new Expediente(contactoFacturacionExpedienteAux.getAnyo(),
				contactoFacturacionExpedienteAux.getNumExp());
		regAcciones.setIdEstadoBitacora(this.expedienteDao.leerIdEstadoBitacora(expediente));
		Locale locale = new Locale(Constants.LANG_EUSKERA);

		StringBuilder observ = new StringBuilder();
		observ.append(this.msg.getMessage(LABNUMEXP, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getAnyo() + "/" + contactoFacturacionExpedienteAux.getNumExp())
				.append("\n ");
		observ.append(this.msg.getMessage("label.facturacionExpediente.eliminadoContacto", null, locale)).append(" - ");
		observ.append(this.msg.getMessage(LABID, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getId058()).append(": \n");
		observ.append(this.msg.getMessage(LABENTASOC, null, locale)).append(": ");
		observ.append(this.msg.getMessage("label.tipoEntidad", null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getTipoEntidadAsoc058()).append(", ");
		observ.append(this.msg.getMessage(LABID, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getIdEntidadAsoc058()).append(": \n");
		observ.append(this.msg.getMessage(LABCONTACTO, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getDniContacto058()).append(": \n");
		observ.append(this.msg.getMessage(LABPORCENTAJE, null, locale)).append(": ")
				.append(contactoFacturacionExpedienteAux.getPorFactura058()).append(": \n");
		regAcciones.setObserv(observ.toString());
		this.registroAccionesDao.add(regAcciones);

	}

	/**
	 * Filter method in the T table.
	 *
	 * @param filter
	 *            T
	 * @param jqGridRequestDto
	 *            JQGridRequestDto
	 * @param startsWith
	 *            Boolean
	 * @return JQGridResponseDto<T>
	 */
	@Override
	public JQGridResponseDto<ContactoFacturacionExpediente> filtroConJoins(ContactoFacturacionExpediente filter,
			JQGridRequestDto jqGridRequestDto, Boolean startsWith) {

		List<ContactoFacturacionExpediente> listaT = this.contactoFacturacionExpedienteDao.filtroConJoins(filter,
				jqGridRequestDto, false);
		Long recordNum = this.contactoFacturacionExpedienteDao.filtroConJoinsCount(filter, false);

		if (jqGridRequestDto.getMultiselection().getSelectedIds() != null) {
			List<TableRowDto<ContactoFacturacionExpediente>> reorderSelection = this.getDao().reorderSelection(filter,
					jqGridRequestDto, startsWith);
			return new JQGridResponseDto<ContactoFacturacionExpediente>(jqGridRequestDto, recordNum, listaT,
					reorderSelection);
		}
		return new JQGridResponseDto<ContactoFacturacionExpediente>(jqGridRequestDto, recordNum, listaT);
	}

	@Override
	public JQGridResponseDto<ContactoFacturacionExpediente> entidadesContactosAFacturarFilter(
			ContactoFacturacionExpediente filter, JQGridRequestDto jqGridRequestDto, Boolean startsWith) {

		List<ContactoFacturacionExpediente> listaT = this.contactoFacturacionExpedienteDao
				.entidadesContactosAFacturarFilter(filter, jqGridRequestDto, false);
		Long recordNum = this.contactoFacturacionExpedienteDao.entidadesContactosAFacturarFilterCount(filter, false);

		if (jqGridRequestDto.getMultiselection().getSelectedIds() != null) {
			List<TableRowDto<ContactoFacturacionExpediente>> reorderSelection = this.getDao().reorderSelection(filter,
					jqGridRequestDto, startsWith);
			return new JQGridResponseDto<ContactoFacturacionExpediente>(jqGridRequestDto, recordNum, listaT,
					reorderSelection);
		}
		return new JQGridResponseDto<ContactoFacturacionExpediente>(jqGridRequestDto, recordNum, listaT);
	}

	/**
	 * validarExcepcionNueva.
	 *
	 * @param excepcionFacturacion
	 *            ExcepcionFacturacion
	 * @return vuelta int 0 - no hay errores 1- ya existe excepción para esa
	 *         entidad y contacto a facturar 2- El sumatorio excede de 100% 3-
	 *         Contacto solicitante ya está en otra excepción
	 */
	@Override
	public int validarExcepcionNueva(ContactoFacturacionExpediente contactoFacturacionExpediente) {
		int vuelta = 0;
		if ((contactoFacturacionExpediente.getIdEntidadAsoc058() != null)
				&& (contactoFacturacionExpediente.getPorFactura058() != null)) {

			// Comprobación de entidad y usuario activos...
			if (this.solicitanteDao.comprobarEntidadYSolicitanteValidos(
					contactoFacturacionExpediente.getTipoEntidadAsoc058(),
					contactoFacturacionExpediente.getIdEntidadAsoc058(),
					contactoFacturacionExpediente.getDniContacto058()) == 0) {
				vuelta = 4;
			} else {
				vuelta = validarExcepcionNuevaRestoTipos(contactoFacturacionExpediente, vuelta);
			}
		} else {
			vuelta = 0;
			// Si no hay datos, pq es un alta y los campos están
			// vacios, para que salte la validación de campos
		}
		return vuelta;
	}

	/**
	 * @param contactoFacturacionExpediente
	 * @param vuelta
	 * @return
	 */
	private int validarExcepcionNuevaRestoTipos(ContactoFacturacionExpediente contactoFacturacionExpediente,
			int vuelta) {
		int vuelta2 = vuelta;
		ContactoFacturacionExpediente contactoFacturacionExpedienteAux = new ContactoFacturacionExpediente();

		contactoFacturacionExpedienteAux.setAnyo(contactoFacturacionExpediente.getAnyo());
		contactoFacturacionExpedienteAux.setNumExp(contactoFacturacionExpediente.getNumExp());
		contactoFacturacionExpedienteAux.setTipoEntidadAsoc058(contactoFacturacionExpediente.getTipoEntidadAsoc058());
		contactoFacturacionExpedienteAux.setIdEntidadAsoc058(contactoFacturacionExpediente.getIdEntidadAsoc058());
		contactoFacturacionExpedienteAux.setDniContacto058(contactoFacturacionExpediente.getDniContacto058());

		List<ContactoFacturacionExpediente> listaContactoFacturacionExpediente = this.contactoFacturacionExpedienteDao
				.findAll(contactoFacturacionExpedienteAux, null);

		if ((listaContactoFacturacionExpediente.isEmpty()) || (listaContactoFacturacionExpediente.get(0).getId058()
				.equals(contactoFacturacionExpediente.getId058()))) {

			// (suma de porcentajes no puede superar 100)
			contactoFacturacionExpedienteAux.setTipoEntidadAsoc058(null);
			contactoFacturacionExpedienteAux.setIdEntidadAsoc058(null);
			contactoFacturacionExpedienteAux.setDniContacto058(null);
			if (contactoFacturacionExpediente.getId058() != null) {
				contactoFacturacionExpedienteAux.setId058(contactoFacturacionExpediente.getId058());
			}
			int sumatorio = this.contactoFacturacionExpedienteDao
					.sumatorioPorcentajesExcepEntidad(contactoFacturacionExpedienteAux);
			if (sumatorio + contactoFacturacionExpediente.getPorFactura058() > 100) {
				vuelta2 = 2;
			}

		} else {
			vuelta2 = 1;
		}
		return vuelta2;
	}

	@Override
	public void borraTodosPorIdExcepcion(Long id058, Long idExcepcion058, Integer numExp) {
		this.contactoFacturacionExpedienteDao.borraTodosPorIdExcepcion(id058, idExcepcion058, numExp);
	}

	@Override
	public void borraTodosContactoEntidadPorId(Long id058) {
		this.contactoFacturacionExpedienteDao.borraTodosContactoEntidadPorId(id058);
	}

	@Override
	public JQGridResponseDto<ContactoFacturacionExpediente> entidadesContactosAFacturarInterFilter(
			ContactoFacturacionExpediente filterContactoFacturacionExpediente, JQGridRequestDto jqGridRequestDto,
			Boolean startsWith) {
		List<ContactoFacturacionExpediente> listaT = this.contactoFacturacionExpedienteDao
				.entidadesContactosAFacturarInterFilter(filterContactoFacturacionExpediente, jqGridRequestDto, false);
		Long recordNum = this.contactoFacturacionExpedienteDao
				.entidadesContactosAFacturarInterFilterCount(filterContactoFacturacionExpediente, false);

		if (jqGridRequestDto.getMultiselection().getSelectedIds() != null) {
			List<TableRowDto<ContactoFacturacionExpediente>> reorderSelection = this.getDao()
					.reorderSelection(filterContactoFacturacionExpediente, jqGridRequestDto, startsWith);
			return new JQGridResponseDto<ContactoFacturacionExpediente>(jqGridRequestDto, recordNum, listaT,
					reorderSelection);
		}
		return new JQGridResponseDto<ContactoFacturacionExpediente>(jqGridRequestDto, recordNum, listaT);
	}

}
