package com.ejie.aa79b.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.DatosTareaTradosDocsDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.model.DatosTareaTradosDocs;

/**
 * DatosTareaTradosDocsServiceImpl generated by UDA, 19-jun-2018 13:27:18.
 * 
 * @author UDA
 */

@Service(value = "datosTareaTradosDocsService")
public class DatosTareaTradosDocsServiceImpl extends GenericoServiceImpl<DatosTareaTradosDocs>
		implements DatosTareaTradosDocsService {

	@Autowired()
	private DatosTareaTradosDocsDao datosTareaTradosDocsDao;

	@Override
	protected GenericoDao<DatosTareaTradosDocs> getDao() {
		return this.datosTareaTradosDocsDao;
	}

}
