package com.ejie.aa79b.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.DireccionNoraDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.model.Direccion;
import com.ejie.aa79b.model.DireccionNora;

/**
 * DireccionNoraServiceImpl generated by UDA, 08-feb-2018 8:37:04.
 * 
 * @author UDA
 */

@Service(value = "direccionNoraService")
public class DireccionNoraServiceImpl extends GenericoServiceImpl<DireccionNora> implements DireccionNoraService {

	@Autowired
	private DireccionNoraDao direccionNoraDao;

	@Override
	protected GenericoDao<DireccionNora> getDao() {
		return this.direccionNoraDao;
	}

	@Override
	public DireccionNora find(DireccionNora direccionNora) {
		final DireccionNora direccionNoraAux = this.direccionNoraDao.find(direccionNora);
		return this.getDireccionNora(direccionNoraAux);
	}

	@Override
	public DireccionNora update(DireccionNora direccionNora) {
		if (direccionNora.getDirNora() == null) {
			final Long dirNora = this.direccionNoraDao.getNextVal("AA79B49Q00");
			direccionNora.setDirNora(dirNora.intValue());
			this.direccionNoraDao.add(direccionNora);
		} else {
			this.direccionNoraDao.update(direccionNora);
		}
		return this.getDireccionNora(direccionNora);
	}

	/**
	 * Obtiene los datos de nora para mostrar en el formulario
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 * @return DireccionNora
	 */
	public DireccionNora getDireccionNora(DireccionNora direccionNora) {

		if (direccionNora != null) {
			this.getPortal(direccionNora);
			this.getCalle(direccionNora);
			this.getLocalidad(direccionNora);
			this.getMunicipio(direccionNora);
			this.getProvincia(direccionNora);
			this.getPais(direccionNora);

		}

		return direccionNora;
	}

	/**
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 */
	private void getPortal(DireccionNora direccionNora) {
		if (direccionNora.getPortal() != null && direccionNora.getPortal().getId() != null) {
			direccionNora.setPortal(this.direccionNoraDao.getPortal(direccionNora.getPortal().getId()));
			direccionNora.getCalle().setId(direccionNora.getPortal().getCalleId());
		}
	}

	/**
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 */
	private void getCalle(DireccionNora direccionNora) {
		if (direccionNora.getCalle() != null && direccionNora.getCalle().getId() != null) {
			direccionNora.setCalle(this.direccionNoraDao.getCalle(direccionNora.getCalle().getId()));
		}
	}

	/**
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 */
	private void getLocalidad(DireccionNora direccionNora) {
		if (direccionNora.getLocalidad() != null && direccionNora.getLocalidad().getId() != null) {
			direccionNora.setLocalidad(this.direccionNoraDao.getLocalidad(direccionNora.getLocalidad().getId()));
		}
	}

	/**
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 */
	private void getMunicipio(DireccionNora direccionNora) {
		if (direccionNora.getMunicipio() != null && direccionNora.getProvincia() != null
				&& direccionNora.getMunicipio().getId() != null && direccionNora.getProvincia().getId() != null) {
			direccionNora.setMunicipio(this.direccionNoraDao.getMunicipio(direccionNora.getMunicipio().getId(),
					direccionNora.getProvincia().getId()));

		}
	}

	/**
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 */
	private void getProvincia(DireccionNora direccionNora) {
		if (direccionNora.getProvincia() != null && direccionNora.getProvincia().getId() != null) {
			direccionNora.setProvincia(this.direccionNoraDao.getProvincia(direccionNora.getProvincia().getId()));
		}
	}

	/**
	 * 
	 * @param direccionNora
	 *            DireccionNora
	 */
	private void getPais(DireccionNora direccionNora) {
		if (direccionNora.getPais() != null && direccionNora.getPais().getId() != null) {
			direccionNora.setPais(this.direccionNoraDao.getPais(direccionNora.getPais().getId()));
		}
	}

	/**
	 * @param dni
	 *            String
	 * @return Direccion
	 */
	@Override
	public Direccion obtenerDireccionConDni(String dni) {
		return this.direccionNoraDao.obtenerDireccionConDni(dni);
	}

}
