package com.ejie.aa79b.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.DocumentosCorreccionDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.model.DocumentoTarea;
import com.ejie.aa79b.model.DocumentosCorreccion;

/**
 * DocumentosCorreccionServiceImpl generated by UDA, 01-abr-2019 15:51:21.
 * 
 * @author UDA
 */

@Service(value = "documentosCorreccionService")
public class DocumentosCorreccionServiceImpl extends GenericoServiceImpl<DocumentosCorreccion>
		implements DocumentosCorreccionService {

	@Autowired
	private DocumentosCorreccionDao documentosCorreccionDao;

	@Override
	protected GenericoDao<DocumentosCorreccion> getDao() {
		return this.documentosCorreccionDao;
	}

	@Override
	public DocumentoTarea getDocumentoCorreccion(DocumentosCorreccion docCorreccion) {
		return this.documentosCorreccionDao.getDocumentoCorreccion(docCorreccion);
	}

}
