package com.ejie.aa79b.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.EmpresasProveedorasDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.model.EmpresasProveedoras;

/**
 * EmpresasProveedorasService generated by UDA, 23-ene-2018 13:19:33.
 * 
 * @author UDA
 */
@Service(value = "empresasProveedorasService")
public class EmpresasProveedorasServiceImpl extends GenericoServiceImpl<EmpresasProveedoras>
		implements EmpresasProveedorasService {

	@Autowired
	private EmpresasProveedorasDao empresasProveedorasDao;

	@Override
	protected GenericoDao<EmpresasProveedoras> getDao() {
		return this.empresasProveedorasDao;
	}

	@Override
	public List<EmpresasProveedoras> getEmpresasProveedorasConTareasNoPagadas(boolean soloNoPagadas) {
		return empresasProveedorasDao.getEmpresasProveedorasConTareasNoPagadas(soloNoPagadas);
	}

	@Override
	public List<EmpresasProveedoras> getEmpresasProveedoras(EmpresasProveedoras empresasProveedoras) {
		return this.empresasProveedorasDao.getEmpresasProveedoras(empresasProveedoras);
	}
}
