package com.ejie.aa79b.service;

import java.util.List;
import java.util.Locale;

import com.ejie.aa79b.model.BitacoraExpediente;
import com.ejie.aa79b.model.CamposSelecSub;
import com.ejie.aa79b.model.CamposSubsanacion;
import com.ejie.aa79b.model.DocumentosExpediente;
import com.ejie.aa79b.model.DocusSelecSub;
import com.ejie.aa79b.model.EntradaFechaFinalizacion;
import com.ejie.aa79b.model.EntradaGestoresRepresentante;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.ExpedientePlanificacion;
import com.ejie.aa79b.model.ExpedienteTradRev;
import com.ejie.aa79b.model.GestorExpediente;
import com.ejie.aa79b.model.ListaExpediente;
import com.ejie.aa79b.model.RechazoExpediente;
import com.ejie.aa79b.model.SalidaFechaFinalizacion;
import com.ejie.aa79b.model.SubsanacionExpediente;
import com.ejie.aa79b.model.Tareas;
import com.ejie.aa79b.model.webservices.Aa79bExpedienteRelacionado;
import com.ejie.aa79b.model.webservices.Aa79bSolicitud;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;

/**
 * ExpedienteService generated by UDA, 31-ene-2018 15:08:48.
 * 
 * @author UDA
 */

public interface ExpedienteService extends GenericoService<Expediente> {

	/**
	 * @param filterExpediente
	 * @param jqGridRequestDto
	 * @param b
	 * @return
	 */
	JQGridResponseDto<Expediente> filtroExpedienteEstadoEnEstudio(Expediente filterExpediente,
			JQGridRequestDto jqGridRequestDto, boolean b);

	JQGridResponseDto<Expediente> filtroExpedienteEstadoEnCurso(Expediente filterExpediente,
			JQGridRequestDto jqGridRequestDto, boolean b);

	/**
	 * @param listaExpedientes
	 * @return
	 */
	Integer asignarTecnicoAExpedientes(ListaExpediente listaExpedientes);

	/**
	 * @param filterExpediente
	 * @param jqGridRequestDto
	 * @param b
	 * @param noRelacionados
	 * @return
	 */
	JQGridResponseDto<Expediente> obtenerExpedientesRelacionados(Expediente filterExpediente,
			JQGridRequestDto jqGridRequestDto, boolean b, boolean noRelacionados);

	Integer modificarEstado(Expediente expedientes);

	/**
	 * @param listaExpedientes
	 * @return
	 */
	ListaExpediente relacionarExpedientes(ListaExpediente listaExpedientes);

	/**
	 * Rechaza el expediente
	 * 
	 * @param expedientes
	 *            Expediente
	 * @param rechazoExp
	 *            RechazoExpediente
	 * @param procedencia
	 *            String
	 * @return Integer
	 */
	Integer rechazarExpediente(Expediente expedientes, RechazoExpediente rechazoExp, String procedencia);

	Integer finalizarEstudio(Expediente expedientes, JQGridRequestDto jqGridRequestDto, Boolean startsWith);

	SubsanacionExpediente registrarSubsanacion(SubsanacionExpediente subsanacionExpediente, String camposSelecSub,
			String docuSelecSub, Expediente expediente);

	SubsanacionExpediente registrarSubsanacionTarea(SubsanacionExpediente subsanacionExpediente, String camposSelecSub,
			String docuSelecSub, Expediente expediente, Tareas tareas, Locale locale);

	List<CamposSubsanacion> findAllCamposSubsanacion(String tipoExp);

	/**
	 * Obtiene los datos de contacto del gestor
	 * 
	 * @param bean
	 *            Expediente
	 * @return Gestor
	 */
	GestorExpediente getDatosContacto(Expediente bean);

	Expediente comprobarRequisitosSub(Expediente expedientes);

	List<Expediente> comprobarCamposSeleccionados(Expediente expedientes);

	List<Expediente> comprobarDocumentosSeleccionados(Expediente expedientes);

	List<String> getTitulosExpediente(EntradaGestoresRepresentante bean);

	Long countGestorExpPdteTramCliente(EntradaGestoresRepresentante bean);

	void setPdteTramitacion(Expediente expedientes);

	void updateFechaLimite(SubsanacionExpediente subsanacionExpediente);

	void setEstudioExp(Expediente expedientes);

	void actualizarSubsanacion(SubsanacionExpediente subsanacionExpediente);

	void actualizarSubsanacionConObsvRechazo(SubsanacionExpediente subsanacionExpediente);

	void setRechazarSubsanacion(Expediente expedientes);

	Integer comprobarRequisitosDocu(Expediente expedientes);

	SubsanacionExpediente getDetalleSubsanacion(Expediente expedientes);

	List<CamposSelecSub> getCampoSubsanacion(SubsanacionExpediente subExp);

	List<DocusSelecSub> getDocuSubsanacion(SubsanacionExpediente subExp);

	/**
	 * @param expedientes
	 *            Expediente
	 * @param jqGridRequestDto
	 *            JQGridRequestDto
	 * @param startsWith
	 *            Boolean
	 * @return Integer
	 */
	Integer finAltaOficio(Expediente expedientes, JQGridRequestDto jqGridRequestDto, Boolean startsWith);

	/**
	 * Obtiene el plazo mínimo de entrega a partir de los params de entrada -
	 * llamado desde el WebService aa79bExpedienteWS (método
	 * obtenerDatosFechaFinalizacionWS)
	 * 
	 * @param bean
	 *            EntradaFechaFinalizacion
	 * @return SalidaFechaFinalizacion
	 */
	SalidaFechaFinalizacion llamadaFncObtenerPlazoMinEntrega(EntradaFechaFinalizacion bean);

	List<Aa79bSolicitud> findSolicitud(Expediente bean);

	List<DocumentosExpediente> documentosRelacionados(Expediente bean);

	Integer updateIndSubsanacion(SubsanacionExpediente bean);

	List<Aa79bExpedienteRelacionado> expRelacionadasFind(Expediente bean);

	List<Expediente> getJustificanteSolicitud(Expediente bean);

	Integer countGruposTrabajoInterpretacion(String dni);

	JQGridResponseDto<ExpedientePlanificacion> busquedageneral(ExpedientePlanificacion filter,
			JQGridRequestDto jqGridRequestDto, boolean isCount);

	JQGridResponseDto<ExpedientePlanificacion> consultaPlanificacionExpediente(ExpedientePlanificacion filter,
			JQGridRequestDto jqGridRequestDto, boolean isCount);

	/**
	 * @param expediente
	 * @return Expediente
	 */
	Expediente updateAsignador(Expediente expediente);

	/**
	 * Obtiene el estado/fase del expediente
	 * 
	 * @param anyo
	 *            Long
	 * @param numExp
	 *            Integer
	 * @return BitacoraExpediente
	 */
	BitacoraExpediente findEstadoFaseExpediente(Long anyo, Integer numExp);

	String getPermisosBopv(Long anyo, Integer numExp);

	/**
	 * 
	 * @param listaExpedientes
	 *            ListaExpediente
	 * @return Integer
	 */
	Integer asignarAsignadorAExpedientes(ListaExpediente listaExpedientes);

	ExpedienteTradRev getFechaFinalIzo(Expediente bean);

	/**
	 * Rechazo del expediente desde el servicio de cambio de estado del
	 * expediente
	 * 
	 * @param expedientes
	 *            Expediente
	 * @param rechazoExp
	 *            RechazoExpediente
	 * @return Integer
	 */
	Integer rechazarExpCambioEstadoExp(Expediente expedientes, RechazoExpediente rechazoExp);

	/**
	 * 
	 * @param filterExpedientePlanificacion
	 *            ExpedientePlanificacion
	 * @param tableData
	 *            JQGridRequestDto
	 * @return List<ExpedientePlanificacion>
	 */
	List<ExpedientePlanificacion> consultaPlanificacionExpedienteGetSelectedIds(
			ExpedientePlanificacion filterExpedientePlanificacion, JQGridRequestDto tableData);

	/**
	 * Operacion de obtencion de ids de elementos seleccionados de RUP_TABLE.
	 * 
	 * @param filter
	 *            ExpedientePlanificacion
	 * @param tableData
	 *            JQGridRequestDto
	 * @return List<ExpedientePlanificacion>
	 */
	List<ExpedientePlanificacion> busquedageneralGetSelectedIds(ExpedientePlanificacion filter,
			JQGridRequestDto tableData);

	/**
	 * Operacion de obtencion de ids de elementos seleccionados de RUP_TABLE.
	 * 
	 * @param filterExpediente
	 *            Expediente
	 * @param tableData
	 *            JQGridRequestDto
	 * @return List<Expediente>
	 */
	List<Expediente> filtroExpedienteEstadoEnEstudioGetSelectedIds(Expediente filterExpediente,
			JQGridRequestDto tableData);

}
