package com.ejie.aa79b.service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.GestorExpedienteDao;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.GruposTrabajo;

/**
 * GestorExpedienteServiceImpl generated by UDA, 31-ene-2018 15:08:48.
 * @author UDA
 */

@Service(value = "gestorExpedienteService")
public class GestorExpedienteServiceImpl extends GenericoServiceImpl<Expediente> implements GestorExpedienteService {

	@Autowired
	private GestorExpedienteDao gestorExpedienteDao;

	@Override
	protected GenericoDao<Expediente> getDao() {
		return this.gestorExpedienteDao;
	}

	@Override
	public GruposTrabajo getGrupoTrabajoGestor(Expediente bean) {
		return this.gestorExpedienteDao.getGrupoTrabajoGestor(bean);
	}
	
}

