package com.ejie.aa79b.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.HorasHorariosAtencionDao;
import com.ejie.aa79b.model.HorasHorariosAtencion;

/**
 * HorasHorariosServiceImpl generated by UDA, 21-nov-2017 14:44:52.
 * 
 * @author UDA
 */

@Service(value = "horasHorariosAtencionService")
public class HorasHorariosAtencionServiceImpl extends GenericoServiceImpl<HorasHorariosAtencion>
        implements HorasHorariosAtencionService {

    @Autowired
    private HorasHorariosAtencionDao horasHorariosDao;

    @Override
    protected GenericoDao<HorasHorariosAtencion> getDao() {
        return this.horasHorariosDao;
    }

}
