package com.ejie.aa79b.service;

/**
 * TiposRevisionService generated by UDA, 28-nov-2017 15:23:30.
 * 
 * @author javarona
 */
public interface OidsAuxiliarService {

	/**
	 * Añade un registro a la tabla auxiliar de OIDs
	 * 
	 * @param nuevoOID
	 */
	void add(String nuevoOID);

	/**
	 * Elimina un registro de la tabla auxiliar de OIDs
	 * 
	 * @param oid
	 */
	void remove(String oid);

	/**
	 * limpiarPIDProcesoBatch
	 */
	void limpiarPIDProcesoBatch();

}
