 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<link href="${staticsUrl}/rup/portal/externals/bootstrap/bt4.min.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/externals/font-awesome/font-awesome.min.css" rel="stylesheet" type="text/css" >
<link href="${staticsUrl}/rup/portal/rup-base.min.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/rup-theme.min.css" rel="stylesheet" type="text/css" />
