 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!--[if !(IE)]> -->
<link href="${staticsUrl}/rup/css/rup.css" rel="stylesheet" type="text/css" />
<!--<![endif]-->
<!--[if IE]>
<link href="${staticsUrl}/rup/css/external/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/external/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/external/gridstack.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/external/gridstack-extra.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/external/jquery.fileupload.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/external/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/rup-rwd.css" rel="stylesheet" type="text/css" />
<![endif]-->

