 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!--[if !(IE)]> -->
<link href="${staticsUrl}/rup/css/rup.min.css" rel="stylesheet" type="text/css" />
<!--<![endif]-->
<!--[if IE]>
<link href="${staticsUrl}/rup/css/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/gridstack.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/gridstack-extra.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/jquery.fileupload.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/rup.css" rel="stylesheet" type="text/css" />
<![endif]-->

