
package com.ejie.w43df.pid.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "w43dfPIDService", targetNamespace = "com/ejie/documents/xml", wsdlLocation = "http://svc.intra.integracion.jakina.ejiedes.net/ctxapp/w43dfPIDService?wsdl")
public class W43DfPIDService extends Service {

    private static final URL W43DFPIDSERVICE_WSDL_LOCATION;
    private static final Logger LOGGER = Logger.getLogger(com.ejie.w43df.pid.client.W43DfPIDService.class.getName());
    private static final String PATH = "com/ejie/documents/xml";

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ejie.w43df.pid.client.W43DfPIDService.class.getResource(".");
            url = new URL(baseUrl, "http://svc.intra.integracion.jakina.ejiedes.net/ctxapp/w43dfPIDService?wsdl");
        } catch (MalformedURLException e) {
            LOGGER.warning(
                    "Failed to create URL for the wsdl Location: 'http://svc.intra.integracion.jakina.ejiedes.net/ctxapp/w43dfPIDService?wsdl', retrying as a local file");
            LOGGER.warning(e.getMessage());
        }
        W43DFPIDSERVICE_WSDL_LOCATION = url;
    }

    public W43DfPIDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public W43DfPIDService() {
        super(W43DFPIDSERVICE_WSDL_LOCATION, new QName(PATH, "w43dfPIDService"));
    }

    /**
     * 
     * @return returns W43DfPIDInterface
     */
    @WebEndpoint(name = "w43dfPIDPort")
    public W43DfPIDInterface getW43DfPIDPort() {
        return super.getPort(new QName(PATH, "w43dfPIDPort"), W43DfPIDInterface.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns W43DfPIDInterface
     */
    @WebEndpoint(name = "w43dfPIDPort")
    public W43DfPIDInterface getW43DfPIDPort(WebServiceFeature... features) {
        return super.getPort(new QName(PATH, "w43dfPIDPort"), W43DfPIDInterface.class, features);
    }

}
