package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.AnulacionExpediente;

/**
 * AnulacionExpedienteDaoImpl generated by UDA, 02-oct-2018 13:29:14.
 * 
 * @author UDA
 */

@Repository()
@Transactional()
public class AnulacionExpedienteDaoImpl extends GenericoDaoImpl<AnulacionExpediente> implements AnulacionExpedienteDao {

	public static final String[] ORDER_BY_WHITE_LIST = new String[] { DBConstants.ID, DBConstants.IDMOTIVOANULACION };

	private RowMapper<AnulacionExpediente> rwMap = new RowMapper<AnulacionExpediente>() {
		public AnulacionExpediente mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new AnulacionExpediente(resultSet.getLong(DBConstants.ID),
					resultSet.getLong(DBConstants.IDMOTIVOANULACION));
		}
	};

	private RowMapper<AnulacionExpediente> rwMapPK = new RowMapper<AnulacionExpediente>() {
		public AnulacionExpediente mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new AnulacionExpediente(resultSet.getLong(DBConstants.ID));
		}
	};

	public AnulacionExpedienteDaoImpl() {
		super(AnulacionExpediente.class);
	}

	@Override()
	public AnulacionExpediente add(AnulacionExpediente anulacionexpediente) {
		String queryID = "SELECT AA79BA1Q00.NEXTVAL from dual";
		Long id = this.getJdbcTemplate().queryForObject(queryID, Long.class);
		anulacionexpediente.setId(id);

		String query = "INSERT INTO AA79BA1S01 (ID_0A1, ID_MOTIVO_ANULACION_0A1) VALUES (?,?)";
		this.getJdbcTemplate().update(query, anulacionexpediente.getId(), anulacionexpediente.getIdMotivoAnulacion());

		return anulacionexpediente;
	}

	@Override()
	public AnulacionExpediente update(AnulacionExpediente anulacionexpediente) {
		String query = "UPDATE AA79BA1S01 SET ID_MOTIVO_ANULACION_0A1=? WHERE ID_0A1=?";
		this.getJdbcTemplate().update(query, anulacionexpediente.getIdMotivoAnulacion(), anulacionexpediente.getId());
		return anulacionexpediente;
	}

	@Override()
	public void remove(AnulacionExpediente anulacionexpediente) {
		String query = "DELETE FROM AA79BA1S01 WHERE ID_0A1=?";
		this.getJdbcTemplate().update(query, anulacionexpediente.getId());
	}

	@Override
	protected String getSelect() {
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.SELECT);
		query.append(DaoConstants.T1_MINUSCULA);
		query.append(DaoConstants.SIGNO_PUNTO);
		query.append(DBConstants.ID_0A1);
		query.append(DaoConstants.BLANK);
		query.append(DBConstants.ID);
		query.append(DaoConstants.BLANK);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.T1_MINUSCULA);
		query.append(DaoConstants.SIGNO_PUNTO);
		query.append(DBConstants.ID_MOTIVO_ANULACION_0A1);
		query.append(DaoConstants.BLANK);
		query.append(DBConstants.IDMOTIVOANULACION);
		query.append(DaoConstants.BLANK);

		return query.toString();
	}

	@Override
	protected String getFrom() {
		StringBuilder from = new StringBuilder();
		from.append(DaoConstants.FROM);
		from.append(DBConstants.AA79BA1S01);
		from.append(DaoConstants.BLANK);
		from.append(DaoConstants.T1_MINUSCULA);
		from.append(DaoConstants.BLANK);

		return from.toString();
	}

	@Override
	protected RowMapper<AnulacionExpediente> getRwMap() {
		return this.rwMap;
	}

	@Override
	protected String[] getOrderBy() {
		return AnulacionExpedienteDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override
	protected String getPK() {
		return DBConstants.ID_0A1;
	}

	@Override
	protected RowMapper<AnulacionExpediente> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override
	protected String getWherePK(AnulacionExpediente bean, List<Object> params) {
		params.add(bean.getId());
		StringBuilder where = new StringBuilder();
		where.append(DaoConstants.WHERE);
		where.append(DaoConstants.T1_MINUSCULA);
		where.append(DaoConstants.SIGNO_PUNTO);
		where.append(DBConstants.ID_0A1);
		where.append(DaoConstants.SIGNOIGUAL_INTERROGACION);

		return where.toString();
	}

	@Override
	protected String getWhere(AnulacionExpediente bean, List<Object> params) {
		return getWhereClausule(bean, params);
	}

	@Override
	protected String getWhereLike(AnulacionExpediente bean, Boolean startsWith, List<Object> params, Boolean search) {
		return getWhereClausule(bean, params);
	}

	/**
	 * @param bean
	 * @param params
	 * @return
	 */
	private String getWhereClausule(AnulacionExpediente bean, List<Object> params) {
		StringBuilder where = new StringBuilder(AnulacionExpedienteDaoImpl.STRING_BUILDER_INIT);

		if (bean != null) {
			where.append(SqlUtils.generarWhereIgual(DBConstants.ID_0A1, bean.getId(), params));
			where.append(SqlUtils.generarWhereIgual(DBConstants.ID_MOTIVO_ANULACION_0A1, bean.getIdMotivoAnulacion(),
					params));
		}

		return where.toString();
	}

}
