package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.ClasificacionDocumentos;
import com.ejie.aa79b.model.enums.ClasificacionDocumentosEnum;

/**
 * ClasificacionDocumentosDaoImpl generated by UDA, 06-feb-2018 8:28:55.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class ClasificacionDocumentosDaoImpl extends GenericoDaoImpl<ClasificacionDocumentos>
		implements ClasificacionDocumentosDao {

	protected static final String ID075 = "ID075";
	protected static final String ID_075 = "ID_075";
	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { ID075, "DESCES075", "DESCEU075",
			"TIPOSEXPEDIENTE075", "ESTADO075" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<ClasificacionDocumentos> rwMap = new RowMapper<ClasificacionDocumentos>() {
		@Override
		public ClasificacionDocumentos mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new ClasificacionDocumentos(resultSet.getLong(ID075), resultSet.getString("DESCES075"),
					resultSet.getString("DESCEU075"), resultSet.getString("TIPOSEXPEDIENTE075"),
					resultSet.getString("ESTADO075"));
		}
	};

	private RowMapper<ClasificacionDocumentos> rwMapPK = new RowMapper<ClasificacionDocumentos>() {
		@Override
		public ClasificacionDocumentos mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new ClasificacionDocumentos(resultSet.getLong(ID075));
		}
	};

	/**
	 * Constructor de la clase.
	 */
	public ClasificacionDocumentosDaoImpl() {
		/* Constructor */
		super(ClasificacionDocumentos.class);
	}
	/*
	 * OPERACIONES CRUD
	 */

	/**
	 * Inserts a single row in the ClasificacionDocumentos table.
	 *
	 * @param clasificaciondocumentos
	 *            ClasificacionDocumentos
	 * @return ClasificacionDocumentos
	 */
	@Override
	public ClasificacionDocumentos add(ClasificacionDocumentos clasificaciondocumentos) {
		String query = "INSERT INTO AA79B75S01 (ID_075, DESC_ES_075, DESC_EU_075, TIPOS_EXPEDIENTE_075, ESTADO_075) VALUES (?,?,?,?,?)";
		this.getJdbcTemplate().update(query, clasificaciondocumentos.getId075(), clasificaciondocumentos.getDescEs075(),
				clasificaciondocumentos.getDescEu075(), clasificaciondocumentos.getTiposExpediente075(),
				clasificaciondocumentos.getEstado075());
		return clasificaciondocumentos;
	}

	/**
	 * Updates a single row in the ClasificacionDocumentos table.
	 *
	 * @param clasificaciondocumentos
	 *            ClasificacionDocumentos
	 * @return ClasificacionDocumentos
	 */
	@Override
	public ClasificacionDocumentos update(ClasificacionDocumentos clasificaciondocumentos) {
		String query = "UPDATE AA79B75S01 SET DESC_ES_075=?, DESC_EU_075=?, TIPOS_EXPEDIENTE_075=?, ESTADO_075=? WHERE ID_075=?";
		this.getJdbcTemplate().update(query, clasificaciondocumentos.getDescEs075(),
				clasificaciondocumentos.getDescEu075(), clasificaciondocumentos.getTiposExpediente075(),
				clasificaciondocumentos.getEstado075(), clasificaciondocumentos.getId075());
		return clasificaciondocumentos;
	}

	/**
	 * Removes a single row in the ClasificacionDocumentos table.
	 *
	 * @param clasificaciondocumentos
	 *            ClasificacionDocumentos
	 * @return
	 */
	@Override
	public void remove(ClasificacionDocumentos clasificaciondocumentos) {
		String query = "DELETE FROM AA79B75S01 WHERE ID_075=?";
		this.getJdbcTemplate().update(query, clasificaciondocumentos.getId075());
	}

	@Override()
	protected String getSelect() {
		StringBuilder sb = new StringBuilder();
		sb.append(
				"SELECT t1.ID_075 ID075, t1.DESC_ES_075 DESCES075, t1.DESC_EU_075 DESCEU075, t1.TIPOS_EXPEDIENTE_075 TIPOSEXPEDIENTE075, t1.ESTADO_075 ESTADO075 ");
		return sb.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B75S01 t1 ";
	}

	@Override()
	protected RowMapper<ClasificacionDocumentos> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return TiposRevisionDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_075;
	}

	@Override()
	protected RowMapper<ClasificacionDocumentos> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(ClasificacionDocumentos bean, List<Object> params) {
		params.add(bean.getId075());
		return " WHERE t1.ID_075 = ? ";
	}

	@Override
	protected String getWhere(ClasificacionDocumentos bean, List<Object> params) {
		StringBuilder where = new StringBuilder(ClasificacionDocumentosDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_075, bean.getId075(), params));
		where.append(SqlUtils.generarWhereLikeNormalizado("DESC_ES_075", bean.getDescEs075(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("DESC_EU_075", bean.getDescEu075(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("TIPOS_EXPEDIENTE_075", bean.getTiposExpediente075(), params,
				false));
		where.append(SqlUtils.generarWhereLikeNormalizado("ESTADO_075", bean.getEstado075(), params, false));
		return where.toString();
	}

	@Override
	protected String getWhereLike(ClasificacionDocumentos bean, Boolean startsWith, List<Object> params,
			Boolean search) {
		StringBuilder where = new StringBuilder(TiposRevisionDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_075, bean.getId075(), params));
		where.append(SqlUtils.generarWhereLikeNormalizado("DESC_ES_075", bean.getDescEs075(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("DESC_EU_075", bean.getDescEu075(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("TIPOS_EXPEDIENTE_075", bean.getTiposExpediente075(), params,
				startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("ESTADO_075", bean.getEstado075(), params, startsWith));
		return where.toString();
	}

	@Override()
	@Transactional(readOnly = true)
	public List<ClasificacionDocumentos> findAllSinTrabajo(ClasificacionDocumentos bean) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getSelect());
		query.append(this.getFrom(bean, params));

		query.append(GenericoDaoImpl.DEFAULT_WHERE);
		query.append(this.getWhere(bean, params));
		query.append(DaoConstants.AND).append("ID_075").append(DaoConstants.SIGNO_DISTINTO)
				.append(ClasificacionDocumentosEnum.TRABAJO.getValue());
		return this.getJdbcTemplate().query(query.toString(), this.getRwMap(), params.toArray());
	}
}
