package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.ConfigHorasPrevistasDatosBasicosFilterRowMapper;
import com.ejie.aa79b.dao.mapper.ConfigHorasPrevistasRowMapper;
import com.ejie.aa79b.model.ConfigHorasPrevistas;
import com.ejie.aa79b.utils.Utils;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * ConfigHorasPrevistasDaoImpl generated by UDA, 05-dic-2017 15:17:18.
 *
 * @author UDA
 */

@Repository
@Transactional
public class ConfigHorasPrevistasDaoImpl extends GenericoDaoImpl<ConfigHorasPrevistas>
		implements ConfigHorasPrevistasDao {

	public ConfigHorasPrevistasDaoImpl() {
		super(ConfigHorasPrevistas.class);
	}

	public static final String[] ORDER_BY_WHITE_LIST = new String[] { "ID002", "PALTRADHORA002",
			"PALHORACONCOR100002", "PALHORACONCOR9599002","PALHORACONCOR8594002", "PALHORACONCOR084002", "PALREVHORA002",
			"PALSEGCONCOR100002", "PALSEGCONCOR9599002","PALSEGCONCOR8594002", "PALSEGCONCOR084002", "PALTRADSEG002", "PALREVSEG002",
			"NIVELUSUARIO002", "IDTIPORELEVANCIA002", "NIVELUSUARIO", "TIPORELEVANCIADESCEU", "TIPORELEVANCIADESCES" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<ConfigHorasPrevistas> rwMap = new ConfigHorasPrevistasRowMapper();

	private RowMapper<ConfigHorasPrevistas> rwMapPK = new RowMapper<ConfigHorasPrevistas>() {
		@Override
		public ConfigHorasPrevistas mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new ConfigHorasPrevistas(resultSet.getInt("ID002"));
		}
	};
	private RowMapper<ConfigHorasPrevistas> rwMapDatosBasicosFilter = new ConfigHorasPrevistasDatosBasicosFilterRowMapper();

	@Override()
	public ConfigHorasPrevistas add(ConfigHorasPrevistas confighorasprevistas) {
		StringBuilder query = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		query.append("INSERT INTO AA79B02S01 ");
		query.append(
				" (ID_002, PAL_TRAD_HORA_002, PAL_HORA_CONCOR_100_002, PAL_HORA_CONCOR_95_99_002, PAL_HORA_CONCOR_85_94_002, PAL_HORA_CONCOR_0_84_002, PAL_REV_HORA_002, ");
		query.append(
				" PAL_SEG_CONCOR_100_002, PAL_SEG_CONCOR_95_99_002, PAL_SEG_CONCOR_85_94_002, PAL_SEG_CONCOR_0_84_002, PAL_TRAD_SEG_002, PAL_REV_SEG_002, NIVEL_USUARIO_002, ID_TIPO_RELEVANCIA_002) ");
		query.append("  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
		this.getJdbcTemplate().update(query.toString(), confighorasprevistas.getId(),
				confighorasprevistas.getPalTradHora(), confighorasprevistas.getPalHoraConcor100(), confighorasprevistas.getPalHoraConcor9599(),
				confighorasprevistas.getPalHoraConcor8594(), confighorasprevistas.getPalHoraConcor084(),
				confighorasprevistas.getPalRevHora(), confighorasprevistas.getPalSegConcor100(), confighorasprevistas.getPalSegConcor9599(),
				confighorasprevistas.getPalSegConcor8594(), confighorasprevistas.getPalSegConcor084(),
				confighorasprevistas.getPalTradSeg(), confighorasprevistas.getPalRevSeg(),
				confighorasprevistas.getNivUsuario(), confighorasprevistas.getTipoRelevancia().getIdTipoRelevancia());
		return confighorasprevistas;
	}

	/**
	 * Updates a single row in the ConfigHorasPrevistas table.
	 *
	 * @param confighorasprevistas ConfigHorasPrevistas
	 * @return ConfigHorasPrevistas
	 */
	@Override()
	public ConfigHorasPrevistas update(ConfigHorasPrevistas confighorasprevistas) {
		StringBuilder query = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		query.append("UPDATE AA79B02S01 SET ");
		query.append(
				" PAL_TRAD_HORA_002=?, PAL_HORA_CONCOR_100_002=?, PAL_HORA_CONCOR_95_99_002=?, PAL_HORA_CONCOR_85_94_002=?, PAL_HORA_CONCOR_0_84_002=?, PAL_REV_HORA_002=?, ");
		query.append(
				" PAL_SEG_CONCOR_100_002=?, PAL_SEG_CONCOR_95_99_002=?, PAL_SEG_CONCOR_85_94_002=?, PAL_SEG_CONCOR_0_84_002=?, PAL_TRAD_SEG_002=?, PAL_REV_SEG_002=? ");
		query.append(" WHERE ID_002=? AND NIVEL_USUARIO_002 = ? AND ID_TIPO_RELEVANCIA_002=?");
		this.getJdbcTemplate().update(query.toString(), confighorasprevistas.getPalTradHora(),
				confighorasprevistas.getPalHoraConcor100(), confighorasprevistas.getPalHoraConcor9599(), confighorasprevistas.getPalHoraConcor8594(),
				confighorasprevistas.getPalHoraConcor084(), confighorasprevistas.getPalRevHora(),
				confighorasprevistas.getPalSegConcor100(), confighorasprevistas.getPalSegConcor9599(), confighorasprevistas.getPalSegConcor8594(),
				confighorasprevistas.getPalSegConcor084(), confighorasprevistas.getPalTradSeg(),
				confighorasprevistas.getPalRevSeg(), confighorasprevistas.getId(), confighorasprevistas.getNivUsuario(),
				confighorasprevistas.getTipoRelevancia().getIdTipoRelevancia());
		return confighorasprevistas;
	}

	/**
	 * Removes a single row in the ConfigHorasPrevistas table.
	 *
	 * @param confighorasprevistas ConfigHorasPrevistas
	 * @return
	 */
	@Override()
	public void remove(ConfigHorasPrevistas confighorasprevistas) {
		StringBuilder query = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		List<Object> params = new ArrayList<Object>();
		query.append("DELETE FROM AA79B02S01 WHERE ID_002=?");
		params.add(confighorasprevistas.getId());
		query.append(SqlUtils.generarWhereIgual("NIVEL_USUARIO_002", confighorasprevistas.getNivUsuario(), params));
		query.append(SqlUtils.generarWhereIgual("ID_TIPO_RELEVANCIA_002",
				confighorasprevistas.getTipoRelevancia() != null
						? confighorasprevistas.getTipoRelevancia().getIdTipoRelevancia()
						: null,
				params));
		this.getJdbcTemplate().update(query.toString(), params.toArray());
	}

	@Override()
	protected String getSelect() {
		StringBuilder query = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		query.append("SELECT t1.ID_002 ID002," + " t1.PAL_TRAD_HORA_002 PALTRADHORA002, "
				+ "t1.PAL_HORA_CONCOR_100_002 PALHORACONCOR100002, "
				+ "t1.PAL_HORA_CONCOR_95_99_002 PALHORACONCOR9599002, "
				+ "t1.PAL_HORA_CONCOR_85_94_002 PALHORACONCOR8594002,"
				+ " t1.PAL_HORA_CONCOR_0_84_002 PALHORACONCOR084002," + " t1.PAL_REV_HORA_002 PALREVHORA002, "
				+ " t1.PAL_SEG_CONCOR_100_002 PALSEGCONCOR100002, "
				+ " t1.PAL_SEG_CONCOR_95_99_002 PALSEGCONCOR9599002, "
				+ " t1.PAL_SEG_CONCOR_85_94_002 PALSEGCONCOR8594002, "
				+ " t1.PAL_SEG_CONCOR_0_84_002 PALSEGCONCOR084002, " + " t1.PAL_TRAD_SEG_002 PALTRADSEG002, "
				+ " t1.PAL_REV_SEG_002 PALREVSEG002, " + " t1.NIVEL_USUARIO_002 NIVELUSUARIO002, "
				+ " t1.ID_TIPO_RELEVANCIA_002 IDTIPORELEVANCIA002 ");
		return query.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B02S01 t1";
	}

	@Override()
	protected RowMapper<ConfigHorasPrevistas> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return ConfigHorasPrevistasDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return "ID_002";
	}

	@Override()
	protected RowMapper<ConfigHorasPrevistas> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(ConfigHorasPrevistas bean, List<Object> params) {
		params.add(bean.getId());
		return " WHERE ID_002 = ?";
	}

	@Override()
	protected String getWhere(ConfigHorasPrevistas bean, List<Object> params) {
		StringBuilder where = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual("ID_002", bean.getId(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_TRAD_HORA_002", bean.getPalTradHora(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_100_002", bean.getPalHoraConcor100(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_95_99_002", bean.getPalHoraConcor9599(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_85_94_002", bean.getPalHoraConcor8594(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_0_84_002", bean.getPalHoraConcor084(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_REV_HORA_002", bean.getPalRevHora(), params));
		return where.toString();
	}

	@Override()
	protected String getWhereLike(ConfigHorasPrevistas bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual("ID_002", bean.getId(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_TRAD_HORA_002", bean.getPalTradHora(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_100_002", bean.getPalHoraConcor100(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_95_99_002", bean.getPalHoraConcor9599(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_85_94_002", bean.getPalHoraConcor8594(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_HORA_CONCOR_0_84_002", bean.getPalHoraConcor084(), params));
		where.append(SqlUtils.generarWhereIgual("PAL_REV_HORA_002", bean.getPalRevHora(), params));
		return where.toString();
	}

	@Override
	public Object datosBasicosFilter(ConfigHorasPrevistas filterConfigHorasPrevistas, JQGridRequestDto jqGridRequestDto,
			Boolean startsWith, Boolean isCount) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		if (isCount) {
			query.append(" SELECT COUNT(1) ");
		} else {
			query.append(this.getFilterSelect());
		}
		query.append(this.getFilterFrom());
		query.append(DaoConstants.WHERE_1_1);
		query.append(this.getWhere(filterConfigHorasPrevistas, params));
		query.append(SqlUtils.generarWhereIgual("ESTADO_010", Constants.ALTA, params));
		StringBuilder paginatedQuery = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		paginatedQuery.append(Utils.getPaginationQuery(jqGridRequestDto, isCount, query));
		if (isCount) {
			return this.getJdbcTemplate().queryForObject(paginatedQuery.toString(), params.toArray(), Long.class);
		} else {
			return this.getJdbcTemplate().query(paginatedQuery.toString(), this.rwMapDatosBasicosFilter,
					params.toArray());
		}
	}

	private String getFilterFrom() {
		StringBuilder queryFilterFrom = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		queryFilterFrom.append(" FROM AA79B10T00 "
				+ " CROSS JOIN (SELECT 'N' nivel_usuario from dual UNION select 'V' nivel_usuario from dual) usuario "
				+ " LEFT JOIN AA79B02T00 ON " + " NIVEL_USUARIO_002 = usuario.nivel_usuario AND "
				+ " ID_TIPO_RELEVANCIA_002 = ID_TIPO_RELEVANCIA_010 AND ID_002 = 0");
		return queryFilterFrom.toString();
	}

	private String getFilterSelect() {
		StringBuilder queryFilterSelect = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		queryFilterSelect.append(" SELECT usuario.nivel_usuario NIVELUSUARIO002,"
				+ " ID_TIPO_RELEVANCIA_010 IDTIPORELEVANCIA002," + " DESC_RELEVANCIA_EU_010 TIPORELEVANCIADESCEU,"
				+ " DESC_RELEVANCIA_ES_010 TIPORELEVANCIADESCES, " + " PAL_TRAD_HORA_002 PALTRADHORA002, "
				+ " PAL_HORA_CONCOR_100_002 PALHORACONCOR100002, "
				+ " PAL_HORA_CONCOR_95_99_002 PALHORACONCOR9599002, "
				+ " PAL_HORA_CONCOR_85_94_002 PALHORACONCOR8594002, "
				+ " PAL_HORA_CONCOR_0_84_002 PALHORACONCOR084002, " + " PAL_REV_HORA_002 PALREVHORA002, "
				+ " PAL_SEG_CONCOR_100_002 PALSEGCONCOR100002, "
				+ " PAL_SEG_CONCOR_95_99_002 PALSEGCONCOR9599002, "
				+ " PAL_SEG_CONCOR_85_94_002 PALSEGCONCOR8594002, " + " PAL_SEG_CONCOR_0_84_002 PALSEGCONCOR084002, "
				+ " PAL_TRAD_SEG_002 PALTRADSEG002, " + " PAL_REV_SEG_002 PALREVSEG002 ");
		return queryFilterSelect.toString();
	}

	@Override
	public Integer isConfigHorasPrevistasAlreadyStored(ConfigHorasPrevistas configHorasPrevistas) {
		List<Object> params = new ArrayList<Object>();
		params.add(configHorasPrevistas.getId());
		params.add(configHorasPrevistas.getNivUsuario());
		params.add(configHorasPrevistas.getTipoRelevancia().getIdTipoRelevancia());
		StringBuilder queryIsConfigStored = new StringBuilder(ConfigHorasPrevistasDaoImpl.STRING_BUILDER_INIT);
		queryIsConfigStored.append(" SELECT COUNT(1) ");
		queryIsConfigStored.append(" FROM AA79B02S01 ");
		queryIsConfigStored.append(" WHERE ID_002 = ? AND NIVEL_USUARIO_002 = ? AND ID_TIPO_RELEVANCIA_002 = ? ");
		return this.getJdbcTemplate().queryForObject(queryIsConfigStored.toString(), params.toArray(), Integer.class);
	}

}
