package com.ejie.aa79b.dao;

import com.ejie.aa79b.model.CuantiaInter;

/**
 * CuantiaInterDao generated by UDA, 15-dic-2017 14:11:45.
 * 
 * @author UDA
 */
public interface CuantiaInterDao extends GenericoDao<CuantiaInter> {

}