package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.DatosTareaTradosDocsRowMapper;
import com.ejie.aa79b.dao.mapper.DatosTareaTradosDocsWithNumPalRowMapper;
import com.ejie.aa79b.model.DatosTareaTradosDocs;
import com.ejie.x38.dto.JQGridManager;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * DatosTareaTradosDocsDaoImpl generated by UDA, 19-jun-2018 13:27:18.
 *
 * @author UDA
 */

@Repository
@Transactional
public class DatosTareaTradosDocsDaoImpl extends GenericoDaoImpl<DatosTareaTradosDocs>
		implements DatosTareaTradosDocsDao {

	protected static final String ID_TAREA_091 = "ID_TAREA_091";

	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { DBConstants.IDTAREA, DBConstants.IDDOCORIG,
			DBConstants.NUMTOTALPAL, DBConstants.NUMPALCONCOR084, DBConstants.NUMPALCONCOR8594,
			DBConstants.NUMPALCONCOR95100, "NUMPALCONCOR9599", "NUMPALCONCOR100" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<DatosTareaTradosDocs> rwMap = new DatosTareaTradosDocsRowMapper();

	private RowMapper<DatosTareaTradosDocs> rwMapWithNumPal = new DatosTareaTradosDocsWithNumPalRowMapper();

	private RowMapper<DatosTareaTradosDocs> rwMapPK = new RowMapper<DatosTareaTradosDocs>() {
		@Override
		public DatosTareaTradosDocs mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			DatosTareaTradosDocs datosTareaTradosDocs = new DatosTareaTradosDocs();
			datosTareaTradosDocs.setIdTarea(resultSet.getBigDecimal("IDTAREA091"));

			return datosTareaTradosDocs;
		}
	};

	/**
	 * Constructor
	 */
	public DatosTareaTradosDocsDaoImpl() {
		super(DatosTareaTradosDocs.class);
	}

	@Override
	public DatosTareaTradosDocs add(DatosTareaTradosDocs datosTareaTradosDocs) {
		String query = "INSERT INTO AA79B91S01 (ID_TAREA_091, ID_DOC_ORIG_091, NUM_TOTAL_PAL_091, NUM_PAL_CONCOR_0_84_091, NUM_PAL_CONCOR_85_94_091, NUM_PAL_CONCOR_95_100_091, NUM_PAL_CONCOR_95_99_091, NUM_PAL_CONCOR_100_091) VALUES (?,?,?,?,?,?,?,?)";
		this.getJdbcTemplate().update(query, datosTareaTradosDocs.getIdTarea(), datosTareaTradosDocs.getIdDocOrig(),
				datosTareaTradosDocs.getNumTotalPal(), datosTareaTradosDocs.getNumPalConcor084(),
				datosTareaTradosDocs.getNumPalConcor8594(), datosTareaTradosDocs.getNumPalConcor95100(), datosTareaTradosDocs.getNumPalConcor9599(), datosTareaTradosDocs.getNumPalConcor100());
		return datosTareaTradosDocs;
	}

	@Override
	public DatosTareaTradosDocs update(DatosTareaTradosDocs datosTareaTradosDocs) {
		String query = "UPDATE AA79B91S01 SET NUM_TOTAL_PAL_091=?, NUM_PAL_CONCOR_0_84_091=?, NUM_PAL_CONCOR_85_94_091=?, NUM_PAL_CONCOR_95_100_091=?, NUM_PAL_CONCOR_95_99_091=?, NUM_PAL_CONCOR_100_091=? WHERE ID_TAREA_091=? AND ID_FICHERO_TRADOS_091=?";
		this.getJdbcTemplate().update(query, datosTareaTradosDocs.getNumTotalPal(),
				datosTareaTradosDocs.getNumPalConcor084(), datosTareaTradosDocs.getNumPalConcor8594(),
				datosTareaTradosDocs.getNumPalConcor95100(), datosTareaTradosDocs.getNumPalConcor9599(), datosTareaTradosDocs.getNumPalConcor100(), datosTareaTradosDocs.getIdTarea(),
				datosTareaTradosDocs.getIdDocOrig());
		return datosTareaTradosDocs;
	}

	@Override
	public void remove(DatosTareaTradosDocs datosTareaTradosDocs) {
		String query = "DELETE FROM AA79B91S01 WHERE ID_TAREA_091=?";
		this.getJdbcTemplate().update(query, datosTareaTradosDocs.getIdTarea());
	}

	@Override()
	protected String getSelect() {
		StringBuilder query = new StringBuilder();

		query.append("SELECT t1.ID_TAREA_091 IDTAREA");
		query.append(", t1.ID_DOC_ORIG_091 IDDOCORIG");
		query.append(", t1.NUM_TOTAL_PAL_091 NUMTOTALPAL");
		query.append(", t1.NUM_PAL_CONCOR_0_84_091 NUMPALCONCOR084");
		query.append(", t1.NUM_PAL_CONCOR_85_94_091 NUMPALCONCOR8594");
		query.append(", t1.NUM_PAL_CONCOR_95_100_091 NUMPALCONCOR95100");
		query.append(", t1.NUM_PAL_CONCOR_95_99_091 NUMPALCONCOR9599");
		query.append(", t1.NUM_PAL_CONCOR_100_091 NUMPALCONCOR100");

		return query.toString();
	}

	@Override()
	protected String getFrom() {
		StringBuilder query = new StringBuilder();

		query.append(" FROM AA79B91S01 t1 ");

		return query.toString();
	}

	@Override()
	protected RowMapper<DatosTareaTradosDocs> getRwMap() {
		return this.rwMap;
	}

	protected RowMapper<DatosTareaTradosDocs> getRwMapWithNumPal() {
		return this.rwMapWithNumPal;
	}

	@Override()
	protected String[] getOrderBy() {
		return DatosTareaTradosDocsDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_TAREA_091 + "," + "ID_DOC_ORIG_091";
	}

	@Override()
	protected RowMapper<DatosTareaTradosDocs> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(DatosTareaTradosDocs bean, List<Object> params) {
		params.add(bean.getIdTarea());
		params.add(bean.getIdDocOrig());
		return " WHERE t1.ID_TAREA_091 = ? AND t1.ID_DOC_ORIG_091 = ?";
	}

	@Override()
	protected String getWhere(DatosTareaTradosDocs bean, List<Object> params) {

		return this.getWhereClause(bean, params);
	}

	@Override()
	protected String getWhereLike(DatosTareaTradosDocs bean, Boolean startsWith, List<Object> params, Boolean search) {

		return this.getWhereClause(bean, params);
	}

	/**
	 * Obtiene la clausula where
	 *
	 * @param bean
	 *            DatosTareaTradosDocs
	 * @param params
	 *            List<Object>
	 * @return String
	 */
	private String getWhereClause(DatosTareaTradosDocs bean, List<Object> params) {
		StringBuilder where = new StringBuilder(DatosTareaTradosDocsDaoImpl.STRING_BUILDER_INIT);

		if (bean != null) {
			where.append(SqlUtils.generarWhereIgual(ID_TAREA_091, bean.getIdTarea(), params));
			where.append(SqlUtils.generarWhereIgual("ID_DOC_ORIG_091", bean.getIdDocOrig(), params));
			where.append(SqlUtils.generarWhereIgual("NUM_PAL_CONCOR_0_84_091", bean.getNumPalConcor084(), params));
			where.append(SqlUtils.generarWhereIgual("NUM_PAL_CONCOR_85_94_091", bean.getNumPalConcor8594(), params));
			where.append(SqlUtils.generarWhereIgual("NUM_PAL_CONCOR_95_100_091", bean.getNumPalConcor95100(), params));
			where.append(SqlUtils.generarWhereIgual("NUM_PAL_CONCOR_95_99_091", bean.getNumPalConcor9599(), params));
			where.append(SqlUtils.generarWhereIgual("NUM_PAL_CONCOR_100_091", bean.getNumPalConcor100(), params));
		}

		return where.toString();
	}

	@Override
	public List<DatosTareaTradosDocs> getDocsTareaTrados(DatosTareaTradosDocs filterDocTareaTrados,
			JQGridRequestDto jqGridRequestDto) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getSelect());
		query.append(DaoConstants.SIGNO_COMA + " t2.NUM_PAL_SOLIC_056 " + DBConstants.NUMPALSOLIC);
		query.append(DaoConstants.SIGNO_COMA + " t2.NUM_PAL_IZO_056 " + DBConstants.NUMPALIZO);
		query.append(DaoConstants.SIGNO_COMA + " t2.NOMBRE_FICHERO_056 " + DBConstants.NOMBREFICHERO);
		query.append(this.getFrom(filterDocTareaTrados, params));
		query.append(DaoConstants.JOIN);
		query.append(DBConstants.TABLA_56 + " t2 ");
		query.append(DaoConstants.ON);
		query.append(" t1.ID_DOC_ORIG_091 " + DaoConstants.SIGNOIGUAL + " t2.ID_DOC_056 ");

		query.append(GenericoDaoImpl.DEFAULT_WHERE);
		query.append(this.getWhere(filterDocTareaTrados, params));

		if (jqGridRequestDto != null) {
			query = JQGridManager.getPaginationQuery(jqGridRequestDto, query, this.getOrderBy());
		}

		return this.getJdbcTemplate().query(query.toString(), this.getRwMapWithNumPal(), params.toArray());
	}

}
