package com.ejie.aa79b.dao;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.dao.support.DataAccessUtils;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.DocsAlinearRowMapper;
import com.ejie.aa79b.dao.mapper.DocumentosPostTraduccionBOERowMapper;
import com.ejie.aa79b.model.DocumentoTareaAdjunto;
import com.ejie.aa79b.model.DocumentosAlinear;
import com.ejie.aa79b.model.DocumentosPostTraduccionBOE;
import com.ejie.aa79b.model.FicheroDocExp;
import com.ejie.aa79b.model.Tareas;

/**
 * DocumentoTareaAdjuntoDaoImpl generated by UDA, 28-nov-2017 15:23:30.
 *
 * @author UDA
 */

@Repository
@Transactional
public class DocumentosGeneralDaoImpl extends GenericoDaoImpl<DocumentoTareaAdjunto> implements DocumentosGeneralDao {

	protected static final String ID_FICHERO_088 = "ID_FICHERO_088";
	protected static final String OID_FICHERO_088 = "OID_FICHERO_088";
	protected static final String WHERE_1 = " WHERE 1=1 ";
	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { ID_FICHERO_088, "NOMBRE_FICHERO_088" };

	protected static final String ID_TAREA_083 = "ID_TAREA_083";
	protected static final String ID_TAREA_086 = "ID_TAREA_086";
	protected static final String ID_DOC_083 = "ID_DOC_083";

	private RowMapper<DocumentoTareaAdjunto> rwMap = new RowMapper<DocumentoTareaAdjunto>() {
		@Override()
		public DocumentoTareaAdjunto mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			DocumentoTareaAdjunto documentoTareaAdjunto = new DocumentoTareaAdjunto(
					resultSet.getBigDecimal(ID_FICHERO_088));
			documentoTareaAdjunto.setNombre(resultSet.getString("NOMBRE_FICHERO_088"));
			documentoTareaAdjunto.setTitulo(resultSet.getString("TITULO_FICHERO_088"));
			documentoTareaAdjunto.setExtension(resultSet.getString("EXTENSION_FICHERO_088"));
			documentoTareaAdjunto.setContentType(resultSet.getString("CONTENT_TYPE_FICHERO_088"));
			documentoTareaAdjunto.setTamano(resultSet.getLong("TAMANO_FICHERO_088"));
			documentoTareaAdjunto.setEncriptado(resultSet.getString("IND_ENCRIPTADO_088"));
			documentoTareaAdjunto.setOid(resultSet.getString(OID_FICHERO_088));

			return documentoTareaAdjunto;
		}
	};

	private RowMapper<DocumentoTareaAdjunto> rwMapPK = new RowMapper<DocumentoTareaAdjunto>() {
		@Override()
		public DocumentoTareaAdjunto mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new DocumentoTareaAdjunto(resultSet.getBigDecimal(ID_FICHERO_088));
		}
	};

	private RowMapper<DocumentoTareaAdjunto> rwMap83 = new RowMapper<DocumentoTareaAdjunto>() {
		@Override()
		public DocumentoTareaAdjunto mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			DocumentoTareaAdjunto documentoTareaAdjunto = new DocumentoTareaAdjunto();
			documentoTareaAdjunto.setIdTarea(resultSet.getBigDecimal("IDTAREA"));
			documentoTareaAdjunto.setIdDocOriginal(resultSet.getBigDecimal("IDDOC"));

			return documentoTareaAdjunto;
		}
	};

	private RowMapper<DocumentosPostTraduccionBOE> rwMap86 = new DocumentosPostTraduccionBOERowMapper();

	private RowMapper<DocumentosAlinear> rwMapB6 = new DocsAlinearRowMapper();

	private RowMapper<FicheroDocExp> rwMapDocumentoTareaFinal = new RowMapper<FicheroDocExp>() {
		@Override()
		public FicheroDocExp mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			FicheroDocExp docFinal = new FicheroDocExp();
			docFinal.setIdDocInsertado(resultSet.getBigDecimal(DBConstants.IDFICHERO));
			docFinal.setNombre(resultSet.getNString(DBConstants.NOMBREFICHERO));
			docFinal.setOid(resultSet.getString(DBConstants.OIDFICHERO));
			return docFinal;
		}
	};

	private RowMapper<FicheroDocExp> rwMapIdDocumentoTareaFinal = new RowMapper<FicheroDocExp>() {
		@Override()
		public FicheroDocExp mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			FicheroDocExp docFinal = new FicheroDocExp();
			docFinal.setIdDocInsertado(resultSet.getBigDecimal("IDDOCFINAL"));
			return docFinal;
		}
	};

	/**
	 * Constructor de la clase.
	 */
	public DocumentosGeneralDaoImpl() {
		/* Constructor */
		super(DocumentoTareaAdjunto.class);
	}

	@Override()
	public DocumentoTareaAdjunto add(DocumentoTareaAdjunto documentoTareaAdjunto) {
		Long elID = this.getNextVal("AA79B88Q00");
		String query = "INSERT INTO AA79B88S01 (ID_FICHERO_088, NOMBRE_FICHERO_088, TITULO_FICHERO_088, EXTENSION_FICHERO_088, CONTENT_TYPE_FICHERO_088, TAMANO_FICHERO_088, IND_ENCRIPTADO_088,OID_FICHERO_088 ) VALUES (?,?,?,?,?,?,?,?)";

		this.getJdbcTemplate().update(query, elID, documentoTareaAdjunto.getNombre(), documentoTareaAdjunto.getTitulo(),
				documentoTareaAdjunto.getExtension(), documentoTareaAdjunto.getContentType(),
				documentoTareaAdjunto.getTamano(), documentoTareaAdjunto.getEncriptado(),
				documentoTareaAdjunto.getOid());
		documentoTareaAdjunto.setIdFichero(new BigDecimal(elID));
		return documentoTareaAdjunto;
	}

	@Override()
	public DocumentoTareaAdjunto add83(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "INSERT INTO AA79B83S01 (ID_TAREA_083, ID_DOC_083) VALUES (?,?)";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal());
		return documentoTareaAdjunto;
	}

	@Override()
	public DocumentosPostTraduccionBOE add86(DocumentosPostTraduccionBOE documentosPostTraduccionBOE) {
		String query = "INSERT INTO AA79B86S01 (ID_TAREA_086, IND_CORRECCIONES_086, "
				+ "ID_FICHERO_INFORME_086, FECHA_ALTA_INFORME_086, ID_FICHERO_DOC_086, FECHA_ALTA_DOC_086) VALUES (?,?,?,?,?,?)";

		this.getJdbcTemplate().update(query, documentosPostTraduccionBOE.getIdTarea(),
				documentosPostTraduccionBOE.getIndCorreciones(), documentosPostTraduccionBOE.getIdFicheroInforme(),
				documentosPostTraduccionBOE.getFechaAltaInforme(), documentosPostTraduccionBOE.getIdFicheroDoc(),
				documentosPostTraduccionBOE.getFechaAltaDoc());

		return documentosPostTraduccionBOE;
	}

	@Override()
	public DocumentosPostTraduccionBOE update86(DocumentosPostTraduccionBOE documentosPostTraduccionBOE,
			Integer destinoUpload) {
		String campoFichero = "";
		String campoFecha = "";
		BigDecimal idFichero = new BigDecimal(Constants.CERO);
		Date fechaAltaFichero = new Date();
		if (Constants.UNO == destinoUpload) {
			// informe
			campoFichero = " ID_FICHERO_INFORME_086 ";
			campoFecha = " FECHA_ALTA_INFORME_086 ";
			idFichero = documentosPostTraduccionBOE.getIdFicheroInforme();
			fechaAltaFichero = documentosPostTraduccionBOE.getFechaAltaInforme();
		} else {
			// documento
			campoFichero = " ID_FICHERO_DOC_086 ";
			campoFecha = " FECHA_ALTA_DOC_086 ";
			idFichero = documentosPostTraduccionBOE.getIdFicheroDoc();
			fechaAltaFichero = documentosPostTraduccionBOE.getFechaAltaDoc();
		}
		String query = "UPDATE AA79B86S01 SET " + campoFichero + "=?, " + campoFecha + "=? WHERE ID_TAREA_086=?";
		this.getJdbcTemplate().update(query, idFichero, fechaAltaFichero, documentosPostTraduccionBOE.getIdTarea());
		return documentosPostTraduccionBOE;
	}

	@Override()
	public Integer updateIdFichero86(DocumentosPostTraduccionBOE documentosPostTraduccionBOE) {
		String query = "UPDATE AA79B86S01 SET ID_FICHERO_INFORME_086=?, FECHA_ALTA_INFORME_086=? WHERE ID_TAREA_086=?";
		return this.getJdbcTemplate().update(query, documentosPostTraduccionBOE.getIdFicheroInforme(),
				documentosPostTraduccionBOE.getFechaAltaInforme(), documentosPostTraduccionBOE.getIdTarea());
	}

	@Override()
	public Integer updateIdDoc86(DocumentosPostTraduccionBOE documentosPostTraduccionBOE) {
		String query = "UPDATE AA79B86S01 SET ID_FICHERO_DOC_086=?, FECHA_ALTA_DOC_086=? WHERE ID_TAREA_086=?";
		return this.getJdbcTemplate().update(query, documentosPostTraduccionBOE.getIdFicheroDoc(),
				documentosPostTraduccionBOE.getFechaAltaDoc(), documentosPostTraduccionBOE.getIdTarea());
	}

	@Override()
	public DocumentosAlinear addB6(DocumentosAlinear documentosAlinear) {
		String query = "INSERT INTO AA79BB6S01 (ID_TAREA_0B6, IND_CORRECCIONES_0B6, "
				+ "ID_FICHERO_LERROKO_0B6, FECHA_ALTA_LERROKO_0B6) VALUES (?,?,?,?)";
		this.getJdbcTemplate().update(query, documentosAlinear.getIdTarea(), documentosAlinear.getIndCorreciones(),
				documentosAlinear.getIdFicheroLerroko(), documentosAlinear.getFechaAltaLerroko());

		return documentosAlinear;
	}

	@Override()
	public DocumentosAlinear updateB6(DocumentosAlinear documentosAlinear) {
		String query = "UPDATE AA79BB6S01 SET ID_FICHERO_LERROKO_0B6=?, FECHA_ALTA_LERROKO_0B6=? WHERE ID_TAREA_0B6=?";
		this.getJdbcTemplate().update(query, documentosAlinear.getIdFicheroLerroko(),
				documentosAlinear.getFechaAltaLerroko(), documentosAlinear.getIdTarea());
		return documentosAlinear;
	}

	@Override()
	public DocumentosAlinear consultaFicherosAlinear(BigDecimal idTarea) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder("SELECT ");
		query.append("t1.ID_TAREA_0B6 IDTAREA ");
		query.append(", t1.IND_CORRECCIONES_0B6 INDCORRECCIONES0B6 ");
		query.append(", t1.ID_FICHERO_LERROKO_0B6 IDFICHEROLERROKO0B6 ");
		query.append(", t1.FECHA_ALTA_LERROKO_0B6 FECHAALTALERROKO086 ");
		query.append(", p1.ID_FICHERO_088 IDFICHEROINFORME088 ");
		query.append(", p1.TITULO_FICHERO_088 TITULOFICHEROINFORME088 ");
		query.append(", p1.EXTENSION_FICHERO_088 EXTENSIONFICHEROINFORME088 ");
		query.append(", p1.CONTENT_TYPE_FICHERO_088 CONTENTTYPEFICHEROINFORME088 ");
		query.append(", p1.TAMANO_FICHERO_088 TAMANOFICHEROINFORME088 ");
		query.append(", p1.IND_ENCRIPTADO_088 INDENCRIPTADOINFORME088 ");
		query.append(", p1.OID_FICHERO_088 OIDFICHEROINFORME088 ");
		query.append(", p1.NOMBRE_FICHERO_088 NOMBREFICHEROINFORME088 ");
		query.append("FROM AA79BB6S01 t1 ");
		query.append("LEFT JOIN AA79B88S01 p1 ");
		query.append("ON t1.ID_FICHERO_LERROKO_0B6 = p1.ID_FICHERO_088 ");

		query.append(GenericoDaoImpl.DEFAULT_WHERE);
		query.append(SqlUtils.generarWhereIgual("ID_TAREA_0B6", idTarea, params));

		List<DocumentosAlinear> listDocu = this.getJdbcTemplate().query(query.toString(), this.rwMapB6,
				params.toArray());
		return DataAccessUtils.uniqueResult(listDocu);
	}

	@Override
	public Integer actualizarValorIndCorreccionesAlinear(BigDecimal idTarea, String indCorrecciones) {
		StringBuilder update = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		update.append(DaoConstants.UPDATE + DBConstants.TABLA_B6 + " t1 ");
		update.append(DaoConstants.SET + " t1.IND_CORRECCIONES_0B6 " + DaoConstants.SIGNOIGUAL_INTERROGACION);
		update.append(DaoConstants.WHERE + " t1.ID_TAREA_0B6 " + DaoConstants.SIGNOIGUAL_INTERROGACION);
		return this.getJdbcTemplate().update(update.toString(), indCorrecciones, idTarea);
	}

	@Override()
	public DocumentosPostTraduccionBOE consultaFicherosBOE(BigDecimal idTarea) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getSelect86());
		query.append(this.getFrom86());

		query.append(GenericoDaoImpl.DEFAULT_WHERE);
		query.append(this.getWhere86(idTarea, params));

		List<DocumentosPostTraduccionBOE> listBOE = this.getJdbcTemplate().query(query.toString(), this.rwMap86,
				params.toArray());
		return DataAccessUtils.uniqueResult(listBOE);
	}

	@Override()
	public DocumentoTareaAdjunto add92(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "INSERT INTO AA79B92S01 (ID_TAREA_092, ID_DOC_ORIG_092, ID_FICHERO_FINAL_092, IND_VISIBLE_092, FECHA_ALTA_092, ID_DOC_FINAL_ORIG_092) VALUES (?,?,?,?,?,?)";

		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal(), documentoTareaAdjunto.getIdFichero(), Constants.NO,
				new Date(), documentoTareaAdjunto.getIdDocOriginalFinal());
		return documentoTareaAdjunto;
	}

	@Override()
	public Integer updateIndVisible92(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B92S01 SET IND_VISIBLE_092=? WHERE ID_TAREA_092=?";
		return this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIndVisible(),
				documentoTareaAdjunto.getIdTarea());
	}

	@Override()
	public DocumentoTareaAdjunto add96(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "INSERT INTO AA79B96S01 (ID_TAREA_096, ID_FICHERO_XLIFF_096, FECHA_ALTA_096) VALUES (?,?,?)";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdFichero(),
				new Date());
		return documentoTareaAdjunto;
	}

	@Override()
	public Integer updateIdFichero96(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B96S01 SET ID_FICHERO_XLIFF_096=? WHERE ID_TAREA_096=?";
		return this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdFichero(),
				documentoTareaAdjunto.getIdTarea());
	}

	@Override()
	public DocumentoTareaAdjunto update(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B88S01 SET NOMBRE_FICHERO_088=?, TITULO_FICHERO_088=?, EXTENSION_FICHERO_088=?, CONTENT_TYPE_FICHERO_088=?, TAMANO_FICHERO_088=?, IND_ENCRIPTADO_088=?, OID_FICHERO_088=? WHERE ID_FICHERO_088=?";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getNombre(), documentoTareaAdjunto.getTitulo(),
				documentoTareaAdjunto.getExtension(), documentoTareaAdjunto.getContentType(),
				documentoTareaAdjunto.getTamano(), documentoTareaAdjunto.getEncriptado(),
				documentoTareaAdjunto.getOid(), documentoTareaAdjunto.getIdFichero());
		return documentoTareaAdjunto;
	}

	@Override()
	public int updateDocOriginalFinal(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B92S01 SET ID_DOC_FINAL_ORIG_092 = ?, ESTADO_FIRMA_092=?, ID_DOC_FIRMADO_ORIG_092=NULL WHERE ID_TAREA_092=? AND ID_DOC_ORIG_092=?";
		return this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdDocOriginalFinal(), 0,
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
	}

	@Override()
	public int updateAllDocOriginalFinal(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B92S01 SET ID_DOC_FINAL_ORIG_092 = ? WHERE ID_TAREA_092=? ";
		return this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdDocOriginalFinal(),
				documentoTareaAdjunto.getIdTarea());
	}

	@Override()
	public DocumentoTareaAdjunto update92(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B92S01 SET ID_TAREA_092=?, ID_DOC_ORIG_092=?, ID_FICHERO_FINAL_092=?, ESTADO_FIRMA_092=?, ID_DOC_FIRMADO_ORIG_092=NULL,ID_DOC_FIRMADO_FINAL_092=NULL WHERE ID_TAREA_092=? AND ID_DOC_ORIG_092=?";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal(), documentoTareaAdjunto.getIdFichero(), 0,
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
		return documentoTareaAdjunto;
	}

	@Override()
	public DocumentoTareaAdjunto updateEstadoFirma(DocumentoTareaAdjunto documentoTareaAdjunto, Integer nuevoEstado) {
		String query = "UPDATE AA79B92S01 SET ESTADO_FIRMA_092=?, ID_DOC_FIRMADO_ORIG_092 = NULL, ID_DOC_FIRMADO_FINAL_092=NULL WHERE ID_TAREA_092=? AND ID_DOC_ORIG_092=?";
		this.getJdbcTemplate().update(query, nuevoEstado, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal());
		documentoTareaAdjunto.setEstadoFirma(nuevoEstado);
		return documentoTareaAdjunto;
	}
	// llamado desde WS

	@Override()
	public Integer updateIdFichero92(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B92S01 SET ID_FICHERO_FINAL_092=?, ESTADO_FIRMA_092=?, ID_DOC_FIRMADO_ORIG_092=NULL,ID_DOC_FIRMADO_FINAL_092=NULL WHERE ID_TAREA_092=?";
		return this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdFichero(), 0,
				documentoTareaAdjunto.getIdTarea());
	}

	@Override()
	public DocumentoTareaAdjunto cambiarvisibilidad(DocumentoTareaAdjunto documentoTareaAdjunto, String numeroTabla) {
		StringBuilder query = new StringBuilder();

		query.append("UPDATE AA79B").append(numeroTabla).append("S01");
		query.append(" SET IND_VISIBLE_0").append(numeroTabla).append("=?");
		query.append(" WHERE ID_TAREA_0").append(numeroTabla).append("=?");
		query.append(" AND ID_DOC_ORIG_0").append(numeroTabla).append("=?");

		this.getJdbcTemplate().update(query.toString(), documentoTareaAdjunto.getIndVisible(),
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
		return documentoTareaAdjunto;
	}

	@Override()
	public void remove(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "DELETE FROM AA79B88S01 WHERE ID_FICHERO_088=?";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdFichero());
	}

	@Override()
	public void remove(BigDecimal idFichero) {
		String query = "DELETE FROM AA79B88S01 WHERE ID_FICHERO_088=?";
		this.getJdbcTemplate().update(query, idFichero);
	}

	@Override()
	public void remove83(BigDecimal idDocOriginal) {
		String query = "DELETE FROM AA79B83S01 WHERE ID_DOC_083=?";
		this.getJdbcTemplate().update(query, idDocOriginal);
	}

	//
	// Hay ficheros finales firmados?
	// si los hay, hay que borrar de la tabla 88 y del PID...
	@Override()
	public void remove92(BigDecimal idDocOriginal) {
		String query = "DELETE FROM AA79B92S01 WHERE ID_DOC_ORIG_092=?";
		this.getJdbcTemplate().update(query, idDocOriginal);
	}

	@Override()
	public Integer remove96(BigDecimal idDocXliff) {
		String query = "DELETE FROM AA79B96S01 WHERE ID_FICHERO_XLIFF_096 = ?";
		return this.getJdbcTemplate().update(query, idDocXliff);
	}

	@Override()
	public void removeDocumentosTarea(BigDecimal idTarea) {
		String query = "DELETE FROM AA79B83S01 WHERE ID_TAREA_083=?";
		this.getJdbcTemplate().update(query, idTarea);
	}

	/**
	 * The method getQuery.
	 *
	 * @return String OJO CON ESTE MÉTOD
	 */
	@Override()
	protected String getSelect() {
		StringBuilder sb = new StringBuilder();
		sb.append(
				"SELECT t1.ID_FICHERO_088 ID_FICHERO_088, t1.NOMBRE_FICHERO_088 NOMBRE_FICHERO_088, t1.TITULO_FICHERO_088 TITULO_FICHERO_088");
		sb.append(
				", t1.EXTENSION_FICHERO_088 EXTENSION_FICHERO_088, t1.CONTENT_TYPE_FICHERO_088 CONTENT_TYPE_FICHERO_088, t1.TAMANO_FICHERO_088 TAMANO_FICHERO_088");
		sb.append(",t1.IND_ENCRIPTADO_088 IND_ENCRIPTADO_088, t1.OID_FICHERO_088 OID_FICHERO_088");
		return sb.toString();
	}

	protected String getSelect83() {
		StringBuilder sb = new StringBuilder();

		sb.append("SELECT ");
		sb.append("t1.ID_TAREA_083 IDTAREA ");
		sb.append(", t1.ID_DOC_083 IDDOC ");

		return sb.toString();
	}

	protected String getSelect86() {
		StringBuilder sb = new StringBuilder();

		sb.append("SELECT ");
		sb.append("b1.ID_TAREA_086 IDTAREA ");
		sb.append(", b1.IND_CORRECCIONES_086 INDCORRECCIONES086 ");
		sb.append(", b1.ID_FICHERO_INFORME_086 IDFICHEROINFORME086 ");
		sb.append(", b1.FECHA_ALTA_INFORME_086 FECHAALTAINFORME086 ");
		sb.append(", b1.ID_FICHERO_DOC_086 IDFICHERODOC086 ");
		sb.append(", b1.FECHA_ALTA_DOC_086 FECHAALTADOC086 ");

		sb.append(", d1.ID_FICHERO_088 IDFICHEROINFORME088 ");
		sb.append(", d1.TITULO_FICHERO_088 TITULOFICHEROINFORME088 ");
		sb.append(", d1.EXTENSION_FICHERO_088 EXTENSIONFICHEROINFORME088 ");
		sb.append(", d1.CONTENT_TYPE_FICHERO_088 CONTENTTYPEFICHEROINFORME088 ");
		sb.append(", d1.TAMANO_FICHERO_088 TAMANOFICHEROINFORME088 ");
		sb.append(", d1.IND_ENCRIPTADO_088 INDENCRIPTADOINFORME088 ");
		sb.append(", d1.OID_FICHERO_088 OIDFICHEROINFORME088 ");
		sb.append(", d1.NOMBRE_FICHERO_088 NOMBREFICHEROINFORME088 ");

		sb.append(", p1.ID_FICHERO_088 IDFICHERODOC088 ");
		sb.append(", p1.TITULO_FICHERO_088 TITULOFICHERODOC088 ");
		sb.append(", p1.EXTENSION_FICHERO_088 EXTENSIONFICHERODOC088 ");
		sb.append(", p1.CONTENT_TYPE_FICHERO_088 CONTENTTYPEFICHERODOC088 ");
		sb.append(", p1.TAMANO_FICHERO_088 TAMANOFICHERODOC088 ");
		sb.append(", p1.IND_ENCRIPTADO_088 INDENCRIPTADODOC088 ");
		sb.append(", p1.OID_FICHERO_088 OIDFICHERODOC088 ");
		sb.append(", p1.NOMBRE_FICHERO_088 NOMBREFICHERODOC088 ");

		return sb.toString();
	}

	@Override()
	protected String getFrom() {
		return "  FROM AA79B88S01 t1 ";
	}

	protected String getFrom83() {
		return "  FROM AA79B83S01 t1 ";
	}

	protected String getFrom86() {
		StringBuilder sb = new StringBuilder();
		sb.append("FROM AA79B86S01 b1 ");
		sb.append("LEFT JOIN AA79B88S01 p1 ");
		sb.append("ON b1.ID_FICHERO_DOC_086 = p1.ID_FICHERO_088 ");
		sb.append("LEFT JOIN AA79B88S01 d1 ");
		sb.append("ON b1.ID_FICHERO_INFORME_086 = d1.ID_FICHERO_088 ");
		return sb.toString();
	}

	@Override()
	protected RowMapper<DocumentoTareaAdjunto> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return DocumentosGeneralDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_FICHERO_088;
	}

	@Override()
	protected RowMapper<DocumentoTareaAdjunto> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(DocumentoTareaAdjunto bean, List<Object> params) {
		params.add(bean.getIdFichero());
		return " WHERE t1.ID_FICHERO_088 = ? ";
	}

	@Override
	protected String getWhere(DocumentoTareaAdjunto bean, List<Object> params) {
		StringBuilder where = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_FICHERO_088, bean.getIdFichero(), params));
		where.append(SqlUtils.generarWhereIgual(OID_FICHERO_088, bean.getOid(), params));
		return where.toString();
	}

	protected String getWhere83(DocumentoTareaAdjunto bean, List<Object> params) {
		StringBuilder where = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_TAREA_083, bean.getIdTarea(), params));
		where.append(SqlUtils.generarWhereIgual(ID_DOC_083, bean.getIdDocOriginal(), params));
		return where.toString();
	}

	protected String getWhere86(BigDecimal idTarea, List<Object> params) {
		StringBuilder where = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_TAREA_086, idTarea, params));
		return where.toString();
	}

	@Override
	protected String getWhereLike(DocumentoTareaAdjunto bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_FICHERO_088, bean.getIdFichero(), params));
		where.append(SqlUtils.generarWhereIgual(OID_FICHERO_088, bean.getOid(), params));
		return where.toString();
	}

	@Override
	public DocumentoTareaAdjunto add87(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "INSERT INTO AA79B87S01 (ID_TAREA_087, ID_DOC_ORIG_087, ID_FICHERO_TRADUCIDO_087,  FECHA_ALTA_087) VALUES (?,?,?,?)";

		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal(), documentoTareaAdjunto.getIdFichero(), new Date());
		return documentoTareaAdjunto;
	}

	@Override
	public DocumentoTareaAdjunto addC8(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "INSERT INTO AA79BC8S01 (ID_TAREA_0C8, ID_FICHERO_0C8) VALUES (?,?)";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdFichero());
		return documentoTareaAdjunto;
	}

	@Override
	public void removeC8(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "DELETE FROM AA79BC8S01 WHERE ID_TAREA_0C8 = ?";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea());
	}

	@Override
	public DocumentoTareaAdjunto update87(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B87S01 SET ID_TAREA_087=?, ID_DOC_ORIG_087=?, ID_FICHERO_TRADUCIDO_087=? WHERE ID_TAREA_087=? AND ID_DOC_ORIG_087=?";
		this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal(), documentoTareaAdjunto.getIdFichero(),
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
		return documentoTareaAdjunto;
	}

	@Override
	public Integer updateIdFichero87(DocumentoTareaAdjunto documentoTareaAdjunto) {
		String query = "UPDATE AA79B87S01 SET ID_FICHERO_TRADUCIDO_087=? WHERE ID_TAREA_087=? AND ID_DOC_ORIG_087=?";
		return this.getJdbcTemplate().update(query, documentoTareaAdjunto.getIdFichero(),
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
	}

	@Override()
	public void remove87(BigDecimal idDocOriginal) {
		String query = "DELETE FROM AA79B87S01 WHERE ID_DOC_ORIG_087=?";
		this.getJdbcTemplate().update(query, idDocOriginal);
	}

	@Override()
	public List<DocumentoTareaAdjunto> findAllDocumentosTarea(DocumentoTareaAdjunto bean) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getSelect83());
		query.append(this.getFrom83());

		query.append(GenericoDaoImpl.DEFAULT_WHERE);
		query.append(this.getWhere83(bean, params));

		return this.getJdbcTemplate().query(query.toString(), this.rwMap83, params.toArray());
	}

	@Override()
	public String getDocumentosTareaStr(BigDecimal idTarea) {
		StringBuilder idDocs = new StringBuilder();

		DocumentoTareaAdjunto docTarea = new DocumentoTareaAdjunto();
		docTarea.setIdTarea(idTarea);

		List<DocumentoTareaAdjunto> lstDocs = this.findAllDocumentosTarea(docTarea);

		if (lstDocs != null && !lstDocs.isEmpty()) {
			for (int i = 0; i < lstDocs.size(); i++) {
				DocumentoTareaAdjunto doc = lstDocs.get(i);
				if (i != 0) {
					idDocs.append(";");
				}
				idDocs.append(doc.getIdDocOriginal());
			}
		}

		return idDocs.toString();
	}

	@Override
	public boolean isRowCreated(BigDecimal idTarea, BigDecimal idDocOrig, int numeroTabla) {
		StringBuilder query = new StringBuilder();
		List<Object> params = new ArrayList<Object>();
		params.add(idTarea);
		params.add(idDocOrig);
		query.append(DaoConstants.SELECT_COUNT);
		query.append(DaoConstants.FROM);
		query.append("AA79B").append(numeroTabla).append("S01");
		query.append(DaoConstants.WHERE);
		query.append(" ID_TAREA_0").append(numeroTabla).append(DaoConstants.BLANK);
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
		query.append(DaoConstants.AND);
		query.append(" ID_DOC_ORIG_0").append(numeroTabla).append(DaoConstants.BLANK);
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
		Integer result = this.getJdbcTemplate().queryForObject(query.toString(), params.toArray(), Integer.class);
		return result > Constants.CERO;
	}

	@Override
	public DocumentoTareaAdjunto add93(DocumentoTareaAdjunto documentoTareaAdjunto) {
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.INSERT_INTO);
		query.append(DBConstants.TABLA_93);
		query.append(DaoConstants.ABRIR_PARENTESIS);
		query.append(" ID_TAREA_093, ID_DOC_ORIG_093, ID_FICHERO_JUSTIFICANTE_093,  IND_VISIBLE_093, FECHA_ALTA_093 ");
		query.append(DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.VALUES);
		query.append(DaoConstants.ABRIR_PARENTESIS);
		query.append(DaoConstants.SIGNOINTERROGACION);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.SIGNOINTERROGACION);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.SIGNOINTERROGACION);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.SIGNOINTERROGACION);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.SIGNOINTERROGACION);
		query.append(DaoConstants.CERRAR_PARENTESIS);

		this.getJdbcTemplate().update(query.toString(), documentoTareaAdjunto.getIdTarea(),
				documentoTareaAdjunto.getIdDocOriginal(), documentoTareaAdjunto.getIdFichero(),
				documentoTareaAdjunto.getIndVisible() != null ? documentoTareaAdjunto.getIndVisible() : Constants.NO,
				new Date());
		return documentoTareaAdjunto;
	}

	@Override
	public DocumentoTareaAdjunto update93(DocumentoTareaAdjunto documentoTareaAdjunto) {
		StringBuilder query = new StringBuilder();
		montarQueryUpdate93(query);
		this.getJdbcTemplate().update(query.toString(), documentoTareaAdjunto.getIdFichero(),
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
		return documentoTareaAdjunto;
	}

	@Override
	public Integer updateIdFichero93(DocumentoTareaAdjunto documentoTareaAdjunto) {
		StringBuilder query = new StringBuilder();
		montarQueryUpdate93(query);
		return this.getJdbcTemplate().update(query.toString(), documentoTareaAdjunto.getIdFichero(),
				documentoTareaAdjunto.getIdTarea(), documentoTareaAdjunto.getIdDocOriginal());
	}

	/**
	 * @param query
	 */
	private void montarQueryUpdate93(StringBuilder query) {
		query.append(DaoConstants.UPDATE);
		query.append(DBConstants.TABLA_93);
		query.append(DaoConstants.SET);
		query.append(" ID_FICHERO_JUSTIFICANTE_093 ");
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
		query.append(DaoConstants.WHERE);
		query.append(" ID_TAREA_093 ");
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
		query.append(DaoConstants.AND);
		query.append(" ID_DOC_ORIG_093 ");
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
	}

	@Override
	public void remove93(BigDecimal idDocOriginal) {
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.DELETE);
		query.append(DaoConstants.FROM);
		query.append(DBConstants.TABLA_93);
		query.append(DaoConstants.WHERE);
		query.append(" ID_DOC_ORIG_093 ");
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
		this.getJdbcTemplate().update(query.toString(), idDocOriginal);

	}

	@Override
	public Integer eliminarJustificante(BigDecimal idficheroJustificante) {
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.DELETE);
		query.append(DaoConstants.FROM);
		query.append(DBConstants.TABLA_93);
		query.append(DaoConstants.WHERE);
		query.append(" ID_FICHERO_JUSTIFICANTE_093 ");
		query.append(DaoConstants.SIGNOIGUAL_INTERROGACION);
		return this.getJdbcTemplate().update(query.toString(), idficheroJustificante);
	}

	@Override
	public Integer actualizarValorIndCorreccionesBOE(BigDecimal idTarea, String indCorrecciones) {
		StringBuilder update = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		update.append(DaoConstants.UPDATE + DBConstants.TABLA_86 + " t1 ");
		update.append(DaoConstants.SET + " t1.IND_CORRECCIONES_086 " + DaoConstants.SIGNOIGUAL_INTERROGACION);
		update.append(DaoConstants.WHERE + " t1.ID_TAREA_086 " + DaoConstants.SIGNOIGUAL_INTERROGACION);
		return this.getJdbcTemplate().update(update.toString(), indCorrecciones, idTarea);
	}

	@Override
	public Integer remove87WithIdFicheroTraducido(BigDecimal idFichero) {
		String query = "DELETE FROM AA79B87S01 WHERE ID_FICHERO_TRADUCIDO_087=?";
		return this.getJdbcTemplate().update(query, idFichero);
	}

	@Override
	public Boolean oidEstaEn88OEn56(String oid) {
		Boolean esta = false;
		StringBuilder selectCount = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		selectCount.append(DaoConstants.SELECT_COUNT + DaoConstants.FROM + DaoConstants.DUAL);
		selectCount.append(DaoConstants.WHERE + DaoConstants.EXISTS + DaoConstants.ABRIR_PARENTESIS);
		selectCount.append(DaoConstants.SELECT + Constants.UNO + DaoConstants.FROM + DBConstants.TABLA_88 + " t1 ");
		selectCount.append(DaoConstants.WHERE + " t1.OID_FICHERO_088 " + DaoConstants.SIGNOIGUAL_INTERROGACION);
		selectCount.append(
				DaoConstants.CERRAR_PARENTESIS + DaoConstants.OR + DaoConstants.EXISTS + DaoConstants.ABRIR_PARENTESIS);
		selectCount.append(DaoConstants.SELECT + Constants.UNO + DaoConstants.FROM + DBConstants.TABLA_56 + " t2 ");
		selectCount.append(DaoConstants.WHERE + " t2.OID_FICHERO_056 " + DaoConstants.SIGNOIGUAL_INTERROGACION
				+ DaoConstants.CERRAR_PARENTESIS);
		List<Object> params = new ArrayList<Object>();
		params.add(oid);
		params.add(oid);
		Integer countEsta = this.getJdbcTemplate().queryForObject(selectCount.toString(), Integer.class,
				params.toArray());
		if (countEsta > 0) {
			esta = true;
		}
		return esta;
	}

	@Override
	public List<FicheroDocExp> getIdDocumentosFinales(BigDecimal idTarea) {
		StringBuilder queryIDF = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> paramsIDF = new ArrayList<Object>();
		queryIDF.append(" SELECT COALESCE(t1.ID_DOC_FIRMADO_FINAL_092,t1.ID_FICHERO_FINAL_092) IDDOCFINAL");
		queryIDF.append(" FROM AA79B92S01 t1 ");
		queryIDF.append(DaoConstants.WHERE_1_1);
		queryIDF.append(SqlUtils.generarWhereIgual("t1." + DBConstants.ID_TAREA_092, idTarea, paramsIDF));
		return this.getJdbcTemplate().query(queryIDF.toString(), this.rwMapIdDocumentoTareaFinal, paramsIDF.toArray());
	}

	@Override
	public List<FicheroDocExp> getIdDocumentosFinalesR02t(BigDecimal idTarea) {
		StringBuilder queryIDF = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> paramsIDF = new ArrayList<Object>();
		queryIDF.append(" SELECT t1.ID_DOC_ORIG_092 IDDOCFINAL ");
		queryIDF.append(" FROM AA79B92S01 t1 ");
		queryIDF.append(DaoConstants.WHERE_1_1);
		queryIDF.append(SqlUtils.generarWhereIgual("t1." + DBConstants.ID_TAREA_092, idTarea, paramsIDF));
		queryIDF.append(SqlUtils.generarWhereIsNotNull("t1." + DBConstants.ID_DOC_ORIG_092));
		queryIDF.append(" UNION ALL");
		queryIDF.append(" SELECT t1.ID_FICHERO_FINAL_092 IDDOCFINAL ");
		queryIDF.append(" FROM AA79B92S01 t1 ");
		queryIDF.append(DaoConstants.WHERE_1_1);
		queryIDF.append(SqlUtils.generarWhereIgual("t1." + DBConstants.ID_TAREA_092, idTarea, paramsIDF));
		queryIDF.append(SqlUtils.generarWhereIsNotNull("t1." + DBConstants.ID_FICHERO_FINAL_092));
		queryIDF.append(" UNION ALL");
		queryIDF.append(" SELECT t1.ID_DOC_FIRMADO_FINAL_092 IDDOCFINAL ");
		queryIDF.append(" FROM AA79B92S01 t1 ");
		queryIDF.append(DaoConstants.WHERE_1_1);
		queryIDF.append(SqlUtils.generarWhereIgual("t1." + DBConstants.ID_TAREA_092, idTarea, paramsIDF));
		queryIDF.append(SqlUtils.generarWhereIsNotNull("t1." + DBConstants.ID_DOC_FIRMADO_FINAL_092));
		queryIDF.append(" UNION ALL");
		queryIDF.append(" SELECT t1.ID_DOC_FIRMADO_ORIG_092 IDDOCFINAL ");
		queryIDF.append(" FROM AA79B92S01 t1 ");
		queryIDF.append(DaoConstants.WHERE_1_1);
		queryIDF.append(SqlUtils.generarWhereIgual("t1." + DBConstants.ID_TAREA_092, idTarea, paramsIDF));
		queryIDF.append(SqlUtils.generarWhereIsNotNull("t1." + DBConstants.ID_DOC_FIRMADO_ORIG_092));
		return this.getJdbcTemplate().query(queryIDF.toString(), this.rwMapIdDocumentoTareaFinal, paramsIDF.toArray());
	}

	@Override
	public FicheroDocExp getDatosFichero(FicheroDocExp docFinal) {
		StringBuilder queryDF = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> paramsDF = new ArrayList<Object>();
		queryDF.append(" SELECT  t1." + DBConstants.ID_FICHERO_088 + " " + DBConstants.IDFICHERO);
		queryDF.append(" ,t1." + DBConstants.NOMBRE_FICHERO_088 + " " + DBConstants.NOMBREFICHERO);
		queryDF.append(" , t1." + DBConstants.OID_FICHERO_088 + " " + DBConstants.OIDFICHERO);
		queryDF.append(" FROM AA79B88S01 t1 ");
		queryDF.append(DaoConstants.WHERE_1_1);
		queryDF.append(
				SqlUtils.generarWhereIgual("t1." + DBConstants.ID_FICHERO_088, docFinal.getIdDocInsertado(), paramsDF));
		return this.getJdbcTemplate().queryForObject(queryDF.toString(), this.rwMapDocumentoTareaFinal,
				paramsDF.toArray());
	}

	@Override
	public FicheroDocExp getDatosFicheroOriginal(FicheroDocExp docFinal) {
		StringBuilder queryDF = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> paramsDF = new ArrayList<Object>();
		queryDF.append(" SELECT  t1." + DBConstants.ID_DOC_056 + " " + DBConstants.IDFICHERO);
		queryDF.append(" ,t1." + DBConstants.NOMBRE_FICHERO_056 + " " + DBConstants.NOMBREFICHERO);
		queryDF.append(" , t1." + DBConstants.OID_FICHERO_056 + " " + DBConstants.OIDFICHERO);
		queryDF.append(" FROM AA79B56S01 t1 ");
		queryDF.append(DaoConstants.WHERE_1_1);
		queryDF.append(
				SqlUtils.generarWhereIgual("t1." + DBConstants.ID_DOC_056, docFinal.getIdDocInsertado(), paramsDF));
		return this.getJdbcTemplate().queryForObject(queryDF.toString(), this.rwMapDocumentoTareaFinal,
				paramsDF.toArray());
	}

	@Override
	public DocumentoTareaAdjunto updateD1(DocumentoTareaAdjunto docTarea) {
		StringBuilder queryD1 = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		queryD1.append(" UPDATE AA79BD1S01 SET ID_FICHERO_0D1 = ? WHERE ID_TAREA_0D1 = ? ");
		this.getJdbcTemplate().update(queryD1.toString(), docTarea.getIdFichero(), docTarea.getIdTarea());
		return docTarea;
	}

	@Override
	public boolean isRowCreatedD1(BigDecimal idTarea) {
		StringBuilder query = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> params = new ArrayList<Object>();
		params.add(idTarea);
		query.append(" SELECT COUNT(1) FROM AA79BD1S01 ");
		query.append(" WHERE ID_TAREA_0D1 = ? ");
		Integer result = this.getJdbcTemplate().queryForObject(query.toString(), params.toArray(), Integer.class);
		return result > Constants.CERO;
	}

	@Override
	public DocumentoTareaAdjunto addD1(DocumentoTareaAdjunto docTarea) {
		StringBuilder query = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> params = new ArrayList<Object>();
		params.add(docTarea.getIdTarea());
		params.add(docTarea.getIdFichero());
		query.append(" INSERT INTO AA79BD1S01 (ID_TAREA_0D1, ID_FICHERO_0D1) VALUES (?,?)");
		this.getJdbcTemplate().update(query.toString(), docTarea.getIdTarea(), docTarea.getIdFichero());
		return docTarea;
	}


	@Override()
	public Integer removeD1(BigDecimal idTarea, BigDecimal idFichero) {
		String query = "DELETE FROM AA79BD1S01 WHERE ID_TAREA_0D1 = ? AND ID_FICHERO_0D1=?";
		return this.getJdbcTemplate().update(query, idTarea, idFichero);
	}

	@Override
	public List<DocumentoTareaAdjunto> obtenerDocsXliffDeTarea(Tareas docTarea) {
		StringBuilder query = new StringBuilder(DocumentosGeneralDaoImpl.STRING_BUILDER_INIT);
		List<Object> params = new ArrayList<Object>();
		query.append("SELECT ");
		query.append("t1.ID_FICHERO_088 ID_FICHERO_088, ");
		query.append("t1.TITULO_FICHERO_088 TITULO_FICHERO_088, ");
		query.append("t1.NOMBRE_FICHERO_088 NOMBRE_FICHERO_088, ");
		query.append("t1.EXTENSION_FICHERO_088 EXTENSION_FICHERO_088, ");
		query.append("t1.CONTENT_TYPE_FICHERO_088 CONTENT_TYPE_FICHERO_088, ");
		query.append("t1.TAMANO_FICHERO_088 TAMANO_FICHERO_088, ");
		query.append("t1.IND_ENCRIPTADO_088 IND_ENCRIPTADO_088, ");
		query.append("t1.OID_FICHERO_088 OID_FICHERO_088 ");
		query.append("FROM aa79b88s01 t1 ");
		query.append("JOIN aa79b96s01 t2 ON t2.ID_FICHERO_XLIFF_096 = t1.ID_FICHERO_088 ");
		query.append("JOIN AA79B81S01 t3 ON t2.ID_TAREA_096 = t3.ID_TAREA_081 ");
		query.append("WHERE 1=1 ");
		query.append(SqlUtils.generarWhereIgual("t3.id_tarea_081", docTarea.getIdTarea(), params));
		return this.getJdbcTemplate().query(query.toString(), this.rwMap, params.toArray());
	}
}
