package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.DocumentoTareaCorreccionRowMapper;
import com.ejie.aa79b.model.DocumentoTarea;
import com.ejie.aa79b.model.DocumentosCorreccion;

/**
 * DocumentosCorreccionDaoImpl generated by UDA, 01-abr-2019 15:51:21.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class DocumentosCorreccionDaoImpl extends GenericoDaoImpl<DocumentosCorreccion>
		implements DocumentosCorreccionDao {

	public static final String[] ORDER_BY_WHITE_LIST = new String[] { DBConstants.ID_TAREA_0B1,
			DBConstants.ID_FICHERO_0B1 };

	private static final Logger LOGGER = LoggerFactory.getLogger(DocumentosCorreccionDaoImpl.class);

	public DocumentosCorreccionDaoImpl() {
		// Constructor
		super(DocumentosCorreccion.class);
	}

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<DocumentosCorreccion> rwMap = new RowMapper<DocumentosCorreccion>() {
		public DocumentosCorreccion mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new DocumentosCorreccion(resultSet.getBigDecimal("IDTAREA0B1"),
					resultSet.getBigDecimal("IDFICHERO0B1"));
		}
	};

	private RowMapper<DocumentosCorreccion> rwMapPK = new RowMapper<DocumentosCorreccion>() {
		public DocumentosCorreccion mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new DocumentosCorreccion(resultSet.getBigDecimal("IDTAREA0B1"),
					resultSet.getBigDecimal("IDFICHERO0B1"));
		}
	};

	private RowMapper<DocumentoTarea> rwMapDocumentoTareaCorreccion = new DocumentoTareaCorreccionRowMapper();

	@Override
	protected String getSelect() {
		StringBuilder selectDC = new StringBuilder(DocumentosCorreccionDaoImpl.STRING_BUILDER_INIT);
		selectDC.append(DaoConstants.SELECT + DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_TAREA_0B1
				+ DaoConstants.BLANK + DBConstants.IDTAREA + DaoConstants.SIGNO_COMA);
		selectDC.append(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_FICHERO_0B1 + DaoConstants.BLANK
				+ DBConstants.IDFICHEROCORRECCION);
		return selectDC.toString();
	}

	@Override
	protected String getFrom() {
		StringBuilder fromDC = new StringBuilder(DocumentosCorreccionDaoImpl.STRING_BUILDER_INIT);
		fromDC.append(DaoConstants.FROM + DBConstants.TABLA_B1 + DaoConstants.BLANK + DaoConstants.T1_MINUSCULA);
		return fromDC.toString();
	}

	@Override
	protected RowMapper<DocumentosCorreccion> getRwMap() {
		return this.rwMap;
	}

	@Override
	protected String[] getOrderBy() {
		return ORDER_BY_WHITE_LIST;
	}

	@Override
	protected String getPK() {
		return DBConstants.ID_TAREA_0B1;
	}

	@Override
	protected RowMapper<DocumentosCorreccion> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override
	protected String getWherePK(DocumentosCorreccion bean, List<Object> paramsDC) {
		paramsDC.add(bean.getIdTarea());
		paramsDC.add(bean.getIdFichero());
		StringBuilder wherePKDC = new StringBuilder(DocumentosCorreccionDaoImpl.STRING_BUILDER_INIT);
		wherePKDC.append(DaoConstants.WHERE + DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_TAREA_0B1
				+ DaoConstants.SIGNOIGUAL_INTERROGACION);
		wherePKDC.append(DaoConstants.AND + DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_FICHERO_0B1
				+ DaoConstants.SIGNOIGUAL_INTERROGACION);
		return wherePKDC.toString();
	}

	@Override
	protected String getWhere(DocumentosCorreccion bean, List<Object> paramsDC) {
		StringBuilder whereDC = new StringBuilder(MetadatosBusquedaDaoImpl.STRING_BUILDER_INIT);
		whereDC.append(DaoConstants.WHERE_1_1);
		whereDC.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_TAREA_0B1,
				bean.getIdTarea(), paramsDC));
		whereDC.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_FICHERO_0B1,
				bean.getIdFichero(), paramsDC));
		return whereDC.toString();
	}

	@Override
	protected String getWhereLike(DocumentosCorreccion bean, Boolean startsWith, List<Object> paramsDC,
			Boolean search) {
		StringBuilder whereLikeDC = new StringBuilder(MetadatosBusquedaDaoImpl.STRING_BUILDER_INIT);
		whereLikeDC.append(DaoConstants.WHERE_1_1);
		whereLikeDC.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_TAREA_0B1,
				bean.getIdTarea(), paramsDC));
		whereLikeDC.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_FICHERO_0B1,
				bean.getIdFichero(), paramsDC));
		return whereLikeDC.toString();
	}

	@Override
	public DocumentoTarea getDocumentoCorreccion(DocumentosCorreccion docCorreccion) {
		StringBuilder queryDC = new StringBuilder(MetadatosBusquedaDaoImpl.STRING_BUILDER_INIT);
		List<Object> paramsDC = new ArrayList<Object>();
		DocumentoTarea documentoTarea = new DocumentoTarea();
		queryDC.append(this.getSelect());
		queryDC.append(DaoConstants.SIGNO_COMA + DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.TITULO_FICHERO_088
				+ DaoConstants.BLANK + DBConstants.TITULO + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.EXTENSION_FICHERO_088 + DaoConstants.BLANK
				+ DBConstants.EXTENSIONFICHERO + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.CONTENT_TYPE_FICHERO_088 + DaoConstants.BLANK
				+ DBConstants.CONTENTTYPE + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.TAMANO_FICHERO_088 + DaoConstants.BLANK
				+ DBConstants.TAMANOFICHERO + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.IND_ENCRIPTADO_088 + DaoConstants.BLANK
				+ DBConstants.INDENCRIPTADO + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.RUTA_PIF_FICHERO_088 + DaoConstants.BLANK
				+ DBConstants.RUTAPIFFICHERO + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.OID_FICHERO_088 + DaoConstants.BLANK
				+ DBConstants.OIDFICHERO + DaoConstants.SIGNO_COMA);
		queryDC.append(DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.NOMBRE_FICHERO_088 + DaoConstants.BLANK
				+ DBConstants.NOMBREFICHERO);
		queryDC.append(this.getFrom());
		queryDC.append(DaoConstants.JOIN + DBConstants.TABLA_88 + DaoConstants.BLANK + DaoConstants.T2_MINUSCULA);
		queryDC.append(DaoConstants.ON + DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_FICHERO_0B1
				+ DaoConstants.SIGNOIGUAL + DaoConstants.T2_MINUSCULA_PUNTO + DBConstants.ID_FICHERO_088);
		queryDC.append(this.getWhere(docCorreccion, paramsDC));
		try {
			documentoTarea = this.getJdbcTemplate().queryForObject(queryDC.toString(), paramsDC.toArray(),
					this.rwMapDocumentoTareaCorreccion);
		} catch (org.springframework.dao.EmptyResultDataAccessException erdae) {
			// si no hay resultados devolvemos un objeto vacio
			DocumentosCorreccionDaoImpl.LOGGER.error(erdae.getMessage(), erdae);
			documentoTarea = new DocumentoTarea();
		}
		return documentoTarea;
	}

	@Override()
	public DocumentosCorreccion add(DocumentosCorreccion documentosCorreccion) {
		String query = "INSERT INTO AA79BB1S01 (ID_TAREA_0B1, ID_FICHERO_0B1) VALUES (?,?)";
		this.getJdbcTemplate().update(query, documentosCorreccion.getIdTarea(), documentosCorreccion.getIdFichero());
		return documentosCorreccion;
	}

}
