package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.dao.support.DataAccessUtils;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.EmpresasProveedorasExtendRowMapper;
import com.ejie.aa79b.dao.mapper.EmpresasProveedorasRowMapper;
import com.ejie.aa79b.dao.mapper.EmpresasProveedorasRowMapperEmpProv;
import com.ejie.aa79b.model.EmpresasProveedoras;
import com.ejie.aa79b.model.enums.EstadoEnum;
import com.ejie.aa79b.model.enums.LotesVigentesEnum;
import com.ejie.aa79b.model.enums.TipoTareaGestionAsociadaEnum;

/**
 * EmpresasProveedorasDaoImpl generated by UDA, 23-ene-2018 13:21:57.
 * 
 * @author UDA
 */

@Repository(value = "empresasProveedorasDao")
@Transactional()
public class EmpresasProveedorasDaoImpl extends GenericoDaoImpl<EmpresasProveedoras> implements EmpresasProveedorasDao {

	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { DBConstants.TIPO, DBConstants.CODIGO,
			DBConstants.DESCAMPES, DBConstants.DESCAMPEU, DBConstants.DESCES, DBConstants.DESCEU, DBConstants.CIF,
			DBConstants.ESTADO, DBConstants.ESTADODESC, DBConstants.FACTURABLE, DBConstants.IVA, DBConstants.CDIRNORA,
			"LOTESVIGENTES", "LOTESVIGENTESDESC" };
	protected static final String SQL_LOTES_VIGENTES = "( SELECT COUNT(1) FROM AA79B29S01 t2 WHERE t2.TIPO_ENTIDAD_029 = TIPO AND t2.ID_EMPRESA_PROV_029 = CODIGO AND t2.FECHA_INICIO_029 <= SYSDATE AND t2.FECHA_FIN_029 >= SYSDATE )";
	private static final String AND = " AND ";

	private RowMapper<EmpresasProveedoras> rwMap = new EmpresasProveedorasRowMapper();

	private RowMapper<EmpresasProveedoras> rwMapPK = new RowMapper<EmpresasProveedoras>() {
		@Override()
		public EmpresasProveedoras mapRow(ResultSet rs, int rowNum) throws SQLException {
			EmpresasProveedoras bean = new EmpresasProveedoras();
			bean.setTipo(rs.getString(DBConstants.TIPO));
			bean.setCodigo(rs.getLong(DBConstants.CODIGO));
			return bean;
		}
	};
	private RowMapper<EmpresasProveedoras> rwMapEmpresas = new RowMapper<EmpresasProveedoras>() {
		public EmpresasProveedoras mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			EmpresasProveedoras emp = new EmpresasProveedoras();
			emp.setCodigo(resultSet.getLong("CODIGO"));
			emp.setDescEu(resultSet.getString("DESC_EU"));
			return emp;
		}
	};
	private RowMapper<EmpresasProveedoras> rwMapFindOne = new EmpresasProveedorasExtendRowMapper();

	private RowMapper<EmpresasProveedoras> rwMapEmpProv = new EmpresasProveedorasRowMapperEmpProv();

	/**
	 * Constructor
	 */
	public EmpresasProveedorasDaoImpl() {
		super(EmpresasProveedoras.class);
	}

	private String getReducedSelect() {
		Locale locale = LocaleContextHolder.getLocale();
		StringBuilder select = new StringBuilder();
		select.append("SELECT t1.TIPO TIPO");
		select.append(", t1.CODIGO CODIGO");
		select.append(", t1.DESC_AMP_ES DESCAMPES");
		select.append(", t1.DESC_AMP_EU DESCAMPEU");
		select.append(", t1.DESC_ES DESCES");
		select.append(", t1.DESC_EU DESCEU");
		select.append(", t1.CIF CIF");
		select.append(", t1.ESTADO ESTADO");
		select.append(", DECODE( t1.ESTADO, '").append(EstadoEnum.ALTA.getValue()).append("', '")
				.append(this.msg.getMessage(EstadoEnum.ALTA.getLabel(), null, locale)).append("', '")
				.append(this.msg.getMessage(EstadoEnum.BAJA.getLabel(), null, locale)).append("') AS ESTADODESC");
		select.append(", t1.FACTURABLE FACTURABLE");
		select.append(", t1.IVA IVA");
		select.append(", t1.CDIRNORA CDIRNORA");
		return select.toString();
	}

	@Override()
	protected String getSelect() {
		Locale locale = LocaleContextHolder.getLocale();
		StringBuilder select = new StringBuilder();
		select.append("SELECT TIPO");
		select.append(", CODIGO");
		select.append(", DESCAMPES");
		select.append(", DESCAMPEU");
		select.append(", DESCES");
		select.append(", DESCEU");
		select.append(", CIF");
		select.append(", ESTADO");
		select.append(", DECODE( ESTADO, '").append(EstadoEnum.ALTA.getValue()).append("', '")
				.append(this.msg.getMessage(EstadoEnum.ALTA.getLabel(), null, locale)).append("', '")
				.append(this.msg.getMessage(EstadoEnum.BAJA.getLabel(), null, locale)).append("') AS ESTADODESC");
		select.append(", FACTURABLE");
		select.append(", IVA");
		select.append(", CDIRNORA");
		select.append(", ").append(SQL_LOTES_VIGENTES).append(" AS LOTESVIGENTES");
		select.append(", DECODE( ").append(SQL_LOTES_VIGENTES).append(", ").append(LotesVigentesEnum.NO.getValue())
				.append(", '").append(this.msg.getMessage(LotesVigentesEnum.NO.getLabel(), null, locale)).append("', '")
				.append(this.msg.getMessage(LotesVigentesEnum.SI.getLabel(), null, locale))
				.append("') AS LOTESVIGENTESDESC");

		return select.toString();
	}

	@Override()
	public EmpresasProveedoras find(EmpresasProveedoras bean) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getReducedSelect());
		query.append(", t2.TIPONORA TIPONORA");
		query.append(", t2.CALLE CALLE");
		query.append(", t2.PORTAL PORTAL");
		query.append(", t2.ESCALERA ESCALERA");
		query.append(", t2.PISO PISO");
		query.append(", t2.MANO MANO");
		query.append(", t2.PUERTA PUERTA");
		query.append(", t2.CODPOSTAL CODPOSTAL");
		query.append(", t2.LOCALIDAD LOCALIDAD");
		query.append(", t2.CODMUNICIPIO CODMUNICIPIO");
		query.append(", t2.MUNICIPIO MUNICIPIO");
		query.append(", t2.CODPROVINCIA CODPROVINCIA");
		query.append(", t2.PROVINCIA PROVINCIA");
		query.append(", t2.PAIS PAIS");
		query.append(", ( SELECT COUNT(1) FROM X54JAPI_EMPRESAS_PROV t7 WHERE t7.TIPO = '");
		query.append(bean.getTipo());
		query.append("' AND t7.CODIGO = ");
		query.append(bean.getCodigo());
		query.append(" ) AS ESPROVEEDORA");
		query.append(" FROM X54JAPI_ENTIDADES_SOLIC t1");
		query.append(" JOIN X54JNORA t2 ON t1.CDIRNORA = t2.CDIRNORA ");
		query.append(this.getWherePK(bean, params));

		List<EmpresasProveedoras> beanList = this.getJdbcTemplate().query(query.toString(), this.getRwMapFindOne(),
				params.toArray());
		return DataAccessUtils.uniqueResult(beanList);
	}

	@Override()
	protected String getFrom() {
		StringBuilder from = new StringBuilder();
		from.append(" FROM ");
		from.append(" ( ");
		from.append(" SELECT t6.TIPO TIPO,");
		from.append(" t6.CODIGO CODIGO,");
		from.append(" t6.DESC_AMP_ES DESCAMPES,");
		from.append(" t6.DESC_AMP_EU DESCAMPEU,");
		from.append(" t6.DESC_ES DESCES,");
		from.append(" t6.DESC_EU DESCEU,");
		from.append(" t6.CIF CIF,");
		from.append(" t6.ESTADO ESTADO,");
		from.append(" t6.FACTURABLE FACTURABLE,");
		from.append(" t6.IVA IVA,");
		from.append(" t6.CDIRNORA CDIRNORA");
		from.append(" FROM X54JAPI_EMPRESAS_PROV t6");
		from.append(" WHERE NOT EXISTS ( ");
		from.append(" SELECT t3.ID_EMPRESA_PROV_029,");
		from.append(" t3.TIPO_ENTIDAD_029");
		from.append(" FROM AA79B29S01 t3");
		from.append(" WHERE t6.CODIGO = t3.ID_EMPRESA_PROV_029 AND t6.TIPO = t3.TIPO_ENTIDAD_029 )");
		from.append(" UNION ");
		from.append(" SELECT t4.TIPO TIPO,");
		from.append(" t4.CODIGO CODIGO,");
		from.append(" t4.DESC_AMP_ES DESCAMPES,");
		from.append(" t4.DESC_AMP_EU DESCAMPEU,");
		from.append(" t4.DESC_ES DESCES,");
		from.append(" t4.DESC_EU DESCEU,");
		from.append(" t4.CIF CIF,");
		from.append(" t4.ESTADO ESTADO,");
		from.append(" t4.FACTURABLE FACTURABLE,");
		from.append(" t4.IVA IVA,");
		from.append(" t4.CDIRNORA CDIRNORA");
		from.append(" FROM X54JAPI_ENTIDADES_SOLIC t4");
		from.append(" JOIN AA79B29S01 t5");
		from.append(" ON ( t4.TIPO = t5.TIPO_ENTIDAD_029");
		from.append(" AND t4.CODIGO = t5.ID_EMPRESA_PROV_029 ) ");
		from.append(" ) ");

		return from.toString();
	}

	@Override()
	protected RowMapper<EmpresasProveedoras> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return "TIPO, CODIGO";
	}

	@Override()
	protected RowMapper<EmpresasProveedoras> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(EmpresasProveedoras bean, List<Object> params) {
		params.add(bean.getTipo());
		params.add(bean.getCodigo());
		return " WHERE t1.TIPO = ? AND t1.CODIGO = ?";
	}

	@Override()
	protected String getWhere(EmpresasProveedoras bean, List<Object> params) {
		StringBuilder where = new StringBuilder();
		where.append(SqlUtils.generarWhereIgual(DBConstants.TIPO, bean.getTipo(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.CODIGO, bean.getCodigo(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.DESC_AMP_ES, bean.getDescAmpEs(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.DESC_AMP_EU, bean.getDescAmpEu(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.DESC_ES, bean.getDescEs(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.DESC_EU, bean.getDescEu(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.CIF, bean.getCif(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.ESTADO, bean.getEstado(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.FACTURABLE, bean.getFacturable(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.IVA, bean.getIva(), params));
		if (bean.getDireccion() != null) {
			where.append(SqlUtils.generarWhereIgual(DBConstants.CDIRNORA, bean.getDireccion().getDirNora(), params));
		}
		this.generarWhereFiltroVigente(bean, params, where);
		return where.toString();
	}

	@Override()
	protected String getWhereLike(EmpresasProveedoras bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder();
		where.append(SqlUtils.generarWhereIgual(DBConstants.TIPO, bean.getTipo(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.CODIGO, bean.getCodigo(), params));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DBConstants.DESC_AMP_ES, bean.getDescAmpEs(), params, startsWith));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DBConstants.DESC_AMP_EU, bean.getDescAmpEu(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado(DBConstants.DESC_ES, bean.getDescEs(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado(DBConstants.DESC_EU, bean.getDescEu(), params, startsWith));
		where.append(SqlUtils.generarWhereIgual(DBConstants.CIF, bean.getCif(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.ESTADO, bean.getEstado(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.FACTURABLE, bean.getFacturable(), params));
		where.append(SqlUtils.generarWhereIgual(DBConstants.IVA, bean.getIva(), params));
		if (bean.getDireccion() != null) {
			where.append(SqlUtils.generarWhereIgual(DBConstants.CDIRNORA, bean.getDireccion().getDirNora(), params));
		}
		this.generarWhereFiltroVigente(bean, params, where);
		return where.toString();
	}

	/**
	 * @param bean
	 * @param params
	 * @param where
	 */
	private void generarWhereFiltroVigente(EmpresasProveedoras bean, List<Object> params, StringBuilder where) {
		if (this.isFiltroLoteNoVigente(bean)) {
			where.append(SqlUtils.generarWhereIgual(SQL_LOTES_VIGENTES, bean.getLotesVigentes(), params));
		} else if (this.isFiltroLoteVigente(bean)) {
			where.append(AND).append(SQL_LOTES_VIGENTES).append(" > 0");
		}
	}

	/**
	 * @param bean
	 * @return
	 */
	private boolean isFiltroLoteVigente(EmpresasProveedoras bean) {
		return StringUtils.isNotBlank(bean.getLotesVigentes())
				&& bean.getLotesVigentes().equals(LotesVigentesEnum.SI.getValue());
	}

	/**
	 * @param bean
	 * @return
	 */
	private boolean isFiltroLoteNoVigente(EmpresasProveedoras bean) {
		return StringUtils.isNotBlank(bean.getLotesVigentes())
				&& bean.getLotesVigentes().equals(LotesVigentesEnum.NO.getValue());
	}

	protected RowMapper<EmpresasProveedoras> getRwMapFindOne() {
		return this.rwMapFindOne;
	}

	@Override
	public List<EmpresasProveedoras> getEmpresasProveedorasConTareasNoPagadas(boolean soloNoPagadas) {
		StringBuilder query = new StringBuilder(DaoConstants.SELECT + DaoConstants.DISTINCT + DBConstants.CODIGO
				+ DaoConstants.SIGNO_COMA + "TRIM(" + DBConstants.DESC_EU + ") " + DBConstants.DESC_EU);
		query.append(DaoConstants.FROM + DBConstants.VISTAX54JAPIENTIDADESSOLIC + DaoConstants.SIGNO_COMA
				+ DBConstants.TABLA_29 + DaoConstants.SIGNO_COMA);
		query.append(DBConstants.TABLA_081 + " tareaFact," + DBConstants.TABLA_081 + " tareaRevPago,"
				+ DBConstants.TABLA_94);
		query.append(DaoConstants.WHERE + " ID_EMPRESA_PROV_029 = " + DBConstants.CODIGO + DaoConstants.AND
				+ " TIPO_ENTIDAD_029 = " + DBConstants.TIPO + DaoConstants.AND + " tareaFact.ID_LOTE_081 = ID_LOTE_029 "
				+ DaoConstants.AND + " tareafact.IND_FACTURABLE_081 = '" + Constants.SI + "' " + DaoConstants.AND
				+ " tarearevpago.ID_TIPO_TAREA_081 = " + TipoTareaGestionAsociadaEnum.REVISION_PAGO_PROVEEDOR.getValue()
				+ DaoConstants.AND + " tareaFact.ID_TAREA_081 = tareaRevPago.ID_TAREA_REL_081 ");
		query.append(DaoConstants.AND + "tareaRevPago" + DaoConstants.SIGNO_PUNTO + DBConstants.ID_TAREA_081
				+ DaoConstants.SIGNOIGUAL + "ID_TAREA_094 ");
		query.append(DaoConstants.AND + " IND_ALBARAN_094 = '" + Constants.SI + "' ");

		if (soloNoPagadas) {
			query.append(DaoConstants.AND + " IND_PAGADO_094 = '" + Constants.NO + "' ");
		}
		return this.getJdbcTemplate().query(query.toString(), this.rwMapEmpresas);
	}

	@Override
	public List<EmpresasProveedoras> getEmpresasProveedoras(EmpresasProveedoras empresasProveedoras) {
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.SELECT + DaoConstants.DISTINCT);
		query.append(DBConstants.TIPO);
		query.append(DaoConstants.SIGNO_COMA + DBConstants.CODIGO);
		query.append(DaoConstants.SIGNO_COMA + DBConstants.DESC_AMP_ES + DaoConstants.BLANK + DBConstants.DESCAMPES);
		query.append(DaoConstants.SIGNO_COMA + DaoConstants.TRIM + DaoConstants.ABRIR_PARENTESIS);
		query.append(DaoConstants.NVL + DaoConstants.ABRIR_PARENTESIS);
		query.append(DBConstants.DESC_AMP_EU + DaoConstants.SIGNO_COMA_SIN_ESPACIOS + DBConstants.DESC_AMP_ES);
		query.append(DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.CERRAR_PARENTESIS + DaoConstants.BLANK + DBConstants.DESCAMPEU);
		query.append(DaoConstants.SIGNO_COMA + DBConstants.DESC_ES + DaoConstants.BLANK + DBConstants.DESCES);
		query.append(DaoConstants.SIGNO_COMA + DaoConstants.TRIM + DaoConstants.ABRIR_PARENTESIS);
		query.append(DaoConstants.NVL + DaoConstants.ABRIR_PARENTESIS);
		query.append(DBConstants.DESC_EU + DaoConstants.SIGNO_COMA_SIN_ESPACIOS + DBConstants.DESC_ES);
		query.append(DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.CERRAR_PARENTESIS + DaoConstants.BLANK + DBConstants.DESCEU);
		query.append(DaoConstants.SIGNO_COMA + DBConstants.CIF);
		query.append(
				DaoConstants.FROM + DBConstants.X54JAPI_EMPRESAS_PROV + DaoConstants.BLANK + DaoConstants.T1_MINUSCULA);
		query.append(DaoConstants.WHERE_1_1);

		List<Object> params = new ArrayList<Object>();
		query.append(SqlUtils.generarWhereLike(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ESTADO,
				EstadoEnum.ALTA.getValue(), params, false));
		if (empresasProveedoras != null) {
			query.append(SqlUtils.generarWhereLike(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.DESC_EU,
					empresasProveedoras.getDescEu(), params, false));
			if (empresasProveedoras.getTipo() != null) {
				query.append(DaoConstants.AND + DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.TIPO
						+ DaoConstants.SIGNOIGUAL_INTERROGACION);
				params.add(empresasProveedoras.getTipo());
			}
		}

		return this.getJdbcTemplate().query(query.toString(), this.rwMapEmpProv, params.toArray());
	}

}
