package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.FestivosCalendarioServicio;

/**
 * FestivosCalendarioServicioDaoImpl generated by UDA, 13-dic-2017 17:05:01.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class FestivosCalendarioServicioDaoImpl extends GenericoDaoImpl<FestivosCalendarioServicio>
        implements FestivosCalendarioServicioDao {

    protected static final String IDDIACALENDARIO023 = "IDDIACALENDARIO023";
    protected static final String DIACALENDARIO023 = "DIACALENDARIO023";
    protected static final String ANYOCALENDARIO023 = "ANYOCALENDARIO023";

    protected static final String[] ORDER_BY_WHITE_LIST = new String[] { ANYOCALENDARIO023, IDDIACALENDARIO023,
            DIACALENDARIO023 };    

    /*
     * ROW_MAPPERS
     */
    private RowMapper<FestivosCalendarioServicio> rwMap = new RowMapper<FestivosCalendarioServicio>() {
        @Override()
        public FestivosCalendarioServicio mapRow(ResultSet resultSet, int rowNum) throws SQLException {
            return new FestivosCalendarioServicio(resultSet.getLong(ANYOCALENDARIO023),
                    resultSet.getInt(IDDIACALENDARIO023), resultSet.getDate(DIACALENDARIO023));
        }
    };

    private RowMapper<FestivosCalendarioServicio> rwMapPK = new RowMapper<FestivosCalendarioServicio>() {
        @Override()
        public FestivosCalendarioServicio mapRow(ResultSet resultSet, int rowNum) throws SQLException {
            return new FestivosCalendarioServicio(resultSet.getLong(ANYOCALENDARIO023),
                    resultSet.getInt(IDDIACALENDARIO023), resultSet.getDate(DIACALENDARIO023));
        }
    };
    
    /**
     * Constructor
     */
    public FestivosCalendarioServicioDaoImpl() {
        super(FestivosCalendarioServicio.class);
    }

    

    @Override()
    public FestivosCalendarioServicio add(FestivosCalendarioServicio festivoscalendarioservicio) {
        String query = "INSERT INTO AA79B23S01 (ANYO_CALENDARIO_023, ID_DIA_CALENDARIO_023, DIA_CALENDARIO_023) VALUES (?,?,?)";
        this.getJdbcTemplate().update(query, festivoscalendarioservicio.getAnyoCalendario023(),
                festivoscalendarioservicio.getIdDiaCalendario023(), festivoscalendarioservicio.getDiaCalendario023());
        return festivoscalendarioservicio;
    }

    @Override()
    public FestivosCalendarioServicio update(FestivosCalendarioServicio festivoscalendarioservicio) {
        String query = "UPDATE AA79B23S01 SET DIA_CALENDARIO_023=? WHERE ANYO_CALENDARIO_023=? AND ID_DIA_CALENDARIO_023=?";
        this.getJdbcTemplate().update(query, festivoscalendarioservicio.getDiaCalendario023(),
                festivoscalendarioservicio.getAnyoCalendario023(), festivoscalendarioservicio.getIdDiaCalendario023());
        return festivoscalendarioservicio;
    }

    @Override()
    public void remove(FestivosCalendarioServicio festivoscalendarioservicio) {
        String query = "DELETE FROM AA79B23S01 WHERE ANYO_CALENDARIO_023=? AND ID_DIA_CALENDARIO_023=?";
        this.getJdbcTemplate().update(query, festivoscalendarioservicio.getAnyoCalendario023(),
                festivoscalendarioservicio.getIdDiaCalendario023());
    }

    @Override()
    public void removeTodosPorAnio(FestivosCalendarioServicio festivoscalendarioservicio) {
        String query = "DELETE FROM AA79B23S01 WHERE ANYO_CALENDARIO_023=?";
        this.getJdbcTemplate().update(query, festivoscalendarioservicio.getAnyoCalendario023());
    }

    @Override()
    protected String getSelect() {
        StringBuilder query = new StringBuilder(
                "SELECT t1.ANYO_CALENDARIO_023 ANYOCALENDARIO023, t1.ID_DIA_CALENDARIO_023 IDDIACALENDARIO023, t1.DIA_CALENDARIO_023 DIACALENDARIO023 ");
        return query.toString();
    }

    @Override()
    protected String getFrom() {
        return " FROM AA79B23S01 t1 ";
    }

    @Override()
    protected RowMapper<FestivosCalendarioServicio> getRwMap() {
        return this.rwMap;
    }

    @Override()
    protected String[] getOrderBy() {
        return HorasHorariosAtencionDaoImpl.ORDER_BY_WHITE_LIST;
    }

    @Override()
    protected String getPK() {
        return "ANYO_CALENDARIO_023 || '_' || ID_DIA_CALENDARIO_023";
    }

    @Override()
    protected RowMapper<FestivosCalendarioServicio> getRwMapPK() {
        return this.rwMapPK;
    }

    @Override()
    protected String getWherePK(FestivosCalendarioServicio bean, List<Object> params) {
        params.add(bean.getAnyoCalendario023());
        params.add(bean.getIdDiaCalendario023());
        return " WHERE t1.ANYO_CALENDARIO_023 = ?   AND t1.ID_DIA_CALENDARIO_023 = ?";
    }

    @Override()
    protected String getWhere(FestivosCalendarioServicio bean, List<Object> params) {

        StringBuilder where = new StringBuilder(FestivosCalendarioServicioDaoImpl.STRING_BUILDER_INIT);

        where.append(SqlUtils.generarWhereIgual("ANYO_CALENDARIO_023", bean.getAnyoCalendario023(), params));
        where.append(SqlUtils.generarWhereIgual("ID_DIA_CALENDARIO_023", bean.getIdDiaCalendario023(), params));
        where.append(SqlUtils.generarWhereIgual("DIA_CALENDARIO_023", bean.getDiaCalendario023(), params));
        return where.toString();
    }

    @Override()
    protected String getWhereLike(FestivosCalendarioServicio bean, Boolean startsWith, List<Object> params,
            Boolean search) {
        StringBuilder where = new StringBuilder(FestivosCalendarioServicioDaoImpl.STRING_BUILDER_INIT);

        where.append(SqlUtils.generarWhereIgual("ANYO_CALENDARIO_023", bean.getAnyoCalendario023(), params));
        where.append(SqlUtils.generarWhereIgual("ID_DIA_CALENDARIO_023", bean.getIdDiaCalendario023(), params));
        where.append(SqlUtils.generarWhereIgual("DIA_CALENDARIO_023", bean.getDiaCalendario023(), params));
        return where.toString();
    }
}
