package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.HorariosAtencion;

/**
 * HorariosAtencionDaoImpl generated by UDA, 21-nov-2017 14:44:52.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class HorariosAtencionDaoImpl extends GenericoDaoImpl<HorariosAtencion> implements HorariosAtencionDao {

	protected static final String ID020 = "ID020";
	protected static final String ID_020 = "ID_020";
	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { ID020, "NIVELUSUARIO020", "INDACTIVO020",
			"INDACTIVOEU", "INDACTIVOES", "NIVELUSUARIOEU", "NIVELUSUARIOES" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<HorariosAtencion> rwMap = new RowMapper<HorariosAtencion>() {
		@Override()
		public HorariosAtencion mapRow(ResultSet resultSet, int rowNum) throws SQLException {

			HorariosAtencion horariosAtencion = new HorariosAtencion(resultSet.getLong(ID020),
					resultSet.getString("NIVELUSUARIO020"), resultSet.getString("INDACTIVO020"));
			horariosAtencion.setIndActivoEs(resultSet.getString("INDACTIVOES"));
			horariosAtencion.setIndActivoEu(resultSet.getString("INDACTIVOEU"));
			horariosAtencion.setNivelUsuarioEs(resultSet.getString("NIVELUSUARIOES"));
			horariosAtencion.setNivelUsuarioEu(resultSet.getString("NIVELUSUARIOEU"));
			return horariosAtencion;
		}
	};

	private RowMapper<HorariosAtencion> rwMapPK = new RowMapper<HorariosAtencion>() {
		@Override()
		public HorariosAtencion mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new HorariosAtencion(resultSet.getLong(ID020));
		}
	};

	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	/**
	 * Constructor
	 */
	public HorariosAtencionDaoImpl() {
		super(HorariosAtencion.class);
	}

	@Override()
	public HorariosAtencion add(HorariosAtencion horariosatencion) {

		String queryID = "SELECT AA79B20Q00.NEXTVAL from dual";
		long elId = this.getJdbcTemplate().queryForObject(queryID, Long.class);

		String query = "INSERT INTO AA79B20S01 (ID_020, NIVEL_USUARIO_020, IND_ACTIVO_020) VALUES (?,?,?)";
		this.getJdbcTemplate().update(query, elId, horariosatencion.getNivelUsuario020(),
				(horariosatencion.getIndActivo020() != null) ? horariosatencion.getIndActivo020() : Constants.NO);
		horariosatencion.setId020(elId);
		return horariosatencion;
	}

	@Override()
	public HorariosAtencion update(HorariosAtencion horariosatencion) {
		String query = "UPDATE AA79B20S01 SET NIVEL_USUARIO_020=?, IND_ACTIVO_020=? WHERE ID_020=?";
		this.getJdbcTemplate().update(query, horariosatencion.getNivelUsuario020(),
				(horariosatencion.getIndActivo020() != null) ? horariosatencion.getIndActivo020() : Constants.NO,
				horariosatencion.getId020());
		return horariosatencion;
	}

	@Override()
	public void remove(HorariosAtencion horariosatencion) {
		String query = "DELETE FROM AA79B20S01 WHERE ID_020=?";
		this.getJdbcTemplate().update(query, horariosatencion.getId020());
	}

	@Override()
	protected String getSelect() {
		Locale es = new Locale(Constants.LANG_CASTELLANO);
		Locale eu = new Locale(Constants.LANG_EUSKERA);
		StringBuilder sb = new StringBuilder();

		sb.append("SELECT t1.ID_020 ID020, t1.NIVEL_USUARIO_020 NIVELUSUARIO020, t1.IND_ACTIVO_020 INDACTIVO020");

		sb.append(", DECODE(t1.IND_ACTIVO_020, '").append(Constants.SI).append("', '")
				.append(this.msg.getMessage("comun.si", null, es)).append("', '").append(Constants.NO).append("', '")
				.append(this.msg.getMessage("comun.no", null, es)).append("') AS INDACTIVOES");
		sb.append(", DECODE(t1.IND_ACTIVO_020, '").append(Constants.SI).append("', '")
				.append(this.msg.getMessage("comun.si", null, eu)).append("', '").append(Constants.NO).append("', '")
				.append(this.msg.getMessage("comun.no", null, eu)).append("') AS INDACTIVOEU");
		sb.append(", DECODE(t1.NIVEL_USUARIO_020, 'V', '").append(this.msg.getMessage("nivelUsuario.vip", null, es))
				.append("', '").append(Constants.NO).append("', '")
				.append(this.msg.getMessage("nivelUsuario.normal", null, es)).append("') AS NIVELUSUARIOES");
		sb.append(", DECODE(t1.NIVEL_USUARIO_020, 'V', '").append(this.msg.getMessage("nivelUsuario.vip", null, eu))
				.append("', '").append(Constants.NO).append("', '")
				.append(this.msg.getMessage("nivelUsuario.normal", null, eu)).append("') AS NIVELUSUARIOEU");

		return sb.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B20S01 t1 ";
	}

	@Override()
	protected RowMapper<HorariosAtencion> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return HorariosAtencionDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_020;
	}

	@Override()
	protected RowMapper<HorariosAtencion> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(HorariosAtencion bean, List<Object> params) {
		params.add(bean.getId020());
		return " WHERE t1.ID_020 = ?";
	}

	@Override()
	protected String getWhere(HorariosAtencion bean, List<Object> params) {

		StringBuilder where = new StringBuilder(HorariosAtencionDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_020, bean.getId020(), params));
		where.append(SqlUtils.generarWhereIgual("NIVEL_USUARIO_020", bean.getNivelUsuario020(), params));
		where.append(SqlUtils.generarWhereIgual("IND_ACTIVO_020", bean.getIndActivo020(), params));
		return where.toString();
	}

	@Override()
	protected String getWhereLike(HorariosAtencion bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(HorariosAtencionDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_020, bean.getId020(), params));
		where.append(SqlUtils.generarWhereIgual("NIVEL_USUARIO_020", bean.getNivelUsuario020(), params));
		where.append(SqlUtils.generarWhereIgual("IND_ACTIVO_020", bean.getIndActivo020(), params));
		return where.toString();
	}

}
