package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.IdiomaDestino;

/**
 * IdiomaDestinoDaoImpl generated by UDA, 24-oct-2017 15:14:42.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class IdiomaDestinoDaoImpl extends GenericoDaoImpl<IdiomaDestino> implements IdiomaDestinoDao {

	private static final String IDIDIOMA009 = "IDIDIOMA009";
	public static final String[] ORDER_BY_WHITE_LIST = new String[] { IDIDIOMA009, "CODIDIOMA009", "DESCIDIOMAEU009",
			"DESCIDIOMAES009", "ESTADO009" };

	public IdiomaDestinoDaoImpl() {
		super(IdiomaDestino.class);
	}

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<IdiomaDestino> rwMap = new RowMapper<IdiomaDestino>() {
		@Override
		public IdiomaDestino mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			final IdiomaDestino idiomaDestino = new IdiomaDestino();
			idiomaDestino.setIdIdioma(resultSet.getLong(IDIDIOMA009));
			idiomaDestino.setCodIdioma(resultSet.getString("CODIDIOMA009"));
			idiomaDestino.setDescIdiomaEu(resultSet.getString("DESCIDIOMAEU009"));
			idiomaDestino.setDescIdiomaEs(resultSet.getString("DESCIDIOMAES009"));
			idiomaDestino.setEstado(resultSet.getString("ESTADO009"));

			return idiomaDestino;
		}
	};

	private RowMapper<IdiomaDestino> rwMapPK = new RowMapper<IdiomaDestino>() {
		@Override
		public IdiomaDestino mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new IdiomaDestino(resultSet.getLong(IDIDIOMA009));
		}
	};

	@Override
	public IdiomaDestino add(IdiomaDestino idiomadestino) {
		String query = "INSERT INTO AA79B09S01 (ID_IDIOMA_009, COD_IDIOMA_009, DESC_IDIOMA_EU_009, DESC_IDIOMA_ES_009, ESTADO_009) VALUES (?,?,?,?,?)";
		this.getJdbcTemplate().update(query, idiomadestino.getIdIdioma(), idiomadestino.getCodIdioma(),
				idiomadestino.getDescIdiomaEu(), idiomadestino.getDescIdiomaEs(), idiomadestino.getEstado());
		return idiomadestino;
	}

	@Override
	public IdiomaDestino update(IdiomaDestino idiomadestino) {
		String query = "UPDATE AA79B09S01 SET COD_IDIOMA_009=?, DESC_IDIOMA_EU_009=?, DESC_IDIOMA_ES_009=?, ESTADO_009=? WHERE ID_IDIOMA_009=?";
		this.getJdbcTemplate().update(query, idiomadestino.getCodIdioma(), idiomadestino.getDescIdiomaEu(),
				idiomadestino.getDescIdiomaEs(), idiomadestino.getEstado(), idiomadestino.getIdIdioma());
		return idiomadestino;
	}

	@Override()
	protected String getSelect() {
		StringBuilder sb = new StringBuilder();
		sb.append(" SELECT t1.ID_IDIOMA_009 IDIDIOMA009");
		sb.append(",  t1.COD_IDIOMA_009 CODIDIOMA009");
		sb.append(", t1.DESC_IDIOMA_EU_009 DESCIDIOMAEU009");
		sb.append(", t1.DESC_IDIOMA_ES_009 DESCIDIOMAES009");
		sb.append(", t1.ESTADO_009 ESTADO009 ");
		return sb.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B09S01 t1 ";
	}

	@Override()
	protected RowMapper<IdiomaDestino> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return IdiomaDestinoDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return "ID_IDIOMA_009";
	}

	@Override()
	protected RowMapper<IdiomaDestino> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(IdiomaDestino bean, List<Object> params) {
		params.add(bean.getIdIdioma());
		return " WHERE t1.ID_IDIOMA_009 = ?";
	}

	@Override
	protected String getWhere(IdiomaDestino bean, List<Object> params) {

		StringBuilder where = new StringBuilder(IdiomaDestinoDaoImpl.STRING_BUILDER_INIT);

		where.append(SqlUtils.generarWhereIgual("t1.ID_IDIOMA_009", bean.getIdIdioma(), params));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.COD_IDIOMA_009", bean.getCodIdioma(), params, false));
		where.append(
				SqlUtils.generarWhereLikeNormalizado("t1.DESC_IDIOMA_EU_009", bean.getDescIdiomaEu(), params, false));
		where.append(
				SqlUtils.generarWhereLikeNormalizado("t1.DESC_IDIOMA_ES_009", bean.getDescIdiomaEs(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.ESTADO_009", bean.getEstado(), params, false));

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put("query", where);
		mapWhere.put("params", params);

		return where.toString();
	}

	@Override
	protected String getWhereLike(IdiomaDestino bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder whereLike = new StringBuilder(IdiomaDestinoDaoImpl.STRING_BUILDER_INIT);

		whereLike.append(SqlUtils.generarWhereIgual("t1.ID_IDIOMA_009", bean.getIdIdioma(), params));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("t1.COD_IDIOMA_009", bean.getCodIdioma(), params, false));
		whereLike.append(
				SqlUtils.generarWhereLikeNormalizado("t1.DESC_IDIOMA_EU_009", bean.getDescIdiomaEu(), params, false));
		whereLike.append(
				SqlUtils.generarWhereLikeNormalizado("t1.DESC_IDIOMA_ES_009", bean.getDescIdiomaEs(), params, false));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("t1.ESTADO_009", bean.getEstado(), params, false));

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put("query", whereLike);
		mapWhere.put("params", params);

		return whereLike.toString();
	}

	@Override
	public String getCodeWithAnyoAndNumeExp(Long anyo, Integer numExp) {
		StringBuilder query = new StringBuilder(IdiomaDestinoDaoImpl.STRING_BUILDER_INIT);
		List<Object> params = new ArrayList<Object>();
		query.append(" SELECT t1.COD_IDIOMA_009 ");
		query.append(this.getFrom());
		query.append(" JOIN AA79B53S01 t2 ");
		query.append(" ON t1.ID_IDIOMA_009 = t2.ID_IDIOMA_053 ");
		query.append(" WHERE 1=1 ");
		query.append(SqlUtils.generarWhereIgual("t2.ANYO_053", anyo, params));
		query.append(SqlUtils.generarWhereIgual("t2.NUM_EXP_053", numExp, params));
		return this.getJdbcTemplate().queryForObject(query.toString(), params.toArray(), String.class);
	}

}
