package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.ObservacionesTareas;

/**
 * ObservacionesTareasDaoImpl generated by UDA, 19-jun-2018 13:27:18.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class ObservacionesTareasDaoImpl extends GenericoDaoImpl<ObservacionesTareas> implements ObservacionesTareasDao {

	protected static final String ID_TAREA_085 = "ID_TAREA_085";
	protected static final String IDTAREA = "IDTAREA";
	protected static final String OBSVEJECUCION = "OBSVEJECUCION";

	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { IDTAREA, OBSVEJECUCION };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<ObservacionesTareas> rwMap = new RowMapper<ObservacionesTareas>() {
		@Override
		public ObservacionesTareas mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			final ObservacionesTareas observacionesTareas = new ObservacionesTareas();
			observacionesTareas.setIdTarea(resultSet.getBigDecimal(IDTAREA));
			observacionesTareas.setObsvEjecucion(resultSet.getString(OBSVEJECUCION));
			return observacionesTareas;
		}
	};

	private RowMapper<ObservacionesTareas> rwMapPK = new RowMapper<ObservacionesTareas>() {
		@Override
		public ObservacionesTareas mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			final ObservacionesTareas observacionesTareas = new ObservacionesTareas();
			observacionesTareas.setIdTarea(resultSet.getBigDecimal(IDTAREA));

			return observacionesTareas;
		}
	};

	/**
	 * Constructor
	 */
	public ObservacionesTareasDaoImpl() {
		super(ObservacionesTareas.class);
	}

	@Override
	public ObservacionesTareas add(ObservacionesTareas observacionestareas) {
		String query = "INSERT INTO AA79B85S01 (ID_TAREA_085, OBSV_EJECUCION_085) VALUES (?,?)";
		this.getJdbcTemplate().update(query, observacionestareas.getIdTarea(), observacionestareas.getObsvEjecucion());
		return observacionestareas;
	}

	@Override
	public ObservacionesTareas update(ObservacionesTareas observacionestareas) {
		String query = "UPDATE AA79B85S01 SET ID_TAREA_085=?, OBSV_EJECUCION_085=? WHERE ID_TAREA_085=?";
		this.getJdbcTemplate().update(query, observacionestareas.getIdTarea(), observacionestareas.getObsvEjecucion(),
				observacionestareas.getIdTarea());
		return observacionestareas;
	}

	@Override
	public void remove(ObservacionesTareas observacionestareas) {
		String query = "DELETE FROM AA79B85S01 WHERE ID_TAREA_085=?";
		this.getJdbcTemplate().update(query, observacionestareas.getIdTarea());
	}

	@Override()
	protected String getSelect() {
		StringBuilder query = new StringBuilder();

		query.append("SELECT t1.ID_TAREA_085 IDTAREA");
		query.append(", t1.OBSV_EJECUCION_085 OBSVEJECUCION");

		return query.toString();
	}

	@Override()
	protected String getFrom() {
		StringBuilder query = new StringBuilder();

		query.append(" FROM AA79B85S01 t1 ");

		return query.toString();
	}

	@Override()
	protected RowMapper<ObservacionesTareas> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return ObservacionesTareasDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_TAREA_085;
	}

	@Override()
	protected RowMapper<ObservacionesTareas> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(ObservacionesTareas bean, List<Object> params) {
		params.add(bean.getIdTarea());
		return " WHERE t1.ID_TAREA_085 = ?";
	}

	@Override()
	protected String getWhere(ObservacionesTareas bean, List<Object> params) {

		return this.getWhereClause(bean, params);
	}

	@Override()
	protected String getWhereLike(ObservacionesTareas bean, Boolean startsWith, List<Object> params, Boolean search) {

		return this.getWhereClause(bean, params);
	}

	/**
	 * Obtiene la clausula where
	 * 
	 * @param bean
	 *            ObservacionesTareas
	 * @param params
	 *            List<Object>
	 * @return String
	 */
	private String getWhereClause(ObservacionesTareas bean, List<Object> params) {
		StringBuilder where = new StringBuilder(ObservacionesTareasDaoImpl.STRING_BUILDER_INIT);

		if (bean != null) {
			where.append(SqlUtils.generarWhereIgual(ID_TAREA_085, bean.getIdTarea(), params));
			where.append(SqlUtils.generarWhereIgual("OBSV_EJECUCION_085", bean.getObsvEjecucion(), params));
		}

		return where.toString();
	}

}
