package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.RegistroAccionesExpedienteRwMapper;
import com.ejie.aa79b.dao.mapper.RegistroAccionesRwMapper;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.ListaExpediente;
import com.ejie.aa79b.model.PuntosMenuAplicacion;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.model.enums.AccionesEnum;
import com.ejie.aa79b.model.enums.ActivoEnum;
import com.ejie.aa79b.model.enums.PuntosMenuEnum;
import com.ejie.aa79b.security.Usuario;
import com.ejie.aa79b.utils.DAOUtils;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * RegistroAccionesDaoImpl generated by UDA, 05-dic-2017 12:40:37.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class RegistroAccionesDaoImpl extends GenericoDaoImpl<RegistroAcciones> implements RegistroAccionesDao {

	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	private static final String IDREGISTROACCION = "IDREGISTROACCION043";
	private static final String ID_REGISTRO_ACCION = "ID_REGISTRO_ACCION_043";
	private static final String INSERT_GENERICA = "INSERT INTO AA79B43S01 (ID_REGISTRO_ACCION_043, ID_PUNTO_MENU_043, ID_ACCION_043, IP_043, FECHA_REGISTRO_043, USUARIO_REGISTRO_043, ANYO_EXP_043, NUM_EXP_043,  OBSERV_043, ID_ESTADO_BITACORA_043) VALUES (AA79B43Q00.NEXTVAL,?,?,?,SYSDATE,?,?,?,?,?)";
	private static final String INSERT_GENERICA_BITACORA = "INSERT INTO AA79B43S01 (ID_REGISTRO_ACCION_043, ID_PUNTO_MENU_043, ID_ACCION_043, IP_043, FECHA_REGISTRO_043, USUARIO_REGISTRO_043, ANYO_EXP_043, NUM_EXP_043,  OBSERV_043, ID_ESTADO_BITACORA_043) VALUES (AA79B43Q00.NEXTVAL,?,?,?,SYSDATE,?,?,?,?,(SELECT ESTADO_BITACORA_051 FROM AA79B51S01 WHERE ANYO_051=? AND NUM_EXP_051=?))";
	private static final String DDMMYY = "DD/mm/YY";
	private static final String YYYYMMDDHHMI = "yyyy/MM/dd hh24:mi";
	public static final String SUBSTR_ANYO_043 = "SUBSTR(ANYO_EXP_043,3,4)";
	public static final String TO_CHAR_FECHA_REGISTRO_043 = "TO_CHAR(t1.FECHA_REGISTRO_043,'HH24:MI')";

	public RegistroAccionesDaoImpl() {
		super(RegistroAcciones.class);
	}

	public static final String[] ORDER_BY_WHITE_LIST = new String[] { IDREGISTROACCION, "IDPUNTOMENU043", "IDACCION043",
			"ACCIONDESCES", "ACCIONDESCEU", "IP043", "IDPUNTOMENUDESCES", "IDPUNTOMENUDESCEU", "FECHAREGISTRO043",
			"USUARIOREGISTRO043", "ANYOEXP043", "NUMEXP043", "ANYONUMEXPCONCATENADO", "OBSERV043",
			"IDESTADOBITACORA043", "INDCONFIDENCIALDESCES", "INDCONFIDENCIALDESCEU" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<RegistroAcciones> rwMap = new RegistroAccionesRwMapper();

	private RowMapper<RegistroAcciones> rwMapPK = new RowMapper<RegistroAcciones>() {
		@Override()
		public RegistroAcciones mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new RegistroAcciones(resultSet.getLong(IDREGISTROACCION));
		}
	};

	private RowMapper<PuntosMenuAplicacion> rwMapPuntosMenuAplicacion = new RowMapper<PuntosMenuAplicacion>() {
		@Override()
		public PuntosMenuAplicacion mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			PuntosMenuAplicacion bean = new PuntosMenuAplicacion();
			bean.setIdPuntoMenu(resultSet.getLong("IDPUNTOMENU"));
			bean.setNombre(resultSet.getString(DBConstants.NOMBRE));
			bean.setDescEs(resultSet.getString(DBConstants.DESCES));
			bean.setDescEu(resultSet.getString(DBConstants.DESCEU));
			bean.setEstado(resultSet.getString(DBConstants.ESTADO));
			return bean;
		}
	};

	private RowMapper<RegistroAcciones> rwMapRegistroAccionesExpediente = new RegistroAccionesExpedienteRwMapper();

	@Override()
	public RegistroAcciones add(RegistroAcciones registroAcciones) {
		if (SecurityContextHolder.getContext().getAuthentication() != null) {
			Usuario credentials = (Usuario) SecurityContextHolder.getContext().getAuthentication().getCredentials();
			registroAcciones.setIp(credentials.getIpPuesto());
			registroAcciones.setUsuarioRegistro(credentials.getNif());
		}
		String query = INSERT_GENERICA;
		this.getJdbcTemplate().update(query, registroAcciones.getIdPuntoMenu(), registroAcciones.getIdAccion(),
				registroAcciones.getIp(), registroAcciones.getUsuarioRegistro(), registroAcciones.getAnyo(),
				registroAcciones.getNumExp(), registroAcciones.getObserv(), registroAcciones.getIdEstadoBitacora());
		return registroAcciones;
	}

	@Override()
	public RegistroAcciones addFromWS(RegistroAcciones registroAcciones) {
		String query = INSERT_GENERICA;
		this.getJdbcTemplate().update(query, registroAcciones.getIdPuntoMenu(), registroAcciones.getIdAccion(),
				registroAcciones.getIp(), registroAcciones.getUsuarioRegistro(), registroAcciones.getAnyo(),
				registroAcciones.getNumExp(), registroAcciones.getObserv(), registroAcciones.getIdEstadoBitacora());
		return registroAcciones;
	}

	@Override()
	protected String getSelect() {
		Locale es = new Locale("es");
		Locale eu = new Locale("eu");
		final StringBuilder query = new StringBuilder(Constants.DIEZ);
		query.append(
				"SELECT t1.ID_REGISTRO_ACCION_043 IDREGISTROACCION043, t1.ID_PUNTO_MENU_043 IDPUNTOMENU043, t2.DESC_ES_044 IDPUNTOMENUDESCES, t2.DESC_EU_044 IDPUNTOMENUDESCEU, t1.ID_ACCION_043 IDACCION043, t1.IP_043 IP043, t1.FECHA_REGISTRO_043 FECHAREGISTRO043, TO_CHAR(t1.FECHA_REGISTRO_043,'HH24:MI') HORAREGISTRO043, t1.USUARIO_REGISTRO_043 USUARIOREGISTRO043, t1.ANYO_EXP_043 ANYOEXP043, t1.NUM_EXP_043 NUMEXP043, SUBSTR(t1.ANYO_EXP_043,3,4) || '/' || LPAD(t1.NUM_EXP_043,6,'0') ANYONUMEXPCONCATENADO, t1.OBSERV_043 OBSERV043, t1.ID_ESTADO_BITACORA_043 IDESTADOBITACORA043, ");
		final String mask = this.msg.getMessage("mask.dateTime", null, LocaleContextHolder.getLocale());
		query.append("TO_CHAR(t1.FECHA_REGISTRO_043, '").append(mask).append("') FECHAHORAREGISTRO");
		query.append(DAOUtils.getDecodeAcciones("t1.ID_ACCION_043", "ACCIONDESCES", this.msg, "AccionesEnum", es));
		query.append(DAOUtils.getDecodeAcciones("t1.ID_ACCION_043", "ACCIONDESCEU", this.msg, "AccionesEnum", eu));
		query.append(DaoConstants.SIGNO_COMA);
		query.append("e1.ID_TIPO_EXPEDIENTE_051 IDTIPOEXPEDIENTE051");
		query.append(DaoConstants.SIGNO_COMA);
		query.append("DECODE(i1.IND_CONFIDENCIAL_053, '").append(ActivoEnum.SI.getValue()).append("', '")
				.append(this.msg.getMessage(ActivoEnum.SI.getLabel(), null, es)).append("', '")
				.append(ActivoEnum.NO.getValue()).append("', '")
				.append(this.msg.getMessage(ActivoEnum.NO.getLabel(), null, es)).append("', null, '")
				.append(this.msg.getMessage(ActivoEnum.NO.getLabel(), null, es)).append("') AS INDCONFIDENCIALDESCES");
		query.append(", DECODE(i1.IND_CONFIDENCIAL_053, '").append(ActivoEnum.SI.getValue()).append("', '")
				.append(this.msg.getMessage(ActivoEnum.SI.getLabel(), null, eu)).append("', '")
				.append(ActivoEnum.NO.getValue()).append("', '")
				.append(this.msg.getMessage(ActivoEnum.NO.getLabel(), null, eu)).append("', null, '")
				.append(this.msg.getMessage(ActivoEnum.NO.getLabel(), null, eu)).append("') AS INDCONFIDENCIALDESCEU");
		return query.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B43S01 t1" + DaoConstants.LEFT_JOIN
				+ " AA79B44S01 t2 ON t2.ID_PUNTO_MENU_044 = t1.ID_PUNTO_MENU_043" + DaoConstants.LEFT_JOIN
				+ " AA79B51S01 e1 ON e1.ANYO_051 = t1.ANYO_EXP_043" + DaoConstants.AND
				+ "e1.NUM_EXP_051 = t1.NUM_EXP_043" + DaoConstants.LEFT_JOIN
				+ " AA79B53S01 i1 ON i1.ANYO_053 = e1.ANYO_051" + DaoConstants.AND + "i1.NUM_EXP_053 = e1.NUM_EXP_051";
	}

	@Override()
	protected RowMapper<RegistroAcciones> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_REGISTRO_ACCION;
	}

	@Override()
	protected RowMapper<RegistroAcciones> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(RegistroAcciones bean, List<Object> params) {
		params.add(bean.getIdAccion());
		return " WHERE t1.ID_REGISTRO_ACCION_043 = ?";
	}

	@Override()
	protected String getWhere(RegistroAcciones bean, List<Object> params) {
		StringBuilder where = new StringBuilder(RegistroAccionesDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_REGISTRO_ACCION, bean.getIdRegistroAccion(), params));
		where.append(SqlUtils.generarWhereIgual("ID_PUNTO_MENU_043", bean.getIdPuntoMenu(), params));
		where.append(SqlUtils.generarWhereIgual("ID_ACCION_043", bean.getIdAccion(), params));
		where.append(SqlUtils.generarWhereIgual("IP_043", bean.getIp(), params));
		where.append(SqlUtils.generarWhereIgual("FECHA_REGISTRO_043", bean.getFechaRegistro(), params));
		where.append(SqlUtils.generarWhereIgual("USUARIO_REGISTRO_043", bean.getUsuarioRegistro(), params));
		where.append(SqlUtils.generarWhereIgual("ANYO_EXP_043", bean.getAnyo(), params));
		where.append(SqlUtils.generarWhereIgual("NUM_EXP_043", bean.getNumExp(), params));
		where.append(SqlUtils.generarWhereIgual("OBSERV_043", bean.getObserv(), params));
		where.append(SqlUtils.generarWhereIgual("ID_ESTADO_BITACORA_043", bean.getIdEstadoBitacora(), params));
		return where.toString();
	}

	@Override()
	protected String getWhereLike(RegistroAcciones bean, Boolean startsWith, List<Object> params, Boolean search) {

		StringBuilder whereLike = new StringBuilder(RegistroAccionesDaoImpl.STRING_BUILDER_INIT);
		whereLike.append(SqlUtils.generarWhereIgual(ID_REGISTRO_ACCION, bean.getIdRegistroAccion(), params));
		whereLike.append(SqlUtils.generarWhereIgual("ID_PUNTO_MENU_043", bean.getIdPuntoMenu(), params));
		whereLike.append(SqlUtils.generarWhereIgual("ID_ACCION_043", bean.getIdAccion(), params));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("IP_043", bean.getIp(), params, startsWith));
		if (bean.getHoraRegistroDesde() != null) {
			if (bean.getFechaRegistroDesde() != null) {
				// crear fecha-hora registro desde
				whereLike.append(SqlUtils.generarWhereMayorIgualFechaHora("t1.FECHA_REGISTRO_043", YYYYMMDDHHMI,
						com.ejie.aa79b.utils.DateUtils.crearDateObject(bean.getFechaRegistroDesde(),
								bean.getHoraRegistroDesde()),
						params));
			} else {
				// comparar solo hora registro desde
				whereLike.append(SqlUtils.generarWhereMayorIgual(TO_CHAR_FECHA_REGISTRO_043,
						bean.getHoraRegistroDesde(), params));
			}
		} else {
			// comparar solo fecha registro desde
			whereLike.append(SqlUtils.generarWhereMayorIgualFecha("FECHA_REGISTRO_043", DDMMYY,
					bean.getFechaRegistroDesde(), params));
		}

		if (bean.getHoraRegistroHasta() != null) {
			if (bean.getFechaRegistroHasta() != null) {
				// crear fecha-hora registro desde
				whereLike.append(SqlUtils.generarWhereMenorIgualFechaHora("t1.FECHA_REGISTRO_043", YYYYMMDDHHMI,
						com.ejie.aa79b.utils.DateUtils.crearDateObject(bean.getFechaRegistroHasta(),
								bean.getHoraRegistroHasta()),
						params));
			} else {
				// comparar solo hora registro desde
				whereLike.append(SqlUtils.generarWhereMenorIgual(TO_CHAR_FECHA_REGISTRO_043,
						bean.getHoraRegistroHasta(), params));
			}
		} else {
			// comparar solo fecha registro desde
			whereLike.append(SqlUtils.generarWhereMenorIgualFecha("FECHA_REGISTRO_043", DDMMYY,
					bean.getFechaRegistroHasta(), params));
		}

		whereLike.append(SqlUtils.generarWhereLikeNormalizado("USUARIO_REGISTRO_043", bean.getUsuarioRegistro(), params,
				startsWith));
		whereLike.append(SqlUtils.generarWhereIgual(SUBSTR_ANYO_043,
				bean.getAnyo() != null ? bean.getAnyo().toString() : bean.getAnyo(), params));
		whereLike.append(SqlUtils.generarWhereIgual("NUM_EXP_043", bean.getNumExp(), params));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("OBSERV_043", bean.getObserv(), params, startsWith));
		whereLike.append(SqlUtils.generarWhereIgual("ID_ESTADO_BITACORA_043", bean.getIdEstadoBitacora(), params));
		whereLike.append(SqlUtils.generarWhereIgual("ID_TIPO_EXPEDIENTE_051", bean.getIdTipoExpediente(), params));

		if (null != bean.getExpedienteTradRev()) {
			whereLike.append(SqlUtils.generarWhereIgual("IND_CONFIDENCIAL_053",
					bean.getExpedienteTradRev().getIndConfidencial(), params));
		}

		return whereLike.toString();
	}

	protected String getWhereRegistroAccionesExpedienteLike(RegistroAcciones bean, Boolean startsWith,
			List<Object> params, Boolean search) {
		StringBuilder whereLike = new StringBuilder(RegistroAccionesDaoImpl.STRING_BUILDER_INIT);
		whereLike.append(SqlUtils.generarWhereIgual("t1.ID_REGISTRO_ACCION_043", bean.getIdRegistroAccion(), params));
		whereLike.append(SqlUtils.generarWhereIgual("t1.ID_PUNTO_MENU_043", bean.getIdPuntoMenu(), params));
		whereLike.append(SqlUtils.generarWhereIgual("t1.ID_ACCION_043", bean.getIdAccion(), params));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("t1.IP_043", bean.getIp(), params, startsWith));
		whereLike.append(SqlUtils.generarWhereIgual("t1.FECHA_REGISTRO_043", bean.getFechaRegistro(), params));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("t1.USUARIO_REGISTRO_043", bean.getUsuarioRegistro(),
				params, startsWith));
		whereLike.append(SqlUtils.generarWhereIgual("t1.ANYO_EXP_043", bean.getAnyo(), params));
		whereLike.append(SqlUtils.generarWhereIgual("t1.NUM_EXP_043", bean.getNumExp(), params));
		whereLike.append(SqlUtils.generarWhereLikeNormalizado("t1.OBSERV_043", bean.getObserv(), params, startsWith));
		whereLike.append(SqlUtils.generarWhereIgual("t1.ID_ESTADO_BITACORA_043", bean.getIdEstadoBitacora(), params));
		return whereLike.toString();
	}

	/**
	 * @param listaExpedientes
	 *            ListaExpediente
	 * @return Integer
	 */
	public Integer addRegistroListaExpedientes(ListaExpediente listaExpedientes) {
		String query = INSERT_GENERICA_BITACORA;
		Usuario credentials = (Usuario) SecurityContextHolder.getContext().getAuthentication().getCredentials();
		final List<Object[]> params = new ArrayList<Object[]>();
		final List<Object> aux = new ArrayList<Object>();
		String[] tecnico = { listaExpedientes.getListaExpediente().get(Constants.CERO).getTecnico().getDni() };
		for (Expediente expediente : listaExpedientes.getListaExpediente()) {
			aux.clear();
			aux.add(PuntosMenuEnum.TRAMITACION_EXPEDIENTES.getValue());
			aux.add(AccionesEnum.MODIFICACION.getValue());
			aux.add(credentials.getIpPuesto());
			aux.add(credentials.getNif());
			aux.add(expediente.getAnyo());
			aux.add(expediente.getNumExp());
			aux.add(this.msg.getMessage("label.asignacionTecnico", tecnico, LocaleContextHolder.getLocale()));
			aux.add(expediente.getAnyo());
			aux.add(expediente.getNumExp());
			params.add(aux.toArray());
		}
		this.getJdbcTemplate().batchUpdate(query, params);
		return Constants.UNO;
	}

	@Override
	@Transactional(readOnly = true)
	public String obtenerObservacionesRegistro(RegistroAcciones bean) {
		StringBuilder query = new StringBuilder();
		List<Object> params = new ArrayList<Object>();
		query.append(DaoConstants.SELECT);
		query.append("OBSERV_043");
		query.append(DaoConstants.FROM);
		query.append("AA79B43S01");
		query.append(DaoConstants.WHERE);
		query.append(ID_REGISTRO_ACCION + " = ? ");

		params.add(bean.getIdRegistroAccion());
		return this.getJdbcTemplate().queryForObject(query.toString(), params.toArray(), String.class);
	}

	@Override
	@Transactional(readOnly = true)
	public List<PuntosMenuAplicacion> findPuntosMenuAplicacion(PuntosMenuAplicacion bean) {
		StringBuilder query = new StringBuilder();
		List<Object> params = new ArrayList<Object>();
		query.append(DaoConstants.SELECT);
		query.append("ID_PUNTO_MENU_044 IDPUNTOMENU" + DaoConstants.SIGNO_COMA);
		query.append("NOMBRE_044 " + DBConstants.NOMBRE + DaoConstants.SIGNO_COMA);
		query.append("DESC_ES_044 " + DBConstants.DESCES + DaoConstants.SIGNO_COMA);
		query.append("DESC_EU_044 " + DBConstants.DESCEU + DaoConstants.SIGNO_COMA);
		query.append("ESTADO_044 " + DBConstants.ESTADO);
		query.append(DaoConstants.FROM);
		query.append("AA79B44S01");
		query.append(DaoConstants.WHERE);
		query.append("ESTADO_044 = ? ");

		params.add(bean.getEstado());
		return this.getJdbcTemplate().query(query.toString(), this.rwMapPuntosMenuAplicacion, params.toArray());
	}

	@Override
	@Transactional(readOnly = true)
	public List<RegistroAcciones> findRegistroAccionesExpediente(RegistroAcciones bean,
			JQGridRequestDto jqGridRequestDto, boolean startsWith) {
		StringBuilder query = new StringBuilder();
		List<Object> params = new ArrayList<Object>();
		Locale es = new Locale("es");
		Locale eu = new Locale("eu");

		query.append(DaoConstants.SELECT);
		query.append("t1.ID_REGISTRO_ACCION_043 IDREGISTROACCION043" + DaoConstants.SIGNO_COMA);
		query.append("t1.ID_PUNTO_MENU_043 IDPUNTOMENU043" + DaoConstants.SIGNO_COMA);
		query.append("t2.DESC_ES_044 " + DBConstants.DESCES + DaoConstants.SIGNO_COMA);
		query.append("t2.DESC_EU_044 " + DBConstants.DESCEU + DaoConstants.SIGNO_COMA);
		query.append("t1.ID_ACCION_043 IDACCION043" + DaoConstants.SIGNO_COMA);
		query.append(DAOUtils.getDecodeAcciones("t1.ID_ACCION_043", "ACCIONDESCES", this.msg, "AccionesEnum", es));
		query.append(DAOUtils.getDecodeAcciones("t1.ID_ACCION_043", "ACCIONDESCEU", this.msg, "AccionesEnum", eu));
		query.append("t1.IP_043 IP043" + DaoConstants.SIGNO_COMA);
		query.append("t1.FECHA_REGISTRO_043 FECHAREGISTRO043" + DaoConstants.SIGNO_COMA);

		final String mask = this.msg.getMessage("mask.dateTime", null, LocaleContextHolder.getLocale());
		query.append("TO_CHAR(t1.FECHA_REGISTRO_043, '").append(mask).append("') FECHAHORAREGISTRO");

		query.append("t1.USUARIO_REGISTRO_043 USUARIOREGISTRO043" + DaoConstants.SIGNO_COMA);
		query.append("t1.ANYO_EXP_043 ANYOEXP043" + DaoConstants.SIGNO_COMA);
		query.append("t1.NUM_EXP_043 NUMEXP043" + DaoConstants.SIGNO_COMA);
		query.append("t1.OBSERV_043 OBSERV043" + DaoConstants.SIGNO_COMA);
		query.append("t1.ID_ESTADO_BITACORA_043 IDESTADOBITACORA043");
		query.append(this.getFrom());
		query.append(DaoConstants.BLANK);
		query.append(DaoConstants.LEFT_JOIN);
		query.append("AA79B53S01 e1 ");
		query.append("t1.ANYO_EXP_043 = e1.ANYO_053" + DaoConstants.AND + "t1.NUM_EXP_043 = e1.NUM_EXP_053");
		query.append(DaoConstants.LEFT_JOIN);
		query.append("AA79B44S01 t2 ");
		query.append("t1.ID_PUNTO_MENU_043 = t2.ID_PUNTO_MENU_044");
		query.append(DaoConstants.WHERE_1_1);
		query.append(this.getWhereRegistroAccionesExpedienteLike(bean, startsWith, params, false));
		return this.getJdbcTemplate().query(query.toString(), this.rwMapRegistroAccionesExpediente, params.toArray());
	}

	@Override
	public Integer addRegistroListaExpedientesConsultaModificarGestor(ListaExpediente listaExpedientes) {
		String query = INSERT_GENERICA_BITACORA;
		Usuario credentials = (Usuario) SecurityContextHolder.getContext().getAuthentication().getCredentials();
		final List<Object[]> params = new ArrayList<Object[]>();
		final List<Object> aux = new ArrayList<Object>();
		String[] gestor = { listaExpedientes.getListaExpediente().get(Constants.CERO).getGestorExpediente()
				.getSolicitante().getDni() };
		for (Expediente expediente : listaExpedientes.getListaExpediente()) {
			aux.clear();
			aux.add(PuntosMenuEnum.CONSULTA_EXPEDIENTES.getValue());
			aux.add(AccionesEnum.MODIFICACION.getValue());
			aux.add(credentials.getIpPuesto());
			aux.add(credentials.getNif());
			aux.add(expediente.getAnyo());
			aux.add(expediente.getNumExp());
			aux.add(this.msg.getMessage("label.asignacionGestor", gestor, LocaleContextHolder.getLocale()));
			aux.add(expediente.getAnyo());
			aux.add(expediente.getNumExp());
			params.add(aux.toArray());
		}
		this.getJdbcTemplate().batchUpdate(query, params);
		return Constants.UNO;
	}

	@Override
	public Integer addBatch(List<RegistroAcciones> lista) {
		String query = INSERT_GENERICA_BITACORA;
		Usuario credentials = (Usuario) SecurityContextHolder.getContext().getAuthentication().getCredentials();
		final List<Object[]> params = new ArrayList<Object[]>();
		final List<Object> aux = new ArrayList<Object>();
		for (RegistroAcciones registro : lista) {
			aux.clear();
			aux.add(registro.getIdPuntoMenu());
			aux.add(registro.getIdAccion());
			aux.add(credentials.getIpPuesto());
			aux.add(credentials.getNif());
			aux.add(registro.getAnyo());
			aux.add(registro.getNumExp());
			aux.add(registro.getObserv());
			aux.add(registro.getAnyo());
			aux.add(registro.getNumExp());
			params.add(aux.toArray());
		}
		this.getJdbcTemplate().batchUpdate(query, params);
		return Constants.UNO;
	}

}
