package com.ejie.aa79b.dao;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.sql.DataSource;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.model.Fichero;
import com.ejie.aa79b.model.enums.TipoSubidaEnum;
import com.ejie.aa79b.model.webservices.Aa79bFicheroDocExp;
import com.ejie.aa79b.model.webservices.Aa79bSalidaDatosDescargaDocumentos;

/**
 * DocumentoTareaDaoImpl generated by UDA, 14-Jul-18 15:23:30.
 * 
 * @author javarona
 */

@Repository
@Transactional
public class SubidaFicherosDaoImpl implements SubidaFicherosDao {

	private JdbcTemplate jdbcTemplate;

	private RowMapper<Fichero> rwFichero = new RowMapper<Fichero>() {
		@Override()
		public Fichero mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			Fichero fichero = new Fichero();
			fichero.setNombre(resultSet.getString("NOMBRE_FICHERO"));
			fichero.setOid(resultSet.getString("OID_FICHERO"));
			fichero.setContentType(resultSet.getString("CONTENT_TYPE_FICHERO"));
			fichero.setTamano(resultSet.getLong("TAMANO_FICHERO"));
			return fichero;
		}
	};
	private RowMapper<Aa79bFicheroDocExp> rwAa79bFicheroDocExp = new RowMapper<Aa79bFicheroDocExp>() {
		@Override()
		public Aa79bFicheroDocExp mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			Aa79bFicheroDocExp fichero = new Aa79bFicheroDocExp();
			fichero.setNombre(resultSet.getString("NOMBRE_FICHERO"));
			fichero.setOid(resultSet.getString("OID_FICHERO"));
			fichero.setContentType(resultSet.getString("CONTENT_TYPE_FICHERO"));
			fichero.setTamano(resultSet.getLong("TAMANO_FICHERO"));
			return fichero;
		}
	};

	/**
	 * @return JdbcTemplate
	 */
	public JdbcTemplate getJdbcTemplate() {
		return this.jdbcTemplate;
	}

	/**
	 * @return the rwFichero
	 */
	public RowMapper<Fichero> getRwFichero() {
		return rwFichero;
	}

	/**
	 * @return the rwAa79bFicheroDocExp
	 */
	public RowMapper<Aa79bFicheroDocExp> getRwAa79bFicheroDocExp() {
		return rwAa79bFicheroDocExp;
	}

	/**
	 * Method use to set the datasource.
	 *
	 * @param dataSource
	 *            DataSource
	 */
	@Resource()
	public void setDataSource(DataSource dataSource) {
		this.jdbcTemplate = new JdbcTemplate(dataSource);
	}

	/**
	 * @param tipoSubidaEnum
	 *            TipoSubidaEnum
	 * @param idFichero
	 *            BigDecimal
	 * @return Fichero
	 */
	@Override
	public Fichero find(TipoSubidaEnum tipoSubidaEnum, BigDecimal idFichero) {

		List<Object> params = new ArrayList<Object>();
		params.add(idFichero);

		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.SELECT).append(tipoSubidaEnum.getNombreCampo()).append(" NOMBRE_FICHERO")
				.append(DaoConstants.SIGNO_COMA).append(tipoSubidaEnum.getContentTypeCampo())
				.append(" CONTENT_TYPE_FICHERO");
		query.append(DaoConstants.SIGNO_COMA).append(tipoSubidaEnum.getOidCampo()).append(" OID_FICHERO");
		query.append(DaoConstants.SIGNO_COMA).append(tipoSubidaEnum.getTamanoCampo()).append(" TAMANO_FICHERO");
		query.append(DaoConstants.FROM).append(tipoSubidaEnum.getTabla());
		query.append(DaoConstants.WHERE).append(tipoSubidaEnum.getIdFichero())
				.append(DaoConstants.SIGNOIGUAL_INTERROGACION);

		return this.getJdbcTemplate().queryForObject(query.toString(), params.toArray(), this.getRwFichero());

	}

	/**
	 * @param tipoSubidaEnum
	 *            TipoSubidaEnum
	 * @param idFichero
	 *            BigDecimal
	 * @return Fichero
	 */

	@Override
	public Aa79bSalidaDatosDescargaDocumentos findWS(TipoSubidaEnum tipoSubidaEnum, List<BigDecimal> listaIdsFicheros) {

		Aa79bSalidaDatosDescargaDocumentos aa79bSalidaDatosDescargaDocumentos = new Aa79bSalidaDatosDescargaDocumentos();

		List<Object> params = new ArrayList<Object>();

		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.SELECT).append(tipoSubidaEnum.getNombreCampo()).append(" NOMBRE_FICHERO")
				.append(DaoConstants.SIGNO_COMA).append(tipoSubidaEnum.getContentTypeCampo())
				.append(" CONTENT_TYPE_FICHERO");
		query.append(DaoConstants.SIGNO_COMA).append(tipoSubidaEnum.getOidCampo()).append(" OID_FICHERO");
		query.append(DaoConstants.SIGNO_COMA).append(tipoSubidaEnum.getTamanoCampo()).append(" TAMANO_FICHERO");
		query.append(DaoConstants.FROM).append(tipoSubidaEnum.getTabla());
		query.append(DaoConstants.WHERE).append(tipoSubidaEnum.getIdFichero()).append(DaoConstants.IN)
				.append(DaoConstants.ABRIR_PARENTESIS);

		for (BigDecimal idFichero : listaIdsFicheros) {
			params.add(idFichero);
			query.append(DaoConstants.SIGNOINTERROGACION).append(DaoConstants.SIGNO_COMA);
		}
		String laQuery = query.substring(0, query.length());
		laQuery += DaoConstants.CERRAR_PARENTESIS;

		List<Aa79bFicheroDocExp> listaDevuelta = this.getJdbcTemplate().query(laQuery, this.getRwAa79bFicheroDocExp(),
				params.toArray());

		aa79bSalidaDatosDescargaDocumentos.setListaFicheros(listaDevuelta);
		return aa79bSalidaDatosDescargaDocumentos;
	}

}