package com.ejie.aa79b.dao;

import java.util.List;

import com.ejie.aa79b.model.TipoRelevancia;

/**
 * TipoRelevanciaDao generated by UDA, 24-oct-2017 15:14:42.
 * 
 * @author UDA
 */

public interface TipoRelevanciaDao extends GenericoDao<TipoRelevancia> {

    /**
     * Comprueba que la prioridad introducida no este asignada a otro objeto
     *
     * @param tipoRelevancia
     *            TipoRelevancia Bean
     * @return boolean determina si hay conflicto de prioridades.
     */
    boolean comprobarPrioridad(TipoRelevancia tipoRelevancia);

    /**
     * @param tipoRelevancia
     *            TipoRelevancia Bean
     * @return List<TipoRelevancia> lista de tipos.
     */
    List<TipoRelevancia> findAllByIdAndState(TipoRelevancia tipoRelevancia);
}
