package com.ejie.aa79b.dao;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.dao.support.DataAccessUtils;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.TiposTarea;
import com.ejie.aa79b.model.enums.ActivoEnum;
import com.ejie.aa79b.model.enums.EstadoEnum;
import com.ejie.aa79b.model.enums.TipoExpedienteEnum;
import com.ejie.aa79b.model.enums.TipoExpedienteGrupoEnum;
import com.ejie.aa79b.model.enums.TipoTareaGestionAsociadaEnum;

/**
 * TiposTareaDaoImpl generated by UDA, 27-nov-2017 15:13:32.
 *
 * @author UDA
 */

@Repository
@Transactional
public class TiposTareaDaoImpl extends GenericoDaoImpl<TiposTarea> implements TiposTareaDao {

	protected static final String ID015 = "ID015";
	protected static final String N = "', 'N', '";
	protected static final String T1DESC_EU_015 = "t1.DESC_EU_015";
	protected static final String T1DESC_ES_015 = "t1.DESC_ES_015";
	protected static final String COMUN_SI = "comun.si";
	protected static final String COMUN_NO = "comun.no";

	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	public TiposTareaDaoImpl() {
		super(TiposTarea.class);
	}

	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { ID015, "DESCES015", "DESCEU015",
			"INDGESTIONASOC015", "INDTIEMPOGESTION015", "INDREQCIERRE015", "ESTADO015", "ESTADODESCEU", "ESTADODESCES",
			"INDGESTIONASOCEU", "INDGESTIONASOCES", "INDTIEMPOGESTIONES", "INDTIEMPOGESTIONEU", "INDREQCIERREES",
			"INDREQCIERREEU", "DESCNORMEU", "DESCNORMES", "INDVISIBLETRABAJO015" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<TiposTarea> rwMap = new RowMapper<TiposTarea>() {
		@Override
		public TiposTarea mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			TiposTarea tarea = new TiposTarea(resultSet.getLong(ID015), resultSet.getString("DESCES015"),
					resultSet.getString("DESCEU015"), resultSet.getString("INDGESTIONASOC015"),
					resultSet.getString("INDREQCIERRE015"), resultSet.getString("ESTADO015"));
			tarea.setDescEstadoEu(resultSet.getString("ESTADODESCEU"));
			tarea.setDescEstadoEs(resultSet.getString("ESTADODESCES"));
			tarea.setDescGestionEu(resultSet.getString("INDGESTIONASOCEU"));
			tarea.setDescGestionEs(resultSet.getString("INDGESTIONASOCES"));
			tarea.setDescTiempoGestionEs(resultSet.getString("INDTIEMPOGESTIONES"));
			tarea.setDescTiempoGestionEu(resultSet.getString("INDTIEMPOGESTIONEU"));
			tarea.setDescCierreEs(resultSet.getString("INDREQCIERREES"));
			tarea.setDescCierreEu(resultSet.getString("INDREQCIERREEU"));
			tarea.setIndTiempoGestion015(resultSet.getString("INDTIEMPOGESTION015"));
			tarea.setIndHorasEjecucion015(resultSet.getString("INDHORASEJECUCION"));
			tarea.setIndFacturable015(resultSet.getString("INDFACTURABLE"));
			tarea.setIndInterpretacion015(resultSet.getString("INDINTERPRETACION"));
			tarea.setIndVisibleTrabajo015(resultSet.getString("INDVISIBLETRABAJO015"));
			return tarea;
		}
	};

	private RowMapper<TiposTarea> rwMapPK = new RowMapper<TiposTarea>() {
		@Override
		public TiposTarea mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new TiposTarea(resultSet.getLong(ID015));
		}
	};

	/*
	 * OPERACIONES CRUD
	 */

	/**
	 * Inserts a single row in the TiposTarea table.
	 *
	 * @param tipostarea TiposTarea
	 * @return TiposTarea
	 */
	@Override
	public TiposTarea add(TiposTarea tipostarea) {
		String query = "INSERT INTO AA79B15S01 (ID_015, DESC_ES_015, DESC_EU_015, IND_GESTION_ASOC_015, IND_REQ_CIERRE_015, ESTADO_015, IND_VISIBLE_TRABAJO_015) VALUES (AA79B15Q00.NEXTVAL,?,?,?,?,?,?)";
		this.getJdbcTemplate().update(query, tipostarea.getDescEs015(), tipostarea.getDescEu015(),
				tipostarea.getIndGestionAsoc015() != null ? tipostarea.getIndGestionAsoc015() : Constants.NO,
				tipostarea.getIndReqCierre015() != null ? tipostarea.getIndReqCierre015() : Constants.NO,
				tipostarea.getEstado015(), tipostarea.getIndVisibleTrabajo015() != null ? tipostarea.getIndVisibleTrabajo015() : Constants.NO);
		return tipostarea;
	}

	/**
	 * Updates a single row in the TiposTarea table.
	 *
	 * @param tipostarea TiposTarea
	 * @return TiposTarea
	 */
	@Override
	public TiposTarea update(TiposTarea tipostarea) {
		String query = "UPDATE AA79B15S01 SET DESC_ES_015=?, DESC_EU_015=?, IND_GESTION_ASOC_015=?, IND_TIEMPO_GESTION_015=?, IND_REQ_CIERRE_015=?, ESTADO_015=?, IND_VISIBLE_TRABAJO_015=? WHERE ID_015=?";
		this.getJdbcTemplate().update(query, tipostarea.getDescEs015(), tipostarea.getDescEu015(),
				tipostarea.getIndGestionAsoc015() != null ? tipostarea.getIndGestionAsoc015() : Constants.NO,
				tipostarea.getIndTiempoGestion015() != null ? tipostarea.getIndTiempoGestion015() : Constants.NO,
				tipostarea.getIndReqCierre015() != null ? tipostarea.getIndReqCierre015() : Constants.NO,
				tipostarea.getEstado015(), tipostarea.getIndVisibleTrabajo015() != null ? tipostarea.getIndVisibleTrabajo015() : Constants.NO, tipostarea.getId015());
		return tipostarea;
	}

	@Override
	protected String getSelect() {
		Locale es = new Locale("es");
		Locale eu = new Locale("eu");
		StringBuilder selectTiposTarea = new StringBuilder();

		selectTiposTarea.append("SELECT t1.ID_015 ID015");
		selectTiposTarea.append(", t1.DESC_EU_015 DESCEU015");
		selectTiposTarea.append(", t1.DESC_ES_015 DESCES015");
		selectTiposTarea.append(", t1.IND_GESTION_ASOC_015 INDGESTIONASOC015");
		selectTiposTarea.append(", t1.IND_TIEMPO_GESTION_015 INDTIEMPOGESTION015");
		selectTiposTarea.append(", t1.IND_REQ_CIERRE_015 INDREQCIERRE015");
		selectTiposTarea.append(", t1.ESTADO_015 ESTADO015");
		selectTiposTarea.append(", t1.IND_HORAS_EJECUCION_015 INDHORASEJECUCION");
		selectTiposTarea.append(", t1.IND_FACTURABLE_015 INDFACTURABLE");
		selectTiposTarea.append(", t1.IND_INTERPRETACION_015 INDINTERPRETACION");
		selectTiposTarea.append(", DECODE(t1.ESTADO_015, 'A', '").append(this.msg.getMessage("estado.alta", null, es))
				.append("', 'B', '").append(this.msg.getMessage("estado.baja", null, es)).append("') AS ESTADODESCES");
		selectTiposTarea.append(", DECODE(t1.ESTADO_015, 'A', '").append(this.msg.getMessage("estado.alta", null, eu))
				.append("', 'B', '").append(this.msg.getMessage("estado.baja", null, eu)).append("') AS ESTADODESCEU");

		selectTiposTarea.append(", DECODE(t1.IND_GESTION_ASOC_015, 'S', '")
				.append(this.msg.getMessage(COMUN_SI, null, es)).append(N)
				.append(this.msg.getMessage(COMUN_NO, null, es)).append("') AS INDGESTIONASOCES");
		selectTiposTarea.append(", DECODE(t1.IND_GESTION_ASOC_015, 'S', '")
				.append(this.msg.getMessage(COMUN_SI, null, eu)).append(N)
				.append(this.msg.getMessage(COMUN_NO, null, eu)).append("') AS INDGESTIONASOCEU");

		selectTiposTarea.append(", DECODE(t1.IND_GESTION_ASOC_015, 'N', '-', ")
				.append("DECODE(t1.IND_TIEMPO_GESTION_015, 'S', '").append(this.msg.getMessage(COMUN_SI, null, es))
				.append(N).append(this.msg.getMessage(COMUN_NO, null, es)).append("')) AS INDTIEMPOGESTIONES");
		selectTiposTarea.append(", DECODE(t1.IND_GESTION_ASOC_015, 'N', '-', ")
				.append("DECODE(t1.IND_TIEMPO_GESTION_015, 'S', '").append(this.msg.getMessage(COMUN_SI, null, eu))
				.append(N).append(this.msg.getMessage(COMUN_NO, null, eu)).append("')) AS INDTIEMPOGESTIONEU");

		selectTiposTarea.append(", DECODE(t1.IND_REQ_CIERRE_015, 'S', '")
				.append(this.msg.getMessage(COMUN_SI, null, es)).append(N)
				.append(this.msg.getMessage(COMUN_NO, null, es)).append("') AS INDREQCIERREES");
		selectTiposTarea.append(", DECODE(t1.IND_REQ_CIERRE_015, 'S', '")
				.append(this.msg.getMessage(COMUN_SI, null, eu)).append(N)
				.append(this.msg.getMessage(COMUN_NO, null, eu)).append("') AS INDREQCIERREEU");

		selectTiposTarea.append(", ").append(SqlUtils.normalizarCampoSql(T1DESC_EU_015)).append(" AS DESCNORMEU");
		selectTiposTarea.append(", ").append(SqlUtils.normalizarCampoSql(T1DESC_ES_015)).append(" AS DESCNORMES");
		selectTiposTarea.append(", t1.IND_VISIBLE_TRABAJO_015 INDVISIBLETRABAJO015");

		return selectTiposTarea.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B15S01 t1";
	}

	@Override()
	protected RowMapper<TiposTarea> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return TiposTareaDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return "ID_015";
	}

	@Override()
	protected RowMapper<TiposTarea> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(TiposTarea bean, List<Object> params) {
		params.add(bean.getId015());
		return " WHERE t1.ID_015 = ?";
	}

	@Override
	protected String getWhere(TiposTarea bean, List<Object> params) {
		StringBuilder where = new StringBuilder(TiposTareaDaoImpl.STRING_BUILDER_INIT);

		where.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_015, bean.getId015(),
				params));
		where.append(SqlUtils.generarWhereLikeNormalizado(T1DESC_EU_015, bean.getDescEu015(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado(T1DESC_ES_015, bean.getDescEs015(), params, false));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_GESTION_ASOC_015,
						bean.getIndGestionAsoc015(), params, false));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_REQ_CIERRE_015,
						bean.getIndReqCierre015(), params, false));

		where.append(
				SqlUtils.generarWhereLikeNormalizado(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_VISIBLE_TRABAJO_015,
						bean.getIndVisibleTrabajo015(), params, false));

		where.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ESTADO_015,
				bean.getEstado015(), params));

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put("query", where);
		mapWhere.put("params", params);

		return where.toString();
	}

	@Override
	protected String getWhereLike(TiposTarea bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(TiposTareaDaoImpl.STRING_BUILDER_INIT);

		where.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_015, bean.getId015(),
				params));
		where.append(SqlUtils.generarWhereLikeNormalizado(T1DESC_EU_015, bean.getDescEu015(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado(T1DESC_ES_015, bean.getDescEs015(), params, startsWith));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_GESTION_ASOC_015,
						bean.getIndGestionAsoc015(), params, false));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_REQ_CIERRE_015,
						bean.getIndReqCierre015(), params, false));
		where.append(
				SqlUtils.generarWhereLikeNormalizado(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_VISIBLE_TRABAJO_015,
						bean.getIndVisibleTrabajo015(), params, false));
		where.append(SqlUtils.generarWhereIgual(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ESTADO_015,
				bean.getEstado015(), params));

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put("query", where);
		mapWhere.put("params", params);

		return where.toString();
	}

	@Override
	public List<TiposTarea> findTiposTareaManuales(String tipoExpediente, boolean correspondeBOE,
			boolean isCorredaccion, boolean isExpCerrado, boolean noConfSinResponer) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getSelect());
		query.append(this.getFrom());
		query.append(this.getWhereTiposTareaManuales(params, tipoExpediente, correspondeBOE, isCorredaccion,
				isExpCerrado, noConfSinResponer));
		query.append(" ORDER BY indreqcierre015 desc, id_015");
		return this.getJdbcTemplate().query(query.toString(), this.getRwMap(), params.toArray());
	}

	private String getWhereTiposTareaManuales(List<Object> params, String tipoExpediente, boolean correspondeBOE,
			boolean isCorredaccion, boolean isExpCerrado, boolean noConfSinResponer) {
		StringBuilder where = new StringBuilder(TiposTareaDaoImpl.STRING_BUILDER_INIT);

		where.append(GenericoDaoImpl.DEFAULT_WHERE);
		where.append(" AND ESTADO_015 = '").append(Constants.ALTA).append("'");
		where.append(" AND IND_AUTOMATICA_015 = '").append(Constants.NO).append("'");

		if (isExpCerrado || noConfSinResponer) {
			if (TipoExpedienteEnum.TRADUCCION.getValue().equals(tipoExpediente)
					|| TipoExpedienteEnum.REVISION.getValue().equals(tipoExpediente)) {
				where.append(DaoConstants.AND + DaoConstants.ABRIR_PARENTESIS);
				where.append(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_REQ_CIERRE_015 + DaoConstants.SIGNOIGUAL
						+ DaoConstants.SIGNO_APOSTROFO + Constants.NO + DaoConstants.SIGNO_APOSTROFO);
				if (!noConfSinResponer) {
					where.append(DaoConstants.OR);
					where.append(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_015 + DaoConstants.SIGNOIGUAL);
					where.append(TipoTareaGestionAsociadaEnum.NO_CONFORMIDAD_CLIENTE.getValue());
				}
				where.append(DaoConstants.CERRAR_PARENTESIS);
			} else {
				where.append(SqlUtils.generarWhereIgual(
						DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.IND_REQ_CIERRE_015, Constants.NO, params));
			}
		}

		if (!correspondeBOE) {
			where.append(DaoConstants.AND);
			where.append(DaoConstants.T1_MINUSCULA);
			where.append(DaoConstants.SIGNO_PUNTO);
			where.append(DBConstants.ID_015);
			where.append(DaoConstants.SIGNO_DISTINTO);
			where.append(TipoTareaGestionAsociadaEnum.POST_TRADUCCION_BOE.getValue()).append(" ");
		}

		if (TipoExpedienteEnum.TRADUCCION.getValue().equals(tipoExpediente)) {
			where.append(SqlUtils.generarWhereIgual("t1.IND_TRADUCCION_015", Constants.SI, params));
			where.append(DaoConstants.AND);
			where.append(DaoConstants.T1_MINUSCULA);
			where.append(DaoConstants.SIGNO_PUNTO);
			where.append(DBConstants.ID_015);
			where.append(DaoConstants.SIGNO_DISTINTO);
			if (isCorredaccion) {
				where.append(TipoTareaGestionAsociadaEnum.TRADUCIR.getValue());
				where.append(DaoConstants.AND);
				where.append(DaoConstants.T1_MINUSCULA);
				where.append(DaoConstants.SIGNO_PUNTO);
				where.append(DBConstants.ID_015);
				where.append(DaoConstants.SIGNO_DISTINTO);
				where.append(TipoTareaGestionAsociadaEnum.ENTREGA_CLIENTE_TRADUCCION.getValue());
				where.append(DaoConstants.AND);
				where.append(DaoConstants.T1_MINUSCULA);
				where.append(DaoConstants.SIGNO_PUNTO);
				where.append(DBConstants.ID_015);
				where.append(DaoConstants.SIGNO_DISTINTO);
				where.append(TipoTareaGestionAsociadaEnum.NO_CONFORMIDAD_CLIENTE.getValue());
				where.append(DaoConstants.AND);
				where.append(DaoConstants.T1_MINUSCULA);
				where.append(DaoConstants.SIGNO_PUNTO);
				where.append(DBConstants.ID_015);
				where.append(DaoConstants.SIGNO_DISTINTO);
				where.append(TipoTareaGestionAsociadaEnum.TRAD_ENTREGA_CLIENTE_TRADUCCION.getValue());
			} else {
				where.append(TipoTareaGestionAsociadaEnum.CORREDACTAR.getValue());
			}
		} else if (TipoExpedienteEnum.REVISION.getValue().equals(tipoExpediente)) {
			where.append(SqlUtils.generarWhereIgual("t1.IND_REVISION_015", Constants.SI, params));
		} else if (TipoExpedienteEnum.INTERPRETACION.getValue().equals(tipoExpediente)) {
			where.append(SqlUtils.generarWhereIgual("t1.IND_INTERPRETACION_015", Constants.SI, params));
		}

		return where.toString();
	}

	@Override
	public TiposTarea getTipoTareaIdTarea(BigDecimal idTarea) {

		List<Object> paramsTTPTE = new ArrayList<Object>();
		StringBuilder queryTTPTE = new StringBuilder(this.getSelect());
		queryTTPTE.append(" FROM AA79B81S01 t2");
		queryTTPTE.append(" JOIN AA79B15S01 t1 ON t2.id_tipo_tarea_081 = t1.ID_015 ");
		queryTTPTE.append(DaoConstants.WHERE_1_1);
		queryTTPTE.append(SqlUtils.generarWhereIgual("t2.ID_TAREA_081", idTarea, paramsTTPTE));
		List<TiposTarea> beanList = this.getJdbcTemplate().query(queryTTPTE.toString(), this.getRwMap(),
				paramsTTPTE.toArray());
		return DataAccessUtils.uniqueResult(beanList);
	}

	@Override
	public List<TiposTarea> getTipoTareaPorTipoExpediente(Expediente expediente) {
		List<String> listaExpedientes = new ArrayList<String>();
		listaExpedientes.add(TipoExpedienteEnum.INTERPRETACION.getValue());
		listaExpedientes.add(TipoExpedienteEnum.REVISION.getValue());
		listaExpedientes.add(TipoExpedienteEnum.TRADUCCION.getValue());
		listaExpedientes.add(TipoExpedienteGrupoEnum.TRADUCCION_REVISION.getCode());
		List<Object> paramsTTPTE = new ArrayList<Object>();
		StringBuilder queryTTPTE = new StringBuilder(this.getSelect());
		queryTTPTE.append(this.getFrom());
		queryTTPTE.append(DaoConstants.WHERE_1_1);
		if (listaExpedientes.contains(expediente.getIdTipoExpediente())) {
			if (TipoExpedienteEnum.TRADUCCION.getValue().equals(expediente.getIdTipoExpediente())) {

				queryTTPTE.append(
						SqlUtils.generarWhereIgual("t1.IND_TRADUCCION_015", ActivoEnum.SI.getValue(), paramsTTPTE));
			} else if (TipoExpedienteEnum.REVISION.getValue().equals(expediente.getIdTipoExpediente())) {

				queryTTPTE.append(
						SqlUtils.generarWhereIgual("t1.IND_REVISION_015", ActivoEnum.SI.getValue(), paramsTTPTE));
			} else if (TipoExpedienteGrupoEnum.TRADUCCION_REVISION.getCode().equals(expediente.getIdTipoExpediente())) {

				queryTTPTE.append(
						SqlUtils.generarWhereIgual("t1.IND_TRADUCCION_015", ActivoEnum.SI.getValue(), paramsTTPTE));
				queryTTPTE.append(DaoConstants.OR + "t1.IND_REVISION_015" + DaoConstants.SIGNOIGUAL
						+ DaoConstants.SIGNO_APOSTROFO + ActivoEnum.SI.getValue() + DaoConstants.SIGNO_APOSTROFO);
			} else {

				this.getQueryPorTipoExpediente(queryTTPTE, expediente.getIdTipoExpediente(), paramsTTPTE);
			}

		}
		queryTTPTE.append(SqlUtils.generarWhereIgual("t1.ESTADO_015", EstadoEnum.ALTA.getValue(), paramsTTPTE));
		queryTTPTE.append(" ORDER BY indreqcierreeu, id_015");
		return this.getJdbcTemplate().query(queryTTPTE.toString(), this.getRwMap(), paramsTTPTE.toArray());
	}

	@Override
	public TiposTarea getTipoTareaPorIdTarea(BigDecimal idTarea) {
		List<String> listaExpedientes = new ArrayList<String>();
		listaExpedientes.add(TipoExpedienteEnum.INTERPRETACION.getValue());
		listaExpedientes.add(TipoExpedienteEnum.REVISION.getValue());
		listaExpedientes.add(TipoExpedienteEnum.TRADUCCION.getValue());
		listaExpedientes.add(TipoExpedienteGrupoEnum.TRADUCCION_REVISION.getCode());
		List<Object> paramsTTPTE = new ArrayList<Object>();
		StringBuilder queryTTPTE = new StringBuilder(this.getSelect());
		queryTTPTE.append(this.getFrom());
		queryTTPTE.append(" JOIN AA79B81T00 t2 ON t2.ID_TIPO_TAREA_081 = T1.ID_015");
		queryTTPTE.append(DaoConstants.WHERE_1_1);
		queryTTPTE.append(SqlUtils.generarWhereIgual("t2.ID_TAREA_081", idTarea, paramsTTPTE));
		List<TiposTarea> tiposTarea = this.getJdbcTemplate().query(queryTTPTE.toString(), this.getRwMap(),
				paramsTTPTE.toArray());
		return DataAccessUtils.uniqueResult(tiposTarea);
	}

	public void getQueryPorTipoExpediente(StringBuilder queryTTPTE, String idTipoExpediente, List<Object> params) {
		if (idTipoExpediente.equals(TipoExpedienteEnum.INTERPRETACION.getValue())) {
			queryTTPTE.append(
					SqlUtils.generarWhereLike("t1.IND_INTERPRETACION_015", ActivoEnum.SI.getValue(), params, false));
		} else if (idTipoExpediente.equals(TipoExpedienteEnum.TRADUCCION.getValue())) {
			queryTTPTE.append(
					SqlUtils.generarWhereLike("t1.IND_TRADUCCION_015", ActivoEnum.SI.getValue(), params, false));
		} else if (idTipoExpediente.equals(TipoExpedienteEnum.REVISION.getValue())) {
			queryTTPTE
					.append(SqlUtils.generarWhereLike("t1.IND_REVISION_015", ActivoEnum.SI.getValue(), params, false));
		}

	}

}
