/*
* Copyright 2024 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/
package com.ejie.x21a.control;


import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.TableRequestDto;
import com.ejie.x38.dto.TableResponseDto;
import com.ejie.x38.dto.TableRowDto;
import com.ejie.x38.util.DateTimeManager;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.ServletRequestDataBinder;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import org.springframework.web.multipart.support.ByteArrayMultipartFileEditor; 
import com.ejie.x21a.service.AreasService;

import java.math.BigDecimal;
import com.ejie.x21a.model.Areas;


/**
 * AreasController generated by UDA", 22-Nov-2024 08:27:48.
 * @author UDA
 */

@Controller
@RequestMapping(value = "/areas")

public class AreasController  {
	private static final Logger logger = LoggerFactory.getLogger(AreasController.class);

	@Autowired
	private AreasService areasService;

	@InitBinder
	protected void initBinder(HttpServletRequest request, ServletRequestDataBinder binder) throws ServletException {
		binder.registerCustomEditor(byte[].class,new ByteArrayMultipartFileEditor());
		binder.registerCustomEditor(Date.class, new CustomDateEditor(DateTimeManager.getDateTimeFormat(LocaleContextHolder.getLocale()), true));
	}
	
	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 */
	
	/**
	 * Operación CRUD Read. Devuelve el bean correspondiente al identificador indicado.
	 *  
	 * @param id_area_t21 BigDecimal
	 *
	 * @return Areas Objeto correspondiente al identificador indicado.
	 */

	@GetMapping(value = "/{idAreaT21}")
	public @ResponseBody Areas get(@PathVariable BigDecimal idAreaT21  ) {
        Areas areas = new Areas();
		
		areas.setIdAreaT21(idAreaT21);
		
        areas = this.areasService.find(areas);
        AreasController.logger.info("[GET - findBy_PK] : Obtener Areas por PK");
        return areas;
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterAreas Areas
	 *            Objeto que contiene los parametros de filtrado utilizados en
	 *            la busqueda.
	 * @return List<Areas> 
	 *            Lista de objetos correspondientes a la busqueda realizada.
	 */
	@GetMapping(value = "/all")
	public @ResponseBody List<Areas> getAll(@ModelAttribute Areas filterAreas) {
		AreasController.logger.info("[GET - find_ALL] : Obtener Areas por filtro");
	    return this.areasService.findAll(filterAreas, null);
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param areas Areas 
	 *            Bean que contiene la informacion a modificar.
	 * @return Areas 
	 *            Bean resultante de la modificacion.
	 */
	@PutMapping(value = "/edit")
    public @ResponseBody Areas edit(@RequestBody Areas areas) {		
        Areas areasAux = this.areasService.update(areas);
		AreasController.logger.info("[PUT] : Areas actualizado correctamente");
        return areasAux;
    }

	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param areas Areas 
	 *            Bean que contiene la informacion con la que se va a crear el
	 *            nuevo registro.
	 * @return Areas
	 *            Bean resultante del proceso de creacion.
	 */
	@PostMapping(value = "/add")
	public @ResponseBody Areas add(@RequestBody Areas areas) {		
        Areas areasAux = this.areasService.add(areas);
        AreasController.logger.info("[POST] : Areas insertado correctamente");
    	return areasAux;
	}

	/**
	 * Operación CRUD Delete. Borrado del registro correspondiente al identificador indicado.
	 *  
	 * @param id_area_t21 BigDecimal
	 *
	 * @return Areas Objeto correspondiente al identificador indicado.
	 */

	@DeleteMapping(value = "/{idAreaT21}")
	public @ResponseBody Areas remove(@PathVariable BigDecimal idAreaT21  ) {
        Areas areas = new Areas();
		
		areas.setIdAreaT21(idAreaT21);
		
        this.areasService.remove(areas);
        AreasController.logger.info("[DELETE] : Obtener Areas borrado correctamente");
        return areas;
	}    
	
	/*
	 * MÉTODOS COMPONENTE RUP_TABLE
	 */

	 /**
	 * Metodo de presentacion del RUP_TABLE.
	 * 
	 * @param model Model
	 * @return String
	 */
	@GetMapping(value = "/maint")
	public String getFormEdit(Model model) {
		AreasController.logger.info("[GET - View] : areas");
		model.addAttribute("content", "areas/areas");
		model.addAttribute("includes", "areas/areas-includes");
		model.addAttribute("areas", new Areas());
		return "template";
	}
	 
	 /**
	 * Operacion de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterAreas Areas
	 *            Bean que contiene los parametros de filtrado a emplear.
	 * @param tableRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return TableResponseDto<Areas>
	 *            Dto que contiene el resultado del filtrado realizado por el 
	 *            componente RUP_TABLE.
	 */
	@PostMapping(value = "/filter")
	public @ResponseBody TableResponseDto<Areas> filter(
			@RequestJsonBody(param="filter") Areas filterAreas,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		AreasController.logger.info("[POST - filter] : Obtener Areass");
		return this.areasService.filter(filterAreas, tableRequestDto, false);
	}
	 
	/**
	 * Operacion de busqueda del componente RUP_TABLE.
	 * 
	 * @param filterAreas Areas
	 *            Bean que contiene los parametros de filtrado a emplear.
	 * @param searchAreas Areas
	 *            Bean que contiene los parametros de busqueda a emplear.
	 * @param tableRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la búsqueda.
	 * @return TableRowDto<Areas> 
	 *            Dto que contiene el resultado de la busqueda realizada por el
	 *            componente RUP_TABLE. 
	 */
	@PostMapping(value = "/search")
	public @ResponseBody List<TableRowDto<Areas>> search(
			@RequestJsonBody(param="filter") Areas filterAreas,
			@RequestJsonBody(param="search") Areas searchAreas,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		AreasController.logger.info("[POST - search] : Buscar Areass");
		return this.areasService.search(filterAreas, searchAreas, tableRequestDto, false);
	}
	
	/**
	 * Borrado multiple de registros
	 * 
	 * @param filterAreas Areas
	 *            Bean que contiene los parametros de filtrado a emplear.
	 * @param tableRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la busqueda.
	 * @return List<String>
	 *            Lista de los identificadores de los registros eliminados.
	 * 
	 */
	@PostMapping(value = "/deleteAll")
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody List<String> removeMultiple(
			@RequestJsonBody(param="filter") Areas filterAreas,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		AreasController.logger.info("[POST - removeMultiple] : Eliminar multiples Areass");
		this.areasService.removeMultiple(tableRequestDto);
		AreasController.logger.info("All entities correctly deleted!");
		
		return tableRequestDto.getMultiselection().getSelectedIds();
	}
	
	/**
 	 * EXPORTERS
 	 */
	
	/**
	 * Devuelve los datos exportados de la tabla y los copia al Portapapeles.
	 *
	 * @param filterAreas Areas
	 * @param tableRequestDto TableRequestDto
	 */	 
	@PostMapping(value = "/clipboardReport")
	protected @ResponseBody List<Areas> getClipboardReport(
			@RequestJsonBody(param="filter") Areas  filterAreas ,
			@RequestJsonBody TableRequestDto  tableRequestDto) {
		AreasController.logger.info("[POST - clipboardReport] : : Copiar en Portapapeles");
		return this.areasService.getDataForReports(filterAreas, tableRequestDto);
	}
	
	/**
	 * Devuelve un fichero excel que contiene los datos exportados de la tabla.
	 *
	 * @param filter          Areas
	 * @param columns         String[]
	 * @param fileName        String
	 * @param sheetTitle      String
	 * @param tableRequestDto TableRequestDto
	 * @param request         HttpServletRequest
	 * @param response        HttpServletResponse
	 */
	@PostMapping(value = { "/xlsReport","/xlsxReport" }, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	protected @ResponseBody void generateExcelReport(@RequestJsonBody(param = "filter", required = false) Areas filter,
			@RequestJsonBody(param = "columns", required = false) String[] columns,
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName,
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto, HttpServletRequest request, HttpServletResponse response)
			throws ServletException {
		AreasController.logger.info("[POST - generateExcelReport] : Devuelve un fichero excel");

		this.areasService.generateReport(filter, columns,columnsName, fileName, sheetTitle,reportsParams, tableRequestDto, request, response);
	}
	
		/**
	 * Devuelve un fichero pdf que contiene los datos exportados de la tabla.
	 *
	 * @param filter          Areas
	 * @param columns         String[]
	 * @param fileName        String
	 * @param sheetTitle      String
	 * @param tableRequestDto TableRequestDto
	 * @param request         HttpServletRequest
	 * @param response        HttpServletResponse
	 */
	@PostMapping(value = "pdfReport", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	protected @ResponseBody void generatePDFReport(@RequestJsonBody(param = "filter", required = false) Areas filter,
			@RequestJsonBody(param = "columns", required = false) String[] columns,
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName,
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto, HttpServletRequest request,
			HttpServletResponse response) {
		AreasController.logger.info("[POST - generatePDFReport] : Devuelve un fichero pdf");

		this.areasService.generateReport(filter, columns,columnsName, fileName, sheetTitle,reportsParams, tableRequestDto, request, response);
	}
	
		/**
	 * Devuelve un fichero ods que contiene los datos exportados de la tabla.
	 *
	 * @param filter          Areas
	 * @param columns         String[]
	 * @param fileName        String
	 * @param sheetTitle      String
	 * @param tableRequestDto TableRequestDto
	 * @param request         HttpServletRequest
	 * @param response        HttpServletResponse
	 */
	@PostMapping(value = "odsReport", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	protected @ResponseBody void generateODSReport(@RequestJsonBody(param = "filter", required = false) Areas filter,
			@RequestJsonBody(param = "columns", required = false) String[] columns,
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName,
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto, HttpServletRequest request,
			HttpServletResponse response) {
		AreasController.logger.info("[POST - generateODSReport] : Devuelve un fichero ods");

		this.areasService.generateReport(filter, columns,columnsName, fileName, sheetTitle,reportsParams, tableRequestDto, request, response);
	}

	/**
	 * Devuelve un fichero csv que contiene los datos exportados de la tabla.
	 *
	 * @param filter          Areas
	 * @param columns         String[]
	 * @param fileName        String
	 * @param sheetTitle      String
	 * @param tableRequestDto TableRequestDto
	 * @param request         HttpServletRequest
	 * @param response        HttpServletResponse
	 */
	@PostMapping(value = "csvReport", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	protected @ResponseBody void generateCSVReport(@RequestJsonBody(param = "filter", required = false) Areas filter,
			@RequestJsonBody(param = "columns", required = false) String[] columns,
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName,
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto, HttpServletRequest request,
			HttpServletResponse response) {
		AreasController.logger.info("[POST - generateCSVReport] : Devuelve un fichero csv");

		this.areasService.generateReport(filter, columns,columnsName, fileName, sheetTitle,reportsParams, tableRequestDto, request, response);
	}
	
	
	
}