/*
* Copyright 2012 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, VersiÃ³n 1.1 exclusivamente (la Â«LicenciaÂ»);
* Solo podrÃ¡ usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislaciÃ³n aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye Â«TAL CUALÂ»,
* SIN GARANTÃ�AS NI CONDICIONES DE NINGÃšN TIPO, ni expresas ni implÃ­citas.
* VÃ©ase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/
package com.ejie.x21a.control;

import java.math.BigDecimal;
import java.text.Normalizer;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.hdiv.services.NoEntity;
import org.hdiv.services.TrustAssertion;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.beans.propertyeditors.CustomNumberEditor;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.hateoas.Resource;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.ServletRequestDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.support.ByteArrayMultipartFileEditor;

import com.ejie.x21a.exception.X21aRuntimeException;
import com.ejie.x21a.model.AutocompleteComboGenericPOJO;
import com.ejie.x21a.model.Comarca;
import com.ejie.x21a.model.Localidad;
import com.ejie.x21a.model.MultiPk;
import com.ejie.x21a.model.TableOptions;
import com.ejie.x21a.model.Usuario;
import com.ejie.x21a.model.Usuario2;
import com.ejie.x21a.service.TableUsuarioService;
import com.ejie.x21a.util.ResourceUtils;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.TableRequestDto;
import com.ejie.x38.dto.TableResourceResponseDto;
import com.ejie.x38.dto.TableRowDto;
import com.ejie.x38.hdiv.annotation.UDALink;
import com.ejie.x38.hdiv.annotation.UDALinkAllower;
import com.ejie.x38.rup.table.filter.model.Filter;
import com.ejie.x38.rup.table.filter.service.FilterService;
import com.ejie.x38.util.DateTimeManager;

/**
 * UsuarioServiceImpl generated by UDA 1.0, 26-may-2011 13:46:35.
 * 
 * @author UDA
 */

@Controller
@RequestMapping (value = "/table")
public class TableUsuarioController {
	private static final Logger logger = LoggerFactory.getLogger(TableUsuarioController.class);
	public static final String MODEL_USUARIO = "usuario";
	public static final String MODEL_OPTIONS = "options";
	
	@Autowired
	private TableUsuarioService tableUsuarioService;
	
	@Autowired
	private FilterService filterService;
	
	@javax.annotation.Resource
	private ReloadableResourceBundleMessageSource messageSource;
	
	@InitBinder
	protected void initBinder(HttpServletRequest request, ServletRequestDataBinder binder) throws ServletException {
		binder.registerCustomEditor(byte[].class,new ByteArrayMultipartFileEditor());
		binder.registerCustomEditor(Date.class, new CustomDateEditor(DateTimeManager.getDateTimeFormat(LocaleContextHolder.getLocale()), true));
		NumberFormat numberFormat = NumberFormat.getInstance(LocaleContextHolder.getLocale());
		binder.registerCustomEditor(BigDecimal.class, new CustomNumberEditor(BigDecimal.class, numberFormat, true));
	}

	/*
	 * OPERACIONES CRUD
	 * 
	 * Metodos correspondientes a las operaciones CRUD (Create, Read, Update, Delete). 
	 * 
	 */
	
	/**
	 * OperaciÃ³n CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 * 
	 * @param id
	 *            Identificador del objeto que se desea recuperar.
	 * @return Objeto correspondiente al identificador indicado.
	 */
	@UDALink(name = "get", linkTo = { @UDALinkAllower(name = "edit"), 
			@UDALinkAllower(name = "getRoles"),@UDALinkAllower(name = "remove"), @UDALinkAllower(name = "filter")})
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public @ResponseBody Resource<Usuario> get(@PathVariable String id) {
        Usuario usuario = new Usuario();
		usuario.setId(id);
        usuario = this.tableUsuarioService.find(usuario);
		TableUsuarioController.logger.info("[GET - findBy_PK] : Obtener Usuarios por PK");
        return new Resource<Usuario>(usuario);
	}
	
	@UDALink(name = "get2", linkTo = { @UDALinkAllower(name = "edit2" ), 
			@UDALinkAllower(name = "remove" ),@UDALinkAllower(name = "getRoles"), @UDALinkAllower(name = "filter2")})
	@RequestMapping(value = "/{bis}/{id}", method = RequestMethod.GET)
	public @ResponseBody Resource<Usuario2> get2(@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis, 
			@PathVariable String id) {
        Usuario usuario = new Usuario();
		usuario.setId(id);
        usuario = this.tableUsuarioService.find(usuario);

		Usuario2 aux = new Usuario2();
		aux.setId2(usuario.getId());
		aux.setNombre2(usuario.getNombre());
		aux.setApellido12(usuario.getApellido1());
		aux.setFechaAlta2(usuario.getFechaAlta());
		aux.setFechaBaja2(usuario.getFechaBaja());
		aux.setRol2(usuario.getRol());

		return new Resource<Usuario2>(aux);
	}
	
	@UDALink(name = "getFiltroSimple", linkTo = {
			@UDALinkAllower(name = "getTableEditForm"),
			@UDALinkAllower(name = "getTableInlineEdit"),
			@UDALinkAllower(name = "getApellidos"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "deleteAll"),
			@UDALinkAllower(name = "getMultiFilterForm"),
			@UDALinkAllower(name = "multifilterAdd"),
			@UDALinkAllower(name = "multifilterDelete"),
			@UDALinkAllower(name = "multifilterDefault"),
			@UDALinkAllower(name = "multifilterGetAll"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "/configurable", method = RequestMethod.GET)
	public String getFiltroSimple (Model model) {
		Usuario usuario = new Usuario();
		model.addAttribute(MODEL_USUARIO, usuario);
		model.addAttribute(MODEL_OPTIONS, new TableOptions());
		
		Map<String,String> comboRol = new LinkedHashMap<String,String>();
		comboRol.put("", "---");
		comboRol.put("Administrador", "Administrador");
		comboRol.put("Desarrollador", "Desarrollador");
		comboRol.put("Espectador", "Espectador");
		comboRol.put("Informador", "Informador");
		comboRol.put("Manager", "Manager");
		model.addAttribute("comboRol", comboRol);
		
		Map<String,String> comboEjie = new LinkedHashMap<String,String>();
		comboEjie.put("", "---");
		comboEjie.put("0", "No");
		comboEjie.put("1", "S�");
		model.addAttribute("comboEjie", comboEjie);
		
		return "table";
	}
	
	@UDALink(name = "getTableDouble", linkTo = {
			@UDALinkAllower(name = "getTableEditForm"),
			@UDALinkAllower(name = "getTableDoubleEditForm"),
			@UDALinkAllower(name = "getApellidos"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "deleteAll"),
			@UDALinkAllower(name = "getMultiFilterForm"),
			@UDALinkAllower(name = "getMultiFilterForm2"),
			@UDALinkAllower(name = "multifilterAdd"),
			@UDALinkAllower(name = "multifilterDelete"),
			@UDALinkAllower(name = "multifilterDefault"),
			@UDALinkAllower(name = "multifilterGetAll"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "clipboardReport2"),
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "excelReport2"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "pdfReport2"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "odsReport2"),
			@UDALinkAllower(name = "csvReport"),
			@UDALinkAllower(name = "csvReport2")})
	@RequestMapping(value = "/double", method = RequestMethod.GET)
	public String getTableDouble (Model model) {
		model.addAttribute(MODEL_USUARIO, new Usuario());
		model.addAttribute(MODEL_OPTIONS, new TableOptions());
		
		Map<String,String> comboRol = new LinkedHashMap<String,String>();
		comboRol.put("", "---");
		comboRol.put("Administrador", "Administrador");
		comboRol.put("Desarrollador", "Desarrollador");
		comboRol.put("Espectador", "Espectador");
		comboRol.put("Informador", "Informador");
		comboRol.put("Manager", "Manager");
		model.addAttribute("comboRol", comboRol);
		
		Map<String,String> comboEjie = new LinkedHashMap<String,String>();
		comboEjie.put("", "---");
		comboEjie.put("0", "No");
		comboEjie.put("1", "S�");
		model.addAttribute("comboEjie", comboEjie);
		
		return "tableDouble";
	}
	
	@UDALink(name = "getSimpleMasterDetail", linkTo = {
			@UDALinkAllower(name = "getTableComarcaEditForm"),
			@UDALinkAllower(name = "getTableDialogComarcaEditForm"),
			@UDALinkAllower(name = "getTableLocalidadEditForm"),
			@UDALinkAllower(name = "getProvincias", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "deleteAll"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "getMultiFilterForm"),
			@UDALinkAllower(name = "multifilterAdd"),
			@UDALinkAllower(name = "multifilterDelete"),
			@UDALinkAllower(name = "multifilterDefault"),
			@UDALinkAllower(name = "multifilterGetAll"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "masterDetail", method = RequestMethod.GET)
	public String getSimpleMasterDetail(Model model) {
		model.addAttribute("tituloPagina", messageSource.getMessage("tablaMasterDetail", null, LocaleContextHolder.getLocale()));
		
		Comarca comarca = new Comarca();
		Localidad localidad = new Localidad();
		localidad.setComarca(comarca);
		
		model.addAttribute("comarca", comarca);
		model.addAttribute("localidad", localidad);
		
		return "tableMasterDetail";
	}
	
	@UDALink(name = "getMasterDialog", linkTo = {
			@UDALinkAllower(name = "getTableComarcaEditForm"),
			@UDALinkAllower(name = "getTableDialogComarcaEditForm"),
			@UDALinkAllower(name = "getTableLocalidadEditForm"),
			@UDALinkAllower(name = "getProvincias", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "deleteAll"),
			@UDALinkAllower(name = "getMultiFilterForm"),
			@UDALinkAllower(name = "multifilterAdd"),
			@UDALinkAllower(name = "multifilterDelete"),
			@UDALinkAllower(name = "multifilterDefault"),
			@UDALinkAllower(name = "multifilterGetAll"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "masterDialog", method = RequestMethod.GET)
	public String getMasterDialog(Model model) {
		model.addAttribute("tituloPagina", messageSource.getMessage("tablaMasterDetail", null, LocaleContextHolder.getLocale()));

		Comarca comarca = new Comarca();
		Localidad localidad = new Localidad();
		localidad.setComarca(comarca);
		
		model.addAttribute("comarca", comarca);
		model.addAttribute("localidad", localidad);
		
		return "tableDialogDetail";
	}
	
	@UDALink(name = "getTableDialog", linkTo = {
			@UDALinkAllower(name = "getTableEditForm", linkClass = TableMultiPkController.class),
			@UDALinkAllower(name = "getTableDialogAjax"),
			@UDALinkAllower(name = "deleteAll"),
			@UDALinkAllower(name = "getMultiFilterForm"),
			@UDALinkAllower(name = "multifilterAdd"),
			@UDALinkAllower(name = "multifilterDelete"),
			@UDALinkAllower(name = "multifilterDefault"),
			@UDALinkAllower(name = "multifilterGetAll"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "tableDialog", method = RequestMethod.GET)
	public String getTableDialog(Model model) {
		model.addAttribute("tituloPagina", messageSource.getMessage("tabla Dialog", null, LocaleContextHolder.getLocale()));
		model.addAttribute("multiPk", new MultiPk());
		return "tableDialog";
	}
	
	@UDALink(name = "getTableDialogAjax", linkTo = {
			@UDALinkAllower(name = "getTableEditForm"),
			@UDALinkAllower(name = "getApellidos"),
			@UDALinkAllower(name = "deleteAll"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "getMultiFilterForm"),
			@UDALinkAllower(name = "multifilterAdd"),
			@UDALinkAllower(name = "multifilterDelete"),
			@UDALinkAllower(name = "multifilterDefault"),
			@UDALinkAllower(name = "multifilterGetAll"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "/tableDialogAjax", method = RequestMethod.GET)
	public String getTableDialogAjax (Model model) {
		model.addAttribute(MODEL_USUARIO, new Usuario());
		model.addAttribute(MODEL_OPTIONS, new TableOptions());
		
		Map<String,String> comboRol = new LinkedHashMap<String,String>();
		comboRol.put("", "---");
		comboRol.put("Administrador", "Administrador");
		comboRol.put("Desarrollador", "Desarrollador");
		comboRol.put("Espectador", "Espectador");
		comboRol.put("Informador", "Informador");
		comboRol.put("Manager", "Manager");
		model.addAttribute("comboRol", comboRol);
		
		Map<String,String> comboEjie = new LinkedHashMap<String,String>();
		comboEjie.put("", "---");
		comboEjie.put("0", "No");
		comboEjie.put("1", "S�");
		model.addAttribute("comboEjie", comboEjie);
		
		return "tableDialogAjax";
	}
	
	@UDALink(name = "getTableEditForm", linkTo = {
			@UDALinkAllower(name = "getApellidos"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "get"),
			@UDALinkAllower(name = "add"),
			@UDALinkAllower(name = "edit"),
			@UDALinkAllower(name = "filter")})
	@RequestMapping(value = "/editForm", method = RequestMethod.POST)
	public String getTableEditForm (
			@RequestParam(required = true) String actionType,
			@RequestParam(required = false) String fixedMessage,
			Model model) {
		model.addAttribute(MODEL_USUARIO, new Usuario());
		model.addAttribute("actionType", actionType);
		if (fixedMessage != null) {
			model.addAttribute("fixedMessage", fixedMessage);
		}
		
		return "tableEditForm";
	}
	
	@UDALink(name = "getTableDoubleEditForm", linkTo = {
			@UDALinkAllower(name = "getApellidos"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "get2"),
			@UDALinkAllower(name = "add2"),
			@UDALinkAllower(name = "edit2"),
			@UDALinkAllower(name = "filter2")})
	@RequestMapping(value = "/editFormDouble", method = RequestMethod.POST)
	public String getTableDoubleEditForm (@RequestParam String actionType, Model model) {
		model.addAttribute("usuario2", new Usuario2());
		model.addAttribute("actionType", actionType);
		
		return "tableDoubleEditForm";
	}
	
	@UDALink(name = "getTableComarcaEditForm", linkTo = {
			@UDALinkAllower(name = "get", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "add", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "edit", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "filter", linkClass = TableComarcaController.class)})
	@RequestMapping(value = "/editFormComarca", method = RequestMethod.POST)
	public String getTableComarcaEditForm (@RequestParam String actionType, Model model) {
		model.addAttribute("comarca", new Comarca());
		model.addAttribute("actionType", actionType);
		
		return "tableComarcaEditForm";
	}
	
	@UDALink(name = "getTableDialogComarcaEditForm", linkTo = {
			@UDALinkAllower(name = "get", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "add", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "edit", linkClass = TableComarcaController.class),
			@UDALinkAllower(name = "filter", linkClass = TableComarcaController.class)})
	@RequestMapping(value = "/editFormDialogComarca", method = RequestMethod.POST)
	public String getTableDialogComarcaEditForm (@RequestParam String actionType, Model model) {
		model.addAttribute("comarca", new Comarca());
		model.addAttribute("actionType", actionType);
		
		return "tableDialogComarcaEditForm";
	}
	
	@UDALink(name = "getTableLocalidadEditForm", linkTo = {
			@UDALinkAllower(name = "get", linkClass = TableLocalidadController.class),
			@UDALinkAllower(name = "add", linkClass = TableLocalidadController.class),
			@UDALinkAllower(name = "edit", linkClass = TableLocalidadController.class),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "filter", linkClass = TableLocalidadController.class)})
	@RequestMapping(value = "/editFormLocalidad", method = RequestMethod.POST)
	public String getTableLocalidadEditForm (@RequestParam String actionType, Model model) {
		Comarca comarca = new Comarca();
		Localidad localidad = new Localidad();
		localidad.setComarca(comarca);
		
		model.addAttribute("comarca", comarca);
		model.addAttribute("localidad", localidad);
		model.addAttribute("actionType", actionType);
		
		return "tableLocalidadEditForm";
	}
	
	@UDALink(name = "getTableInlineEdit", linkTo = {
			@UDALinkAllower(name = "get"),
			@UDALinkAllower(name = "add"),
			@UDALinkAllower(name = "getRoles"),
			@UDALinkAllower(name = "edit"),
			@UDALinkAllower(name = "filter")})
	@RequestMapping(value = "/inlineEdit", method = RequestMethod.POST)
	public String getTableInlineEdit (
			@RequestParam(required = true) String actionType,
			@RequestParam(required = true) String tableID,
			@RequestParam(required = false) String mapping,
			Model model) {
		model.addAttribute("entity", new Usuario());
		model.addAttribute("actionType", actionType);
		model.addAttribute("tableID", tableID);
		
		// Controlar que el mapping siempre se a�ada al modelo de la manera esperada
		if (mapping == null || mapping.isEmpty()) {
			mapping = "/table";
		} else if (mapping.endsWith("/")) {
			mapping = mapping.substring(0, mapping.length() - 1);
		}
		model.addAttribute("mapping", mapping);
		
		return "tableInlineEditAuxForm";
	}
	
	@UDALink(name = "getApellidos")
	@RequestMapping(value = "/apellidos", method = RequestMethod.GET)
	public @ResponseBody List<AutocompleteComboGenericPOJO> getApellidos (
			@RequestParam(value = "q", required = false) String q,
            @RequestParam(value = "c", required = false) Boolean c) {
		List<AutocompleteComboGenericPOJO> apellidos = new ArrayList<AutocompleteComboGenericPOJO>();
		if(q != null){
			q = Normalizer.normalize(q, Normalizer.Form.NFD);
			q = q.replaceAll("[^\\p{ASCII}]", "");
			q = q.toUpperCase();
		}else{
			q = "";
		}

		List<String> listaApellidos = new ArrayList<String>();
		listaApellidos.add("Garc�a");
		listaApellidos.add("Gonz�lez");
		listaApellidos.add("Fern�ndez");
		listaApellidos.add("Rodr�guez");
		listaApellidos.add("L�pez");
		listaApellidos.add("Mart�nez");
		listaApellidos.add("S�nchez");
		listaApellidos.add("P�rez");
		listaApellidos.add("G�mez");
		listaApellidos.add("Mart�n");
		listaApellidos.add("Jim�nez");
		listaApellidos.add("Ruiz");
		listaApellidos.add("Hern�ndez");
		listaApellidos.add("D�az");
		listaApellidos.add("Moreno");
		listaApellidos.add("�lvarez");
		listaApellidos.add("Mu�oz");
		listaApellidos.add("Romero");
		listaApellidos.add("Alonso");
		listaApellidos.add("Guti�rrez");
		listaApellidos.add("Navarro");
		listaApellidos.add("Torres");
		listaApellidos.add("Dom�nguez");
		listaApellidos.add("V�zquez");
		listaApellidos.add("Ramos");
		listaApellidos.add("Prueba");
		listaApellidos.add("Pedroche");
		listaApellidos.add("Zangano");
		listaApellidos.add("Perurena");
		listaApellidos.add("Neymar");
		listaApellidos.add("Tranquilino");
		
		for(String str : listaApellidos)
		{
			String original = str;
			str = Normalizer.normalize(str, Normalizer.Form.NFD);
			str = str.toUpperCase();
			str = str.replaceAll("[^\\p{ASCII}]", "");
			if(q.equals("") || str.indexOf(q) >= 0){
				apellidos.add(new AutocompleteComboGenericPOJO(original, original));
			}
		}
		
		return apellidos;
	}
	
	@UDALink(name = "getRoles")
	@RequestMapping(value = "/roles", method = RequestMethod.GET)
	public @ResponseBody List<AutocompleteComboGenericPOJO> getRoles (
			@RequestParam(value = "q", required = false) String q,
            @RequestParam(value = "c", required = false) Boolean c) {	
		List<AutocompleteComboGenericPOJO> roles = new ArrayList<AutocompleteComboGenericPOJO>();
		roles.add(new AutocompleteComboGenericPOJO("Administrador", "Administrador"));
		roles.add(new AutocompleteComboGenericPOJO("Desarrollador", "Desarrollador"));
		roles.add(new AutocompleteComboGenericPOJO("Espectador", "Espectador"));
		roles.add(new AutocompleteComboGenericPOJO("Informador", "Informador"));
		roles.add(new AutocompleteComboGenericPOJO("Manager", "Manager"));
		
		return roles;
	}
	
	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parÃ¡metro.
	 * 
	 * @param usuarioFilter
	 *            Objeto que contiene los parÃ¡metros de filtrado utilizados en
	 *            la bÃºsqueda.
	 * @return Lista de objetos correspondientes a la bÃºsqueda realizada.
	 */
	@UDALink(name = "getall", linkTo = { @UDALinkAllower(name = "edit" ), 
			@UDALinkAllower(name = "remove" ), 
			@UDALinkAllower(name = "getRoles"),@UDALinkAllower(name = "get" )})
	@RequestMapping(value = "/all",method = RequestMethod.GET)
	public @ResponseBody
	List<Resource<Usuario>> getAll(@ModelAttribute() Usuario usuarioFilter){
		TableUsuarioController.logger.info("[GET - find_ALL] : Obtener Usuarios por filtro");
		return ResourceUtils.fromListToResource(this.tableUsuarioService.findAllLike(usuarioFilter, null, false));
	}
	
	/**
	 * OperaciÃ³n CRUD Edit. ModificaciÃ³n del bean indicado.
	 * 
	 * @param usuario
	 *            Bean que contiene la informaciÃ³n a modificar.
	 * @return Bean resultante de la modificaciÃ³n.
	 */
	@UDALink(name = "edit", linkTo = { @UDALinkAllower(name = "filter")})
	@RequestMapping(value = "/edit", method = RequestMethod.PUT)
    public @ResponseBody Resource<Usuario> edit(@RequestBody Usuario usuario) {
		Usuario usuarioAux = this.tableUsuarioService.update(usuario);
		logger.info("Entity correctly updated!");
        return new Resource<Usuario>(usuarioAux);
    }
	
	@UDALink(name = "edit2", linkTo = { @UDALinkAllower(name = "filter2")})
	@RequestMapping(value = "/{bis}/edit", method = RequestMethod.PUT)
    public @ResponseBody Resource<Usuario2> edit2(@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
    		@RequestBody Usuario2 usuario) {
		Usuario2 usuarioAux = this.tableUsuarioService.update(usuario);
		logger.info("Entity correctly updated!");
		return new Resource<Usuario2>(usuarioAux);
    }
	
	@UDALink(name = "editar")
	@RequestMapping(value = "/editar", method = RequestMethod.PUT, produces="application/json")
    public @ResponseBody Resource<Usuario> editar(
    		@Validated @ModelAttribute Usuario usuario,
    		@RequestParam(value = "imagenAlumno", required = false) MultipartFile imagen,
    		HttpServletRequest request, HttpServletResponse response){
		System.out.print("USUARIO::::"+usuario.getId()+" --- "+new Date()+"\n");
		if (imagen!=null){
			System.out.print("IMAGEN::::"+imagen);
        }
        Usuario usuarioAux = this.tableUsuarioService.update(usuario);
		logger.info("Entity correctly updated!");
		return new Resource<Usuario>(usuarioAux);
    }

	/**
	 * OperaciÃ³n CRUD Create. CreaciÃ³n de un nuevo registro a partir del bean
	 * indicado.
	 * 
	 * @param usuario
	 *            Bean que contiene la informaciÃ³n con la que se va a crear el
	 *            nuevo registro.
	 * @return Bean resultante del proceso de creaciÃ³n.
	 */
	@UDALink(name = "add", linkTo = { @UDALinkAllower(name = "filter") })
	@RequestMapping(value = "/add", method = RequestMethod.POST)
	public @ResponseBody Resource<Usuario> add(@Validated @RequestBody Usuario usuario) {		
		Usuario usuarioAux = this.tableUsuarioService.add(usuario);
        logger.info("Entity correctly inserted!");	
        return new Resource<Usuario>(usuarioAux);
	}
	
	@UDALink(name = "add2", linkTo = { @UDALinkAllower(name = "filter2") })
	@RequestMapping(value = "/{bis}/add", method = RequestMethod.POST)
	public @ResponseBody Resource<Usuario2> add2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis, 
			@Validated @RequestBody Usuario2 usuario) {		
		Usuario2 usuarioAux = this.tableUsuarioService.add(usuario);
        logger.info("Entity correctly inserted!");	
        return new Resource<Usuario2>(usuarioAux);
	}
	

	/**
	 * OperaciÃ³n CRUD Delete. Borrado del registro correspondiente al
	 * identificador especificado.
	 * 
	 * @param id
	 *            Identificador del objeto que se desea eliminar.
	 * @return Bean eliminado.
	 */
	@UDALink(name = "remove")
	@RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
	@ResponseStatus(value=HttpStatus.OK)
    public @ResponseBody Resource<Usuario> remove(@PathVariable String id, HttpServletResponse  response) {
        Usuario usuario = new Usuario();
        usuario.setId(id);
        this.tableUsuarioService.remove(usuario);
        logger.info("Entity correctly deleted!");
        return new Resource<Usuario>(usuario);
    }
	
	
	/*
	 * METODOS COMPONENTE RUP_TABLE
	 * 
	 */
	
	/**
	 * OperaciÃ³n de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterUsuario Usuario
	 *            Bean que contiene los parÃ¡metros de filtrado a emplear.
	 * @param tableRequestDto TableRequestDto
	 *            Dto que contiene los parÃ¡mtros de configuraciÃ³n propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return Dto que contiene el resultado del filtrado realizado por el
	 *         componente RUP_TABLE.
	 * 
	 */
	//@Json(mixins={@JsonMixin(target=Usuario.class, mixin=UsuarioMixIn.class)})
	@UDALink(name = "filter", linkTo = { @UDALinkAllower(name = "get"), 
			@UDALinkAllower(name = "remove"),
	@UDALinkAllower(name = "getRoles"), @UDALinkAllower(name = "filter"), @UDALinkAllower(name = "deleteAll")})
	@RequestMapping(value = "/filter", method = RequestMethod.POST)
	public @ResponseBody TableResourceResponseDto<Usuario> filter(
			@RequestJsonBody(param="filter") Usuario filterUsuario,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		TableUsuarioController.logger.info("[POST - table] : Obtener Usuarios");
		return filterUsuario(filterUsuario, tableRequestDto);
	}

	private TableResourceResponseDto<Usuario> filterUsuario(final Usuario filterUsuario, final TableRequestDto tableRequestDto) {
		return tableUsuarioService.filter(filterUsuario, tableRequestDto, false);
	}

	@SuppressWarnings("unchecked")
	@UDALink(name = "filter2", linkTo = { @UDALinkAllower(name = "get2"), 
	@UDALinkAllower(name = "remove")
	, @UDALinkAllower(name = "filter2"),
	@UDALinkAllower(name = "getRoles")
	, @UDALinkAllower(name = "deleteAll")})
	@RequestMapping(value = "{bis}/filter", method = RequestMethod.POST)
	@ResponseBody()
	public TableResourceResponseDto<Usuario2> filter2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
			@RequestJsonBody(param="filter") Usuario2 filterUsuario,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		TableUsuarioController.logger.info("[POST - table] : Obtener Usuarios 2");
		try {
			tableRequestDto.setSidx(tableRequestDto.getSidx().substring(0, tableRequestDto.getSidx().length()-1));
			TableResourceResponseDto<Usuario> rdo1 = this.filterUsuario(filterUsuario, tableRequestDto);
			List<Usuario2> rows = new ArrayList<Usuario2>();
			for (Resource<Usuario> usuarioResource : (List<Resource<Usuario>>) rdo1.getRows()) {
				Usuario2 aux = new Usuario2();
				Usuario usuario = usuarioResource.getContent();
				aux.setId(usuario.getId());
				aux.setNombre(usuario.getNombre());
				aux.setApellido1(usuario.getApellido1());
				aux.setFechaAlta(usuario.getFechaAlta());
				aux.setFechaBaja(usuario.getFechaBaja());
				aux.setRol(usuario.getRol());
				rows.add(aux);
			}
			return new TableResourceResponseDto<Usuario2>(tableRequestDto, Long.valueOf(rdo1.getRecords()), Long.valueOf(rdo1.getRecords()), rows);
		} catch (Exception e) {
			throw new X21aRuntimeException(e);
		}
	}
	
	// Obtiene el formulario del multi filtro
	@UDALink(name = "getMultiFilterForm")
	@RequestMapping(value = "/multiFilter", method = RequestMethod.POST)
	public String getMultiFilterForm (
			@RequestParam(required = false) String mapping,
			@RequestParam(required = true) String tableID,
			@RequestParam(required = true) String containerClass,
			@RequestParam(required = true) String labelClass,
			@RequestParam(required = true) String defaultContainerClass,
			@RequestParam(required = true) String defaultCheckboxClass,
			Model model) {
		model.addAttribute("entity", new Usuario());
		model.addAttribute("tableID", tableID);
		model.addAttribute("containerClass", containerClass);
		model.addAttribute("labelClass", labelClass);
		model.addAttribute("defaultContainerClass", defaultContainerClass);
		model.addAttribute("defaultCheckboxClass", defaultCheckboxClass);
		
		// Controlar que el mapping siempre se a�ada al modelo de la manera esperada
		if (mapping == null || mapping.isEmpty()) {
			mapping = "/table/multiFilter";
		} else if (mapping.endsWith("/")) {
			mapping = mapping.substring(0, mapping.length() - 1);
		}
		model.addAttribute("mapping", mapping);
		
		return "multiFilterForm";
	}
	
	// Obtiene el formulario del multi filtro
	@UDALink(name = "getMultiFilterForm2")
	@RequestMapping(value = "{bis}/multiFilter", method = RequestMethod.POST)
	public String getMultiFilterForm2 (
			@RequestParam(required = false) String mapping,
			@RequestParam(required = true) String tableID,
			@RequestParam(required = true) String containerClass,
			@RequestParam(required = true) String labelClass,
			@RequestParam(required = true) String defaultContainerClass,
			@RequestParam(required = true) String defaultCheckboxClass,
			Model model) {
		model.addAttribute("entity", new Usuario2());
		model.addAttribute("tableID", tableID);
		model.addAttribute("containerClass", containerClass);
		model.addAttribute("labelClass", labelClass);
		model.addAttribute("defaultContainerClass", defaultContainerClass);
		model.addAttribute("defaultCheckboxClass", defaultCheckboxClass);
		
		// Controlar que el mapping siempre se a�ada al modelo de la manera esperada
		if (mapping == null || mapping.isEmpty()) {
			mapping = "/table/multiFilter";
		} else if (mapping.endsWith("/")) {
			mapping = mapping.substring(0, mapping.length() - 1);
		}
		model.addAttribute("mapping", mapping);
		
		return "multiFilterForm";
	}
	
	// A�ade o actualiza un filtro
	@UDALink(name = "multifilterAdd")
	@RequestMapping(value = "/multiFilter/add", method = RequestMethod.POST)
	public @ResponseBody Resource<Filter> filterAdd(@RequestBody Filter filtro){
		TableUsuarioController.logger.info("[POST - table] : add filter");
		return new Resource<Filter>(filterService.insert(filtro));
	}
	
	// Elimina un filtro
	@UDALink(name = "multifilterDelete")
	@RequestMapping(value = "/multiFilter/delete", method = RequestMethod.POST)
	public @ResponseBody Resource<Filter> filterDelete(@RequestBody Filter filtro) {
		TableUsuarioController.logger.info("[POST - table] : delete filter");
		return new Resource<Filter>(filterService.delete(filtro));
	}
	
	// Obtiene el filtro por defecto
	@UDALink(name = "multifilterDefault")
	@RequestMapping(value = "/multiFilter/getDefault", method = RequestMethod.GET)
	public @ResponseBody Resource<Filter> filterGetDefault(
			@RequestParam(value = "filterSelector", required = true) String filterSelector,
			@RequestParam(value = "user", required = true) String filterUser) {
		TableUsuarioController.logger.info("[GET - table] : getDefault filter");
		return ResourceUtils.toResource(filterService.getDefault(filterSelector, filterUser));
	}
	
	// Obtiene los filtros disponibles
	@UDALink(name = "multifilterGetAll")
	@RequestMapping(value = "/multiFilter/getAll", method = RequestMethod.GET)
	public @ResponseBody List<Resource<Filter>> filterGetAll(
			@RequestParam(value = "q", required = false) String filterQ,
			@RequestParam(value = "c", required = false) Boolean filterC,
			@RequestParam(value = "filterSelector", required = true) String filterSelector,
			@RequestParam(value = "user", required = true) String filterUser) {
		TableUsuarioController.logger.info("[GET - table] : GetAll filter");
		return ResourceUtils.fromListToResource(filterService.getAllFilters(filterSelector, filterUser));
	}
	
	/**
	 * OperaciÃ³n de bÃºsqueda del componente RUP_TABLE.
	 * 
	 * @param filterUsuario
	 *            Bean que contiene los parÃ¡metros de filtrado a emplear.
	 * @param searchUsuario
	 *            Bean que contiene los parÃ¡metros de bÃºsqueda a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parÃ¡mtros de configuraciÃ³n propios del
	 *            RUP_TABLE a aplicar en la bÃºsqueda.
	 * @return Lista de lineas de la tabla que se corresponden con los registros
	 *         que se ajustan a los parÃ¡metros de bÃºsqueda.
	 * 
	 */
	@UDALink(name = "search", linkTo = { @UDALinkAllower(name = "filter")})
	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public @ResponseBody List<TableRowDto<Usuario>> search(
			@RequestJsonBody(param="filter") Usuario filterUsuario,
			@RequestJsonBody(param="search") Usuario searchUsuario,
			@RequestJsonBody TableRequestDto tableRequestDto){
		TableUsuarioController.logger.info("[POST - search] : Buscar Usuarios");
		return tableUsuarioService.search(filterUsuario, searchUsuario, tableRequestDto, false);
	}
	
	/**
	 * Borrado mÃºltiple de registros
	 * 
	 * @param filterUsuario Usuario
	 *            Bean que contiene los parÃ¡metros de filtrado a emplear.
	 * @param TableRequestDto
	 *            Dto que contiene los parÃ¡mtros de configuraciÃ³n propios del
	 *            RUP_TABLE a aplicar en la bÃºsqueda.
	 * @return Lista de los identificadores de los registros eliminados.
	 */
	@UDALink(name = "deleteAll")
	@RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
	@ResponseStatus(value=HttpStatus.OK)
	public @ResponseBody List<String> removeMultiple(
			@RequestJsonBody(param="filter") Usuario filterUsuario,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		TableUsuarioController.logger.info("[POST - removeMultiple] : Eliminar multiples usuarios");
	   // this.tableUsuarioService.removeMultiple(filterUsuario, tableRequestDto, false);
	    TableUsuarioController.logger.info("All entities correctly deleted!");
	    
	    return tableRequestDto.getMultiselection().getSelectedIds();
	}
	
	/*
	 * EXPORTACIONES DE DATOS
	 */
	
	/**
	 * Devuelve los datos exportados de la tabla.
	 *
	 * @param filterUsuario Usuario
	 * @param tableRequestDto TableRequestDto
	 */
	@UDALink(name = "clipboardReport", linkTo = { 
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "/clipboardReport", method = RequestMethod.POST)
	public @ResponseBody List<Resource<Usuario>> getClipboardReport(
			@RequestJsonBody(param = "filter", required = false) Usuario filterUsuario,
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		TableUsuarioController.logger.info("[POST - clipboardReport] : Copiar multiples usuarios");
		return ResourceUtils.fromListToResource(this.tableUsuarioService.getDataForReports(filterUsuario, tableRequestDto));
	}
	
	@UDALink(name = "clipboardReport2")
	@RequestMapping(value = "{bis}/clipboardReport", method = RequestMethod.POST)
	public @ResponseBody List<Resource<Usuario>> getClipboardReport2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
			@RequestJsonBody(param = "filter", required = false) Usuario2 filterUsuario,
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		TableUsuarioController.logger.info("[POST - clipboardReport2] : Copiar multiples usuarios");
		return ResourceUtils.fromListToResource(this.tableUsuarioService.getDataForReports((Usuario) filterUsuario, tableRequestDto));
	}
	
	/**
	 * Devuelve un fichero excel que contiene los datos exportados de la tabla.
	 *
	 * @param filterUsuario Usuario
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@UDALink(name = "excelReport", linkTo = { 
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = {"/xlsReport" , "/xlsxReport"}, method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateExcelReport(
			@RequestJsonBody(param = "filter", required = false) Usuario filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName, 
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response) throws ServletException{
		TableUsuarioController.logger.info("[POST - generateExcelReport] : Devuelve un fichero excel");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.tableUsuarioService.generateReport(filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
    }
	
	@UDALink(name = "excelReport2")
	@RequestMapping(value = {"{bis}/xlsReport" , "{bis}/xlsxReport"}, method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateExcelReport2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
			@RequestJsonBody(param = "filter", required = false) Usuario2 filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns2, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response) throws ServletException{
		TableUsuarioController.logger.info("[POST - generateExcelReport2] : Devuelve un fichero excel");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
        
        // Corregir nombres de columnas
        ArrayList<String> tempColumns = new ArrayList<String>();
        for (String column : columns2) {
        	String newColumn = column.substring(0, column.length() - 1);
        	tempColumns.add(newColumn);
        }
        String[] columns = tempColumns.toArray(new String[0]);
        
		this.tableUsuarioService.generateReport((Usuario) filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
    }
	
	/**
	 * Devuelve un fichero pdf que contiene los datos exportados de la tabla.
	 *
	 * @param filterUsuario Usuario
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@UDALink(name = "pdfReport", linkTo = { 
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "pdfReport", method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generatePDFReport(
			@RequestJsonBody(param = "filter", required = false) Usuario filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableUsuarioController.logger.info("[POST - generatePDFReport] : Devuelve un fichero pdf");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.tableUsuarioService.generateReport(filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	@UDALink(name = "pdfReport2")
	@RequestMapping(value = "{bis}/pdfReport", method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generatePDFReport2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
			@RequestJsonBody(param = "filter", required = false) Usuario2 filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns2, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableUsuarioController.logger.info("[POST - generatePDFReport2] : Devuelve un fichero pdf");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
        
        // Corregir nombres de columnas
        ArrayList<String> tempColumns = new ArrayList<String>();
        for (String column : columns2) {
        	String newColumn = column.substring(0, column.length() - 1);
        	tempColumns.add(newColumn);
        }
        String[] columns = tempColumns.toArray(new String[0]);
        
		this.tableUsuarioService.generateReport((Usuario) filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	/**
	 * Devuelve un fichero ods que contiene los datos exportados de la tabla.
	 *
	 * @param filterUsuario Usuario
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@UDALink(name = "odsReport", linkTo = { 
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "clipboardReport"),
			@UDALinkAllower(name = "csvReport")})
	@RequestMapping(value = "odsReport", method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateODSReport(
			@RequestJsonBody(param = "filter", required = false) Usuario filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableUsuarioController.logger.info("[POST - generateODSReport] : Devuelve un fichero ods");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.tableUsuarioService.generateReport(filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	@UDALink(name = "odsReport2")
	@RequestMapping(value = "{bis}/odsReport", method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateODSReport2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
			@RequestJsonBody(param = "filter", required = false) Usuario2 filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns2, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableUsuarioController.logger.info("[POST - generateODSReport2] : Devuelve un fichero ods");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
        
        // Corregir nombres de columnas
        ArrayList<String> tempColumns = new ArrayList<String>();
        for (String column : columns2) {
        	String newColumn = column.substring(0, column.length() - 1);
        	tempColumns.add(newColumn);
        }
        String[] columns = tempColumns.toArray(new String[0]);
        	
		this.tableUsuarioService.generateReport((Usuario) filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	/**
	 * Devuelve un fichero csv que contiene los datos exportados de la tabla.
	 *
	 * @param filterUsuario Usuario
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@UDALink(name = "csvReport", linkTo = { 
			@UDALinkAllower(name = "excelReport"),
			@UDALinkAllower(name = "pdfReport"),
			@UDALinkAllower(name = "odsReport"),
			@UDALinkAllower(name = "clipboardReport")})
	@RequestMapping(value = "csvReport", method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateCSVReport(
			@RequestJsonBody(param = "filter", required = false) Usuario filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableUsuarioController.logger.info("[POST - generateCSVReport] : Devuelve un fichero csv");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.tableUsuarioService.generateReport(filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	@UDALink(name = "csvReport2")
	@RequestMapping(value = "{bis}/csvReport", method = RequestMethod.POST, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateCSVReport2(
			@PathVariable @TrustAssertion(idFor = NoEntity.class) final String bis,
			@RequestJsonBody(param = "filter", required = false) Usuario2 filterUsuario, 
			@RequestJsonBody(param = "columns", required = false) String[] columns2, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableUsuarioController.logger.info("[POST - generateCSVReport2] : Devuelve un fichero csv");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
        
        // Corregir nombres de columnas
        ArrayList<String> tempColumns = new ArrayList<String>();
        for (String column : columns2) {
        	String newColumn = column.substring(0, column.length() - 1);
        	tempColumns.add(newColumn);
        }
        String[] columns = tempColumns.toArray(new String[0]);
        
		this.tableUsuarioService.generateReport((Usuario) filterUsuario, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
}
