/*
* Copyright 2020 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versi�n 1.1 exclusivamente (la �Licencia�);
* Solo podr� usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislaci�n aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye �TAL CUAL�,
* SIN GARANT�AS NI CONDICIONES DE NING�N TIPO, ni expresas ni impl�citas.
* V�ase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/
package com.ejie.x21a.control;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.x21a.model.ComarcaExtendida;
import com.ejie.x21a.model.Provincia;
import com.ejie.x21a.service.ComarcaExtendidaService;
import com.ejie.x21a.service.ProvinciaService;
import com.ejie.x21a.util.Constants;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.TableRequestDto;
import com.ejie.x38.dto.TableResponseDto;
import com.ejie.x38.dto.TableRowDto;
import com.ejie.x38.rup.table.filter.model.Filter;
import com.ejie.x38.rup.table.filter.service.FilterService;
/**
 * ComarcaExtendidaServiceImpl generated by UDA 1.0, 26-may-2011 13:46:35.
 * @author UDA
 */
@Controller
@RequestMapping (value = "/tableComarcaExtendida")
public class TableComarcaExtendidaController {

	private static final Logger logger = LoggerFactory.getLogger(TableComarcaExtendidaController.class);
	public static final String MODEL_COMARCA_EXTENDIDA = "comarcaExtendida";

	@Autowired 
	private ComarcaExtendidaService comarcaService;
	
	@Autowired 
	private ProvinciaService provinciaService;
	
	@Autowired
	private FilterService filterService;
	
	@Resource
	private ReloadableResourceBundleMessageSource messageSource;
	
	@GetMapping(value = "filterSimple")
	public String getSimpleMasterDetail(Model model) {
		model.addAttribute("tituloPagina", "Comarca Extendida");
		model.addAttribute("comarcaExtendida", new ComarcaExtendida());
		return "tableComarcaExtendida";
	}
	
	@PostMapping(value = "/editForm")
	public String getTableComarcaExtendidaEditForm (
			@RequestParam(required = true) String actionType,
			@RequestParam(required = false) BigDecimal pkValue,
			Model model) {
		model.addAttribute(MODEL_COMARCA_EXTENDIDA, new ComarcaExtendida());
		model.addAttribute(Constants.MODEL_ACTIONTYPE, actionType);
		model.addAttribute(Constants.MODEL_ENCTYPE, Constants.APPLICATION_URLENCODED);
		
		if (pkValue != null) {
			model.addAttribute(Constants.MODEL_PKVALUE, pkValue);
		}
		
		if (actionType.equals("POST")) {
			model.addAttribute(Constants.MODEL_ENDPOINT, "add");
		} else {
			model.addAttribute(Constants.MODEL_ENDPOINT, "edit");
		}
		
		return "tableComarcaExtendidaEditForm";
	}
	
	@PostMapping(value = "/editFormDialog")
	public String getTableDialogComarcaExtendidaEditForm (
			@RequestParam(required = true) String actionType,
			@RequestParam(required = false) BigDecimal pkValue,
			Model model) {
		model.addAttribute(MODEL_COMARCA_EXTENDIDA, new ComarcaExtendida());
		model.addAttribute(Constants.MODEL_ACTIONTYPE, actionType);
		model.addAttribute(Constants.MODEL_ENCTYPE, Constants.APPLICATION_URLENCODED);
		
		if (pkValue != null) {
			model.addAttribute(Constants.MODEL_PKVALUE, pkValue);
		}
		
		if (actionType.equals("POST")) {
			model.addAttribute(Constants.MODEL_ENDPOINT, "add");
		} else {
			model.addAttribute(Constants.MODEL_ENDPOINT, "edit");
		}
		
		return "tableDialogComarcaExtendidaEditForm";
	}
	
	/**
	 * Method 'getById'.
	 * @param  id String
	 * @return String
	 */
	@GetMapping(value = "/{code}")
	public @ResponseBody ComarcaExtendida get(@PathVariable final BigDecimal code) {
        ComarcaExtendida comarca = new ComarcaExtendida();
        comarca.setCode(code);
        comarca = this.comarcaService.find(comarca);
        return comarca;
	}
	
	/**
	 * Method 'edit'.
 	 * @param comarca ComarcaExtendida 
 	 * @return ComarcaExtendida
 	 */
	@PutMapping(value = "/edit")
    public @ResponseBody ComarcaExtendida edit(@Validated @RequestBody final ComarcaExtendida comarca) {		
        final ComarcaExtendida comarcaAux = this.comarcaService.update(comarca);
		logger.info("Entity correctly updated!");
		return comarcaAux;
    }

	/**
	 * Method 'add'.
	 * @param comarca ComarcaExtendida 
	 * @return ComarcaExtendida
	 */
	@PostMapping(value = "/add")
	public @ResponseBody ComarcaExtendida add(@Validated @RequestBody final ComarcaExtendida comarca) {		
		final ComarcaExtendida comarcaAux = this.comarcaService.add(comarca);
		logger.info("Entity correctly inserted!");
		return comarcaAux;
	}

	/**
	 * Method 'remove'.
	 * @param id String
	 *
	 */
	@DeleteMapping(value = "/{id}")
	@ResponseStatus(value=HttpStatus.OK)
	public @ResponseBody ComarcaExtendida remove(@PathVariable(value="id") final BigDecimal id, final HttpServletResponse  response) {
		final ComarcaExtendida comarca = new ComarcaExtendida();
		comarca.setCode(id);
		this.comarcaService.remove(comarca);
		logger.info("Entity correctly deleted!");
		return comarca;
	}
		
	/**
	 * RUP_TABLE
	 */
	@PostMapping(value = "/filter")
	public @ResponseBody TableResponseDto<ComarcaExtendida> filter(
			@RequestJsonBody(param="filter") final ComarcaExtendida comarca,
			@RequestJsonBody final TableRequestDto tableRequestDto) {
		TableComarcaExtendidaController.logger.info("[GET - table] : Obtener ComarcaExtendidas");	
		return comarcaService.filter(comarca, tableRequestDto, false);
	}
	
	// Obtiene el formulario del multi filtro
	@PostMapping(value = "/multiFilter")
	public String getMultiFilterForm (
			@RequestParam(required = false) String mapping,
			@RequestParam(required = true) String tableID,
			@RequestParam(required = true) String containerClass,
			@RequestParam(required = true) String labelClass,
			@RequestParam(required = true) String defaultContainerClass,
			@RequestParam(required = true) String defaultCheckboxClass,
			Model model) {
		model.addAttribute("filter", new Filter());
		model.addAttribute("tableID", tableID);
		model.addAttribute("containerClass", containerClass);
		model.addAttribute("labelClass", labelClass);
		model.addAttribute("defaultContainerClass", defaultContainerClass);
		model.addAttribute("defaultCheckboxClass", defaultCheckboxClass);
		
		// Controlar que el mapping siempre se a�ada al modelo de la manera esperada
		if (mapping == null || mapping.isEmpty()) {
			mapping = "/tableComarcaExtendida/multiFilter";
		} else if (mapping.endsWith("/")) {
			mapping = mapping.substring(0, mapping.length() - 1);
		}
		model.addAttribute("mapping", mapping);
		
		return "multiFilterForm";
	}
	
	@PostMapping(value = "/multiFilter/add")
	public @ResponseBody Filter filterAdd(@RequestJsonBody(param="filtro") final Filter filtro){
		TableComarcaExtendidaController.logger.info("[POST - table] : add filter");
		return filterService.insert(filtro);
	}	
	
	@DeleteMapping(value = "/multiFilter/delete")
	public @ResponseBody Filter  filterDelete(
			@RequestJsonBody(param="filtro") final Filter filtro) {
		TableComarcaExtendidaController.logger.info("[DELETE - table] : delete filter");
		return filterService.delete(filtro);
	}
	
	@GetMapping(value = "/multiFilter/getDefault")
	public @ResponseBody Filter filterGetDefault(
		@RequestParam(value = "filterSelector", required = true) final String filterSelector,
		@RequestParam(value = "comarca", required = true) final String filterComarcaExtendida) {
		TableComarcaExtendidaController.logger.info("[get - table] : getDefault filter");
		return filterService.getDefault(filterSelector, filterComarcaExtendida);
	}
	
	@GetMapping(value = "/multiFilter/getAll")
	public @ResponseBody List<Filter> filterGetAll(
		@RequestParam(value = "filterSelector", required = true) final String filterSelector,
		@RequestParam(value = "comarca", required = true) final String filterComarcaExtendida) {
		TableComarcaExtendidaController.logger.info("[get - table] : GetAll filter");
		return filterService.getAllFilters(filterSelector, filterComarcaExtendida);
	}
	
	@PostMapping(value = "/search")
	public @ResponseBody List<TableRowDto<ComarcaExtendida>> search(
			@RequestJsonBody(param="filter") final ComarcaExtendida comarcaFilter,
			@RequestJsonBody(param="search") final ComarcaExtendida comarcaSearch,
			@RequestJsonBody final TableRequestDto tableRequestDto){	
		TableComarcaExtendidaController.logger.info("[GET - search] : Obtener ComarcaExtendidas por filtro");
		return comarcaService.search(comarcaFilter, comarcaSearch, tableRequestDto, true);
	}
	
	/*
	 * EXPORTACIONES DE DATOS
	 */
	
	/**
	 * Devuelve los datos exportados de la tabla.
	 *
	 * @param filterComarcaExtendida ComarcaExtendida
	 * @param tableRequestDto TableRequestDto
	 */
	@PostMapping(value = "/filter", params = "clipboardReport")
	public @ResponseBody List<ComarcaExtendida> getClipboardReport(
			@RequestJsonBody(param = "filter", required = false) ComarcaExtendida filterComarcaExtendida,
			@RequestParam(required = false) String[] columns, 
			@RequestParam(required = false) String[] columnsName,
			@RequestParam(required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto) {
		TableComarcaExtendidaController.logger.info("[POST - clipboardReport] : Copiar multiples ComarcaExtendidas");
		return this.comarcaService.getDataForReports(filterComarcaExtendida, tableRequestDto);
	}
	
	/**
	 * Devuelve un fichero excel que contiene los datos exportados de la tabla.
	 *
	 * @param filterComarcaExtendida ComarcaExtendida
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@PostMapping(value = {"/xlsReport" , "/xlsxReport"}, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateExcelReport(
			@RequestJsonBody(param = "filter", required = false) ComarcaExtendida filterComarcaExtendida, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName, 
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response) throws ServletException{
		TableComarcaExtendidaController.logger.info("[POST - generateExcelReport] : Devuelve un fichero excel");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.comarcaService.generateReport(filterComarcaExtendida, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
    }
	
	/**
	 * Devuelve un fichero pdf que contiene los datos exportados de la tabla.
	 *
	 * @param filterComarcaExtendida ComarcaExtendida
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@PostMapping(value = "pdfReport", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generatePDFReport(
			@RequestJsonBody(param = "filter", required = false) ComarcaExtendida filterComarcaExtendida, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableComarcaExtendidaController.logger.info("[POST - generatePDFReport] : Devuelve un fichero pdf");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.comarcaService.generateReport(filterComarcaExtendida, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	/**
	 * Devuelve un fichero ods que contiene los datos exportados de la tabla.
	 *
	 * @param filterComarcaExtendida ComarcaExtendida
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@PostMapping(value = "odsReport", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateODSReport(
			@RequestJsonBody(param = "filter", required = false) ComarcaExtendida filterComarcaExtendida, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableComarcaExtendidaController.logger.info("[POST - generateODSReport] : Devuelve un fichero ods");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.comarcaService.generateReport(filterComarcaExtendida, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
	
	/**
	 * Devuelve un fichero csv que contiene los datos exportados de la tabla.
	 *
	 * @param filterComarcaExtendida ComarcaExtendida
	 * @param columns String[]
	 * @param columnsName String[]
	 * @param fileName String
	 * @param sheetTitle String
	 * @param reportsParams ArrayList<?>
	 * @param tableRequestDto TableRequestDto
	 * @param request HttpServletRequest
	 * @param response HttpServletResponse
	 */
	@PostMapping(value = "csvReport", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
	public @ResponseBody void generateCSVReport(
			@RequestJsonBody(param = "filter", required = false) ComarcaExtendida filterComarcaExtendida, 
			@RequestJsonBody(param = "columns", required = false) String[] columns, 
			@RequestJsonBody(param = "columnsName", required = false) String[] columnsName,
			@RequestJsonBody(param = "fileName", required = false) String fileName, 
			@RequestJsonBody(param = "sheetTitle", required = false) String sheetTitle,
			@RequestJsonBody(param = "reportsParams", required = false) ArrayList<?> reportsParams,
			@RequestJsonBody TableRequestDto tableRequestDto,
			HttpServletRequest request,
			HttpServletResponse response){
		TableComarcaExtendidaController.logger.info("[POST - generateCSVReport] : Devuelve un fichero csv");
		//Idioma
        Locale locale = LocaleContextHolder.getLocale();
		this.comarcaService.generateReport(filterComarcaExtendida, columns, columnsName, fileName, sheetTitle, reportsParams, tableRequestDto, locale, request, response);
	}
		
	/*
	 * MAPPING PARA EL COMBO DE PROVINCIAS
	 */
	@GetMapping(value = "/provincia")
	public @ResponseBody List<Provincia> getProvincias() {
		final Provincia filtroProvincia = new Provincia();
		final List<Provincia> findAll = provinciaService.findAll(filtroProvincia, null);
		return findAll;
	}
	
	/*
	 * MAPPING PARA EL COMBO DE COMARCAS
	 */
	@GetMapping(value = "/comarca")
	public @ResponseBody List<ComarcaExtendida> getComarcaExtendidas() {
		final ComarcaExtendida filtroComarcaExtendida = new ComarcaExtendida();
		final List<ComarcaExtendida> findAll = comarcaService.findAll(filtroComarcaExtendida, null);
		return findAll;
	}
}