package com.ejie.aa79b.model;

import java.math.BigDecimal;

import com.ejie.aa79b.common.JsonNumbersDeserializer;
import com.ejie.aa79b.common.jackson.JsonImporteSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * CuantiaInter generated by UDA, 15-dic-2017 14:11:44.
 * 
 * @author UDA
 */

public class CuantiaInter implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Long idOrden;
    private Integer jornCompHorasDesde;
    private Integer jornCompHorasHasta;
    private Integer jornMediaHorasDesde;
    private Integer jornMediaHorasHasta;
    private BigDecimal precMinCae;
    private BigDecimal precMinNoCae;
    private BigDecimal precHoraReunionCae;
    private BigDecimal precHoraReunionNoCae;
    private BigDecimal precJornCongresoEu;
    private BigDecimal precMediaCongresoEu;
    private BigDecimal precHoraCongresoEu;
    private BigDecimal precJornCongresoNoEu;
    private BigDecimal precMediaCongresoNoEu;
    private BigDecimal precHoraCongresoNoEu;
    private boolean existeReg = false;

    public boolean isExisteReg() {
        return this.existeReg;
    }

    public void setExisteReg(boolean existeReg) {
        this.existeReg = existeReg;
    }

    /**
     * Method 'CuantiaInter'.
     */
    public CuantiaInter() {
        // Constructor
    }

    /**
     * Method 'CuantiaInter'.
     * 
     * @param idOrden
     *            Long
     */
    public CuantiaInter(Long idOrden) {
        this.idOrden = idOrden;
    }

    /**
     * Method 'getIdOrden'.
     *
     * @return Long
     */

    public Long getIdOrden() {
        return this.idOrden;
    }

    /**
     * Method 'setIdOrden'.
     *
     * @param idOrden
     *            Long
     * @return
     */

    public void setIdOrden(Long idOrden) {
        this.idOrden = idOrden;
    }

    /**
     * Method 'getJornCompHorasDesde'.
     *
     * @return Integer
     */

    public Integer getJornCompHorasDesde() {
        return this.jornCompHorasDesde;
    }

    /**
     * Method 'setJornCompHorasDesde'.
     *
     * @param jornCompHorasDesde
     *            Integer
     * @return
     */

    public void setJornCompHorasDesde(Integer jornCompHorasDesde) {
        this.jornCompHorasDesde = jornCompHorasDesde;
    }

    /**
     * Method 'getJornCompHorasHasta'.
     *
     * @return Integer
     */

    public Integer getJornCompHorasHasta() {
        return this.jornCompHorasHasta;
    }

    /**
     * Method 'setJornCompHorasHasta'.
     *
     * @param jornCompHorasHasta
     *            Integer
     * @return
     */

    public void setJornCompHorasHasta(Integer jornCompHorasHasta) {
        this.jornCompHorasHasta = jornCompHorasHasta;
    }

    /**
     * Method 'getJornMediaHorasDesde'.
     *
     * @return Integer
     */

    public Integer getJornMediaHorasDesde() {
        return this.jornMediaHorasDesde;
    }

    /**
     * Method 'setJornMediaHorasDesde'.
     *
     * @param jornMediaHorasDesde
     *            Integer
     * @return
     */

    public void setJornMediaHorasDesde(Integer jornMediaHorasDesde) {
        this.jornMediaHorasDesde = jornMediaHorasDesde;
    }

    /**
     * Method 'getJornMediaHorasHasta'.
     *
     * @return Integer
     */

    public Integer getJornMediaHorasHasta() {
        return this.jornMediaHorasHasta;
    }

    /**
     * Method 'setJornMediaHorasHasta'.
     *
     * @param jornMediaHorasHasta
     *            Integer
     * @return
     */

    public void setJornMediaHorasHasta(Integer jornMediaHorasHasta) {
        this.jornMediaHorasHasta = jornMediaHorasHasta;
    }

    /**
     * Method 'getPrecMinCae'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecMinCae() {
        return this.precMinCae;
    }

    /**
     * Method 'setPrecMinCae'.
     *
     * @param precMinCae
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecMinCae(BigDecimal precMinCae) {
        this.precMinCae = precMinCae;
    }

    /**
     * Method 'getPrecMinNoCae'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecMinNoCae() {
        return this.precMinNoCae;
    }

    /**
     * Method 'setPrecMinNoCae'.
     *
     * @param precMinNoCae
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecMinNoCae(BigDecimal precMinNoCae) {
        this.precMinNoCae = precMinNoCae;
    }

    /**
     * Method 'getPrecHoraReunionCae'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecHoraReunionCae() {
        return this.precHoraReunionCae;
    }

    /**
     * Method 'setPrecHoraReunionCae'.
     *
     * @param precHoraReunionCae
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecHoraReunionCae(BigDecimal precHoraReunionCae) {
        this.precHoraReunionCae = precHoraReunionCae;
    }

    /**
     * Method 'getPrecHoraReunionNoCae'.
     *
     * @return BigDecimal
     */
    
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecHoraReunionNoCae() {
        return this.precHoraReunionNoCae;
    }

    /**
     * Method 'setPrecHoraReunionNoCae'.
     *
     * @param precHoraReunionNoCae
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecHoraReunionNoCae(BigDecimal precHoraReunionNoCae) {
        this.precHoraReunionNoCae = precHoraReunionNoCae;
    }

    /**
     * Method 'getPrecJornCongresoEu'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecJornCongresoEu() {
        return this.precJornCongresoEu;
    }

    /**
     * Method 'setPrecJornCongresoEu'.
     *
     * @param precJornCongresoEu
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecJornCongresoEu(BigDecimal precJornCongresoEu) {
        this.precJornCongresoEu = precJornCongresoEu;
    }

    /**
     * Method 'getPrecMediaCongresoEu'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecMediaCongresoEu() {
        return this.precMediaCongresoEu;
    }

    /**
     * Method 'setPrecMediaCongresoEu'.
     *
     * @param precMediaCongresoEu
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecMediaCongresoEu(BigDecimal precMediaCongresoEu) {
        this.precMediaCongresoEu = precMediaCongresoEu;
    }

    /**
     * Method 'getPrecHoraCongresoEu'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecHoraCongresoEu() {
        return this.precHoraCongresoEu;
    }

    /**
     * Method 'setPrecHoraCongresoEu'.
     *
     * @param precHoraCongresoEu
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecHoraCongresoEu(BigDecimal precHoraCongresoEu) {
        this.precHoraCongresoEu = precHoraCongresoEu;
    }

    /**
     * Method 'getPrecJornCongresoNoEu'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecJornCongresoNoEu() {
        return this.precJornCongresoNoEu;
    }

    /**
     * Method 'setPrecJornCongresoNoEu'.
     *
     * @param precJornCongresoNoEu
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecJornCongresoNoEu(BigDecimal precJornCongresoNoEu) {
        this.precJornCongresoNoEu = precJornCongresoNoEu;
    }

    /**
     * Method 'getPrecMediaCongresoNoEu'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecMediaCongresoNoEu() {
        return this.precMediaCongresoNoEu;
    }

    /**
     * Method 'setPrecMediaCongresoNoEu'.
     *
     * @param precMediaCongresoNoEu
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecMediaCongresoNoEu(BigDecimal precMediaCongresoNoEu) {
        this.precMediaCongresoNoEu = precMediaCongresoNoEu;
    }

    /**
     * Method 'getPrecHoraCongresoNoEu'.
     *
     * @return BigDecimal
     */
    @JsonSerialize(using = JsonImporteSerializer.class)
    public BigDecimal getPrecHoraCongresoNoEu() {
        return this.precHoraCongresoNoEu;
    }

    /**
     * Method 'setPrecHoraCongresoNoEu'.
     *
     * @param precHoraCongresoNoEu
     *            BigDecimal
     * @return
     */
    @JsonDeserialize(using = JsonNumbersDeserializer.class)
    public void setPrecHoraCongresoNoEu(BigDecimal precHoraCongresoNoEu) {
        this.precHoraCongresoNoEu = precHoraCongresoNoEu;
    }

    /**
     * Intended only for logging and debugging.
     * 
     * Here, the contents of every main field are placed into the result.
     * 
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        result.append(this.getClass().getName()).append(" Object { ");
        result.append(" [ idOrden: ").append(this.idOrden).append(" ]");
        result.append(", [ jornCompHorasDesde: ").append(this.jornCompHorasDesde).append(" ]");
        result.append(", [ jornCompHorasHasta: ").append(this.jornCompHorasHasta).append(" ]");
        result.append(", [ jornMediaHorasDesde: ").append(this.jornMediaHorasDesde).append(" ]");
        result.append(", [ jornMediaHorasHasta: ").append(this.jornMediaHorasHasta).append(" ]");
        result.append(", [ precMinCae: ").append(this.precMinCae).append(" ]");
        result.append(", [ precMinNoCae: ").append(this.precMinNoCae).append(" ]");
        result.append(", [ precHoraReunionCae: ").append(this.precHoraReunionCae).append(" ]");
        result.append(", [ precHoraReunionNoCae: ").append(this.precHoraReunionNoCae).append(" ]");
        result.append(", [ precJornCongresoEu: ").append(this.precJornCongresoEu).append(" ]");
        result.append(", [ precMediaCongresoEu: ").append(this.precMediaCongresoEu).append(" ]");
        result.append(", [ precHoraCongresoEu: ").append(this.precHoraCongresoEu).append(" ]");
        result.append(", [ precJornCongresoNoEu: ").append(this.precJornCongresoNoEu).append(" ]");
        result.append(", [ precMediaCongresoNoEu: ").append(this.precMediaCongresoNoEu).append(" ]");
        result.append(", [ precHoraCongresoNoEu: ").append(this.precHoraCongresoNoEu).append(" ]");
        result.append(", [ existeReg: ").append(this.existeReg).append(" ]");
        result.append("}");
        return result.toString();
    }

}
