package com.ejie.aa79b.model;

/**
 * CuantiaRev generated by UDA, 15-dic-2017 14:11:44.
 * 
 * @author UDA
 */

public class CuantiaRev extends Cuantias implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Method 'CuantiaRev'.
     */
    public CuantiaRev() {
        // Constructor
    }

}
