package com.ejie.aa79b.model;

import org.apache.commons.lang.StringUtils;

/**
 * EntidadesGruposTrabajo generated by UDA, 24-nov-2017 10:10:27.
 * @author UDA
 */

public class EntidadesGruposTrabajo extends Entidad implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
    private Long idGrupo;
    private String estadoGrupo;

	
    /**
	 * Method 'getIdGrupo'.
	 *
	 * @return Long
	 */
	public Long getIdGrupo() {
		return this.idGrupo;
	}

	/**
	 * Method 'setIdGrupo'.
	 *
	 * @param idGrupo Long
	 * @return
     */
	public void setIdGrupo(Long idGrupo) {
		this.idGrupo = idGrupo;
	}
	
	@Override()
	public String getCodigoCompleto() {
		return this.idGrupo + "_" + this.getTipo() + "_" + this.getCodigo();
	}
	
	@Override()
	public void setCodigoCompleto(String codigo) {
		String[] split = StringUtils.split(codigo, "_");
		if (split.length == 3) {
			Integer i = 0;
			this.idGrupo = Long.parseLong(split[i++]); 
			this.setTipo(split[i++]);
			this.setCodigo(Integer.parseInt(split[i++]));
		} else if (split.length == 2) {
			super.setCodigoCompleto(codigo);
		}
	}

	/**
	 * @return the estadoGrupo
	 */
	public String getEstadoGrupo() {
		return estadoGrupo;
	}

	/**
	 * @param estadoGrupo the estadoGrupo to set
	 */
	public void setEstadoGrupo(String estadoGrupo) {
		this.estadoGrupo = estadoGrupo;
	}
}

