package com.ejie.aa79b.model;

import java.util.Date;
import java.util.List;

import com.ejie.x38.serialization.JsonDateDeserializer;
import com.ejie.x38.serialization.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * GruposTrabajo generated by UDA, 24-nov-2017 10:10:27.
 * 
 * @author UDA
 */

public class GruposTrabajo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Integer idTipoExpediente;
	private String descEu;
	private String indBopv;
	private String indPrevistoBopv;
	private PersonalIZO responsable = new PersonalIZO();
	private Long palabrasDesde;
	private Long palabrasHasta;
	private String estado;
	private Date fechaAlta;
	private Date fechaBaja;

	private String tipoExpedienteDesc;
	private String bopvDesc;
	private String previstoBopvDesc;
	private String estadoDesc;

	private Entidad entidadSolicitante = new Entidad();
	private PersonalIZO traductor = new PersonalIZO();

	private List<EntidadesGruposTrabajo> entidades;
	private List<TrabajadoresGruposTrabajo> trabajadores;

	private boolean excluirBOE = false;

	public boolean isExcluirBOE() {
		return excluirBOE;
	}

	public void setExcluirBOE(boolean excluirBOE) {
		this.excluirBOE = excluirBOE;
	}

	/**
	 * Method 'GruposTrabajo'.
	 */
	public GruposTrabajo() {
		// Constructor vacío
	}

	/**
	 * Method 'GruposTrabajo'.
	 * 
	 * @param id Long
	 */
	public GruposTrabajo(Long id) {
		this.id = id;
	}

	/**
	 * Method 'getId'.
	 *
	 * @return Long
	 */

	public Long getId() {
		return this.id;
	}

	/**
	 * Method 'setId'.
	 *
	 * @param id Long
	 * @return
	 */

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Method 'getIdTipoExpediente'.
	 *
	 * @return Integer
	 */

	public Integer getIdTipoExpediente() {
		return this.idTipoExpediente;
	}

	/**
	 * Method 'setIdTipoExpediente'.
	 *
	 * @param idTipoExpediente Integer
	 * @return
	 */

	public void setIdTipoExpediente(Integer idTipoExpediente) {
		this.idTipoExpediente = idTipoExpediente;
	}

	/**
	 * Method 'getDescEu'.
	 *
	 * @return String
	 */

	public String getDescEu() {
		return this.descEu;
	}

	/**
	 * Method 'setDescEu'.
	 *
	 * @param descEu String
	 * @return
	 */

	public void setDescEu(String descEu) {
		this.descEu = descEu;
	}

	/**
	 * Method 'getIndBopv'.
	 *
	 * @return String
	 */

	public String getIndBopv() {
		return this.indBopv;
	}

	/**
	 * Method 'setIndBopv'.
	 *
	 * @param indBopv String
	 * @return
	 */

	public void setIndBopv(String indBopv) {
		this.indBopv = indBopv;
	}

	/**
	 * Method 'getIndPrevistoBopv'.
	 *
	 * @return String
	 */

	public String getIndPrevistoBopv() {
		return this.indPrevistoBopv;
	}

	/**
	 * Method 'setIndPrevistoBopv'.
	 *
	 * @param indPrevistoBopv String
	 * @return
	 */

	public void setIndPrevistoBopv(String indPrevistoBopv) {
		this.indPrevistoBopv = indPrevistoBopv;
	}

	/**
	 * Method 'getPalabrasDesde'.
	 *
	 * @return Long
	 */

	public Long getPalabrasDesde() {
		return this.palabrasDesde;
	}

	/**
	 * Method 'setPalabrasDesde'.
	 *
	 * @param palabrasDesde Long
	 * @return
	 */

	public void setPalabrasDesde(Long palabrasDesde) {
		this.palabrasDesde = palabrasDesde;
	}

	/**
	 * Method 'getPalabrasHasta'.
	 *
	 * @return Long
	 */

	public Long getPalabrasHasta() {
		return this.palabrasHasta;
	}

	/**
	 * Method 'setPalabrasHasta'.
	 *
	 * @param palabrasHasta Long
	 * @return
	 */

	public void setPalabrasHasta(Long palabrasHasta) {
		this.palabrasHasta = palabrasHasta;
	}

	/**
	 * @return String
	 */
	public String getPalabrasDesdeHasta() {
		StringBuilder str = new StringBuilder();
		if (this.palabrasDesde != null && this.palabrasHasta != null) {
			str.append(this.palabrasDesde).append(" - ").append(this.palabrasHasta);
		}
		return str.toString();
	}

	/**
	 * Method 'getEstado'.
	 *
	 * @return String
	 */

	public String getEstado() {
		return this.estado;
	}

	/**
	 * Method 'setEstado'.
	 *
	 * @param estado String
	 * @return
	 */

	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * Method 'getFechaAlta'.
	 *
	 * @return java.util.Date
	 */

	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	/**
	 * Method 'setFechaAlta'.
	 *
	 * @param fechaAlta java.util.Date
	 * @return
	 */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	/**
	 * Method 'getFechaBaja'.
	 *
	 * @return java.util.Date
	 */

	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	/**
	 * Method 'setFechaBaja'.
	 *
	 * @param fechaBaja java.util.Date
	 * @return
	 */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { ");
		result.append(" [ id: ").append(this.id).append(" ]");
		result.append(", [ idTipoExpediente: ").append(this.idTipoExpediente).append(" ]");
		result.append(", [ descEu: ").append(this.descEu).append(" ]");
		result.append(", [ indBopv: ").append(this.indBopv).append(" ]");
		result.append(", [ indPrevistoBopv: ").append(this.indPrevistoBopv).append(" ]");
		result.append(", [ responsable: ").append(this.responsable).append(" ]");
		result.append(", [ palabrasDesde: ").append(this.palabrasDesde).append(" ]");
		result.append(", [ palabrasHasta: ").append(this.palabrasHasta).append(" ]");
		result.append(", [ estado: ").append(this.estado).append(" ]");
		result.append(", [ fechaAlta: ").append(this.fechaAlta).append(" ]");
		result.append(", [ fechaBaja: ").append(this.fechaBaja).append(" ]");
		result.append("}");
		return result.toString();
	}

	public PersonalIZO getResponsable() {
		return this.responsable;
	}

	public void setResponsable(PersonalIZO responsable) {
		this.responsable = responsable;
	}

	public String getTipoExpedienteDesc() {
		return this.tipoExpedienteDesc;
	}

	public void setTipoExpedienteDesc(String tipoExpedienteDesc) {
		this.tipoExpedienteDesc = tipoExpedienteDesc;
	}

	public String getBopvDesc() {
		return this.bopvDesc;
	}

	public void setBopvDesc(String bopvDesc) {
		this.bopvDesc = bopvDesc;
	}

	public String getPrevistoBopvDesc() {
		return this.previstoBopvDesc;
	}

	public void setPrevistoBopvDesc(String previstoBopvDesc) {
		this.previstoBopvDesc = previstoBopvDesc;
	}

	public String getEstadoDesc() {
		return this.estadoDesc;
	}

	public void setEstadoDesc(String estadoDesc) {
		this.estadoDesc = estadoDesc;
	}

	public Entidad getEntidadSolicitante() {
		return this.entidadSolicitante;
	}

	public void setEntidadSolicitante(Entidad entidadSolicitante) {
		this.entidadSolicitante = entidadSolicitante;
	}

	public PersonalIZO getTraductor() {
		return this.traductor;
	}

	public void setTraductor(PersonalIZO traductor) {
		this.traductor = traductor;
	}

	public List<EntidadesGruposTrabajo> getEntidades() {
		return this.entidades;
	}

	public void setEntidades(List<EntidadesGruposTrabajo> entidades) {
		this.entidades = entidades;
	}

	public List<TrabajadoresGruposTrabajo> getTrabajadores() {
		return this.trabajadores;
	}

	public void setTrabajadores(List<TrabajadoresGruposTrabajo> trabajadores) {
		this.trabajadores = trabajadores;
	}

}
