package com.ejie.aa79b.model;

import java.math.BigDecimal;

import com.ejie.aa79b.common.JsonNumbersDeserializer;
import com.ejie.aa79b.common.jackson.JsonImporteSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * TarifExpTradRev generated by UDA, 15-dic-2017 14:11:44.
 * 
 * @author UDA
 */

public class TarifExpTradRev implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long idOrden;
	private Long porRecargoDif;
	private Long porRecargoUrg;
	private BigDecimal precioMinimo;
	private Integer numPalabrasTarifConcor;
	private Long porPalabraConcor084;
	private Long porPalabraConcor8594;
	private Long porPalabraConcor95100;
	private boolean existeReg = false;

	/**
	 * Method 'TarifExpTradRev'.
	 */
	public TarifExpTradRev() {
		// Constructor
	}

	/**
	 * Method 'TarifExpTradRev'.
	 * 
	 * @param idOrden
	 *            Long
	 */
	public TarifExpTradRev(Long idOrden) {
		this.idOrden = idOrden;
	}

	/**
	 * Method 'getIdOrden'.
	 *
	 * @return Long
	 */

	public Long getIdOrden() {
		return this.idOrden;
	}

	/**
	 * Method 'setIdOrden'.
	 *
	 * @param idOrden
	 *            Long
	 * @return
	 */

	public void setIdOrden(Long idOrden) {
		this.idOrden = idOrden;
	}

	/**
	 * Method 'getPorRecargoDif'.
	 *
	 * @return Long
	 */

	public Long getPorRecargoDif() {
		return this.porRecargoDif;
	}

	/**
	 * Method 'setPorRecargoDif'.
	 *
	 * @param porRecargoDif
	 *            Long
	 * @return
	 */

	public void setPorRecargoDif(Long porRecargoDif) {
		this.porRecargoDif = porRecargoDif;
	}

	/**
	 * Method 'getPorRecargoUrg'.
	 *
	 * @return Long
	 */

	public Long getPorRecargoUrg() {
		return this.porRecargoUrg;
	}

	/**
	 * Method 'setPorRecargoUrg'.
	 *
	 * @param porRecargoUrg
	 *            Long
	 * @return
	 */

	public void setPorRecargoUrg(Long porRecargoUrg) {
		this.porRecargoUrg = porRecargoUrg;
	}

	/**
	 * Method 'getPrecioMinimo'.
	 *
	 * @return BigDecimal
	 */
	@JsonSerialize(using = JsonImporteSerializer.class)
	public BigDecimal getPrecioMinimo() {
		return this.precioMinimo;
	}

	/**
	 * Method 'setPrecioMinimo'.
	 *
	 * @param precioMinimo
	 *            BigDecimal
	 * @return
	 */
	@JsonDeserialize(using = JsonNumbersDeserializer.class)
	public void setPrecioMinimo(BigDecimal precioMinimo) {
		this.precioMinimo = precioMinimo;
	}

	/**
	 * Method 'getNumPalabrasTarifConcor'.
	 *
	 * @return Integer
	 */

	public Integer getNumPalabrasTarifConcor() {
		return this.numPalabrasTarifConcor;
	}

	/**
	 * Method 'setNumPalabrasTarifConcor'.
	 *
	 * @param numPalabrasTarifConcor
	 *            Integer
	 * @return
	 */

	public void setNumPalabrasTarifConcor(Integer numPalabrasTarifConcor) {
		this.numPalabrasTarifConcor = numPalabrasTarifConcor;
	}

	/**
	 * Method 'getPorPalabraConcor084'.
	 *
	 * @return Long
	 */

	public Long getPorPalabraConcor084() {
		return this.porPalabraConcor084;
	}

	/**
	 * Method 'setPorPalabraConcor084'.
	 *
	 * @param porPalabraConcor084
	 *            Long
	 * @return
	 */

	public void setPorPalabraConcor084(Long porPalabraConcor084) {
		this.porPalabraConcor084 = porPalabraConcor084;
	}

	/**
	 * Method 'getPorPalabraConcor8594'.
	 *
	 * @return Long
	 */

	public Long getPorPalabraConcor8594() {
		return this.porPalabraConcor8594;
	}

	/**
	 * Method 'setPorPalabraConcor8594'.
	 *
	 * @param porPalabraConcor8594
	 *            Long
	 * @return
	 */

	public void setPorPalabraConcor8594(Long porPalabraConcor8594) {
		this.porPalabraConcor8594 = porPalabraConcor8594;
	}

	/**
	 * Method 'getPorPalabraConcor95100'.
	 *
	 * @return Long
	 */

	public Long getPorPalabraConcor95100() {
		return this.porPalabraConcor95100;
	}

	/**
	 * Method 'setPorPalabraConcor95100'.
	 *
	 * @param porPalabraConcor95100
	 *            Long
	 * @return
	 */

	public void setPorPalabraConcor95100(Long porPalabraConcor95100) {
		this.porPalabraConcor95100 = porPalabraConcor95100;
	}

	public boolean isExisteReg() {
		return this.existeReg;
	}

	public void setExisteReg(boolean existeReg) {
		this.existeReg = existeReg;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { ");
		result.append(" [ idOrden: ").append(this.idOrden).append(" ]");
		result.append(", [ porRecargoDif: ").append(this.porRecargoDif).append(" ]");
		result.append(", [ porRecargoUrg: ").append(this.porRecargoUrg).append(" ]");
		result.append(", [ precioMinimo: ").append(this.precioMinimo).append(" ]");
		result.append(", [ numPalabrasTarifConcor: ").append(this.numPalabrasTarifConcor).append(" ]");
		result.append(", [ porPalabraConcor084: ").append(this.porPalabraConcor084).append(" ]");
		result.append(", [ porPalabraConcor8594: ").append(this.porPalabraConcor8594).append(" ]");
		result.append(", [ porPalabraConcor95100: ").append(this.porPalabraConcor95100).append(" ]");
		result.append(", [ existeReg: ").append(this.existeReg).append(" ]");
		result.append("}");
		return result.toString();
	}

}
