
package com.ejie.aa79b.control;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.model.ConfigPlazoMinimo;
import com.ejie.aa79b.service.ConfigPlazoMinimoService;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * ConfigPlazoMinimoController generated by UDA, 05-dic-2017 15:17:21.
 * 
 * @author UDA
 */

@Controller
@RequestMapping(value = "/administracion/datosBasicos")

public class ConfigPlazoMinimoController {

	private static final Logger LOGGER = LoggerFactory.getLogger(ConfigPlazoMinimoController.class);

	@Autowired
	private ConfigPlazoMinimoService configPlazoMinimoService;

	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 * 
	 */

	/**
	 * 
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 * 
	 * @param id001
	 *            Integer
	 * @param nivelUsuario001
	 *            String
	 * @return ConfigPlazoMinimo Objeto correspondiente al identificador
	 *         indicado.
	 */
	@RequestMapping(value = "/{id001}/{nivelUsuario001}", method = RequestMethod.GET)
	public @ResponseBody ConfigPlazoMinimo get(@PathVariable Integer id001, @PathVariable String nivelUsuario001) {
		ConfigPlazoMinimo configPlazoMinimo = new ConfigPlazoMinimo();
		configPlazoMinimo.setId(id001);
		configPlazoMinimo.setNivelUsuario(nivelUsuario001);
		configPlazoMinimo = this.configPlazoMinimoService.find(configPlazoMinimo);
		ConfigPlazoMinimoController.LOGGER.info("[GET - findBy_PK] : Obtener ConfigPlazoMinimo por PK");
		return configPlazoMinimo;
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterConfigPlazoMinimo
	 *            ConfigPlazoMinimo Objeto que contiene los parametros de
	 *            filtrado utilizados en la busqueda.
	 * @return List<ConfigPlazoMinimo> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody List<ConfigPlazoMinimo> getAll(@ModelAttribute ConfigPlazoMinimo filterConfigPlazoMinimo) {
		ConfigPlazoMinimoController.LOGGER.info("[GET - find_ALL] : Obtener ConfigPlazoMinimo por filtro");
		return this.configPlazoMinimoService.findAll(filterConfigPlazoMinimo, null);
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param configPlazoMinimo
	 *            ConfigPlazoMinimo Bean que contiene la informacion a
	 *            modificar.
	 * @return ConfigPlazoMinimo Bean resultante de la modificacion.
	 */
	@RequestMapping(method = RequestMethod.PUT)
	public @ResponseBody ConfigPlazoMinimo edit(@RequestBody ConfigPlazoMinimo configPlazoMinimo) {
		ConfigPlazoMinimo configPlazoMinimoAux = this.configPlazoMinimoService.update(configPlazoMinimo);
		ConfigPlazoMinimoController.LOGGER.info("[PUT] : ConfigPlazoMinimo actualizado correctamente");
		return configPlazoMinimoAux;
	}

	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param configPlazoMinimo
	 *            ConfigPlazoMinimo Bean que contiene la informacion con la que
	 *            se va a crear el nuevo registro.
	 * @return ConfigPlazoMinimo Bean resultante del proceso de creacion.
	 */
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody ConfigPlazoMinimo add(@RequestBody ConfigPlazoMinimo configPlazoMinimo) {
		ConfigPlazoMinimo configPlazoMinimoAux = this.configPlazoMinimoService.add(configPlazoMinimo);
		ConfigPlazoMinimoController.LOGGER.info("[POST] : ConfigPlazoMinimo insertado correctamente");
		return configPlazoMinimoAux;
	}

	/**
	 * Operacion CRUD Delete. Borrado del registro correspondiente al
	 * identificador especificado.
	 *
	 * @param id001
	 *            Integer
	 * @param nivelUsuario001
	 *            String Identificador del objeto que se desea eliminar.
	 * @return ConfigPlazoMinimo Bean eliminado.
	 */
	@RequestMapping(value = "/{id001}/{nivelUsuario001}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody ConfigPlazoMinimo remove(@PathVariable Integer id001, @PathVariable String nivelUsuario001) {
		ConfigPlazoMinimo configPlazoMinimo = new ConfigPlazoMinimo();
		configPlazoMinimo.setId(id001);
		configPlazoMinimo.setNivelUsuario(nivelUsuario001);
		this.configPlazoMinimoService.remove(configPlazoMinimo);
		ConfigPlazoMinimoController.LOGGER.info("[DELETE] : ConfigPlazoMinimo borrado correctamente");
		return configPlazoMinimo;
	}

	/*
	 * METODOS COMPONENTE RUP_TABLE
	 * 
	 */

	/**
	 * Operacion de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterConfigPlazoMinimo
	 *            ConfigPlazoMinimo Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return JQGridResponseDto<ConfigPlazoMinimo> Dto que contiene el
	 *         resultado del filtrado realizado por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/filter", method = RequestMethod.POST)
	public @ResponseBody JQGridResponseDto<ConfigPlazoMinimo> filter(
			@RequestJsonBody(param = "filter") ConfigPlazoMinimo filterConfigPlazoMinimo,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ConfigPlazoMinimoController.LOGGER.info("[POST - filter] : Obtener ConfigPlazoMinimos");
		return this.configPlazoMinimoService.filter(filterConfigPlazoMinimo, jqGridRequestDto, false);
	}

	/**
	 * Operacion de busqueda del componente RUP_TABLE.
	 * 
	 * @param filterConfigPlazoMinimo
	 *            ConfigPlazoMinimo Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param searchConfigPlazoMinimo
	 *            ConfigPlazoMinimo Bean que contiene los parametros de busqueda
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la búsqueda.
	 * @return TableRowDto<ConfigPlazoMinimo> Dto que contiene el resultado de
	 *         la busqueda realizada por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public @ResponseBody List<TableRowDto<ConfigPlazoMinimo>> search(
			@RequestJsonBody(param = "filter") ConfigPlazoMinimo filterConfigPlazoMinimo,
			@RequestJsonBody(param = "search") ConfigPlazoMinimo searchConfigPlazoMinimo,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ConfigPlazoMinimoController.LOGGER.info("[POST - search] : Buscar ConfigPlazoMinimos");
		return this.configPlazoMinimoService.search(filterConfigPlazoMinimo, searchConfigPlazoMinimo, jqGridRequestDto,
				false);
	}

	/**
	 * Borrado multiple de registros
	 * 
	 * @param filterConfigPlazoMinimo
	 *            ConfigPlazoMinimo Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la busqueda.
	 * @return List<String> Lista de los identificadores de los registros
	 *         eliminados.
	 * 
	 */
	@RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody List<String> removeMultiple(
			@RequestJsonBody(param = "filter") ConfigPlazoMinimo filterConfigPlazoMinimo,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ConfigPlazoMinimoController.LOGGER
				.info("[POST - search] : [POST - removeMultiple] : Eliminar multiples ConfigPlazoMinimos");
		this.configPlazoMinimoService.removeMultiple(filterConfigPlazoMinimo, jqGridRequestDto, false);
		ConfigPlazoMinimoController.LOGGER.info("All entities correctly deleted!");

		return jqGridRequestDto.getMultiselection().getSelectedIds();
	}

}
