package com.ejie.aa79b.control;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.model.ConfigPagoProveedores;
import com.ejie.aa79b.service.ConfigPagoProveedoresService;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * ConfigPagoProveedoresController generated by UDA, 05-dic-2017 15:17:21.
 * @author UDA
 */
 
@Controller
@RequestMapping (value = "/configpagoproveedores")

public class ConfigPagoProveedoresController  {

	private static final Logger LOGGER = LoggerFactory.getLogger(ConfigPagoProveedoresController.class);

	@Autowired
	private ConfigPagoProveedoresService configPagoProveedoresService;
	
	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 * 
	 */
	
	/**
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador indicado.
	 * 
	 * @param id005 Long
	 * @return ConfigPagoProveedores 
	 *            Objeto correspondiente al identificador indicado.
	 */
	@RequestMapping(value = "/{id005}", method = RequestMethod.GET)
	public @ResponseBody ConfigPagoProveedores get(@PathVariable Long id005) {
        ConfigPagoProveedores configPagoProveedores = new ConfigPagoProveedores();
		configPagoProveedores.setId(id005);
        configPagoProveedores = this.configPagoProveedoresService.find(configPagoProveedores);
        ConfigPagoProveedoresController.LOGGER.info("[GET - findBy_PK] : Obtener ConfigPagoProveedores por PK");
        return configPagoProveedores;
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterConfigPagoProveedores ConfigPagoProveedores
	 *            Objeto que contiene los parametros de filtrado utilizados en
	 *            la busqueda.
	 * @return List<ConfigPagoProveedores> 
	 *            Lista de objetos correspondientes a la busqueda realizada.
	 */
	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody List<ConfigPagoProveedores> getAll(@ModelAttribute ConfigPagoProveedores filterConfigPagoProveedores) {
		ConfigPagoProveedoresController.LOGGER.info("[GET - find_ALL] : Obtener ConfigPagoProveedores por filtro");
	    return this.configPagoProveedoresService.findAll(filterConfigPagoProveedores, null);
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param configPagoProveedores ConfigPagoProveedores 
	 *            Bean que contiene la informacion a modificar.
	 * @return ConfigPagoProveedores 
	 *            Bean resultante de la modificacion.
	 */
	@RequestMapping(method = RequestMethod.PUT)
    public @ResponseBody ConfigPagoProveedores edit(@RequestBody ConfigPagoProveedores configPagoProveedores) {		
        ConfigPagoProveedores configPagoProveedoresAux = this.configPagoProveedoresService.update(configPagoProveedores);
		ConfigPagoProveedoresController.LOGGER.info("[PUT] : ConfigPagoProveedores actualizado correctamente");
        return configPagoProveedoresAux;
    }

	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param configPagoProveedores ConfigPagoProveedores 
	 *            Bean que contiene la informacion con la que se va a crear el
	 *            nuevo registro.
	 * @return ConfigPagoProveedores
	 *            Bean resultante del proceso de creacion.
	 */
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody ConfigPagoProveedores add(@RequestBody ConfigPagoProveedores configPagoProveedores) {		
        ConfigPagoProveedores configPagoProveedoresAux = this.configPagoProveedoresService.add(configPagoProveedores);
        ConfigPagoProveedoresController.LOGGER.info("[POST] : ConfigPagoProveedores insertado correctamente");
    	return configPagoProveedoresAux;
	}

	/**
	 * Operacion CRUD Delete. Borrado del registro correspondiente al
	 * identificador especificado.
	 *
	 * @param id005 Long
	 *            Identificador del objeto que se desea eliminar.
	 * @return ConfigPagoProveedores
	 *            Bean eliminado.
	 */
	@RequestMapping(value = "/{id005}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
    public @ResponseBody ConfigPagoProveedores remove(@PathVariable Long id005) {
        ConfigPagoProveedores configPagoProveedores = new ConfigPagoProveedores();
        configPagoProveedores.setId(id005);
        this.configPagoProveedoresService.remove(configPagoProveedores);
       	ConfigPagoProveedoresController.LOGGER.info("[DELETE] : ConfigPagoProveedores borrado correctamente");
       	return configPagoProveedores;
    }
    
	
	/*
	 * METODOS COMPONENTE RUP_TABLE
	 * 
	 */

	 /**
	 * Metodo de presentacion del RUP_TABLE.
	 * 
	 * @param model Model
	 * @return String
	 */
	@RequestMapping(value = "/maint", method = RequestMethod.GET)
	public String getFormEdit(Model model) {
		ConfigPagoProveedoresController.LOGGER.info("[GET - View] : configpagoproveedores");
		return "configpagoproveedores";
	}
	 
	 /**
	 * Operacion de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterConfigPagoProveedores ConfigPagoProveedores
	 *            Bean que contiene los parametros de filtrado a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return JQGridResponseDto<ConfigPagoProveedores>
	 *            Dto que contiene el resultado del filtrado realizado por el 
	 *            componente RUP_TABLE.
	 */
	@RequestMapping(value = "/filter", method = RequestMethod.POST)
	public @ResponseBody JQGridResponseDto<ConfigPagoProveedores> filter(
			@RequestJsonBody(param="filter") ConfigPagoProveedores filterConfigPagoProveedores,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ConfigPagoProveedoresController.LOGGER.info("[POST - filter] : Obtener ConfigPagoProveedoress");
		return this.configPagoProveedoresService.filter(filterConfigPagoProveedores, jqGridRequestDto, false);
	}
	 
	/**
	 * Operacion de busqueda del componente RUP_TABLE.
	 * 
	 * @param filterConfigPagoProveedores ConfigPagoProveedores
	 *            Bean que contiene los parametros de filtrado a emplear.
	 * @param searchConfigPagoProveedores ConfigPagoProveedores
	 *            Bean que contiene los parametros de busqueda a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la búsqueda.
	 * @return TableRowDto<ConfigPagoProveedores> 
	 *            Dto que contiene el resultado de la busqueda realizada por el
	 *            componente RUP_TABLE. 
	 */
	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public @ResponseBody List<TableRowDto<ConfigPagoProveedores>> search(
			@RequestJsonBody(param="filter") ConfigPagoProveedores filterConfigPagoProveedores,
			@RequestJsonBody(param="search") ConfigPagoProveedores searchConfigPagoProveedores,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ConfigPagoProveedoresController.LOGGER.info("[POST - search] : Buscar ConfigPagoProveedoress");
		return this.configPagoProveedoresService.search(filterConfigPagoProveedores, searchConfigPagoProveedores, jqGridRequestDto, false);
	}
	
	/**
	 * Borrado multiple de registros
	 * 
	 * @param filterConfigPagoProveedores ConfigPagoProveedores
	 *            Bean que contiene los parametros de filtrado a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la busqueda.
	 * @return List<String>
	 *            Lista de los identificadores de los registros eliminados.
	 * 
	 */
	@RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody List<String> removeMultiple(
			@RequestJsonBody(param="filter") ConfigPagoProveedores filterConfigPagoProveedores,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ConfigPagoProveedoresController.LOGGER.info("[POST - search] : [POST - removeMultiple] : Eliminar multiples ConfigPagoProveedoress");
		this.configPagoProveedoresService.removeMultiple(filterConfigPagoProveedores, jqGridRequestDto, false);
		ConfigPagoProveedoresController.LOGGER.info("All entities correctly deleted!");
		
		return jqGridRequestDto.getMultiselection().getSelectedIds();
	}
}	
