package com.ejie.aa79b.control;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.model.Entidad;
import com.ejie.aa79b.model.Solicitante;
import com.ejie.aa79b.service.SolicitanteService;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * SolicitanteController generated by UDA, 05-dic-2017 15:17:21.
 *
 * @author UDA
 */

@Controller
@RequestMapping(value = "/solicitante")

public class SolicitanteController {

	private static final Logger LOGGER = LoggerFactory.getLogger(SolicitanteController.class);

	@Autowired()
	private SolicitanteService solicitanteService;

	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody() List<Solicitante> get() {
		final Solicitante filterSolicitante = new Solicitante();
		return this.solicitanteService.findAll(filterSolicitante, null);
	}

	@RequestMapping(value = "/{tipoEntidad}", method = RequestMethod.GET)
	public @ResponseBody() List<Solicitante> getListaSolicitantesParam(@PathVariable() String tipoEntidad) {
		final Solicitante filterSolicitante = new Solicitante();
		filterSolicitante.setGestorExpedientes("S");
		filterSolicitante.setGestorExpedientesVIP("S");
		filterSolicitante.setGestorExpedientesBOPV("S");
		if (tipoEntidad != null && !"".equals(tipoEntidad) && !"null".equals(tipoEntidad)) {
			Entidad entidad = new Entidad();
			entidad.setTipo(tipoEntidad);
			filterSolicitante.setEntidad(entidad);
		}

		return this.solicitanteService.findAll(filterSolicitante, null);
	}

	@RequestMapping(value = "/suggest", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> getListado(@RequestParam String q,
			@RequestParam(required = false) String tipoEntidad, @RequestParam(required = false) String codEntidad) {
		SolicitanteController.LOGGER.info("[GET - find_ALL] : Solicitante autocomplete");

		final Solicitante filterSolicitante = new Solicitante();

		if ((q != null) && (!q.isEmpty())) {
			filterSolicitante.setNombreFiltro(q);
		}
		if (!codEntidad.contentEquals("")) {
			Entidad entidadSolicitante = new Entidad();
			if (!codEntidad.contentEquals("")) {
				entidadSolicitante.setTipo(tipoEntidad);
			}
			entidadSolicitante.setCodigo(Integer.parseInt(codEntidad));
			filterSolicitante.setEntidad(entidadSolicitante);
			filterSolicitante.setGestorExpedientes("S");
			filterSolicitante.setGestorExpedientesVIP("S");
			filterSolicitante.setGestorExpedientesBOPV("S");
		}

		return this.solicitanteService.findAllLike(filterSolicitante, null, false);
	}

	@RequestMapping(value = "/{tipoEntidad}/{codEntidad}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> getListadoEntidad(@PathVariable String tipoEntidad,
			@PathVariable String codEntidad, Locale locale) {
		SolicitanteController.LOGGER.info("[GET - find_ALL] : Solicitante combo");

		final Solicitante filterSolicitante = new Solicitante();

		if (StringUtils.isNotEmpty(codEntidad) && StringUtils.isNotEmpty(tipoEntidad)) {
			Entidad entidadSolicitante = new Entidad();
			entidadSolicitante.setTipo(tipoEntidad);
			entidadSolicitante.setCodigo(Integer.parseInt(codEntidad));
			filterSolicitante.setEntidad(entidadSolicitante);
			filterSolicitante.setGestorExpedientes("S");
			filterSolicitante.setGestorExpedientesVIP("S");
			filterSolicitante.setGestorExpedientesBOPV("S");
			JQGridRequestDto jQGridRequestDto = new JQGridRequestDto();
			if (locale.getLanguage().equals(Constants.LANG_CASTELLANO)) {
				jQGridRequestDto.setSidx(DBConstants.CENTRO_ORGANICO_ES);
			}else {
				jQGridRequestDto.setSidx(DBConstants.CENTRO_ORGANICO_EU);
			}
			jQGridRequestDto.setSord("asc");
			return this.solicitanteService.findEntidadCentroOrganico(filterSolicitante, jQGridRequestDto, false);
		}
		return Collections.emptyList();

	}

	@RequestMapping(value = "/comboExcepcionFact/{tipoEntidad}/{codEntidad}/{dniContacto}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> getListadoEntidad(@PathVariable String tipoEntidad,
			@PathVariable String codEntidad, @PathVariable String dniContacto, Locale locale) {
		SolicitanteController.LOGGER.info("[GET - find_ALL] : Solicitante combo");

		Solicitante filterSolicitante = new Solicitante();
		List<Solicitante> listaSolicitantes = new ArrayList<Solicitante>();

		if (StringUtils.isNotEmpty(codEntidad) && StringUtils.isNotEmpty(tipoEntidad)) {
			Entidad entidadSolicitante = new Entidad();
			entidadSolicitante.setTipo(tipoEntidad);
			entidadSolicitante.setCodigo(Integer.parseInt(codEntidad));
			filterSolicitante.setEntidad(entidadSolicitante);
			filterSolicitante.setGestorExpedientes("S");
			filterSolicitante.setGestorExpedientesVIP("S");
			filterSolicitante.setGestorExpedientesBOPV("S");
			JQGridRequestDto jQGridRequestDto = new JQGridRequestDto();
			if (locale.getLanguage().equals(Constants.LANG_CASTELLANO)) {
				jQGridRequestDto.setSidx(DBConstants.CENTRO_ORGANICO_ES);
			}else {
				jQGridRequestDto.setSidx(DBConstants.CENTRO_ORGANICO_EU);
			}
			jQGridRequestDto.setSord("asc");
			listaSolicitantes = this.solicitanteService.findEntidadCentroOrganico(filterSolicitante, jQGridRequestDto, false);
		}
		// si hay que seleccionar un valor en el combo
		if (StringUtils.isNotEmpty(dniContacto) && !"null".equals(dniContacto)) {

			if (!listaSolicitantes.isEmpty()) {
				for (Solicitante unSolicitante : listaSolicitantes) {
					if (unSolicitante.getDni().contentEquals(dniContacto)) {
						return listaSolicitantes;
					}
				}
			}
			Solicitante solicitanteDeBaja = new Solicitante();
			filterSolicitante = new Solicitante();
			filterSolicitante.setDni(dniContacto);
			solicitanteDeBaja = this.solicitanteService.find77(filterSolicitante);
			listaSolicitantes.add(solicitanteDeBaja);
		}
		return listaSolicitantes;

	}

	@RequestMapping(value = "/findGestoresDeExp", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findGestoresDeExp(@RequestParam() String q) {
		Solicitante solicitanteFilter = new Solicitante();
		solicitanteFilter.setNombreFiltro(q);
		return this.solicitanteService.findGestoresDeExp(solicitanteFilter);
	}

	@RequestMapping(value = "/findGestoresDeExpCEntidad/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findGestoresDeExpCEntidad(@PathVariable() String tipo,
			@PathVariable() Integer codigo, @RequestParam() String q) {
		Solicitante solicitanteFilter = new Solicitante();
		solicitanteFilter.setNombreFiltro(q);
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		solicitanteFilter.setEntidad(entidad);
		return this.solicitanteService.findGestoresDeExpCEntidad(solicitanteFilter);
	}

	@RequestMapping(value = "/findRevisionContactoFacturarConExpedientes/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findRevisionContactoFacturarConExpedientes(@PathVariable() String tipo,
			@PathVariable() Integer codigo) {
		Solicitante solicitanteFilter = new Solicitante();
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		solicitanteFilter.setEntidad(entidad);
		return this.solicitanteService.findRevisionContactoFacturarConExpedientes(solicitanteFilter);
	}

	@RequestMapping(value = "/findGestoresExpConfidenciales", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findGestoresExpConfidenciales(@RequestParam() String q) {
		Solicitante solicitanteFilter = new Solicitante();
		solicitanteFilter.setNombreFiltro(q);
		solicitanteFilter.setEntidad(new Entidad());
		return this.solicitanteService.findGestoresExpConfidenciales(solicitanteFilter);
	}

	@RequestMapping(value = "/findGestoresExpConfidenciales/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findGestoresExpConfidencialesConTipoYCodigo(@PathVariable() String tipo,
			@PathVariable() Integer codigo, @RequestParam() String q) {
		Solicitante solicitanteFilter = new Solicitante();
		solicitanteFilter.setNombreFiltro(q);
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		solicitanteFilter.setEntidad(entidad);
		return this.solicitanteService.findGestoresExpConfidenciales(solicitanteFilter);
	}

	@RequestMapping(value = "/findSolicitantesGestAnul/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findSolicitantesGestAnul(@PathVariable() String tipo,
			@PathVariable() Integer codigo) {
		SolicitanteController.LOGGER.info("[GET - findSolicitantesGestAnul] : Solicitante combo");
		Solicitante filterSolicitante = new Solicitante();
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		filterSolicitante.setEntidad(entidad);
		return this.solicitanteService.findSolicitantesGestAnul(filterSolicitante);
	}

	@RequestMapping(value = "/findSolicitanteActDatosFact/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findSolicitanteActDatosFact(@PathVariable() String tipo,
			@PathVariable() Integer codigo) {
		Solicitante solicitanteFilter = new Solicitante();
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		solicitanteFilter.setEntidad(entidad);
		return this.solicitanteService.findSolicitanteActDatosFact(solicitanteFilter);
	}

	@RequestMapping(value = "/findSolicitanteAFacturarActDatosFact/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findSolicitanteAFacturarActDatosFact(@PathVariable() String tipo,
			@PathVariable() Integer codigo) {
		Solicitante solicitanteFilter = new Solicitante();
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		solicitanteFilter.setEntidad(entidad);
		return this.solicitanteService.findSolicitanteAFacturarActDatosFact(solicitanteFilter);
	}

	@RequestMapping(value = "/findGestores/{tipo}/{codigo}", method = RequestMethod.GET)
	public @ResponseBody List<Solicitante> findGestores(@PathVariable() String tipo, @PathVariable() Integer codigo,
			@RequestParam() String q) {
		Solicitante solicitanteFilter = new Solicitante();
		solicitanteFilter.setNombreFiltro(q);
		Entidad entidad = new Entidad();
		// si la entidad pasada es nula, vacia o un string con valor "-1", no lo
		// incluye en el filtro
		if (!StringUtils.isBlank(tipo) && !Constants.MINUS_UNO.toString().equals(tipo)) {
			entidad.setTipo(tipo);
		}
		// si el codigo de entidad pasado es -1, no lo incluye en el filtro
		if (Constants.MINUS_UNO != codigo) {
			entidad.setCodigo(codigo);
		}
		solicitanteFilter.setEntidad(entidad);
		return this.solicitanteService.findGestores(solicitanteFilter);
	}

}
