package com.ejie.aa79b.control;

import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.model.TiposInterpretacion;
import com.ejie.aa79b.service.ExcelReportService;
import com.ejie.aa79b.service.PdfReportService;
import com.ejie.aa79b.service.TiposInterpretacionService;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * TiposInterpretacionController generated by UDA, 22-nov-2017 10:22:35.
 * 
 * @author UDA
 */

@Controller
@RequestMapping(value = "/administracion/datosmaestros/tiposinterpretacion")

public class TiposInterpretacionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(TiposInterpretacionController.class);

    @Autowired
    private TiposInterpretacionService tiposInterpretacionService;
    @Autowired
    private ExcelReportService aa79bExcelReportService;
    @Autowired()
    private PdfReportService aa79bPdfReportService;
    @Autowired()
    private ReloadableResourceBundleMessageSource appMessageSource;

    private static final String LITERAL_LABEL = "titulo.tiposInterpretacion";

    /*
     * OPERACIONES CRUD (Create, Read, Update, Delete)
     * 
     */

    /**
     * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
     * indicado.
     * 
     * @param id008
     *            Long
     * @param descEs008
     *            String
     * @param descEu008
     *            String
     * @param estado008
     *            String
     * @param tipoFacturacion008
     *            String
     * @return TiposInterpretacion Objeto correspondiente al identificador
     *         indicado.
     */
    @RequestMapping(value = "/{id008}", method = RequestMethod.GET)
    public @ResponseBody TiposInterpretacion get(@PathVariable Long id008) {
        TiposInterpretacion tiposInterpretacion = new TiposInterpretacion();
        tiposInterpretacion.setId008(id008);
        tiposInterpretacion = this.tiposInterpretacionService.find(tiposInterpretacion);
        TiposInterpretacionController.LOGGER.info("[GET - findBy_PK] : Obtener TiposInterpretacion por PK");
        return tiposInterpretacion;
    }

    /**
     * Devuelve una lista de beans correspondientes a los valores de filtrados
     * indicados en el objeto pasado como parametro.
     *
     * @param filterTiposInterpretacion
     *            TiposInterpretacion Objeto que contiene los parametros de
     *            filtrado utilizados en la busqueda.
     * @return List<TiposInterpretacion> Lista de objetos correspondientes a la
     *         busqueda realizada.
     */
    @RequestMapping(method = RequestMethod.GET)
    public @ResponseBody List<TiposInterpretacion> getAll(
            @ModelAttribute TiposInterpretacion filterTiposInterpretacion) {
        TiposInterpretacionController.LOGGER.info("[GET - find_ALL] : Obtener TiposInterpretacion por filtro");
        return this.tiposInterpretacionService.findAll(filterTiposInterpretacion, null);
    }

    /**
     * Operacion CRUD Edit. Modificacion del bean indicado.
     *
     * @param tiposInterpretacion
     *            TiposInterpretacion Bean que contiene la informacion a
     *            modificar.
     * @return TiposInterpretacion Bean resultante de la modificacion.
     */
    @RequestMapping(method = RequestMethod.PUT)
    public @ResponseBody TiposInterpretacion edit(@RequestBody TiposInterpretacion tiposInterpretacion) {
        TiposInterpretacion tiposInterpretacionAux = this.tiposInterpretacionService.update(tiposInterpretacion);
        TiposInterpretacionController.LOGGER.info("[PUT] : TiposInterpretacion actualizado correctamente");
        return tiposInterpretacionAux;
    }

    /**
     * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
     * indicado.
     *
     * @param tiposInterpretacion
     *            TiposInterpretacion Bean que contiene la informacion con la
     *            que se va a crear el nuevo registro.
     * @return TiposInterpretacion Bean resultante del proceso de creacion.
     */
    @RequestMapping(method = RequestMethod.POST)
    public @ResponseBody TiposInterpretacion add(@RequestBody TiposInterpretacion tiposInterpretacion) {
        TiposInterpretacion tiposInterpretacionAux = this.tiposInterpretacionService.add(tiposInterpretacion);
        TiposInterpretacionController.LOGGER.info("[POST] : TiposInterpretacion insertado correctamente");
        return tiposInterpretacionAux;
    }

    /**
     * Operacion CRUD Delete. Borrado del registro correspondiente al
     * identificador especificado.
     *
     * @param id008
     *            Long
     * @param descEs008
     *            String
     * @param descEu008
     *            String
     * @param estado008
     *            String
     * @param tipoFacturacion008
     *            String Identificador del objeto que se desea eliminar.
     * @return TiposInterpretacion Bean eliminado.
     */
    @RequestMapping(value = "/{id008}", method = RequestMethod.DELETE)
    @ResponseStatus(value = HttpStatus.OK)
    public @ResponseBody TiposInterpretacion remove(@PathVariable Long id008) {
        TiposInterpretacion tiposInterpretacion = new TiposInterpretacion();
        tiposInterpretacion.setId008(id008);
        this.tiposInterpretacionService.remove(tiposInterpretacion);
        TiposInterpretacionController.LOGGER.info("[DELETE] : TiposInterpretacion borrado correctamente");
        return tiposInterpretacion;
    }

    /*
     * METODOS COMPONENTE RUP_TABLE
     * 
     */

    /**
     * Metodo de presentacion del RUP_TABLE.
     * 
     * @param model
     *            Model
     * @return String
     */
    @RequestMapping(value = "/maint", method = RequestMethod.GET)
    public String getFormEdit(Model model) {
        TiposInterpretacionController.LOGGER.info("[GET - View] : tiposinterpretacion");
        return "tiposinterpretacion";
    }

    /**
     * Operacion de filtrado del componente RUP_TABLE.
     * 
     * @param filterTiposInterpretacion
     *            TiposInterpretacion Bean que contiene los parametros de
     *            filtrado a emplear.
     * @param jqGridRequestDto
     *            Dto que contiene los parametros de configuracion propios del
     *            RUP_TABLE a aplicar en el filtrado.
     * @return JQGridResponseDto<TiposInterpretacion> Dto que contiene el
     *         resultado del filtrado realizado por el componente RUP_TABLE.
     */
    @RequestMapping(value = "/filter", method = RequestMethod.POST)
    public @ResponseBody JQGridResponseDto<TiposInterpretacion> filter(
            @RequestJsonBody(param = "filter") TiposInterpretacion filterTiposInterpretacion,
            @RequestJsonBody JQGridRequestDto jqGridRequestDto) {
        TiposInterpretacionController.LOGGER.info("[POST - filter] : Obtener TiposInterpretacions");
        return this.tiposInterpretacionService.filter(filterTiposInterpretacion, jqGridRequestDto, false);
    }

    /**
     * Operacion de busqueda del componente RUP_TABLE.
     * 
     * @param filterTiposInterpretacion
     *            TiposInterpretacion Bean que contiene los parametros de
     *            filtrado a emplear.
     * @param searchTiposInterpretacion
     *            TiposInterpretacion Bean que contiene los parametros de
     *            busqueda a emplear.
     * @param jqGridRequestDto
     *            Dto que contiene los parametros de configuracion propios del
     *            RUP_TABLE a aplicar en la busqueda.
     * @return TableRowDto<TiposInterpretacion> Dto que contiene el resultado de
     *         la busqueda realizada por el componente RUP_TABLE.
     */
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    public @ResponseBody List<TableRowDto<TiposInterpretacion>> search(
            @RequestJsonBody(param = "filter") TiposInterpretacion filterTiposInterpretacion,
            @RequestJsonBody(param = "search") TiposInterpretacion searchTiposInterpretacion,
            @RequestJsonBody JQGridRequestDto jqGridRequestDto) {
        TiposInterpretacionController.LOGGER.info("[POST - search] : Buscar TiposInterpretacions");
        return this.tiposInterpretacionService.search(filterTiposInterpretacion, searchTiposInterpretacion,
                jqGridRequestDto, false);
    }

    /**
     * Borrado multiple de registros
     * 
     * @param filterTiposInterpretacion
     *            TiposInterpretacion Bean que contiene los parametros de
     *            filtrado a emplear.
     * @param jqGridRequestDto
     *            Dto que contiene los parametros de configuracion propios del
     *            RUP_TABLE a aplicar en la busqueda.
     * @return List<String> Lista de los identificadores de los registros
     *         eliminados.
     * 
     */
    @RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
    @ResponseStatus(value = HttpStatus.OK)
    public @ResponseBody List<String> removeMultiple(
            @RequestJsonBody(param = "filter") TiposInterpretacion filterTiposInterpretacion,
            @RequestJsonBody JQGridRequestDto jqGridRequestDto) {
        TiposInterpretacionController.LOGGER
                .info("[POST - search] : [POST - removeMultiple] : Eliminar multiples TiposInterpretacions");
        this.tiposInterpretacionService.removeMultiple(filterTiposInterpretacion, jqGridRequestDto, false);
        TiposInterpretacionController.LOGGER.info("All entities correctly deleted!");

        return jqGridRequestDto.getMultiselection().getSelectedIds();
    }

    @RequestMapping(value = "/xlsxReport", method = RequestMethod.POST)
    public void xlsxTabla(@RequestParam(value = "columns", required = false) String columns,
            @RequestParam(value = "criterios", required = false) String criterios,
            @ModelAttribute() JQGridRequestDto jqGridRequestDto,
            @ModelAttribute() TiposInterpretacion filterTiposInterpretacion, HttpServletRequest request,
            HttpServletResponse response, Model model) {
        TiposInterpretacionController.LOGGER.info("[POST - subm]: xlsxTabla ========================================");
        Locale locale = LocaleContextHolder.getLocale();
        JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
                jqGridRequestDto.getSord());
        JQGridResponseDto<TiposInterpretacion> respuesta = this.tiposInterpretacionService
                .filter(filterTiposInterpretacion, jqGridRequestDtoReport, false);

        final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

        this.aa79bExcelReportService.generarExcel("printExcel", response, criterios, columns, respuesta.getRows(),
                locale, LITERAL_LABEL, label);
    }

    /**
     * @param columns
     * @param criterios
     * @param request
     * @param response
     * @param jqGridRequestDto
     * @param filter
     * @param model
     * @throws Exception
     */
    @RequestMapping(value = "/pdfReport", method = RequestMethod.POST)
    public void pdfTabla(@RequestParam(value = "columns", required = false) String columns,
            @RequestParam(value = "criterios", required = false) String criterios, HttpServletRequest request,
            HttpServletResponse response, @ModelAttribute() JQGridRequestDto jqGridRequestDto,
            @ModelAttribute() TiposInterpretacion filterTiposInterpretacion, Model model) {
        TiposInterpretacionController.LOGGER.info("[POST - subm]: pdfTabla ========================================");

        JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
                jqGridRequestDto.getSord());

        JQGridResponseDto<TiposInterpretacion> respuesta = this.tiposInterpretacionService
                .filter(filterTiposInterpretacion, jqGridRequestDtoReport, false);

        Locale locale = LocaleContextHolder.getLocale();
        final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

        this.aa79bPdfReportService.generarPdf("defaultPDF", response, criterios, columns, respuesta.getRows(),
                LITERAL_LABEL, locale, label);
    }

}
