CREATE OR REPLACE VIEW AA79O06V00 AS
    SELECT TIPO_SOLICITANTE
         , COD_SOLICITANTE
         , DESC_SOLICITANTE
      FROM ( SELECT TIPO_ENTIDAD   TIPO_SOLICITANTE
                , COD_ENTIDAD    COD_SOLICITANTE
                , DESC_EU        DESC_SOLICITANTE
                , ROW_NUMBER() OVER(PARTITION BY TIPO_ENTIDAD, COD_ENTIDAD ORDER BY DESC_EU) RN
             FROM X54JAPI_SOLICITANTES
         )
     WHERE RN = 1;