CREATE OR REPLACE VIEW AA79O02V00 AS
    SELECT 1 MES
         , 'Urtarrila' DESC_MES
      FROM DUAL
    UNION ALL
    SELECT 2
         , 'Otsaila'
      FROM DUAL
    UNION ALL
    SELECT 3
         , 'Martxoa'
      FROM DUAL
    UNION ALL
    SELECT 4
         , 'Apirila'
      FROM DUAL
    UNION ALL
    SELECT 5
         , 'Maiatza'
      FROM DUAL
    UNION ALL
    SELECT 6
         , 'Ekaina'
      FROM DUAL
    UNION ALL
    SELECT 7
         , 'Uztaila'
      FROM DUAL
    UNION ALL
    SELECT 8
         , 'Abuztua'
      FROM DUAL
    UNION ALL
    SELECT 9
         , 'Iraila'
      FROM DUAL
    UNION ALL
    SELECT 10
         , 'Urria'
      FROM DUAL
    UNION ALL
    SELECT 11
         , 'Azaroa'
      FROM DUAL
    UNION ALL
    SELECT 12
         , 'Abendua'
      FROM DUAL;