CREATE OR REPLACE VIEW AA79O21V00 AS
    SELECT 1 COD_TIPO_INTERPRETE
         , 'IZO' DESC_TIPO_INTERPRETE
      FROM DUAL
    UNION ALL
    SELECT 2
         , 'Hornitzailea'
      FROM DUAL
    UNION ALL
    SELECT 3
         , 'Biak'
      FROM DUAL;