CREATE OR REPLACE VIEW AA79O20V00 AS
    SELECT ID_IDIOMA_009        COD_IDIOMA
         , DESC_IDIOMA_EU_009   DESC_IDIOMA
      FROM AA79B09T00
      UNION ALL
    SELECT 3, 'Bestelakoak' FROM DUAL;