CREATE OR REPLACE VIEW AA79O51V00 AS
SELECT ANYO_051 ANYO
, NUM_EXP_051 NUM_EXP
, EXTRACT(month FROM FECHA_ALTA_051) MES
, CASE WHEN EXTRACT(day FROM FECHA_ALTA_051) <= 15 THEN 1 ELSE 2 END QUINCENA
, MOD(TO_CHAR(FECHA_ALTA_051, 'J'), 7)+1 DIA
, DECODE(ID_ESTADO_EXP_059,4,2,5,3,1) ESTADO
, ID_TIPO_EXPEDIENTE_051 TIPO_EXP
, DECODE(IND_CORREDACCION_053, 'S', 1, 'N', 0) EXP_CORREDACCION
, CASE WHEN id_estado_exp_059 = 5 AND ID_MOTIVO_ANULACION_0A1 in (4,5,6,7) THEN 1 ELSE 0 END ABANDONADO
, CASE WHEN TIPO_B7 IS NOT NULL THEN TIPO_B7
       WHEN TIPO_ENTIDAD_054 = 'L' THEN 6
       WHEN TIPO_ENTIDAD_054 = 'E' THEN 1
       WHEN TIPO_ENTIDAD_054 = 'B' THEN 2
  END TIPO_SOLICITANTE
, TIPO_ENTIDAD_054 || ID_ENTIDAD_054 SOLICITANTE
, CASE WHEN IND_PUBLICAR_BOPV_053 = 'S' THEN 1
       WHEN TIPO_ENTIDAD_054 = 'B' AND ID_ENTIDAD_054 = BOE.VALOR_000 THEN 2
       ELSE 3 
  END PUBLICACION
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'T' THEN DECODE(RECURSO_ASIGNACION_081,'I',1,'P',2,3) ELSE NULL END TIPO_TRADUCTOR
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'R' THEN DECODE(RECURSO_ASIGNACION_081,'I',1,'P',2,3) ELSE NULL END TIPO_REVISOR
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'I' THEN DECODE(RECURSO_ASIGNACION_081,'I',1,'P',2,3) ELSE NULL END TIPO_INTERPRETE
, TIPO_ACTO_052 TIPO_INTERPRETACION
, DECODE(TIPO_DOCUMENTO_056, 69, 1, 70, 2) TIPO_DOCUMENTO
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null and TRUNC(FECHA_FINAL_IZO_053) = TRUNC(FECHA_ENTREGA_REAL_053) THEN 1 
       WHEN FECHA_ENTREGA_REAL_053 is not null and TRUNC(FECHA_FINAL_IZO_053) < TRUNC(FECHA_ENTREGA_REAL_053) THEN 2
       WHEN FECHA_ENTREGA_REAL_053 is not null and TRUNC(FECHA_FINAL_IZO_053) > TRUNC(FECHA_ENTREGA_REAL_053) THEN 3 
       ELSE null 
  END PLAZO
, NUM_TOTAL_PAL_IZO_053 NUM_PALABRAS
, CASE WHEN NUM_TOTAL_PAL_IZO_053 > NUM_PALABRAS.pal_trados_003 THEN 1 ELSE 0 END TIPO_PROYECTO
, 1 SUBCONTRATADO
, CASE WHEN NUM_INTERPRETES_089 > 1 THEN 1 ELSE 0 END MAS_1_INTERPRETE
, porcentajeEuskera.POR_EUSKERA PORCEN_EUSKERA
, TIPO_DOCUMENTO_056 TIPO_DOCUMENTAL
, ID_MOTIVO_ANULACION_0A1 TIPO_ANULACION
, ID_MOTIVO_RECHAZO_067 TIPO_RECHAZO
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'I' THEN 1 ELSE DECODE(IND_FACTURABLE_053,'S',1,0) END FACTURABLE
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'I' THEN 0 ELSE DECODE(IND_URGENTE_053,'S',1,0) END MARCA_PRISA
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'I' THEN 0 ELSE DECODE(IND_DIFICIL_053,'S',1,0) END RECARGO
, ID_IDIOMA_053 IDIOMA
, CASE WHEN ID_TIPO_EXPEDIENTE_051 = 'I' THEN DECODE(IND_PRESUPUESTO_052,'S',1,0) ELSE DECODE(IND_PRESUPUESTO_053,'S',1,0) END PRESUPUESTO
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null THEN DIAS_ENTRE_FECHAS_ATENCION (primeraAsignacion.FECHA_ASIGNACION_081, FECHA_ENTREGA_REAL_053 ) ELSE null END DIAS_TRABAJO
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null THEN PARSE_HORA_MINUTOS(HORAS_ENTRE_FECHAS_ATENCION (primeraAsignacion.FECHA_ASIGNACION_081, FECHA_ENTREGA_REAL_053)) ELSE null END HORAS_TRABAJO
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null THEN PARSE_HORA_MINUTOS(HORAS_ENTRE_FECHAS_ATENCION (fechaEnCurso.fechaEstado, FECHA_FINAL_IZO_053)) ELSE null END TIEMPO_PREVISTO
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null THEN PARSE_HORA_MINUTOS(HORAS_ENTRE_FECHAS_ATENCION (primeraAsignacion.FECHA_ASIGNACION_081, FECHA_ENTREGA_REAL_053)) ELSE null END  TIEMPO_REALIZACION
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null AND TRUNC(FECHA_FINAL_IZO_053) < TRUNC(FECHA_ENTREGA_REAL_053) THEN DIAS_ENTRE_FECHAS_ATENCION(FECHA_FINAL_IZO_053, FECHA_ENTREGA_REAL_053) ELSE null END DIAS_RETRASO
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null THEN DIAS_ENTRE_FECHAS_ATENCION (FECHA_ALTA_051, FECHA_ENTREGA_REAL_053 ) ELSE null END DIAS_DURACION
, CASE WHEN FECHA_ENTREGA_REAL_053 is not null THEN PARSE_HORA_MINUTOS(HORAS_ENTRE_FECHAS_ATENCION(FECHA_ALTA_051, FECHA_ENTREGA_REAL_053 )) ELSE null END HORAS_DURACION
FROM AA79B51T00
JOIN AA79B59T00 ON ANYO_059 = ANYO_051 AND NUM_EXP_059 = NUM_EXP_051 AND id_estado_bitacora_059 = estado_bitacora_051
JOIN AA79B54T00 ON ANYO_054 = ANYO_051 AND NUM_EXP_054 = NUM_EXP_051
LEFT JOIN AA79BB7T00 ON TIPO_ENTIDAD_B7 = TIPO_ENTIDAD_054 AND ID_ENTIDAD_B7 = ID_ENTIDAD_054
LEFT JOIN AA79B53T00 ON ANYO_053 = ANYO_051 AND NUM_EXP_053 = NUM_EXP_051
LEFT JOIN AA79B52T00 ON ANYO_052 = ANYO_051 AND NUM_EXP_052 = NUM_EXP_051
LEFT JOIN AA79B67T00 ON ID_067 = ID_RECHAZO_059
LEFT JOIN AA79BA1T00 ON ID_0A1 = ID_ANULACION_059
LEFT JOIN (SELECT DISTINCT estadoActual.ANYO_059, estadoActual.NUM_EXP_059, 
    MIN(estadoEnCurso.FECHA_ALTA_059) OVER (PARTITION BY estadoEnCurso.ANYO_059, estadoEnCurso.NUM_EXP_059) fechaEstado
    FROM AA79B59T00 estadoActual
    JOIN AA79B51T00 expEstado ON estadoActual.ANYO_059 = expEstado.ANYO_051 AND estadoActual.NUM_EXP_059 = expEstado.NUM_EXP_051 AND estadoActual.id_estado_bitacora_059 = expEstado.estado_bitacora_051
    JOIN AA79B59T00 estadoEnCurso ON estadoEnCurso.ANYO_059 = expEstado.ANYO_051 AND estadoEnCurso.NUM_EXP_059 = expEstado.NUM_EXP_051 AND estadoEnCurso.ID_ESTADO_EXP_059 = 3
    WHERE ANYO_051 >= 2019 AND estadoActual.ID_ESTADO_EXP_059 in (4,5,6,7)) fechaEnCurso ON  fechaEnCurso.ANYO_059 = ANYO_051 AND fechaEnCurso.NUM_EXP_059 = NUM_EXP_051  --  JOIN PARA OBTENER LA FECHA EN LA QUE EL EXPEDIENTE ENTRA EN CURSO
LEFT JOIN (SELECT ANYO_081, NUM_EXP_081, FECHA_ASIGNACION_081, RECURSO_ASIGNACION_081, NUM_INTERPRETES_089
                , ROW_NUMBER() OVER (PARTITION BY ANYO_081, NUM_EXP_081 ORDER BY FECHA_ASIGNACION_081) RN_TAREA
             FROM AA79B81T00
            LEFT JOIN AA79B89T00 ON ID_TAREA_081 = ID_TAREA_089
             ) primeraAsignacion ON primeraAsignacion.ANYO_081 = ANYO_051 AND primeraAsignacion.NUM_EXP_081 = NUM_EXP_051 AND RN_TAREA = 1
LEFT JOIN (SELECT ANYO_056, NUM_EXP_056, ID_DOC_056, TIPO_DOCUMENTO_056, NUM_PAL_IZO_056,  FECHA_ALTA_056
                , ROW_NUMBER() OVER (PARTITION BY ANYO_056, NUM_EXP_056 ORDER BY FECHA_ALTA_056) RN_DOCU
             FROM AA79B56T00 
            WHERE ID_DOC_REL_056 is null AND CLASE_DOCUMENTO_056 in (1,2)) ON ANYO_056 = ANYO_051 AND NUM_EXP_056 = NUM_EXP_051 AND RN_DOCU = 1
LEFT JOIN (SELECT ANYO_081, NUM_EXP_081, AVG(POR_USO_EUSKERA_082) POR_EUSKERA
 FROM AA79B81T00 
 JOIN AA79B82T00 ON ID_TAREA_081 = ID_TAREA_082 AND ID_TIPO_TAREA_081 = 8 group by ANYO_081, NUM_EXP_081
 ) porcentajeEuskera ON porcentajeEuskera.ANYO_081 = ANYO_051 AND porcentajeEuskera.NUM_EXP_081 = NUM_EXP_051 
JOIN AA79B00T00 BOE ON ID_000 = 1
JOIN aa79b03t00 NUM_PALABRAS ON id_003 = 0
WHERE ANYO_051 >= 2019 AND ID_ESTADO_EXP_059 in (4,5,6,7)
UNION ALL
SELECT ANYO
, NUM_EXP
, MES
, QUINCENA
, DIA
, ESTADO
, TIPO_EXP
, EXP_CORREDACCION
, ABANDONADO
, TIPO_SOLICITANTE
, SOLICITANTE
, PUBLICACION
, TIPO_TRADUCTOR
, TIPO_REVISOR
, TIPO_INTERPRETE
, TIPO_INTERPRETACION
, TIPO_DOCUMENTO
, PLAZO
, NUM_PALABRAS
, TIPO_PROYECTO
, SUBCONTRATADO
, MAS_1_INTERPRETE
, PORCEN_EUSKERA
, TIPO_DOCUMENTAL
, TIPO_ANULACION
, TIPO_RECHAZO
, FACTURABLE
, MARCA_PRISA
, RECARGO
, IDIOMA
, PRESUPUESTO
, DIAS_TRABAJO
, HORAS_TRABAJO
, TIEMPO_PREVISTO
, TIEMPO_REALIZACION
, DIAS_RETRASO
, DIAS_DURACION
, HORAS_DURACION
FROM R75O30T00
;

