CREATE OR REPLACE VIEW AA79O08V00 AS
    SELECT 1 COD_TIPO_TRADUC
         , 'IZO' DESC_TIPO_TRADUC
      FROM DUAL
    UNION ALL
    SELECT 2
         , 'Hornitzailea'
      FROM DUAL
    UNION ALL
    SELECT 3
         , 'Biak'
      FROM DUAL;