CREATE OR REPLACE VIEW AA79O16V00 AS
    SELECT 1 COD_TIPO_REVISOR
         , 'IZO' DESC_TIPO_REVISOR
      FROM DUAL
    UNION ALL
    SELECT 2
         , 'Hornitzailea'
      FROM DUAL
    UNION ALL
    SELECT 3
         , 'Biak'
      FROM DUAL;