CREATE OR REPLACE VIEW R75O30V00 AS
SELECT 
  T30_ANYO AS ANYO
, T30_N_EXP AS NUM_EXP
, EXTRACT(MONTH FROM T30_FEC_SOLI) AS MES
, CASE WHEN EXTRACT(day FROM T30_FEC_SOLI) <= 15 THEN 1 ELSE 2 END AS QUINCENA
, MOD(TO_CHAR(T30_FEC_SOLI, 'J'), 7)+1 AS DIA
, CASE WHEN T30_RECHAZADO = 1 THEN 2
  ELSE 1 END AS ESTADO
, DECODE(T30_COD_TIPO_EXP,'2','R','3','T','4','I') AS TIPO_EXP
, 0 AS EXP_CORREDACCION
, 0 AS ABANDONADO
, CASE WHEN TIPO_B7 IS NOT NULL THEN TIPO_B7
       WHEN NVL(TIPO_X54,'B') = 'L' THEN 6
       WHEN NVL(TIPO_X54,'B') = 'E' THEN 1
       WHEN NVL(TIPO_X54,'B') = 'B' THEN 2
  END AS TIPO_SOLICITANTE
, NVL(TIPO_X54,'B') || NVL(ID_X54,570) AS SOLICITANTE
, CASE WHEN t32_BOPV = 1 THEN 1
	   ELSE 3 END AS PUBLICACION
, CASE WHEN T30_COD_TIPO_EXP = 3 THEN DECODE(T12_COD_TIPO_RECURSO,1,1,4,2,3) ELSE NULL END TIPO_TRADUCTOR
, CASE WHEN T30_COD_TIPO_EXP = 2 THEN DECODE(T12_COD_TIPO_RECURSO,1,1,4,2,3) ELSE NULL END TIPO_REVISOR
, CASE WHEN T30_COD_TIPO_EXP = 4 THEN DECODE(T12_COD_TIPO_RECURSO,1,1,4,2,3) ELSE NULL END TIPO_INTERPRETE
, DECODE(T31_TIPO_INTER, 5, 0, 0, NULL, T31_TIPO_INTER) AS TIPO_INTERPRETACION
, NULL AS TIPO_DOCUMENTO
, CASE WHEN FECHA_ENTREGA is not null and TRUNC(T32_FEC_ENTR_IVAP) = TRUNC(FECHA_ENTREGA) THEN 1 
       WHEN FECHA_ENTREGA is not null and TRUNC(T32_FEC_ENTR_IVAP) < TRUNC(FECHA_ENTREGA) THEN 2
       WHEN FECHA_ENTREGA is not null and TRUNC(T32_FEC_ENTR_IVAP) > TRUNC(FECHA_ENTREGA) THEN 3 
       ELSE null 
  END AS PLAZO
, PALABRAS AS NUM_PALABRAS
, CASE WHEN PALABRAS > 1000 THEN 1 ELSE 0 END AS TIPO_PROYECTO
, 1 AS SUBCONTRATADO
, CASE WHEN T31_NUM_INTER > 1 THEN 1 ELSE 0 END AS MAS_1_INTERPRETE
, T31_POR_EUSK AS PORCEN_EUSKERA
, NVL(T36_COD_TIPO_DOCUMENTO, T39_COD_TIPO_DOCUMENTO) AS TIPO_DOCUMENTAL
, NULL AS TIPO_ANULACION
, NULL AS TIPO_RECHAZO
, T30_FACTURABLE AS FACTURABLE
, T32_URGENCIA AS MARCA_PRISA
, T32_DIFICULTAD AS RECARGO
, NULLIF(T32_IDIOMA, '0') AS IDIOMA
, T30_PPTO AS PRESUPUESTO
, CASE WHEN FECHA_ENTREGA is not null THEN R75B.DIAS_ENTRE_FECHAS_ATENCION (T26_FEC_ASIGNACION, FECHA_ENTREGA ) ELSE null END DIAS_TRABAJO
, CASE WHEN FECHA_ENTREGA is not null THEN R75B.HORAS_ENTRE_FECHAS_ATENCION (T26_FEC_ASIGNACION, FECHA_ENTREGA) ELSE null END HORAS_TRABAJO
, CASE WHEN FECHA_ENTREGA is not null THEN R75B.HORAS_ENTRE_FECHAS_ATENCION (T26_FEC_INI_PREV, T32_FEC_ENTR_IVAP) ELSE null END TIEMPO_PREVISTO
, CASE WHEN FECHA_ENTREGA is not null THEN R75B.HORAS_ENTRE_FECHAS_ATENCION (T26_FEC_ASIGNACION, FECHA_ENTREGA) ELSE null END  TIEMPO_REALIZACION
, CASE WHEN FECHA_ENTREGA is not null AND TRUNC(T32_FEC_ENTR_IVAP) < TRUNC(FECHA_ENTREGA) THEN R75B.DIAS_ENTRE_FECHAS_ATENCION(T32_FEC_ENTR_IVAP, FECHA_ENTREGA) ELSE null END DIAS_RETRASO
, CASE WHEN FECHA_ENTREGA is not null THEN R75B.DIAS_ENTRE_FECHAS_ATENCION (T30_FEC_SOLI, FECHA_ENTREGA ) ELSE null END DIAS_DURACION
, CASE WHEN FECHA_ENTREGA is not null THEN R75B.HORAS_ENTRE_FECHAS_ATENCION(T30_FEC_SOLI, FECHA_ENTREGA ) ELSE null END HORAS_DURACION
FROM R75B.R7530T00
JOIN (SELECT T30_ANYO ANYO, T30_N_EXP EXP, MAX(T30_FASE) FASE
        FROM R75B.R7530T00
        GROUP BY T30_ANYO, T30_N_EXP) ON T30_ANYO = ANYO AND T30_N_EXP = EXP AND T30_FASE = FASE
LEFT JOIN CODR75X54J ON t30_cod_solicitante = ID_R75
LEFT JOIN AA79BB7T00 ON TIPO_ENTIDAD_B7 = NVL(TIPO_X54,'B') AND ID_ENTIDAD_B7 = NVL(ID_X54,570)
LEFT JOIN (SELECT T39_ANYO, T39_N_EXP
        , SUM(COALESCE(NULLIF(T39_IZO_TOT_PAL, 0), NULLIF(T39_TRADOS_TOT_PAL, 0), T39_TOT_PAL)) OVER (PARTITION BY T39_ANYO, T39_N_EXP) PALABRAS
        , T39_COD_TIPO_DOCUMENTO
        , MAX(T39_FEC_ENVIO) OVER (PARTITION BY T39_ANYO, T39_N_EXP) FECHA_ENTREGA
        , ROW_NUMBER() OVER (PARTITION BY T39_ANYO, T39_N_EXP ORDER BY T39_COD_ORIG) RN
        FROM R75B.R7539T00) ON T30_ANYO = T39_ANYO AND T30_N_EXP = T39_N_EXP AND RN = 1
LEFT JOIN (select T26_ANYO, T26_N_EXP, T12_COD_TIPO_RECURSO
		, ROW_NUMBER() OVER (PARTITION BY T26_ANYO, T26_N_EXP ORDER BY T26_COD_ORIG, T26_COD_TRAB) RN2
        from R75B.R7526T00
        JOIN R75B.R7512T00 ON T12_COD_RECURSO = T26_COD_RECURSO
        where t26_resp = 1) A ON T30_ANYO = A.T26_ANYO AND T30_N_EXP = A.T26_N_EXP AND A.RN2 = 1
LEFT JOIN (select T26_ANYO, T26_N_EXP
        , MIN(T26_FEC_ASIGNACION) T26_FEC_ASIGNACION
        , MAX(T26_FEC_INI_PREV) T26_FEC_INI_PREV        
        from R75B.R7526T00
        JOIN R75B.R7512T00 ON T12_COD_RECURSO = T26_COD_RECURSO
        GROUP BY T26_ANYO, T26_N_EXP) B ON T30_ANYO = B.T26_ANYO AND T30_N_EXP = B.T26_N_EXP
LEFT JOIN R75B.R7531S00 ON T31_ANYO = T30_ANYO AND T31_FASE = T30_FASE AND T31_N_EXP = T30_N_EXP
LEFT JOIN R75B.R7532T00 ON T32_ANYO = T30_ANYO AND T32_FASE = T30_FASE AND T32_N_EXP = T30_N_EXP
LEFT JOIN R75O36T00 ON T39_COD_TIPO_DOCUMENTO + 900 = T36_COD_TIPO_DOCUMENTO
WHERE T30_ANYO <= 2018
AND CASE WHEN T30_FASE = 5 THEN 1
WHEN T30_RECHAZADO = 1 THEN 1
ELSE 0 END = 1;
