package com.ejie.aa79b.dao;

import com.ejie.aa79b.model.ConfigCalculoPresupuesto;

/**
 * ConfigCalculoPresupuestoDao generated by UDA, 05-dic-2017 15:17:18.
 * @author UDA
 */

public interface ConfigCalculoPresupuestoDao extends GenericoDao<ConfigCalculoPresupuesto>{
	
}

