package com.ejie.aa79b.dao;

import java.util.List;

import com.ejie.aa79b.model.DatosTareaTradosDocs;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * DatosTareaTradosDocsDao generated by UDA, 19-jun-2018 13:27:18.
 * 
 * @author UDA
 */

public interface DatosTareaTradosDocsDao extends GenericoDao<DatosTareaTradosDocs> {

	/**
	 * 
	 * @param filterDocTareaTrados
	 *            DatosTareaTradosDocs
	 * @param jqGridRequestDto
	 *            JQGridRequestDto
	 * @return List<DatosTareaTradosDocs>
	 */
	List<DatosTareaTradosDocs> getDocsTareaTrados(DatosTareaTradosDocs filterDocTareaTrados,
			JQGridRequestDto jqGridRequestDto);

}
