package com.ejie.aa79b.dao;

import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import com.ejie.aa79b.model.DocumentosExpediente;
import com.ejie.aa79b.model.EntradaDatosDocumento;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.FicheroDocExp;
import com.ejie.aa79b.model.Tareas;
import com.ejie.aa79b.model.webservices.Aa79bDocumentoExpediente;
import com.ejie.aa79b.model.webservices.Aa79bFicheroDocExp;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * DocumentosExpedienteDao generated by UDA, 06-feb-2018 10:13:42.
 *
 * @author UDA
 */

public interface DocumentosExpedienteDao extends GenericoDao<DocumentosExpediente> {

	/**
	 * add, aniade el doc
	 *
	 * @param documentosexpediente DocumentosExpediente
	 * @param x                    int
	 * @return DocumentosExpediente
	 */
	DocumentosExpediente add(DocumentosExpediente documentosexpediente, int x);

	/**
	 * update, modifica el doc
	 *
	 * @param documentosexpediente DocumentosExpediente
	 * @param x                    int
	 * @return DocumentosExpediente
	 */
	DocumentosExpediente update(DocumentosExpediente documentosexpediente, int x);

	List<String> getOidsABorrar(BigDecimal elId);

	Integer sumatorioPalabrasExpediente(DocumentosExpediente bean);

	List<Aa79bFicheroDocExp> getAa79bDocumentoExpediente(EntradaDatosDocumento bean);

	List<Aa79bDocumentoExpediente> getAa79bDocumentosExpediente(Aa79bDocumentoExpediente bean, Locale locale);

	/**
	 *
	 * @param anyo    Long
	 * @param numExp  Integer
	 * @param idTarea
	 * @return Map<String, BigDecimal>
	 */
	Map<String, BigDecimal> getMapaDocumentosExpediente(Long anyo, Integer numExp, BigDecimal idTarea);

	/**
	 *
	 * @param documentosExpedienteFiltro DocumentosExpediente
	 * @return List<DocumentosExpediente>
	 */
	List<DocumentosExpediente> findAllEstudioSubsanacion(Long anyo, Integer numExp, Long idTarea);

	/**
	 * Obtiene los datos del fichero
	 *
	 * @param idDoc BigDecimal
	 * @return FicheroDocExp
	 */
	FicheroDocExp findDatosFichero(BigDecimal idDoc);

	/**
	 * @param documentosExpediente DocumentosExpediente
	 * @param dni                  String, dni del usuario conectado
	 * @param jqGridRequestDto     JQGridRequestDto
	 * @return List<DocumentosExpediente>
	 */
	List<DocumentosExpediente> findDocumentosTarea(DocumentosExpediente documentosExpediente, String dni,
			JQGridRequestDto jqGridRequestDto);

	/**
	 *
	 * @param documentosExpediente
	 * @param jqGridRequestDto
	 * @return
	 */
	List<DocumentosExpediente> findAllConFinales(DocumentosExpediente documentosExpediente, String dni,
			JQGridRequestDto jqGridRequestDto);

	/**
	 *
	 * @param documentosExpedienteFiltro
	 * @param reqEncriptado
	 * @return
	 */
	Long comprobarencriptados(DocumentosExpediente documentosExpedienteFiltro, String reqEncriptado);

	/**
	 * Comprueba si para finalizar la tarea es necesario adjuntar fichero
	 * xliff,sdlxliff o tmx
	 *
	 * @param expediente Expediente
	 * @return Boolean
	 */
	Boolean comprobarXliffObligatorio(Expediente expediente);

	/**
	 * Comprueba si para finalizar la tarea es necesario adjuntar fichero
	 * xliff,sdlxliff o tmx
	 *
	 * @param expediente Expediente
	 * @return Boolean
	 */
	Boolean comprobarXliffObligatorioAlinearPostEntrega(Tareas tarea);

	/**
	 *
	 * @param documentosExpediente
	 * @param dni
	 * @param jqGridRequestDto
	 * @return
	 */
	List<FicheroDocExp> findAllIntermedios(DocumentosExpediente documentosExpediente, String dni,
			JQGridRequestDto jqGridRequestDto);

	/**
	 *
	 * @param documentosExpediente
	 * @param dni
	 * @param jqGridRequestDto
	 * @return
	 */
	List<FicheroDocExp> findAllJustificantesIntermedios(DocumentosExpediente documentosExpediente, String dni,
			JQGridRequestDto jqGridRequestDto);

}