package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.EstadosExpediente;
import com.ejie.aa79b.model.enums.EstadoExpedienteEnum;

/**
 * EstadosExpedienteDaoImpl generated by UDA, 02-feb-2018 10:27:12.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class EstadosExpedienteDaoImpl extends GenericoDaoImpl<EstadosExpediente> implements EstadosExpedienteDao {

	protected static final String ID_ESTADOS_EXPEDIENTE = "ID_060";
	protected static final String DESC_EU_ESTADOS_EXPEDIENTE = "DESC_EU_060";
	protected static final String DESC_ES_ESTADOS_EXPEDIENTE = "DESC_ES_060";
	protected static final String DESC_ABR_EU_ESTADOS_EXPEDIENTE = "DESC_ABR_EU_060";
	protected static final String DESC_ABR_ES_ESTADOS_EXPEDIENTE = "DESC_ABR_ES_060";

	public static final String[] ORDER_BY_WHITE_LIST = new String[] { ID_ESTADOS_EXPEDIENTE, DESC_EU_ESTADOS_EXPEDIENTE,
			DESC_ES_ESTADOS_EXPEDIENTE, DESC_ABR_EU_ESTADOS_EXPEDIENTE, DESC_ABR_ES_ESTADOS_EXPEDIENTE };

	public EstadosExpedienteDaoImpl() {
		// Constructor
		super(EstadosExpediente.class);
	}

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<EstadosExpediente> rwMap = new RowMapper<EstadosExpediente>() {
		public EstadosExpediente mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			EstadosExpediente estadosExpediente = new EstadosExpediente();
			estadosExpediente.setId(resultSet.getLong(ID_ESTADOS_EXPEDIENTE));
			estadosExpediente.setDescEu(resultSet.getString(DESC_EU_ESTADOS_EXPEDIENTE));
			estadosExpediente.setDescEs(resultSet.getString(DESC_ES_ESTADOS_EXPEDIENTE));
			estadosExpediente.setDescAbrEu(resultSet.getString(DESC_ABR_EU_ESTADOS_EXPEDIENTE));
			estadosExpediente.setDescAbrEs(resultSet.getString(DESC_ABR_ES_ESTADOS_EXPEDIENTE));
			estadosExpediente.setClassStyle(resultSet.getString("CLASS_060"));

			return estadosExpediente;
		}
	};

	private RowMapper<EstadosExpediente> rwMapPK = new RowMapper<EstadosExpediente>() {
		public EstadosExpediente mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			EstadosExpediente estadosExpediente = new EstadosExpediente();
			estadosExpediente.setId(resultSet.getLong(ID_ESTADOS_EXPEDIENTE));

			return estadosExpediente;
		}
	};

	/*
	 * OPERACIONES CRUD
	 */

	/**
	 * Inserts a single row in the EstadosExpediente table.
	 *
	 * @param estadosexpediente
	 *            EstadosExpediente
	 * @return EstadosExpediente
	 */
	public EstadosExpediente add(EstadosExpediente estadosexpediente) {
		String query = "INSERT INTO AA79B60S01 (ID_060, DESC_EU_060, DESC_ES_060, DESC_ABR_EU_060, DESC_ABR_ES_060, CLASS_060) VALUES (?,?,?,?,?,?)";
		this.getJdbcTemplate().update(query, estadosexpediente.getId(), estadosexpediente.getDescEu(),
				estadosexpediente.getDescEs(), estadosexpediente.getDescAbrEu(), estadosexpediente.getDescAbrEs(),
				estadosexpediente.getClassStyle());
		return estadosexpediente;
	}

	/**
	 * Updates a single row in the EstadosExpediente table.
	 *
	 * @param estadosexpediente
	 *            EstadosExpediente
	 * @return EstadosExpediente
	 */
	public EstadosExpediente update(EstadosExpediente estadosexpediente) {
		String query = "UPDATE AA79B60S01 SET DESC_EU_060=?, DESC_ES_060=?, DESC_ABR_EU_060=?, DESC_ABR_ES_060=?, CLASS_060=? WHERE ID_060=?";
		this.getJdbcTemplate().update(query, estadosexpediente.getDescEu(), estadosexpediente.getDescEs(),
				estadosexpediente.getDescAbrEu(), estadosexpediente.getDescAbrEs(), estadosexpediente.getClassStyle(),
				estadosexpediente.getId());
		return estadosexpediente;
	}

	/**
	 * Removes a single row in the EstadosExpediente table.
	 *
	 * @param estadosexpediente
	 *            EstadosExpediente
	 * @return
	 */
	public void remove(EstadosExpediente estadosexpediente) {
		String query = "DELETE FROM AA79B60S01 WHERE ID_060=?";
		this.getJdbcTemplate().update(query, estadosexpediente.getId());
	}

	@Override
	protected String getSelect() {

		StringBuilder sbEstados = new StringBuilder();

		sbEstados.append("SELECT t1.ID_060 ID_060");
		sbEstados.append(", t1.DESC_EU_060 DESC_EU_060");
		sbEstados.append(", t1.DESC_ES_060 DESC_ES_060");
		sbEstados.append(", t1.DESC_ABR_EU_060 DESC_ABR_EU_060");
		sbEstados.append(", t1.DESC_ABR_ES_060 DESC_ABR_ES_060");
		sbEstados.append(", t1.CLASS_060 CLASS_060");
		sbEstados.append(", ").append(SqlUtils.normalizarCampoSql("t1.DESC_EU_060")).append(" AS DESCNORMEU");
		sbEstados.append(", ").append(SqlUtils.normalizarCampoSql("t1.DESC_ES_060")).append(" AS DESCNORMES");
		sbEstados.append(", ").append(SqlUtils.normalizarCampoSql("t1.DESC_ABR_EU_060")).append(" AS DESCNORMABREU");
		sbEstados.append(", ").append(SqlUtils.normalizarCampoSql("t1.DESC_ABR_ES_060")).append(" AS DESCNORMABRES");

		return sbEstados.toString();
	}

	@Override
	protected String getFrom() {
		return " FROM AA79B60S01 t1 ";
	}

	@Override
	protected RowMapper<EstadosExpediente> getRwMap() {
		return this.rwMap;
	}

	@Override
	protected String[] getOrderBy() {
		return EstadosExpedienteDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override
	protected String getPK() {
		return ID_ESTADOS_EXPEDIENTE;
	}

	@Override
	protected RowMapper<EstadosExpediente> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override
	protected String getWherePK(EstadosExpediente bean, List<Object> params) {
		params.add(bean.getId());
		return " WHERE t1.ID_060 = ?";
	}

	@Override
	protected String getWhere(EstadosExpediente bean, List<Object> params) {
		StringBuilder where = new StringBuilder(EstadosExpedienteDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual("t1.ID_060", bean.getId(), params));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_ES_060", bean.getDescEs(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_EU_060", bean.getDescEu(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_ABR_ES_060", bean.getDescEs(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_ABR_EU_060", bean.getDescEu(), params, false));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.CLASS_060", bean.getClassStyle(), params, false));

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put("query", where);
		mapWhere.put("params", params);

		return where.toString();
	}

	@Override
	protected String getWhereLike(EstadosExpediente bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(EstadosExpedienteDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual("t1.ID_060", bean.getId(), params));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_ES_060", bean.getDescEs(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_EU_060", bean.getDescEu(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_ABR_ES_060", bean.getDescEs(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.DESC_ABR_EU_060", bean.getDescEu(), params, startsWith));
		where.append(SqlUtils.generarWhereLikeNormalizado("t1.CLASS_060", bean.getClassStyle(), params, false));

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put("query", where);
		mapWhere.put("params", params);

		return where.toString();
	}

	@Override()
	public List<EstadosExpediente> findAllSinAltaExp() {
		String filtroEstadosExp = String.valueOf(EstadoExpedienteEnum.ALTA_EXPEDIENTE.getValue());
		return findAllEstadosExp(filtroEstadosExp, true);
	}

	@Override()
	public List<EstadosExpediente> findAllEstadosExpRechAnulado() {
		String filtroEstadosExp = String.valueOf(EstadoExpedienteEnum.RECHAZADO.getValue()) + DaoConstants.SIGNO_COMA
				+ String.valueOf(EstadoExpedienteEnum.ANULADO.getValue());
		return findAllEstadosExp(filtroEstadosExp, false);
	}

	@Override()
	public List<EstadosExpediente> findAllEstadosExpEnEstudioCurso() {
		String filtroEstadosExp = String.valueOf(EstadoExpedienteEnum.EN_ESTUDIO.getValue()) + DaoConstants.SIGNO_COMA
				+ String.valueOf(EstadoExpedienteEnum.EN_CURSO.getValue());
		return findAllEstadosExp(filtroEstadosExp, false);
	}

	@Override
	public List<EstadosExpediente> findAllEstadosExpEnCurso() {
		String filtroEstadosExp = String.valueOf(EstadoExpedienteEnum.EN_CURSO.getValue());
		return findAllEstadosExp(filtroEstadosExp, false);
	}

	private List<EstadosExpediente> findAllEstadosExp(String filtroEstadosExp, boolean clausulaNot) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(this.getSelect());
		query.append(this.getFrom());
		query.append(EstadosExpedienteDaoImpl.DEFAULT_WHERE);
		query.append(DaoConstants.AND + DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_060);
		if (clausulaNot) {
			query.append(DaoConstants.NOT);
		}
		query.append(
				DaoConstants.IN + DaoConstants.ABRIR_PARENTESIS + filtroEstadosExp + DaoConstants.CERRAR_PARENTESIS);

		return this.getJdbcTemplate().query(query.toString(), this.getRwMap(), params.toArray());
	}

	@Override
	public List<EstadosExpediente> getEstados(List<Integer> listaEstados) {
		List<Object> paramsE = new ArrayList<Object>();
		StringBuilder queryE = new StringBuilder(this.getSelect());
		queryE.append(this.getFrom());
		queryE.append(DaoConstants.WHERE_1_1);
		if (listaEstados != null && !listaEstados.isEmpty()) {
			queryE.append(SqlUtils.generarWhereIn(DaoConstants.T1_MINUSCULA_PUNTO + DBConstants.ID_060, listaEstados,
					paramsE));
		}

		return this.getJdbcTemplate().query(queryE.toString(), this.getRwMap(), paramsE.toArray());
	}

	@Override
	public List<EstadosExpediente> findAllSinEstados(List<Integer> listaEstados) {
		StringBuilder estados = new StringBuilder(EstadosExpedienteDaoImpl.STRING_BUILDER_INIT);
		boolean esPrimero = true;
		for (Integer iEstado : listaEstados) {
			if (esPrimero) {
				esPrimero = false;
			} else {
				estados.append(",");
			}
			estados.append(iEstado);

		}
		return findAllEstadosExp(estados.toString(), true);
	}

}
