package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.model.HorariosLaborales;

/**
 * HorariosLaboralesDaoImpl generated by UDA, 21-nov-2017 14:44:52.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class HorariosLaboralesDaoImpl extends GenericoDaoImpl<HorariosLaborales> implements HorariosLaboralesDao {
	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	protected static final String ID038 = "ID038";
	protected static final String ID_038 = "ID_038";
	protected static final String[] ORDER_BY_WHITE_LIST = new String[] { ID038, "INDACTIVO038", "INDACTIVOEU",
			"INDACTIVOES" };

	/*
	 * ROW_MAPPERS
	 */
	private RowMapper<HorariosLaborales> rwMap = new RowMapper<HorariosLaborales>() {
		@Override()
		public HorariosLaborales mapRow(ResultSet resultSet, int rowNum) throws SQLException {

			HorariosLaborales horariosLaborales = new HorariosLaborales(resultSet.getLong(ID038),
					resultSet.getString("INDACTIVO038"));
			horariosLaborales.setIndActivoEs(resultSet.getString("INDACTIVOES"));
			horariosLaborales.setIndActivoEu(resultSet.getString("INDACTIVOEU"));
			return horariosLaborales;
		}
	};

	private RowMapper<HorariosLaborales> rwMapPK = new RowMapper<HorariosLaborales>() {
		@Override()
		public HorariosLaborales mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			return new HorariosLaborales(resultSet.getLong(ID038));
		}
	};

	/**
	 * Constructor
	 */
	public HorariosLaboralesDaoImpl() {
		super(HorariosLaborales.class);
	}

	@Override()
	public HorariosLaborales add(HorariosLaborales horarioslaborales) {

		String queryID = "SELECT AA79B38Q00.NEXTVAL from dual";
		long elId = this.getJdbcTemplate().queryForObject(queryID, Long.class);

		String query = "INSERT INTO AA79B38S01 (ID_038, IND_ACTIVO_038) VALUES (?,?)";
		this.getJdbcTemplate().update(query, elId,
				(horarioslaborales.getIndActivo038() != null) ? horarioslaborales.getIndActivo038() : "N");
		horarioslaborales.setId038(elId);
		return horarioslaborales;
	}

	@Override()
	public HorariosLaborales update(HorariosLaborales horarioslaborales) {
		String query = "UPDATE AA79B38S01 SET IND_ACTIVO_038=? WHERE ID_038=?";
		this.getJdbcTemplate().update(query,
				(horarioslaborales.getIndActivo038() != null) ? horarioslaborales.getIndActivo038() : "N",
				horarioslaborales.getId038());
		return horarioslaborales;
	}

	@Override()
	public void remove(HorariosLaborales horarioslaborales) {
		String query = "DELETE FROM AA79B38S01 WHERE ID_038=?";
		this.getJdbcTemplate().update(query, horarioslaborales.getId038());
	}

	@Override()
	protected String getSelect() {
		Locale es = new Locale(Constants.LANG_CASTELLANO);
		Locale eu = new Locale(Constants.LANG_EUSKERA);
		StringBuilder sb = new StringBuilder();

		sb.append("SELECT t1.ID_038 ID038, t1.IND_ACTIVO_038 INDACTIVO038");

		sb.append(", DECODE(t1.IND_ACTIVO_038, '").append(Constants.SI).append("', '")
				.append(this.msg.getMessage("comun.si", null, es)).append("', '").append(Constants.NO).append("', '")
				.append(this.msg.getMessage("comun.no", null, es)).append("') AS INDACTIVOES");
		sb.append(", DECODE(t1.IND_ACTIVO_038, '").append(Constants.SI).append("', '")
				.append(this.msg.getMessage("comun.si", null, eu)).append("', '").append(Constants.NO).append("', '")
				.append(this.msg.getMessage("comun.no", null, eu)).append("') AS INDACTIVOEU");

		return sb.toString();
	}

	@Override()
	protected String getFrom() {
		return " FROM AA79B38S01 t1 ";
	}

	@Override()
	protected RowMapper<HorariosLaborales> getRwMap() {
		return this.rwMap;
	}

	@Override()
	protected String[] getOrderBy() {
		return HorariosLaboralesDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override()
	protected String getPK() {
		return ID_038;
	}

	@Override()
	protected RowMapper<HorariosLaborales> getRwMapPK() {
		return this.rwMapPK;
	}

	@Override()
	protected String getWherePK(HorariosLaborales bean, List<Object> params) {
		params.add(bean.getId038());
		return " WHERE t1.ID_038 = ?";
	}

	@Override()
	protected String getWhere(HorariosLaborales bean, List<Object> params) {

		StringBuilder where = new StringBuilder(HorariosAtencionDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_038, bean.getId038(), params));
		where.append(SqlUtils.generarWhereIgual("IND_ACTIVO_038", bean.getIndActivo038(), params));
		return where.toString();
	}

	@Override()
	protected String getWhereLike(HorariosLaborales bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(HorariosAtencionDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ID_038, bean.getId038(), params));
		where.append(SqlUtils.generarWhereIgual("IND_ACTIVO_038", bean.getIndActivo038(), params));
		return where.toString();
	}
}
