package com.ejie.aa79b.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.dao.support.DataAccessUtils;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.common.SqlUtils;
import com.ejie.aa79b.dao.mapper.DetalleAlbaranRowMapper;
import com.ejie.aa79b.dao.mapper.TareasAlbaranRowMapper;
import com.ejie.aa79b.model.Albaran;
import com.ejie.aa79b.model.DatosPagoProveedores;
import com.ejie.aa79b.model.enums.TipoTareaGestionAsociadaEnum;
import com.ejie.aa79b.utils.DAOUtils;
import com.ejie.x38.dto.JQGridRequestDto;

/**
 * facturacionDaoImpl generated by UDA, 10/out/2018 17:43:55.
 * 
 * @author UDA
 */

@Repository
@Transactional
public class ServicioActualizacionAlbaranDaoImpl extends GenericoDaoImpl<Albaran>
		implements ServicioActualizacionAlbaranDao {

	@Autowired()
	private ReloadableResourceBundleMessageSource msg;
	protected static final String ALBARAN = "albaran";
	protected static final String TAREA = "tarea";
	protected static final String TAREAFACT = "tareaFact";
	protected static final String TAREAREVPAGO = "tareaRevPago";
	protected static final String PAGOPROVEEDOR = "pagoProveedor";
	protected static final String LOTES = "lotes";
	protected static final String X54JAPI_PROVEEDORES = "x54jProveedores";
	protected static final String TIPOSTAREA = "tiposTarea";
	protected static final String QUERY = "query";
	protected static final String PARAMS = "params";
	protected static final String PUNTO_ID_TAREA_081_IGUAL = ".ID_TAREA_081 = ";

	public static final String[] ORDER_BY_WHITE_LIST = new String[] { DBConstants.IDALBARAN, DBConstants.REFALBARAN,
			DBConstants.FECHAALTA, DBConstants.HORAALTA, DBConstants.ESTADO, DBConstants.DESCES, DBConstants.DESCEU,
			DBConstants.IMPORTEFACTURA, "IMPORTEPREVISTO", "ANYONUMEXPCONCATENADO" };

	public ServicioActualizacionAlbaranDaoImpl(Class<Albaran> type) {
		super(type);
	}

	public ServicioActualizacionAlbaranDaoImpl() {
		super(Albaran.class);
	}

	private RowMapper<Albaran> rwMap = new RowMapper<Albaran>() {
		@Override
		public Albaran mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			Albaran albaran = new Albaran();
			albaran.setIdAlbaran(resultSet.getBigDecimal(DBConstants.IDALBARAN));
			albaran.setRefAlbaran(resultSet.getString(DBConstants.REFALBARAN));
			albaran.setFechaAlta(resultSet.getDate(DBConstants.FECHAALTA));
			albaran.setHoraAlta(resultSet.getString(DBConstants.HORAALTA));
			albaran.setEstado(resultSet.getInt(DBConstants.ESTADO));
			albaran.setDescEstadoEs(resultSet.getString(DBConstants.DESCES));
			albaran.setDescEstadoEu(resultSet.getString(DBConstants.DESCEU));
			albaran.setImporteFactura(resultSet.getBigDecimal("IMPORTEFACTURA"));
			albaran.setImportePrevisto(resultSet.getBigDecimal("IMPORTEPREVISTO"));
			return albaran;
		}
	};

	private RowMapper<Albaran> rwMapPk = new RowMapper<Albaran>() {
		@Override
		public Albaran mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			Albaran albaran = new Albaran();
			albaran.setIdAlbaran(resultSet.getBigDecimal(DBConstants.IDALBARAN));
			return albaran;
		}
	};

	private RowMapper<Albaran> rwMapDetalleAlbaran = new DetalleAlbaranRowMapper();

	private RowMapper<Albaran> rwMapAlbaranTareas = new RowMapper<Albaran>() {
		@Override
		public Albaran mapRow(ResultSet resultSet, int rowNum) throws SQLException {
			Albaran albaran = new Albaran();
			albaran.setIdAlbaran(resultSet.getBigDecimal(DBConstants.IDALBARAN));
			albaran.setRefAlbaran(resultSet.getString(DBConstants.REFALBARAN));
			albaran.setEstado(resultSet.getInt(DBConstants.ESTADO));
			albaran.setNumTareasAsoc(resultSet.getInt("NUMTAREASASOC"));
			return albaran;
		}
	};

	private RowMapper<DatosPagoProveedores> rwMapTareasAlbaran = new TareasAlbaranRowMapper();

	@Override
	protected String getSelect() {
		StringBuilder query = new StringBuilder();
		Locale es = new Locale("es");
		Locale eu = new Locale("eu");

		query.append(DaoConstants.SELECT);
		query.append(DaoConstants.DISTINCT + ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.ID_099
				+ DaoConstants.BLANK + DBConstants.IDALBARAN);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.REF_ALBARAN_099 + DaoConstants.BLANK
				+ DBConstants.REFALBARAN);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(
				ALBARAN + DaoConstants.SIGNO_PUNTO + "FECHA_ALTA_099" + DaoConstants.BLANK + DBConstants.FECHAALTA);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.TO_CHAR + DaoConstants.ABRIR_PARENTESIS + ALBARAN + DaoConstants.SIGNO_PUNTO
				+ "FECHA_ALTA_099" + DaoConstants.SIGNO_COMA + DaoConstants.FORMATO_HORA
				+ DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.BLANK + DBConstants.HORAALTA);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(
				ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.ESTADO_099 + DaoConstants.BLANK + DBConstants.ESTADO);
		query.append(DaoConstants.BLANK);
		query.append(DAOUtils.getDecodeAcciones(ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.ESTADO_099,
				DBConstants.DESCES, this.msg, "EstadoAlbaranEnum", es));
		query.append(DAOUtils.getDecodeAcciones(ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.ESTADO_099,
				DBConstants.DESCEU, this.msg, "EstadoAlbaranEnum", eu));
		query.append(", NVL(albaran.IMPORTE_FACTURA_099, 0) IMPORTEFACTURA");
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.ABRIR_PARENTESIS + DBConstants.SELECT + DaoConstants.SUM_ABRIR_PARENTESIS
				+ "IMPORTE_TOTAL_094" + DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.FROM + DBConstants.TABLA_94);
		query.append(DaoConstants.WHERE + "COD_ALBARAN_094" + DaoConstants.SIGNOIGUAL + ALBARAN
				+ DaoConstants.SIGNO_PUNTO + "ID_099" + DaoConstants.CERRAR_PARENTESIS + "IMPORTEPREVISTO");
		return query.toString();
	}

	@Override
	protected String getFrom() {
		StringBuilder fromActAlbaran = new StringBuilder();

		fromActAlbaran.append(DaoConstants.FROM + DBConstants.TABLA_99 + DaoConstants.BLANK + ALBARAN);
		fromActAlbaran.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_94);
		fromActAlbaran.append(DaoConstants.BLANK);
		fromActAlbaran.append(PAGOPROVEEDOR + DaoConstants.ON);
		fromActAlbaran.append(PAGOPROVEEDOR + ".COD_ALBARAN_094 = " + ALBARAN + ".ID_099");
		fromActAlbaran.append(" AND pagoProveedor.IND_ALBARAN_094 = '" + Constants.SI + "'");
		fromActAlbaran.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_81);
		fromActAlbaran.append(DaoConstants.BLANK);
		fromActAlbaran.append(TAREAREVPAGO + DaoConstants.ON);
		fromActAlbaran.append(TAREAREVPAGO + ".ID_TIPO_TAREA_081 = "
				+ TipoTareaGestionAsociadaEnum.REVISION_PAGO_PROVEEDOR.getValue());
		fromActAlbaran.append(DaoConstants.AND);
		fromActAlbaran.append(TAREAREVPAGO + PUNTO_ID_TAREA_081_IGUAL + PAGOPROVEEDOR + ".ID_TAREA_094");
		fromActAlbaran.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_81 + DaoConstants.BLANK + TAREAFACT);
		fromActAlbaran
				.append(DaoConstants.ON + TAREAFACT + PUNTO_ID_TAREA_081_IGUAL + TAREAREVPAGO + ".ID_TAREA_REL_081");
		fromActAlbaran.append(" AND tareaFact.IND_FACTURABLE_081  = '" + Constants.SI + "'");
		fromActAlbaran.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_29);
		fromActAlbaran.append(DaoConstants.BLANK);
		fromActAlbaran.append(LOTES + DaoConstants.ON);
		fromActAlbaran.append(ALBARAN + ".ID_LOTE_099 = " + LOTES + ".ID_LOTE_029");

		return fromActAlbaran.toString();

	}

	private String getSelectDetalleAlbaran() {
		StringBuilder query = new StringBuilder();

		query.append(this.getSelect() + DaoConstants.SIGNO_COMA);
		query.append(ALBARAN + DaoConstants.SIGNO_PUNTO + "ID_LOTE_099" + DaoConstants.BLANK + DBConstants.IDLOTE);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(
				LOTES + DaoConstants.SIGNO_PUNTO + "NOMBRE_LOTE_029" + DaoConstants.BLANK + DBConstants.NOMBRELOTE);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(LOTES + DaoConstants.SIGNO_PUNTO + "IMPORTE_ASIGNADO_029" + DaoConstants.BLANK
				+ DBConstants.IMPORTEASIGNADO);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(LOTES + DaoConstants.SIGNO_PUNTO + "IMPORTE_CONSUMIDO_029" + DaoConstants.BLANK
				+ DBConstants.IMPORTECONSUMIDO);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(
				ALBARAN + DaoConstants.SIGNO_PUNTO + "REF_FACTURA_099" + DaoConstants.BLANK + DBConstants.REFFACTURA);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.ABRIR_PARENTESIS + DBConstants.SELECT + DaoConstants.COUNT
				+ DaoConstants.ABRIR_PARENTESIS + "*" + DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.FROM + DBConstants.TABLA_94);
		query.append(DaoConstants.WHERE + "COD_ALBARAN_094" + DaoConstants.SIGNOIGUAL + ALBARAN
				+ DaoConstants.SIGNO_PUNTO + DBConstants.ID_099 + DaoConstants.CERRAR_PARENTESIS + "NUMTAREASASOC");
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.ABRIR_PARENTESIS + DBConstants.SELECT + DaoConstants.COUNT
				+ DaoConstants.ABRIR_PARENTESIS + "*" + DaoConstants.CERRAR_PARENTESIS);
		query.append(DaoConstants.FROM + DBConstants.TABLA_51);
		query.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_81 + DaoConstants.ON + DBConstants.ANYO_051
				+ DaoConstants.SIGNOIGUAL + DBConstants.ANYO_081 + DaoConstants.AND + DBConstants.NUM_EXP_051
				+ DaoConstants.SIGNOIGUAL + DBConstants.NUM_EXP_081);
		query.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_94 + DaoConstants.ON + DBConstants.ID_TAREA_081
				+ DaoConstants.SIGNOIGUAL + DBConstants.ID_TAREA_094);
		query.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_99 + DaoConstants.ON + DBConstants.COD_ALBARAN_094
				+ DaoConstants.SIGNOIGUAL + DBConstants.ID_099);
		query.append(DaoConstants.WHERE + DBConstants.ID_099 + DaoConstants.SIGNOIGUAL + ALBARAN
				+ DaoConstants.SIGNO_PUNTO + DBConstants.ID_099 + DaoConstants.CERRAR_PARENTESIS + "NUMEXPASOC");
		query.append(DaoConstants.SIGNO_COMA);
		query.append("IMPORTE_PREVISTO_LOTE(lotes.ID_LOTE_029, NULL) AS IMPORTEPREVISTOLOTE");
		query.append(DaoConstants.SIGNO_COMA);
		query.append(
				"(lotes.IMPORTE_ASIGNADO_029 - (lotes.IMPORTE_CONSUMIDO_029 + IMPORTE_PREVISTO_LOTE(lotes.ID_LOTE_029, NULL))) IMPORTEDISPONIBLE");
		return query.toString();
	}

	private String getSelectTareasAlbaran() {
		StringBuilder query = new StringBuilder();

		query.append(DaoConstants.SELECT);
		query.append(
				" TAREAFACT.ANYO_081 ANYO,TAREAFACT.NUM_EXP_081 NUMEXP,SUBSTR(TAREAFACT.ANYO_081,2,4) || '/' || LPAD(TAREAFACT.NUM_EXP_081,6,'0') ANYONUMEXPCONCATENADO, ");
		query.append(TAREAFACT + ".ID_TAREA_081" + DaoConstants.BLANK + DBConstants.IDTAREA);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.DECODE + DaoConstants.ABRIR_PARENTESIS + DBConstants.TIPOSTAREA_DESC_ES_015
				+ DaoConstants.SIGNO_COMA + "'Traducir'" + DaoConstants.SIGNO_COMA + "'IT'" + DaoConstants.SIGNO_COMA
				+ "'Revisar'" + DaoConstants.SIGNO_COMA + "'BE'" + DaoConstants.CERRAR_PARENTESIS + DaoConstants.AS
				+ DBConstants.TIPOTAREADESCES + DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.DECODE + DaoConstants.ABRIR_PARENTESIS + DBConstants.TIPOSTAREA_DESC_EU_015
				+ DaoConstants.SIGNO_COMA + "'Itzuli'" + DaoConstants.SIGNO_COMA + "'IT'" + DaoConstants.SIGNO_COMA
				+ "'Berrikusi'" + DaoConstants.SIGNO_COMA + "'BE'" + DaoConstants.CERRAR_PARENTESIS + DaoConstants.AS
				+ DBConstants.TIPOTAREADESCEU + DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "NUM_TOTAL_PAL_094" + DaoConstants.BLANK
				+ DBConstants.NUMTOTALPAL);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "NUM_PAL_CONCOR_0_84_094" + DaoConstants.BLANK
				+ DBConstants.NUMPALCONCOR084);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "NUM_PAL_CONCOR_85_94_094" + DaoConstants.BLANK
				+ DBConstants.NUMPALCONCOR8594);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "NUM_PAL_CONCOR_95_100_094" + DaoConstants.BLANK
				+ DBConstants.NUMPALCONCOR95100);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(
				PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IVA_APLIC_094" + DaoConstants.BLANK + DBConstants.IVAAPLIC);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_PAL_APLIC_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTEPALAPLIC);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_TAREA_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTETAREA);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_RECARGO_FORMATO_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTERECARGOFORMATO);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_RECARGO_APREMIO_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTERECARGOAPREMIO);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_PENALIZACION_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTEPENALIZACION);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_BASE_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTEBASE);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_IVA_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTEIVA);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "IMPORTE_TOTAL_094" + DaoConstants.BLANK
				+ DBConstants.IMPORTETOTAL);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "NUM_PAL_RECARGO_FORMATO_094" + DaoConstants.BLANK
				+ DBConstants.NUMPALRECARGOFORMATO);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "POR_RECARGO_APREMIO_094" + DaoConstants.BLANK
				+ DBConstants.PORRECARGOAPREMIO);
		query.append(DaoConstants.SIGNO_COMA);
		query.append(PAGOPROVEEDOR + DaoConstants.SIGNO_PUNTO + "POR_PENALIZACION_094" + DaoConstants.BLANK
				+ DBConstants.PORPENALIZACION);
		query.append(
				" , NIVEL_CALIDAD_094 NIVELCALIDAD, POR_PENAL_CALIDAD_094 PORPENALCALIDAD, IMP_PENAL_CALIDAD_094 IMPPENALCALIDAD");

		return query.toString();
	}

	private String getFromTareasAlbaran() {

		StringBuilder from = new StringBuilder();
		from.append(DaoConstants.FROM + DBConstants.TABLA_81 + DaoConstants.BLANK + TAREAFACT);

		from.append(DaoConstants.JOIN + DBConstants.TABLA_81);
		from.append(DaoConstants.BLANK);
		from.append(TAREAREVPAGO + DaoConstants.ON);
		from.append(TAREAREVPAGO + ".ID_TIPO_TAREA_081 = "
				+ TipoTareaGestionAsociadaEnum.REVISION_PAGO_PROVEEDOR.getValue());
		from.append(DaoConstants.BLANK);
		from.append(DaoConstants.AND);
		from.append(DaoConstants.BLANK);
		from.append(TAREAFACT + PUNTO_ID_TAREA_081_IGUAL + TAREAREVPAGO + ".ID_TAREA_REL_081");

		from.append(DaoConstants.JOIN + DBConstants.TABLA_94);
		from.append(DaoConstants.BLANK);
		from.append(PAGOPROVEEDOR + DaoConstants.ON);
		from.append(TAREAREVPAGO + PUNTO_ID_TAREA_081_IGUAL + PAGOPROVEEDOR + ".ID_TAREA_094");

		from.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_99);
		from.append(DaoConstants.BLANK);
		from.append(ALBARAN + DaoConstants.ON);
		from.append(PAGOPROVEEDOR + ".COD_ALBARAN_094 = " + ALBARAN + ".ID_099");
		from.append(DaoConstants.LEFT_JOIN + DBConstants.TABLA_15);
		from.append(DaoConstants.BLANK);
		from.append(TIPOSTAREA + DaoConstants.ON);
		from.append(TAREAFACT + ".ID_TIPO_TAREA_081 = ID_015 ");

		return from.toString();
	}

	@Override
	public Albaran obtenerDatosDetalleAlbaran(Albaran albaran) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder();
		query.append(this.getSelectDetalleAlbaran());
		query.append(this.getFrom());
		query.append(DaoConstants.WHERE_1_1);
		query.append(this.getWhereLike(albaran, false, params, false));

		List<Albaran> albaranList = this.getJdbcTemplate().query(query.toString(), this.rwMapDetalleAlbaran,
				params.toArray());

		return DataAccessUtils.uniqueResult(albaranList);
	}

	private String obtenerTareasAlbaran(DatosPagoProveedores datosPagoProveedores, List<Object> params,
			boolean isCount) {
		StringBuilder query = new StringBuilder();
		if (!isCount) {
			query.append(this.getSelectTareasAlbaran());
		}
		query.append(this.getFromTareasAlbaran());
		query.append(DaoConstants.WHERE_1_1);
		query.append(this.getWhereLike(datosPagoProveedores.getAlbaran(), false, params, false));

		return query.toString();
	}

	@Override
	public Object detalleTareasAlbaran(DatosPagoProveedores datosPagoProveedores, JQGridRequestDto jqGridRequestDto,
			Boolean startsWith, Boolean isCount) {

		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder(Aa79bTareaWsDaoImpl.STRING_BUILDER_INIT);

		if (isCount) {
			query.append(DaoConstants.SELECT + " COUNT " + DaoConstants.ABRIR_PARENTESIS + DaoConstants.DISTINCT
					+ TAREAFACT + ".ID_TAREA_081" + DaoConstants.CERRAR_PARENTESIS);
			query.append(this.obtenerTareasAlbaran(datosPagoProveedores, params, true));
		} else {
			query.append(this.obtenerTareasAlbaran(datosPagoProveedores, params, false));
		}

		if (isCount) {
			return this.getJdbcTemplate().queryForObject(query.toString(), params.toArray(), Long.class);
		} else {
			return this.getJdbcTemplate().query(query.toString(), this.getRwMapTareasAlbaran(), params.toArray());
		}
	}

	@Override
	public List<Albaran> datosAlbaranTareasAsocPorIdAlbaranIn(String[] refAlbaranListString) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.SELECT);
		query.append(DBConstants.ID_099 + DaoConstants.BLANK + DBConstants.IDALBARAN + DaoConstants.SIGNO_COMA);
		query.append(
				DBConstants.REF_ALBARAN_099 + DaoConstants.BLANK + DBConstants.REFALBARAN + DaoConstants.SIGNO_COMA);
		query.append(DBConstants.ESTADO_099 + DaoConstants.BLANK + DBConstants.ESTADO + DaoConstants.SIGNO_COMA);
		query.append(DaoConstants.ABRIR_PARENTESIS + DaoConstants.SELECT + DaoConstants.COUNT
				+ DaoConstants.ABRIR_PARENTESIS + "*" + DaoConstants.CERRAR_PARENTESIS + DaoConstants.BLANK
				+ DaoConstants.FROM + DBConstants.TABLA_94);
		query.append(DaoConstants.WHERE + DBConstants.COD_ALBARAN_094 + DaoConstants.SIGNOIGUAL + DBConstants.ID_099
				+ DaoConstants.CERRAR_PARENTESIS + DaoConstants.BLANK + DBConstants.NUMTAREASASOC);
		query.append(DaoConstants.FROM + DBConstants.TABLA_99);
		query.append(DaoConstants.WHERE);
		query.append(SqlUtils.generarWhereInWithOutAnd(DBConstants.ID_099, refAlbaranListString, params));
		return this.getJdbcTemplate().query(query.toString(), this.rwMapAlbaranTareas, params.toArray());
	}

	@Override
	public void borrarAlbaran(String[] refAlbaranListString) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.DELETE);
		query.append(DaoConstants.FROM + DBConstants.TABLA_99);
		query.append(DaoConstants.WHERE);
		query.append(SqlUtils.generarWhereInWithOutAnd(DBConstants.ID_099, refAlbaranListString, params));
		this.getJdbcTemplate().update(query.toString(), params.toArray());
	}

	@Override
	public void desasociarAlbaran(String[] idTareasList) {
		List<Object> params = new ArrayList<Object>();
		StringBuilder query = new StringBuilder();
		query.append(DaoConstants.UPDATE + DBConstants.TABLA_94);
		query.append(DaoConstants.SET + DBConstants.COD_ALBARAN_094 + DaoConstants.SIGNOIGUAL + DaoConstants.NULL);
		query.append(DaoConstants.WHERE + "ID_TAREA_094 IN ");
		query.append(" ( SELECT t2.ID_TAREA_081 FROM AA79B81S01 t1 ");
		query.append(" JOIN AA79B81S01 t2 ");
		query.append(" ON t2.ID_TIPO_TAREA_081 = 11 ");
		query.append(" AND t1.ID_TAREA_081 = t2.ID_TAREA_REL_081 ");
		query.append(" JOIN AA79B94S01 t3 ");
		query.append(" ON t2.ID_TAREA_081 = t3.ID_TAREA_094 ");
		query.append(DaoConstants.WHERE);
		query.append(SqlUtils.generarWhereInWithOutAnd("t1.ID_TAREA_081", idTareasList, params));
		query.append(" )");
		this.getJdbcTemplate().update(query.toString(), params.toArray());
	}

	@Override
	protected RowMapper<Albaran> getRwMap() {
		return this.rwMap;
	}

	private RowMapper<DatosPagoProveedores> getRwMapTareasAlbaran() {
		return this.rwMapTareasAlbaran;
	}

	@Override
	protected String[] getOrderBy() {
		return ServicioActualizacionAlbaranDaoImpl.ORDER_BY_WHITE_LIST;
	}

	@Override
	protected String getPK() {
		return "ID_099";
	}

	@Override
	protected RowMapper<Albaran> getRwMapPK() {
		return this.rwMapPk;
	}

	@Override
	protected String getWherePK(Albaran bean, List<Object> params) {
		params.add(bean.getIdAlbaran());
		return "WHERE ID_099 = ? ";
	}

	@Override
	protected String getWhere(Albaran bean, List<Object> params) {
		return null;
	}

	@Override
	protected String getWhereLike(Albaran bean, Boolean startsWith, List<Object> params, Boolean search) {
		StringBuilder where = new StringBuilder(ExpedienteDaoImpl.STRING_BUILDER_INIT);
		where.append(SqlUtils.generarWhereIgual(ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.ID_099,
				bean.getIdAlbaran(), params));
		if (bean.getRefAlbaran() != null) {
			where.append(SqlUtils.generarWhereLike(ALBARAN + DaoConstants.SIGNO_PUNTO + DBConstants.REF_ALBARAN_099,
					bean.getRefAlbaran().trim(), params, false));
		}

		if (bean.getLotes() != null) {
			where.append(SqlUtils.generarWhereIgual(ALBARAN + DaoConstants.SIGNO_PUNTO + "ID_LOTE_099",
					bean.getLotes().getIdLote(), params));
		}

		if (bean.getLotes() != null && bean.getLotes().getEmpresasProveedoras() != null) {
			where.append(SqlUtils.generarWhereIgual(LOTES + DaoConstants.SIGNO_PUNTO + "ID_EMPRESA_PROV_029",
					bean.getLotes().getEmpresasProveedoras().getCodigo(), params));
		}

		Map<String, Object> mapWhere = new HashMap<String, Object>();
		mapWhere.put(QUERY, where);
		mapWhere.put(PARAMS, params);

		return where.toString();
	}

	@Override
	public List<Albaran> filterGetSelectedIds(Albaran filterAlbaran, JQGridRequestDto tableData) {
		List<Object> paramsFGSI = new ArrayList<Object>();
		StringBuilder queryFGSI = new StringBuilder(ServicioActualizacionAlbaranDaoImpl.STRING_BUILDER_INIT);
		List<String> camposIds = new ArrayList<String>();
		camposIds.add("albaran.ID_099");
		// SELECT
		queryFGSI.append(" SELECT DISTINCT albaran.ID_099 IDALBARAN ");
		// FROM
		queryFGSI.append(this.getFrom(filterAlbaran, paramsFGSI));
		// WHERE
		queryFGSI.append(GenericoDaoImpl.DEFAULT_WHERE);
		queryFGSI.append(this.getWhereLike(filterAlbaran, false, paramsFGSI, false));
		queryFGSI.append(SqlUtils.generarRupTableSelectedIds(camposIds, tableData.getMultiselection().getSelectedIds(),
				tableData.getMultiselection().getSelectedAll(), tableData.getCore().getPkToken()));

		return this.getJdbcTemplate().query(queryFGSI.toString(), this.getRwMapPK(), paramsFGSI.toArray());
	}

}
