/*
* Copyright 2011 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/
package com.ejie.x21a.service;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.x21a.dao.ExpedienteDao;
import com.ejie.x21a.model.Expediente;

/**
 *  * AlumnoServiceImpl generated by UDA, 01-mar-2012 9:33:10.
 * @author UDA
 */

@Service(value = "expedienteService")
public  class ExpedienteServiceImpl implements ExpedienteService {

	/**
    * Final static logger.
    */
	private static final  Logger logger = LoggerFactory.getLogger(ExpedienteServiceImpl.class);
	
	@Autowired
	private ExpedienteDao expedienteDao;

	@Override
	public List<Expediente> getAll() {
		return expedienteDao.getAll();
	}

	@Override
	public Boolean putFase(Expediente expediente) {
		return expedienteDao.putFase(expediente);
	}
	
}

