package com.ejie.x21a.service;


import com.ejie.x38.dto.TableRequestDto;
import java.util.ArrayList;
import java.util.List;

import com.ejie.x21a.model.NoraCalle;

/**
 *  * NoraCalleService generated by UDA, 16-ene-2012 13:17:20.
 * @author UDA
 */

public interface NoraCalleService {

	/**
	 * Inserts a single row in the Calle table.
	 *
	 * @param calle Calle
	 * @return Calle
	 */
    NoraCalle add(NoraCalle calle);

	/**
	 * Updates a single row in the Calle table.
	 *
	 * @param calle Calle
	 * @return Calle
	 */
	NoraCalle update(NoraCalle calle);

	/**
	 * Finds a single row in the Calle table.
	 *
	 * @param calle Calle
	 * @return Calle
	 */
	NoraCalle find(NoraCalle calle);

	/**
	 * Finds a List of rows in the Calle table.
	 *
	 * @param calle Calle
	 * @param tableRequestDto TableRequestDto
	 * @return List
	 */
	List<NoraCalle> findAll(NoraCalle calle, TableRequestDto tableRequestDto);

	/**
	 * Counts rows in the Calle table.
	 *
	 * @param calle Calle
	 * @return Long
	 */
	Long findAllCount(NoraCalle calle);
	
	/**
	 * Finds rows in the Calle table using like.
	 *
	 * @param calle Calle
	 * @param tableRequestDto TableRequestDto
     * @param startsWith Boolean	 
	 * @return List
	 */
	List<NoraCalle> findAllLike(NoraCalle calle, TableRequestDto tableRequestDto, Boolean startsWith) ;
  
	/**
	 * Deletes a single row in the Calle table.
	 *
	 * @param calle Calle
	 * @return 
	 */
	void remove(NoraCalle calle);
	
	/**
	 * Deletes multiple rows in the Calle table.
	 *
	 * @param calleList  ArrayList
	 * @return 
	 */	
	void removeMultiple(ArrayList<NoraCalle> calleList);    
}
