/*
* Copyright 2012 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/
package com.ejie.x21a.service;


import java.util.List;

import com.ejie.x21a.model.TaskList;
import com.ejie.x38.dto.Pagination;

/**
 * ListService generated by UDA, 14-ago-2012 12:59:39.
 * @author UDA
 */

public interface TaskListService {

	/**
	 * Inserts a single row in the List table.
	 *
	 * @param taskList List
	 * @return List
	 */
    TaskList add(TaskList taskList);
    
    /**
	 * Inserts a single row in the List table.
	 *
	 * @param taskList List
	 * @return List
	 */
    TaskList delete(TaskList taskList);

	/**
	 * Updates a single row in the List table.
	 *
	 * @param taskList List
	 * @return List
	 */
	TaskList update(TaskList taskList);

	/**
	 * Finds a single row in the List table.
	 *
	 * @param taskList List
	 * @return List
	 */
	TaskList find(TaskList taskList);

	/**
	 * Finds a List of rows in the List table.
	 *
	 * @param List List
	 * @param pagination Pagination
	 * @return List
	 */
	List<TaskList> findAll(TaskList List, Pagination pagination);

    
}


