DEFINE DIR_SCRIPTS = '/aplic/aa79b/scripts';

@@&DIR_SCRIPTS/Vistas/X54j/X54JAPI_SOLICITANTES.sql;
@@&DIR_SCRIPTS/Vistas/X54j/X54JAPI_PERSONAL_IZO.sql;
@@&DIR_SCRIPTS/Vistas/X54j/X54JAPI_PROVEEDORES.sql;
@@&DIR_SCRIPTS/Vistas/X54j/X54JAPI_ENTIDADES_SOLIC.sql;
@@&DIR_SCRIPTS/Vistas/X54j/X54JAPI_EMPRESAS_PROV.sql;

GRANT SELECT ON X54JAPI_SOLICITANTES TO AA79B;
GRANT SELECT ON X54JAPI_PERSONAL_IZO TO AA79B;
GRANT SELECT ON X54JAPI_PROVEEDORES TO AA79B;
GRANT SELECT ON X54JAPI_ENTIDADES_SOLIC TO AA79B;
GRANT SELECT ON X54JAPI_EMPRESAS_PROV TO AA79B;
GRANT SELECT ON X54JNORA TO AA79B;

EXIT;
