package com.ejie.aa79b.model;


import java.util.Date;

import com.ejie.x38.serialization.JsonDateDeserializer;
import com.ejie.x38.serialization.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * ConfigPagoProveedores generated by UDA, 05-dic-2017 15:17:18.
 * @author UDA
 */

public class ConfigPagoProveedores  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
            private Long id;
            private Long porIva;
            private Date fechaDesde;
            private Date fechaHasta;
            private String vigente;
            private String vigenteDesc;

	/** 
	 * Method 'ConfigPagoProveedores'.
	 */
    public ConfigPagoProveedores() {
    	//Constructor vacío
    }


	
    
    /** 
     * Method 'ConfigPagoProveedores'.
     * @param id Long
     */    
     public ConfigPagoProveedores(Long id) {
          this.id = id;
	}

    

    /** 
     * Method 'ConfigPagoProveedores'.
     * @param id Long
     * @param porIva Long
     * @param fechaDesde Date
     * @param fechaHasta Date
     */
   public ConfigPagoProveedores(Long id, Long porIva, Date fechaDesde, Date fechaHasta) {	

           this.id = id;
           this.porIva = porIva;
           this.fechaDesde = fechaDesde;
           this.fechaHasta = fechaHasta;
    }

    /**
	 * Method 'getId'.
	 *
	 * @return Long
	 */
	
	
	public Long getId() {
		return this.id;
	}

	/**
	 * Method 'setId'.
	 *
	 * @param id Long
	 * @return
     */
	
	public void setId(Long id) {
		this.id = id;
	}
    /**
	 * Method 'getPorIva'.
	 *
	 * @return Long
	 */
	
	
	public Long getPorIva() {
		return this.porIva;
	}

	/**
	 * Method 'setPorIva'.
	 *
	 * @param porIva Long
	 * @return
     */
	
	public void setPorIva(Long porIva) {
		this.porIva = porIva;
	}
    /**
	 * Method 'getFechaHasta'.
	 *
	 * @return java.util.Date
	 */
	
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}
    /**
	 * Method 'getFechaDesde'.
	 *
	 * @return java.util.Date
	 */
	
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	/**
	 * Method 'setFechaDesde'.
	 *
	 * @param fechaDesde java.util.Date
	 * @return
     */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	/**
	 * Method 'setFechaHasta'.
	 *
	 * @param fechaHasta java.util.Date
	 * @return
     */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		result.append(" [ id: ").append(this.id).append(" ]");
		result.append(", [ porIva: ").append(this.porIva).append(" ]");
		result.append(", [ fechaDesde: ").append(this.fechaDesde).append(" ]");
		result.append(", [ fechaHasta: ").append(this.fechaHasta).append(" ]");
		result.append("}");
		return result.toString();
	}




	public String getVigente() {
		return this.vigente;
	}




	public void setVigente(String vigente) {
		this.vigente = vigente;
	}




	public String getVigenteDesc() {
		return this.vigenteDesc;
	}




	public void setVigenteDesc(String vigenteDesc) {
		this.vigenteDesc = vigenteDesc;
	}


}

