package com.ejie.aa79b.model;

import java.math.BigDecimal;

import com.ejie.aa79b.common.JsonNumbersDeserializer;
import com.ejie.aa79b.common.jackson.JsonTarifaSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * CuantiaTrad generated by UDA, 15-dic-2017 14:11:44.
 * 
 * @author UDA
 */

public class Cuantias implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long idTipoRelevancia;
	private Long idOrden;
	private BigDecimal tarifaEsEu;
	private BigDecimal tarifaEuEs;
	private TipoRelevancia tipoRelevancia;

	/**
	 * Method 'Cuantias'.
	 */
	public Cuantias() {
		// Constructor
	}

	/**
	 * Method 'getIdTipoRelevancia'.
	 *
	 * @return Long
	 */

	public Long getIdTipoRelevancia() {
		return this.idTipoRelevancia;
	}

	/**
	 * Method 'setIdTipoRelevancia'.
	 *
	 * @param idTipoRelevancia
	 *            Long
	 * @return
	 */

	public void setIdTipoRelevancia(Long idTipoRelevancia) {
		this.idTipoRelevancia = idTipoRelevancia;
	}

	/**
	 * 
	 * @return Long
	 */
	public Long getIdOrden() {
		return this.idOrden;
	}

	/**
	 * 
	 * @param idOrden
	 *            Long
	 */
	public void setIdOrden(Long idOrden) {
		this.idOrden = idOrden;
	}

	/**
	 * Method 'getTarifaEsEu'.
	 *
	 * @return BigDecimal
	 */
	@JsonSerialize(using = JsonTarifaSerializer.class)
	public BigDecimal getTarifaEsEu() {
		return this.tarifaEsEu;
	}

	/**
	 * Method 'setTarifaEsEu'.
	 *
	 * @param tarifaEsEu
	 *            BigDecimal
	 * @return
	 */
	@JsonDeserialize(using = JsonNumbersDeserializer.class)
	public void setTarifaEsEu(BigDecimal tarifaEsEu) {
		this.tarifaEsEu = tarifaEsEu;
	}

	/**
	 * Method 'getTarifaEuEs'.
	 *
	 * @return BigDecimal
	 */
	
	@JsonSerialize(using = JsonTarifaSerializer.class)
	public BigDecimal getTarifaEuEs() {
		return this.tarifaEuEs;
	}

	/**
	 * Method 'setTarifaEuEs'.
	 *
	 * @param tarifaEuEs
	 *            BigDecimal
	 * @return
	 */
	@JsonDeserialize(using = JsonNumbersDeserializer.class)
	public void setTarifaEuEs(BigDecimal tarifaEuEs) {
		this.tarifaEuEs = tarifaEuEs;
	}

	/**
	 * 
	 * @return TipoRelevancia
	 */
	public TipoRelevancia getTipoRelevancia() {
		return this.tipoRelevancia;
	}

	/**
	 * 
	 * @param tipoRelevancia
	 *            TipoRelevancia
	 */
	public void setTipoRelevancia(TipoRelevancia tipoRelevancia) {
		this.tipoRelevancia = tipoRelevancia;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { ");
		result.append(", [ idTipoRelevancia: ").append(this.idTipoRelevancia).append(" ]");
		result.append(", [ idOrden: ").append(this.idOrden).append(" ]");
		result.append(", [ tarifaEsEu: ").append(this.tarifaEsEu).append(" ]");
		result.append(", [ tarifaEuEs: ").append(this.tarifaEuEs).append(" ]");
		result.append("}");
		return result.toString();
	}

}
