package com.ejie.aa79b.model;

/**
 * DireccionNora generated by UDA, 08-feb-2018 8:37:04.
 * 
 * @author UDA
 */
public class DireccionNora extends Direccion {

    private static final long serialVersionUID = 1L;
    private Long codNora;
    private String codComun;
    private String codLocal;
    private String aprox;
    private String codPais;
    private String txtDirec;

    // datos de NORA
    private Portal portal = new Portal();
    private Municipio municipio = new Municipio();
    private Localidad localidad = new Localidad();
    private Pais pais = new Pais();
    private Provincia provincia = new Provincia();
    private Calle calle = new Calle();

    /**
     * Method 'DireccionNora'.
     */
    public DireccionNora() {
        // Constructor
    }

    /**
     * Method 'getCodnora'.
     *
     * @return Long
     */
    public Long getCodNora() {
        return this.codNora;
    }

    /**
     * Method 'setCodNora'.
     *
     * @param codNora
     *            Long
     * @return
     */
    public void setCodNora(Long codNora) {
        this.codNora = codNora;
    }

    /**
     * Method 'getAprox'.
     *
     * @return String
     */
    public String getAprox() {
        return this.aprox;
    }

    /**
     * Method 'setAprox'.
     *
     * @param aprox
     *            String
     * @return
     */
    public void setAprox(String aprox) {
        this.aprox = aprox;
    }

    public String getCodComun() {
        return codComun;
    }

    public void setCodComun(String codComun) {
        this.codComun = codComun;
    }

    public String getCodLocal() {
        return codLocal;
    }

    public void setCodLocal(String codLocal) {
        this.codLocal = codLocal;
    }

    public String getCodPais() {
        return codPais;
    }

    public void setCodPais(String codPais) {
        this.codPais = codPais;
    }

    public String getTxtDirec() {
        return txtDirec;
    }

    public void setTxtDirec(String txtDirec) {
        this.txtDirec = txtDirec;
    }

    /**
     * @return the portal
     */
    public Portal getPortal() {
        return portal;
    }

    /**
     * @param portal
     *            the portal to set
     */
    public void setPortal(Portal portal) {
        this.portal = portal;
    }

    /**
     * @return the municipio
     */
    public Municipio getMunicipio() {
        return municipio;
    }

    /**
     * @param municipio
     *            the municipio to set
     */
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

    /**
     * @return the localidad
     */
    public Localidad getLocalidad() {
        return localidad;
    }

    /**
     * @param localidad
     *            the localidad to set
     */
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }

    /**
     * @return the pais
     */
    public Pais getPais() {
        return pais;
    }

    /**
     * @param pais
     *            the pais to set
     */
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    /**
     * @return the provincia
     */
    public Provincia getProvincia() {
        return provincia;
    }

    /**
     * @param provincia
     *            the provincia to set
     */
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    /**
     * @return the calle
     */
    public Calle getCalle() {
        return calle;
    }

    /**
     * @param calle
     *            the calle to set
     */
    public void setCalle(Calle calle) {
        this.calle = calle;
    }

    /**
     * Intended only for logging and debugging.
     * 
     * Here, the contents of every main field are placed into the result.
     * 
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        result.append(this.getClass().getName()).append(" Object { ");
        result.append("[ codnora: ").append(this.codNora).append(" ]");
        result.append(", [ codcomun: ").append(this.codComun).append(" ]");
        result.append(", [ codlocal: ").append(this.codLocal).append(" ]");
        result.append(", [ aprox: ").append(this.aprox).append(" ]");
        result.append(", [ codpais: ").append(this.codPais).append(" ]");
        result.append(", [ txtdirec: ").append(this.txtDirec).append(" ]");
        result.append("}");
        return result.toString();
    }

}
