package com.ejie.aa79b.model;

/**
 * FormatosFichero generated by UDA, 30-nov-2017 10:16:22.
 * 
 * @author UDA
 */

public class FormatosFichero implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id011;
	private String formato011;
	private String descEs011;
	private String descEu011;
	private String observEu011;
	private String observEs011;
	private String estado011;
	private String estadoDescEs;
	private String estadoDescEu;

	public String getEstadoDescEs() {
		return this.estadoDescEs;
	}

	public void setEstadoDescEs(String estadoDescEs) {
		this.estadoDescEs = estadoDescEs;
	}

	public String getEstadoDescEu() {
		return this.estadoDescEu;
	}

	public void setEstadoDescEu(String estadoDescEu) {
		this.estadoDescEu = estadoDescEu;
	}

	/**
	 * Method 'FormatosFichero'.
	 */
	public FormatosFichero() {
	    /*constructor*/
	}

	/**
	 * Method 'FormatosFichero'.
	 * 
	 * @param id011
	 *            Long
	 */
	public FormatosFichero(Long id011) {
		this.id011 = id011;
	}

	/**
	 * Method 'FormatosFichero'.
	 * 
	 * @param id011
	 *            Long
	 * @param formato011
	 *            String
	 * @param descEs011
	 *            String
	 * @param descEu011
	 *            String
	 * @param observEu011
	 *            String
	 * @param observEs011
	 *            String
	 * @param estado011
	 *            String
	 */
	public FormatosFichero(Long id011, String formato011, String descEs011, String descEu011, String observEu011,
			String observEs011, String estado011) {

		this.id011 = id011;
		this.formato011 = formato011;
		this.descEs011 = descEs011;
		this.descEu011 = descEu011;
		this.observEu011 = observEu011;
		this.observEs011 = observEs011;
		this.estado011 = estado011;
	}

	/**
	 * Method 'getId011'.
	 *
	 * @return Long
	 */

	public Long getId011() {
		return this.id011;
	}

	/**
	 * Method 'setId011'.
	 *
	 * @param id011
	 *            Long
	 * @return
	 */

	public void setId011(Long id011) {
		this.id011 = id011;
	}

	/**
	 * Method 'getFormato011'.
	 *
	 * @return String
	 */

	public String getFormato011() {
		return this.formato011;
	}

	/**
	 * Method 'setFormato011'.
	 *
	 * @param formato011
	 *            String
	 * @return
	 */

	public void setFormato011(String formato011) {
		this.formato011 = formato011;
	}

	/**
	 * Method 'getDescEs011'.
	 *
	 * @return String
	 */

	public String getDescEs011() {
		return this.descEs011;
	}

	/**
	 * Method 'setDescEs011'.
	 *
	 * @param descEs011
	 *            String
	 * @return
	 */

	public void setDescEs011(String descEs011) {
		this.descEs011 = descEs011;
	}

	/**
	 * Method 'getDescEu011'.
	 *
	 * @return String
	 */

	public String getDescEu011() {
		return this.descEu011;
	}

	/**
	 * Method 'setDescEu011'.
	 *
	 * @param descEu011
	 *            String
	 * @return
	 */

	public void setDescEu011(String descEu011) {
		this.descEu011 = descEu011;
	}

	/**
	 * Method 'getObservEu011'.
	 *
	 * @return String
	 */

	public String getObservEu011() {
		return this.observEu011;
	}

	/**
	 * Method 'setObservEu011'.
	 *
	 * @param observEu011
	 *            String
	 * @return
	 */

	public void setObservEu011(String observEu011) {
		this.observEu011 = observEu011;
	}

	/**
	 * Method 'getObservEs011'.
	 *
	 * @return String
	 */

	public String getObservEs011() {
		return this.observEs011;
	}

	/**
	 * Method 'setObservEs011'.
	 *
	 * @param observEs011
	 *            String
	 * @return
	 */

	public void setObservEs011(String observEs011) {
		this.observEs011 = observEs011;
	}

	/**
	 * Method 'getEstado011'.
	 *
	 * @return String
	 */

	public String getEstado011() {
		return this.estado011;
	}

	/**
	 * Method 'setEstado011'.
	 *
	 * @param estado011
	 *            String
	 * @return
	 */

	public void setEstado011(String estado011) {
		this.estado011 = estado011;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { ");
		result.append(" [ id011: ").append(this.id011).append(" ]");
		result.append(", [ formato011: ").append(this.formato011).append(" ]");
		result.append(", [ descEs011: ").append(this.descEs011).append(" ]");
		result.append(", [ descEu011: ").append(this.descEu011).append(" ]");
		result.append(", [ observEu011: ").append(this.observEu011).append(" ]");
		result.append(", [ observEs011: ").append(this.observEs011).append(" ]");
		result.append(", [ estado011: ").append(this.estado011).append(" ]");
		result.append("}");
		return result.toString();
	}

}
