package com.ejie.aa79b.model;

import java.util.ArrayList;
import java.util.List;

/**
 * HorasHorarios generated by UDA, 21-nov-2017 14:44:52.
 * 
 * @author UDA
 */

public class HorasHorariosLaborales implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    // Clave compuesta
    private Long idHorario039;
    private String indVerano039;
    private String horaIniLjM039;
    private String horaFinLjM039;
    private String horaIniLjT039;
    private String horaFinLjT039;
    private String horaIniVM039;
    private String horaFinVM039;
    private String horaIniVT039;
    private String horaFinVT039;

    private List<Long> idsHorariosLaborales = new ArrayList<Long>();

    /**
     * Method 'HorasHorarios'.
     */
    public HorasHorariosLaborales() {
        /* Constructor */
    }

    /**
     * Method 'HorasHorarios'.
     * 
     * @param id039
     *            Long
     * @param indVerano039
     *            String
     */
    public HorasHorariosLaborales(Long id039, String indVerano039) {
        this.idHorario039 = id039;
        this.indVerano039 = indVerano039;
    }

    /**
     * Method 'getId039'.
     *
     * @return Long
     */
    public Long getIdHorario039() {
        return this.idHorario039;
    }

    /**
     * Method 'setId039'.
     * 
     * @param id039
     */
    public void setIdHorario039(Long id039) {
        this.idHorario039 = id039;
    }

    /**
     * Method 'getIndVerano039'.
     *
     * @return String
     */

    public String getIndVerano039() {
        return this.indVerano039;
    }

    /**
     * Method 'setIndVerano039'.
     *
     * @param indVerano039
     *            String
     * @return
     */

    public void setIndVerano039(String indVerano039) {
        this.indVerano039 = indVerano039;
    }

    /**
     * Method 'getHoraIniLjM039'.
     *
     * @return String
     */

    public String getHoraIniLjM039() {
        return this.horaIniLjM039;
    }

    /**
     * Method 'setHoraIniLjM039'.
     *
     * @param horaIniLjM039
     *            String
     * @return
     */

    public void setHoraIniLjM039(String horaIniLjM039) {
        this.horaIniLjM039 = horaIniLjM039;
    }

    /**
     * Method 'getHoraFinLjM039'.
     *
     * @return String
     */

    public String getHoraFinLjM039() {
        return this.horaFinLjM039;
    }

    /**
     * Method 'setHoraFinLjM039'.
     *
     * @param horaFinLjM039
     *            String
     * @return
     */

    public void setHoraFinLjM039(String horaFinLjM039) {
        this.horaFinLjM039 = horaFinLjM039;
    }

    /**
     * Method 'getHoraIniLjT039'.
     *
     * @return String
     */

    public String getHoraIniLjT039() {
        return this.horaIniLjT039;
    }

    /**
     * Method 'setHoraIniLjT039'.
     *
     * @param horaIniLjT039
     *            String
     * @return
     */

    public void setHoraIniLjT039(String horaIniLjT039) {
        this.horaIniLjT039 = horaIniLjT039;
    }

    /**
     * Method 'getHoraFinLjT039'.
     *
     * @return String
     */

    public String getHoraFinLjT039() {
        return this.horaFinLjT039;
    }

    /**
     * Method 'setHoraFinLjT039'.
     *
     * @param horaFinLjT039
     *            String
     * @return
     */

    public void setHoraFinLjT039(String horaFinLjT039) {
        this.horaFinLjT039 = horaFinLjT039;
    }

    /**
     * Method 'getHoraIniVM039'.
     *
     * @return String
     */

    public String getHoraIniVM039() {
        return this.horaIniVM039;
    }

    /**
     * Method 'setHoraIniVM039'.
     *
     * @param horaIniVM039
     *            String
     * @return
     */

    public void setHoraIniVM039(String horaIniVM039) {
        this.horaIniVM039 = horaIniVM039;
    }

    /**
     * Method 'getHoraFinVM039'.
     *
     * @return String
     */

    public String getHoraFinVM039() {
        return this.horaFinVM039;
    }

    /**
     * Method 'setHoraFinVM039'.
     *
     * @param horaFinVM039
     *            String
     * @return
     */

    public void setHoraFinVM039(String horaFinVM039) {
        this.horaFinVM039 = horaFinVM039;
    }

    /**
     * Method 'getHoraIniVT039'.
     *
     * @return String
     */

    public String getHoraIniVT039() {
        return this.horaIniVT039;
    }

    /**
     * Method 'setHoraIniVT039'.
     *
     * @param horaIniVT039
     *            String
     * @return
     */

    public void setHoraIniVT039(String horaIniVT039) {
        this.horaIniVT039 = horaIniVT039;
    }

    /**
     * Method 'getHoraFinVT039'.
     *
     * @return String
     */

    public String getHoraFinVT039() {
        return this.horaFinVT039;
    }

    /**
     * Method 'setHoraFinVT039'.
     *
     * @param horaFinVT039
     *            String
     * @return
     */

    public void setHoraFinVT039(String horaFinVT039) {
        this.horaFinVT039 = horaFinVT039;
    }

    public List<Long> getIdsHorariosLaborales() {
        return this.idsHorariosLaborales;
    }

    public void setIdsHorariosLaborales(List<Long> idsHorariosLaborales) {
        this.idsHorariosLaborales = idsHorariosLaborales;
    }

  //Métodos para el registro de acciones
    public String getComparaLJ() {
        StringBuilder salida = new StringBuilder(this.horaIniLjM039+" - "+this.horaFinLjM039);
        if (this.horaIniLjT039 !=null) {
            salida.append(" / "+this.horaIniLjT039+" - "+this.horaFinLjT039);
        }
        return salida.toString();
    }
    public String getComparaV() {
        StringBuilder salida = new StringBuilder(this.horaIniVM039+" - "+this.horaFinVM039);
        if (this.horaIniVT039 !=null) {
            salida.append(" / "+this.horaIniVT039+" - "+this.horaFinVT039);
        }
        return salida.toString();
    }
    
    /**
     * Intended only for logging and debugging.
     * 
     * Here, the contents of every main field are placed into the result.
     * 
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        result.append(this.getClass().getName()).append(" Object { ");
        // Clave compuesta

        result.append("[ id039: ").append(this.idHorario039).append(" ]");
        result.append(", [ indVerano039: ").append(this.indVerano039).append(" ]");
        result.append(", [ horaIniLjM039: ").append(this.horaIniLjM039).append(" ]");
        result.append(", [ horaFinLjM039: ").append(this.horaFinLjM039).append(" ]");
        result.append(", [ horaIniLjT039: ").append(this.horaIniLjT039).append(" ]");
        result.append(", [ horaFinLjT039: ").append(this.horaFinLjT039).append(" ]");
        result.append(", [ horaIniVM039: ").append(this.horaIniVM039).append(" ]");
        result.append(", [ horaFinVM039: ").append(this.horaFinVM039).append(" ]");
        result.append(", [ horaIniVT039: ").append(this.horaIniVT039).append(" ]");
        result.append(", [ horaFinVT039: ").append(this.horaFinVT039).append(" ]");
        result.append("}");
        return result.toString();
    }

}
