package com.ejie.aa79b.model;

import java.util.Date;

import com.ejie.x38.serialization.JsonDateDeserializer;
import com.ejie.x38.serialization.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * LibroRegistro generated by UDA, 03-abr-2018 9:49:16.
 * 
 * @author UDA
 */
public class LibroRegistro implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Long anyo;
	private Integer numExp;
	private String indSalida;
	private String matter;
	private String telematico;
	private Date fechaRegistro;
	private String numRegistro;

	/**
	 * Method 'LibroRegistro'.
	 */
	public LibroRegistro() {
		// Constructor
	}

	/**
	 * Method 'LibroRegistro'.
	 * 
	 * @param id
	 *            Long
	 */
	public LibroRegistro(Long id) {
		this.id = id;
	}

	/**
	 * Method 'getId'.
	 *
	 * @return Long
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Method 'setId'.
	 *
	 * @param id
	 *            Long
	 * @return
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Method 'getAnyo'.
	 *
	 * @return Long
	 */
	public Long getAnyo() {
		return this.anyo;
	}

	/**
	 * Method 'setAnyo'.
	 *
	 * @param anyo
	 *            Long
	 * @return
	 */
	public void setAnyo(Long anyo) {
		this.anyo = anyo;
	}

	/**
	 * Method 'getNumExp'.
	 *
	 * @return Integer
	 */
	public Integer getNumExp() {
		return this.numExp;
	}

	/**
	 * Method 'setNumExp'.
	 *
	 * @param numExp
	 *            Integer
	 * @return
	 */
	public void setNumExp(Integer numExp) {
		this.numExp = numExp;
	}

	/**
	 * Method 'getIndSalida'.
	 *
	 * @param indSalida
	 *            String
	 * @return
	 */
	public String getIndSalida() {
		return indSalida;
	}

	/**
	 * Method 'setIndSalida'.
	 *
	 * @param indSalida
	 *            String
	 * @return
	 */
	public void setIndSalida(String indSalida) {
		this.indSalida = indSalida;
	}

	/**
	 * Method 'getMatter'.
	 *
	 * @return String
	 */
	public String getMatter() {
		return this.matter;
	}

	/**
	 * Method 'setMatter'.
	 *
	 * @param matter
	 *            String
	 * @return
	 */
	public void setMatter(String matter) {
		this.matter = matter;
	}

	/**
	 * Method 'getTelematico'.
	 *
	 * @return String
	 */
	public String getTelematico() {
		return this.telematico;
	}

	/**
	 * Method 'setTelematico'.
	 *
	 * @param telematico
	 *            String
	 * @return
	 */
	public void setTelematico(String telematico) {
		this.telematico = telematico;
	}

	/**
	 * Method 'getFechaRegistro'.
	 *
	 * @return java.util.Date
	 */
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	/**
	 * Method 'setFechaRegistro'.
	 *
	 * @param fechaRegistro
	 *            java.util.Date
	 * @return
	 */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	/**
	 * Method 'getNumRegistro'.
	 *
	 * @return String
	 */
	public String getNumRegistro() {
		return this.numRegistro;
	}

	/**
	 * Method 'setNumRegistro'.
	 *
	 * @param numRegistro
	 *            String
	 * @return
	 */
	public void setNumRegistro(String numRegistro) {
		this.numRegistro = numRegistro;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { ");
		result.append(" [ id: ").append(this.id).append(" ]");
		result.append(", [ anyo: ").append(this.anyo).append(" ]");
		result.append(", [ numExp: ").append(this.numExp).append(" ]");
		result.append(", [ matter: ").append(this.matter).append(" ]");
		result.append(", [ telematico: ").append(this.telematico).append(" ]");
		result.append(", [ fechaRegistro: ").append(this.fechaRegistro).append(" ]");
		result.append(", [ numRegistro: ").append(this.numRegistro).append(" ]");
		result.append("}");
		return result.toString();
	}

}
