package com.ejie.aa79b.model;

/**
 * TiposTarea generated by UDA, 28-nov-2017 9:50:00.
 *
 * @author UDA
 */

/**
 * @author mrodriguez
 *
 */
public class TiposTarea implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id015;
	private String descEs015;
	private String descEu015;
	private String indGestionAsoc015;
	private String indTiempoGestion015;
	private String indReqCierre015;
	private String estado015;
	private String descEstadoEs;
	private String descEstadoEu;
	private String descGestionEs;
	private String descGestionEu;
	private String descTiempoGestionEs;
	private String descTiempoGestionEu;
	private String descCierreEs;
	private String descCierreEu;
	private String indHorasEjecucion015;
	private String indFacturable015;
	private String indInterpretacion015;

	private String indVisibleTrabajo015;

	public String getDescEstadoEs() {
		return this.descEstadoEs;
	}

	public void setDescEstadoEs(String descEstadoEs) {
		this.descEstadoEs = descEstadoEs;
	}

	public String getDescEstadoEu() {
		return this.descEstadoEu;
	}

	public void setDescEstadoEu(String descEstadoEu) {
		this.descEstadoEu = descEstadoEu;
	}

	public String getDescGestionEs() {
		return this.descGestionEs;
	}

	public void setDescGestionEs(String descGestionEs) {
		this.descGestionEs = descGestionEs;
	}

	public String getDescGestionEu() {
		return this.descGestionEu;
	}

	public void setDescGestionEu(String descGestionEu) {
		this.descGestionEu = descGestionEu;
	}

	public String getDescTiempoGestionEs() {
		return this.descTiempoGestionEs;
	}

	public void setDescTiempoGestionEs(String descTiempoGestionEs) {
		this.descTiempoGestionEs = descTiempoGestionEs;
	}

	public String getDescTiempoGestionEu() {
		return this.descTiempoGestionEu;
	}

	public void setDescTiempoGestionEu(String descTiempoGestionEu) {
		this.descTiempoGestionEu = descTiempoGestionEu;
	}

	public String getDescCierreEs() {
		return this.descCierreEs;
	}

	public void setDescCierreEs(String descCierreEs) {
		this.descCierreEs = descCierreEs;
	}

	public String getDescCierreEu() {
		return this.descCierreEu;
	}

	public void setDescCierreEu(String descCierreEu) {
		this.descCierreEu = descCierreEu;
	}

	/**
	 * Method 'TiposTarea'.
	 */
	public TiposTarea() {
		// Contructor
	}

	/**
	 * Method 'TiposTarea'.
	 *
	 * @param id015 Long
	 */
	public TiposTarea(Long id015) {
		this.id015 = id015;
	}

	/**
	 * Method 'TiposTarea'.
	 *
	 * @param id015             Long
	 * @param descEs015         String
	 * @param descEu015         String
	 * @param indGestionAsoc015 String
	 * @param indReqCierre015   String
	 * @param estado015         String
	 */
	public TiposTarea(Long id015, String descEs015, String descEu015, String indGestionAsoc015, String indReqCierre015,
			String estado015) {

		this.id015 = id015;
		this.descEs015 = descEs015;
		this.descEu015 = descEu015;
		this.indGestionAsoc015 = indGestionAsoc015;
		this.indReqCierre015 = indReqCierre015;
		this.estado015 = estado015;
	}

	/**
	 * Method 'getId015'.
	 *
	 * @return Long
	 */

	public Long getId015() {
		return this.id015;
	}

	/**
	 * Method 'setId015'.
	 *
	 * @param id015 Long
	 * @return
	 */

	public void setId015(Long id015) {
		this.id015 = id015;
	}

	/**
	 * Method 'getDescEs015'.
	 *
	 * @return String
	 */

	public String getDescEs015() {
		return this.descEs015;
	}

	/**
	 * Method 'setDescEs015'.
	 *
	 * @param descEs015 String
	 * @return
	 */

	public void setDescEs015(String descEs015) {
		this.descEs015 = descEs015;
	}

	/**
	 * Method 'getDescEu015'.
	 *
	 * @return String
	 */

	public String getDescEu015() {
		return this.descEu015;
	}

	/**
	 * Method 'setDescEu015'.
	 *
	 * @param descEu015 String
	 * @return
	 */

	public void setDescEu015(String descEu015) {
		this.descEu015 = descEu015;
	}

	/**
	 * Method 'getIndGestionAsoc015'.
	 *
	 * @return String
	 */

	public String getIndGestionAsoc015() {
		return this.indGestionAsoc015;
	}

	/**
	 * Method 'setIndGestionAsoc015'.
	 *
	 * @param indGestionAsoc015 String
	 * @return
	 */

	public void setIndGestionAsoc015(String indGestionAsoc015) {
		this.indGestionAsoc015 = indGestionAsoc015;
	}

	public String getIndTiempoGestion015() {
		return this.indTiempoGestion015;
	}

	public void setIndTiempoGestion015(String indTiempoGestion015) {
		this.indTiempoGestion015 = indTiempoGestion015;
	}

	/**
	 * Method 'getIndReqCierre015'.
	 *
	 * @return String
	 */

	public String getIndReqCierre015() {
		return this.indReqCierre015;
	}

	/**
	 * Method 'setIndReqCierre015'.
	 *
	 * @param indReqCierre015 String
	 * @return
	 */

	public void setIndReqCierre015(String indReqCierre015) {
		this.indReqCierre015 = indReqCierre015;
	}

	/**
	 * Method 'getEstado015'.
	 *
	 * @return String
	 */

	public String getEstado015() {
		return this.estado015;
	}

	/**
	 * Method 'setEstado015'.
	 *
	 * @param estado015 String
	 * @return
	 */

	public void setEstado015(String estado015) {
		this.estado015 = estado015;
	}

	/**
	 * @return the indHorasEjecucion015
	 */
	public String getIndHorasEjecucion015() {
		return this.indHorasEjecucion015;
	}

	/**
	 * @param indHorasEjecucion015 the indHorasEjecucion015 to set
	 */
	public void setIndHorasEjecucion015(String indHorasEjecucion015) {
		this.indHorasEjecucion015 = indHorasEjecucion015;
	}

	/**
	 * @return the indFacturable015
	 */
	public String getIndFacturable015() {
		return this.indFacturable015;
	}

	/**
	 * @param indFacturable015 the indFacturable015 to set
	 */
	public void setIndFacturable015(String indFacturable015) {
		this.indFacturable015 = indFacturable015;
	}

	public String getIndInterpretacion015() {
		return this.indInterpretacion015;
	}

	public void setIndInterpretacion015(String indInterpretacion015) {
		this.indInterpretacion015 = indInterpretacion015;
	}

	public String getIndVisibleTrabajo015() {
		return this.indVisibleTrabajo015;
	}

	public void setIndVisibleTrabajo015(String indVisibleTrabajo015) {
		this.indVisibleTrabajo015 = indVisibleTrabajo015;
	}

	/**
	 * Intended only for logging and debugging.
	 *
	 * Here, the contents of every main field are placed into the result.
	 *
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { ");
		result.append(" [ id015: ").append(this.id015).append(" ]");
		result.append(", [ descEs015: ").append(this.descEs015).append(" ]");
		result.append(", [ descEu015: ").append(this.descEu015).append(" ]");
		result.append(", [ indGestionAsoc015: ").append(this.indGestionAsoc015).append(" ]");
		result.append(", [ indReqCierre015: ").append(this.indReqCierre015).append(" ]");
		result.append(", [ estado015: ").append(this.estado015).append(" ]");
		result.append(", [ indFacturable015: ").append(this.indFacturable015).append(" ]");
		result.append(", [ indVisibleTrabajo015: ").append(this.indVisibleTrabajo015).append(" ]");
		result.append("}");
		return result.toString();
	}



}
