CREATE OR REPLACE FUNCTION CREAR_ESTRUCTURA_AUDITORIA (
   ANYO IN NUMBER,
   NUM_EXP IN NUMBER,
   IDTAREA_REVISION IN NUMBER,
   IDTAREA_AUDITAR IN NUMBER
) RETURN NUMBER IS

 

    CONTADOR NUMBER(2) := 0;
    ESTADO_SIN_HACER NUMBER(1):= 1;



    ID_AUDITORIA NUMBER(20);
    DNI_AUDITOR VARCHAR2(10);
    VAL_MIN_APROBADO NUMBER(3);
    VAL_MIN_PELIGRO NUMBER(3);

    POR_NIVEL_0    NUMBER(4,1);
    POR_NIVEL_1    NUMBER(4,1);
    POR_NIVEL_3    NUMBER(4,1);
    POR_NIVEL_5    NUMBER(4,1);

    CURSOR SECCIONES_VISIBLES IS (
        SELECT ID_0C0,
                 TIPO_SECCION_0C0,
               IND_RESPUESTA_0C0,
               NOMBRE_EU_0C0,
               IND_OBSERVACIONES_0C0,
               ORDEN_0C0
        FROM AA79BC0S01
        WHERE IND_VISIBLE_0C0 = 'S'
    );

    CURSOR CAMPOS_VISIBLES IS (
        SELECT ID_0C1,
                 TIPO_CAMPO_0C1,
               NOMBRE_EU_0C1,
               IND_OBSERVACIONES_0C1,
               NOTA_OK_0C1,
               NOTA_NO_OK_0C1,
               IND_OBLIGATORIO_0C1,
               ID_SECCION_PADRE_0C1,
               ORDEN_0C1,
               ID_PESO_0C1,
               POR_NIVEL_0_0B9, 
               POR_NIVEL_1_0B9, 
               POR_NIVEL_3_0B9, 
               POR_NIVEL_5_0B9
        FROM AA79BC1S01
        LEFT JOIN AA79BB9S01 
        ON ID_PESO_0C1 = ID_0B9
        AND ESTADO_0B9 = 'A'
        WHERE IND_VISIBLE_0C1 = 'S'
    );

BEGIN

    SELECT COUNT(1) INTO CONTADOR FROM AA79BC2S01 WHERE ANYO_0C2 = ANYO AND NUM_EXP_0C2 = NUM_EXP AND ID_TAREA_REVISION_0C2 = IDTAREA_REVISION AND ID_TAREA_AUDITAR_0C2 = IDTAREA_AUDITAR;

    IF ( CONTADOR > 0 ) THEN

        SELECT ID_0C2 INTO ID_AUDITORIA FROM AA79BC2S01 WHERE ANYO_0C2 = ANYO AND NUM_EXP_0C2 = NUM_EXP AND ID_TAREA_REVISION_0C2 = IDTAREA_REVISION AND ID_TAREA_AUDITAR_0C2 = IDTAREA_AUDITAR;
        RETURN ID_AUDITORIA;
    ELSE

        SELECT AA79BC2Q00.NEXTVAL INTO ID_AUDITORIA FROM DUAL;

        SELECT DNI_RECURSO_081 INTO DNI_AUDITOR FROM AA79B81S01 WHERE ID_TAREA_081 = IDTAREA_REVISION;

        SELECT VAL_MIN_APROBADO_0B8, VAL_MIN_PELIGRO_0B8 INTO VAL_MIN_APROBADO, VAL_MIN_PELIGRO FROM AA79BB8S01 WHERE ID_0B8 = 0;

        INSERT INTO AA79BC2S01 (ID_0C2, ANYO_0C2, NUM_EXP_0C2, ID_TAREA_REVISION_0C2, ID_TAREA_AUDITAR_0C2, DNI_AUDITOR_0C2, ESTADO_AUDITORIA_0C2, VALOR_MIN_APROBADO_0C2, VALOR_MIN_PELIGRO_0C2, RESULTADO_AUDITORIA_0C2, NOTA_AUDITORIA_0C2, IND_ENVIADO_0C2)
        VALUES (ID_AUDITORIA, ANYO, NUM_EXP, IDTAREA_REVISION, IDTAREA_AUDITAR, DNI_AUDITOR, ESTADO_SIN_HACER, VAL_MIN_APROBADO, VAL_MIN_PELIGRO, NULL, NULL, 'N');

        FOR S_VISIBLES IN SECCIONES_VISIBLES LOOP

            INSERT INTO AA79BC3S01 (ID_AUDITORIA_0C3, ID_SECCION_0C3, TIPO_SECCION_0C3, IND_RESPUESTA_0C3, NOMBRE_EU_0C3, IND_OBSERVACIONES_0C3, ORDEN_0C3, VALOR_MIN_APROBADO_0C3, VALOR_MIN_PELIGRO_0C3, RESULTADO_AUDITORIA_0C3, NOTA_AUDITORIA_0C3, OBSERV_0C3)
            VALUES (ID_AUDITORIA, S_VISIBLES.ID_0C0, S_VISIBLES.TIPO_SECCION_0C0, S_VISIBLES.IND_RESPUESTA_0C0, S_VISIBLES.NOMBRE_EU_0C0, S_VISIBLES.IND_OBSERVACIONES_0C0, S_VISIBLES.ORDEN_0C0, VAL_MIN_APROBADO, VAL_MIN_PELIGRO, NULL, NULL, NULL);

        END LOOP;

        FOR C_VISIBLES IN CAMPOS_VISIBLES LOOP
            INSERT INTO AA79BC4S01 (ID_AUDITORIA_0C4, ID_CAMPO_0C4, TIPO_CAMPO_0C4, NOMBRE_EU_0C4, IND_OBSERVACIONES_0C4, NOTA_OK_0C4, NOTA_NO_OK_0C4, IND_OBLIGATORIO_0C4, ID_SECCION_PADRE_0C4, ORDEN_0C4, POR_NIVEL_0_0C4, POR_NIVEL_1_0C4, POR_NIVEL_3_0C4, POR_NIVEL_5_0C4, OBSERV_0C4, NIVEL_CALIDAD_0C4, POR_NIVEL_CALIDAD_0C4, IND_MARCADO_0C4)
            VALUES (ID_AUDITORIA, C_VISIBLES.ID_0C1, C_VISIBLES.TIPO_CAMPO_0C1, C_VISIBLES.NOMBRE_EU_0C1, C_VISIBLES.IND_OBSERVACIONES_0C1, C_VISIBLES.NOTA_OK_0C1, C_VISIBLES.NOTA_NO_OK_0C1, C_VISIBLES.IND_OBLIGATORIO_0C1, C_VISIBLES.ID_SECCION_PADRE_0C1, C_VISIBLES.ORDEN_0C1, C_VISIBLES.POR_NIVEL_0_0B9, C_VISIBLES.POR_NIVEL_1_0B9, C_VISIBLES.POR_NIVEL_3_0B9, C_VISIBLES.POR_NIVEL_5_0B9, NULL, NULL, NULL, 'N');

        END LOOP;

    END IF;

    RETURN ID_AUDITORIA;
END;
/