CREATE OR REPLACE VIEW INF_SOLASKIDEAK ( 
DNICOMPLETO,
NOMBRE, APEL1, APEL2,
TIPO_ENTIDAD, COD_ENTIDAD,
DESC_ES, DESC_EU )
AS 
SELECT 
(PREDNI ||DNI || SUFDNI), 
NOMBRE, APEL1, APEL2, 
TIPO_ENTIDAD, COD_ENTIDAD, 
DESC_ES, DESC_EU 
FROM X54JAPI_SOLICITANTES 
WHERE ESTADO = 'V' AND (gestor_expedientes = 'S' OR  gestor_expedientes_bopv = 'S' OR gestor_expedientes_vip = 'S');
/