<title>Uda</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
	
<!-- BASE (sub-productos para patrones) -->
<link href="/appcont/rup-cac/rup/basic-theme/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />

<!-- jQuery UI (custom-theme) -->
<link href="/appcont/rup-cac/rup/custom-theme/jquery-ui-1.8.20.custom.css" rel="stylesheet" type="text/css" />

<!-- Patrones (basic-theme) -->
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.base-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.accordion-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.autocomplete-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.breadCrumb-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.combo-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.date-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.feedback-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.grid-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.lang-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.maint-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.menu-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.messages-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.tabs-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.time-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.toolbar-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.tooltip-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.upload-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.validate-2.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.wizard-2.0.0.css" rel="stylesheet" type="text/css" />

<!-- Aplicacion -->
<link href="/appcont/rup-cac/x21a/styles/x21a.css" rel="stylesheet" type="text/css" />
