<title>Uda</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
	
<!-- BASE (sub-productos para patrones) -->
<link href="/appcont/rup-cac/rup/basic-theme/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />

<!-- jQuery UI (custom-theme) -->
<link href="/appcont/rup-cac/rup/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />

<!-- Patrones (basic-theme) -->
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.base-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.accordion-1.0.0.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.autocomplete-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.breadCrumb-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.combo-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.date-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.feedback-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.grid-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.lang-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.maint-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.menu-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.message-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.tabs-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.time-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.toolbar-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.tooltip-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="/appcont/rup-cac/rup/basic-theme/theme.rup.upload-1.2.1.css" rel="stylesheet" type="text/css" />

<!-- Aplicacion -->
<link href="/appcont/rup-cac/x21a/styles/x21a.css" rel="stylesheet" type="text/css" />
