
package com.ejie.aa79b.webservices.cp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Q99rCPFacadeWSSoap", targetNamespace = "http://www.openuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Q99RCPFacadeWSSoap {


    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureDataAsXml")
    @WebResult(name = "getProcedureDataAsXmlResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureDataAsXml", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureDataAsXml")
    @ResponseWrapper(localName = "getProcedureDataAsXmlResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureDataAsXmlResponse")
    public String getProcedureDataAsXml(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sFamilia
     * @param sEntidad
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureList")
    @WebResult(name = "getProcedureListResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureList", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureList")
    @ResponseWrapper(localName = "getProcedureListResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureListResponse")
    public String getProcedureList(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sEntidad", targetNamespace = "http://www.openuri.org/")
        String sEntidad,
        @WebParam(name = "sFamilia", targetNamespace = "http://www.openuri.org/")
        String sFamilia);

    /**
     * 
     * @param sSessionToken
     * @param saProcedureIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureNamesByIds")
    @WebResult(name = "getProcedureNamesByIdsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureNamesByIds", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureNamesByIds")
    @ResponseWrapper(localName = "getProcedureNamesByIdsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureNamesByIdsResponse")
    public String getProcedureNamesByIds(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "saProcedureIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString saProcedureIds);

    /**
     * 
     * @param sOrganismID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getOrganismCertificateIdByOrganismId")
    @WebResult(name = "getOrganismCertificateIdByOrganismIdResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getOrganismCertificateIdByOrganismId", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetOrganismCertificateIdByOrganismId")
    @ResponseWrapper(localName = "getOrganismCertificateIdByOrganismIdResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetOrganismCertificateIdByOrganismIdResponse")
    public String getOrganismCertificateIdByOrganismId(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sOrganismID", targetNamespace = "http://www.openuri.org/")
        String sOrganismID);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getSoftConsultationContext")
    @WebResult(name = "getSoftConsultationContextResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getSoftConsultationContext", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetSoftConsultationContext")
    @ResponseWrapper(localName = "getSoftConsultationContextResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetSoftConsultationContextResponse")
    public String getSoftConsultationContext(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.openuri.org/getIfProcedureExists")
    @WebResult(name = "getIfProcedureExistsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getIfProcedureExists", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetIfProcedureExists")
    @ResponseWrapper(localName = "getIfProcedureExistsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetIfProcedureExistsResponse")
    public boolean getIfProcedureExists(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sInstanceId
     * @param sProcedureId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureTelActionFormsV22")
    @WebResult(name = "getProcedureTelActionFormsV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureTelActionFormsV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureTelActionFormsV22")
    @ResponseWrapper(localName = "getProcedureTelActionFormsV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureTelActionFormsV22Response")
    public String getProcedureTelActionFormsV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId);

    /**
     * 
     * @param sProcedureId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureTelActionForms")
    @WebResult(name = "getProcedureTelActionFormsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureTelActionForms", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureTelActionForms")
    @ResponseWrapper(localName = "getProcedureTelActionFormsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureTelActionFormsResponse")
    public String getProcedureTelActionForms(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureCatalogDataAsXml")
    @WebResult(name = "getProcedureCatalogDataAsXmlResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureCatalogDataAsXml", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureCatalogDataAsXml")
    @ResponseWrapper(localName = "getProcedureCatalogDataAsXmlResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureCatalogDataAsXmlResponse")
    public String getProcedureCatalogDataAsXml(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sProcedureId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAssociatedDocumentsFac")
    @WebResult(name = "getAssociatedDocumentsFacResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAssociatedDocumentsFac", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedDocumentsFac")
    @ResponseWrapper(localName = "getAssociatedDocumentsFacResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedDocumentsFacResponse")
    public String getAssociatedDocumentsFac(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId);

    /**
     * 
     * @param sProcedureId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getControlSubmissionContextFAC")
    @WebResult(name = "getControlSubmissionContextFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getControlSubmissionContextFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetControlSubmissionContextFAC")
    @ResponseWrapper(localName = "getControlSubmissionContextFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetControlSubmissionContextFACResponse")
    public String getControlSubmissionContextFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId);

    /**
     * 
     * @param sProcedureId
     * @param sInnerDocument
     * @param sSessionToken
     * @param stelematicActionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getDocumentsInfoFac")
    @WebResult(name = "getDocumentsInfoFacResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDocumentsInfoFac", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentsInfoFac")
    @ResponseWrapper(localName = "getDocumentsInfoFacResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentsInfoFacResponse")
    public String getDocumentsInfoFac(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sInnerDocument", targetNamespace = "http://www.openuri.org/")
        String sInnerDocument,
        @WebParam(name = "stelematicActionId", targetNamespace = "http://www.openuri.org/")
        String stelematicActionId);

    /**
     * 
     * @param sSessionToken
     * @param sNotifiedActID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getNotifiedActFAC")
    @WebResult(name = "getNotifiedActFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getNotifiedActFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetNotifiedActFAC")
    @ResponseWrapper(localName = "getNotifiedActFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetNotifiedActFACResponse")
    public String getNotifiedActFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sNotifiedActID", targetNamespace = "http://www.openuri.org/")
        String sNotifiedActID);

    /**
     * 
     * @param sProcedureId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAssociatedFormsFac")
    @WebResult(name = "getAssociatedFormsFacResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAssociatedFormsFac", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedFormsFac")
    @ResponseWrapper(localName = "getAssociatedFormsFacResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedFormsFacResponse")
    public String getAssociatedFormsFac(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureHtmlReport")
    @WebResult(name = "getProcedureHtmlReportResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureHtmlReport", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureHtmlReport")
    @ResponseWrapper(localName = "getProcedureHtmlReportResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureHtmlReportResponse")
    public String getProcedureHtmlReport(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sEntidad
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getManagingUnitList")
    @WebResult(name = "getManagingUnitListResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getManagingUnitList", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetManagingUnitList")
    @ResponseWrapper(localName = "getManagingUnitListResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetManagingUnitListResponse")
    public String getManagingUnitList(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sEntidad", targetNamespace = "http://www.openuri.org/")
        String sEntidad);

    /**
     * 
     * @param sProcedureId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureInboxID")
    @WebResult(name = "getProcedureInboxIDResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureInboxID", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureInboxID")
    @ResponseWrapper(localName = "getProcedureInboxIDResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureInboxIDResponse")
    public String getProcedureInboxID(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getNotifiedActForProcedureFAC")
    @WebResult(name = "getNotifiedActForProcedureFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getNotifiedActForProcedureFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetNotifiedActForProcedureFAC")
    @ResponseWrapper(localName = "getNotifiedActForProcedureFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetNotifiedActForProcedureFACResponse")
    public String getNotifiedActForProcedureFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sEntidad
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getFamilyProcedureList")
    @WebResult(name = "getFamilyProcedureListResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getFamilyProcedureList", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetFamilyProcedureList")
    @ResponseWrapper(localName = "getFamilyProcedureListResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetFamilyProcedureListResponse")
    public String getFamilyProcedureList(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sEntidad", targetNamespace = "http://www.openuri.org/")
        String sEntidad);

    /**
     * 
     * @param sSessionToken
     * @param saBuzones
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProceduresInboxID")
    @WebResult(name = "getProceduresInboxIDResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProceduresInboxID", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProceduresInboxID")
    @ResponseWrapper(localName = "getProceduresInboxIDResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProceduresInboxIDResponse")
    public String getProceduresInboxID(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "saBuzones", targetNamespace = "http://www.openuri.org/")
        ArrayOfString saBuzones);

    /**
     * 
     * @param sSessionToken
     * @param sDocumentTypeID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getDocumentTypeFAC")
    @WebResult(name = "getDocumentTypeFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDocumentTypeFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentTypeFAC")
    @ResponseWrapper(localName = "getDocumentTypeFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentTypeFACResponse")
    public String getDocumentTypeFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sDocumentTypeID", targetNamespace = "http://www.openuri.org/")
        String sDocumentTypeID);

    /**
     * 
     * @param sProcedureId
     * @param sFormId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAssociatedProcedureValidationsFAC")
    @WebResult(name = "getAssociatedProcedureValidationsFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAssociatedProcedureValidationsFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedProcedureValidationsFAC")
    @ResponseWrapper(localName = "getAssociatedProcedureValidationsFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedProcedureValidationsFACResponse")
    public String getAssociatedProcedureValidationsFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId,
        @WebParam(name = "sFormId", targetNamespace = "http://www.openuri.org/")
        String sFormId);

    /**
     * 
     * @param sProcedureId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureFac")
    @WebResult(name = "getProcedureFacResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureFac", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureFac")
    @ResponseWrapper(localName = "getProcedureFacResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureFacResponse")
    public String getProcedureFac(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAllDocuments")
    @WebResult(name = "getAllDocumentsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAllDocuments", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAllDocuments")
    @ResponseWrapper(localName = "getAllDocumentsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAllDocumentsResponse")
    public String getAllDocuments(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sProcedureId
     * @param sSessionToken
     * @param sDocumentData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getDocumentForProcedure")
    @WebResult(name = "getDocumentForProcedureResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDocumentForProcedure", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentForProcedure")
    @ResponseWrapper(localName = "getDocumentForProcedureResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentForProcedureResponse")
    public String getDocumentForProcedure(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sDocumentData", targetNamespace = "http://www.openuri.org/")
        String sDocumentData);

    /**
     * 
     * @param sProcedureId
     * @param sSessionToken
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://www.openuri.org/isOpenFAC")
    @WebResult(name = "isOpenFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "isOpenFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.IsOpenFAC")
    @ResponseWrapper(localName = "isOpenFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.IsOpenFACResponse")
    public Boolean isOpenFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getConsultationContext")
    @WebResult(name = "getConsultationContextResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getConsultationContext", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetConsultationContext")
    @ResponseWrapper(localName = "getConsultationContextResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetConsultationContextResponse")
    public String getConsultationContext(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureCatalogHtmlReport")
    @WebResult(name = "getProcedureCatalogHtmlReportResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureCatalogHtmlReport", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureCatalogHtmlReport")
    @ResponseWrapper(localName = "getProcedureCatalogHtmlReportResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureCatalogHtmlReportResponse")
    public String getProcedureCatalogHtmlReport(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAllOfProceduresFAC")
    @WebResult(name = "getAllOfProceduresFACResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAllOfProceduresFAC", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAllOfProceduresFAC")
    @ResponseWrapper(localName = "getAllOfProceduresFACResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAllOfProceduresFACResponse")
    public String getAllOfProceduresFAC(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param bAllowAdminStart
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureFamilies")
    @WebResult(name = "getProcedureFamiliesResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureFamilies", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureFamilies")
    @ResponseWrapper(localName = "getProcedureFamiliesResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureFamiliesResponse")
    public String getProcedureFamilies(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "bAllowAdminStart", targetNamespace = "http://www.openuri.org/")
        Boolean bAllowAdminStart);

    /**
     * 
     * @param sSessionToken
     * @param sSearchProceduresParametersXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/searchProcedures")
    @WebResult(name = "searchProceduresResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "searchProcedures", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.SearchProcedures")
    @ResponseWrapper(localName = "searchProceduresResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.SearchProceduresResponse")
    public String searchProcedures(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sSearchProceduresParametersXml", targetNamespace = "http://www.openuri.org/")
        String sSearchProceduresParametersXml);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getCalendarTypes")
    @WebResult(name = "getCalendarTypesResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getCalendarTypes", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetCalendarTypes")
    @ResponseWrapper(localName = "getCalendarTypesResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetCalendarTypesResponse")
    public String getCalendarTypes(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAppealTypes")
    @WebResult(name = "getAppealTypesResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAppealTypes", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAppealTypes")
    @ResponseWrapper(localName = "getAppealTypesResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAppealTypesResponse")
    public String getAppealTypes(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAppealTypesForProcedure")
    @WebResult(name = "getAppealTypesForProcedureResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAppealTypesForProcedure", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAppealTypesForProcedure")
    @ResponseWrapper(localName = "getAppealTypesForProcedureResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAppealTypesForProcedureResponse")
    public String getAppealTypesForProcedure(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAppealsForProcedure")
    @WebResult(name = "getAppealsForProcedureResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAppealsForProcedure", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAppealsForProcedure")
    @ResponseWrapper(localName = "getAppealsForProcedureResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAppealsForProcedureResponse")
    public String getAppealsForProcedure(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getTelematicActions")
    @WebResult(name = "getTelematicActionsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getTelematicActions", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetTelematicActions")
    @ResponseWrapper(localName = "getTelematicActionsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetTelematicActionsResponse")
    public String getTelematicActions(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sTelematicActionID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getTelematicAction")
    @WebResult(name = "getTelematicActionResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getTelematicAction", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetTelematicAction")
    @ResponseWrapper(localName = "getTelematicActionResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetTelematicActionResponse")
    public String getTelematicAction(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sTelematicActionID", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionID);

    /**
     * 
     * @param sInstanceId
     * @param sProcedureId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAssociatedDocumentsFacV22")
    @WebResult(name = "getAssociatedDocumentsFacV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAssociatedDocumentsFacV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedDocumentsFacV22")
    @ResponseWrapper(localName = "getAssociatedDocumentsFacV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedDocumentsFacV22Response")
    public String getAssociatedDocumentsFacV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId);

    /**
     * 
     * @param sInstanceId
     * @param sProcedureId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAssociatedFormsFacV22")
    @WebResult(name = "getAssociatedFormsFacV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAssociatedFormsFacV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedFormsFacV22")
    @ResponseWrapper(localName = "getAssociatedFormsFacV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedFormsFacV22Response")
    public String getAssociatedFormsFacV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId);

    /**
     * 
     * @param sInstanceId
     * @param sProcedureId
     * @param sInnerDocument
     * @param sSessionToken
     * @param stelematicActionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getDocumentsInfoFacV22")
    @WebResult(name = "getDocumentsInfoFacV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDocumentsInfoFacV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentsInfoFacV22")
    @ResponseWrapper(localName = "getDocumentsInfoFacV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentsInfoFacV22Response")
    public String getDocumentsInfoFacV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sInnerDocument", targetNamespace = "http://www.openuri.org/")
        String sInnerDocument,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId,
        @WebParam(name = "stelematicActionId", targetNamespace = "http://www.openuri.org/")
        String stelematicActionId);

    /**
     * 
     * @param sInstanceId
     * @param sProcedureId
     * @param sFormId
     * @param sTelematicActionId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAssociatedProcedureValidationsFACV22")
    @WebResult(name = "getAssociatedProcedureValidationsFACV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAssociatedProcedureValidationsFACV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedProcedureValidationsFACV22")
    @ResponseWrapper(localName = "getAssociatedProcedureValidationsFACV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAssociatedProcedureValidationsFACV22Response")
    public String getAssociatedProcedureValidationsFACV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId,
        @WebParam(name = "sFormId", targetNamespace = "http://www.openuri.org/")
        String sFormId);

    /**
     * 
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getTelematicActionInstancesByProcedureId")
    @WebResult(name = "getTelematicActionInstancesByProcedureIdResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getTelematicActionInstancesByProcedureId", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetTelematicActionInstancesByProcedureId")
    @ResponseWrapper(localName = "getTelematicActionInstancesByProcedureIdResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetTelematicActionInstancesByProcedureIdResponse")
    public String getTelematicActionInstancesByProcedureId(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getAllNotifiedActos")
    @WebResult(name = "getAllNotifiedActosResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getAllNotifiedActos", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAllNotifiedActos")
    @ResponseWrapper(localName = "getAllNotifiedActosResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetAllNotifiedActosResponse")
    public String getAllNotifiedActos(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param sInstanceId
     * @param sTelematicActionID
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getManagingUnitInfoForTelematicActionV22")
    @WebResult(name = "getManagingUnitInfoForTelematicActionV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getManagingUnitInfoForTelematicActionV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetManagingUnitInfoForTelematicActionV22")
    @ResponseWrapper(localName = "getManagingUnitInfoForTelematicActionV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetManagingUnitInfoForTelematicActionV22Response")
    public String getManagingUnitInfoForTelematicActionV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID,
        @WebParam(name = "sTelematicActionID", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionID,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId);

    /**
     * 
     * @param sXmlProcedureTelActionInstanceIds
     * @param sInnerDocument
     * @param sSessionToken
     * @return
     *     returns com.ejie.aa79b.webservices.cp.Map
     */
    @WebMethod(action = "http://www.openuri.org/getDocumentTypesForProcedureV22")
    @WebResult(name = "getDocumentTypesForProcedureV22Result", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDocumentTypesForProcedureV22", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentTypesForProcedureV22")
    @ResponseWrapper(localName = "getDocumentTypesForProcedureV22Response", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentTypesForProcedureV22Response")
    public Map getDocumentTypesForProcedureV22(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sXmlProcedureTelActionInstanceIds", targetNamespace = "http://www.openuri.org/")
        String sXmlProcedureTelActionInstanceIds,
        @WebParam(name = "sInnerDocument", targetNamespace = "http://www.openuri.org/")
        String sInnerDocument);

    /**
     * 
     * @param sTelematicActionId
     * @param sProcedureID
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureTelActionInstancesByProcedureId")
    @WebResult(name = "getProcedureTelActionInstancesByProcedureIdResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureTelActionInstancesByProcedureId", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureTelActionInstancesByProcedureId")
    @ResponseWrapper(localName = "getProcedureTelActionInstancesByProcedureIdResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureTelActionInstancesByProcedureIdResponse")
    public String getProcedureTelActionInstancesByProcedureId(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureID", targetNamespace = "http://www.openuri.org/")
        String sProcedureID,
        @WebParam(name = "sTelematicActionId", targetNamespace = "http://www.openuri.org/")
        String sTelematicActionId);

    /**
     * 
     * @param sSessionToken
     * @param saProcedureIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureNamesByIdsXml")
    @WebResult(name = "getProcedureNamesByIdsXmlResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureNamesByIdsXml", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureNamesByIdsXml")
    @ResponseWrapper(localName = "getProcedureNamesByIdsXmlResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureNamesByIdsXmlResponse")
    public String getProcedureNamesByIdsXml(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "saProcedureIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString saProcedureIds);

    /**
     * 
     * @param saTipos
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureCatalogDataAsXmlWithFilters")
    @WebResult(name = "getProcedureCatalogDataAsXmlWithFiltersResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureCatalogDataAsXmlWithFilters", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureCatalogDataAsXmlWithFilters")
    @ResponseWrapper(localName = "getProcedureCatalogDataAsXmlWithFiltersResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureCatalogDataAsXmlWithFiltersResponse")
    public String getProcedureCatalogDataAsXmlWithFilters(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "saTipos", targetNamespace = "http://www.openuri.org/")
        ArrayOfString saTipos);

    /**
     * 
     * @param sProcedureId
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getSignProcedureType")
    @WebResult(name = "getSignProcedureTypeResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getSignProcedureType", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetSignProcedureType")
    @ResponseWrapper(localName = "getSignProcedureTypeResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetSignProcedureTypeResponse")
    public String getSignProcedureType(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId);

    /**
     * 
     * @param lProcesIds
     * @param sSessionToken
     * @return
     *     returns com.ejie.aa79b.webservices.cp.Map
     */
    @WebMethod(action = "http://www.openuri.org/getProceduresPlatea")
    @WebResult(name = "getProceduresPlateaResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProceduresPlatea", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProceduresPlatea")
    @ResponseWrapper(localName = "getProceduresPlateaResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProceduresPlateaResponse")
    public Map getProceduresPlatea(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "lProcesIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString lProcesIds);

    /**
     * 
     * @param sSessionToken
     * @param lProcesW93BIds
     * @return
     *     returns com.ejie.aa79b.webservices.cp.Map
     */
    @WebMethod(action = "http://www.openuri.org/getProceduresW93B")
    @WebResult(name = "getProceduresW93BResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProceduresW93B", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProceduresW93B")
    @ResponseWrapper(localName = "getProceduresW93BResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProceduresW93BResponse")
    public Map getProceduresW93B(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "lProcesW93BIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString lProcesW93BIds);

    /**
     * 
     * @param sParameters
     * @param sInstanceId
     * @param sProcedureId
     * @param sInnerDocument
     * @param sSessionToken
     * @param stelematicActionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getDocumentsInfoParameters")
    @WebResult(name = "getDocumentsInfoParametersResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDocumentsInfoParameters", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentsInfoParameters")
    @ResponseWrapper(localName = "getDocumentsInfoParametersResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDocumentsInfoParametersResponse")
    public String getDocumentsInfoParameters(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "sProcedureId", targetNamespace = "http://www.openuri.org/")
        String sProcedureId,
        @WebParam(name = "sInnerDocument", targetNamespace = "http://www.openuri.org/")
        String sInnerDocument,
        @WebParam(name = "sInstanceId", targetNamespace = "http://www.openuri.org/")
        String sInstanceId,
        @WebParam(name = "stelematicActionId", targetNamespace = "http://www.openuri.org/")
        String stelematicActionId,
        @WebParam(name = "sParameters", targetNamespace = "http://www.openuri.org/")
        String sParameters);

    /**
     * 
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getProcedureListCodes")
    @WebResult(name = "getProcedureListCodesResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getProcedureListCodes", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureListCodes")
    @ResponseWrapper(localName = "getProcedureListCodesResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetProcedureListCodesResponse")
    public String getProcedureListCodes(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken);

    /**
     * 
     * @param void1
     */
    @WebMethod(action = "getSingProcedureType")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void getSingProcedureType(
        @WebParam(name = "void1", targetNamespace = "http://www.openuri.org/", partName = "void1")
        Object void1);

    /**
     * 
     * @param void2
     */
    @WebMethod(action = "getManagingUnitInfoForTelematicAction")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void getManagingUnitInfoForTelematicAction(
        @WebParam(name = "void2", targetNamespace = "http://www.openuri.org/", partName = "void2")
        Object void2);

    /**
     * 
     * @param void3
     */
    @WebMethod(action = "getProcedureTelActionInstance")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void getProcedureTelActionInstance(
        @WebParam(name = "void3", targetNamespace = "http://www.openuri.org/", partName = "void3")
        Object void3);

    /**
     * 
     * @param sSessionToken
     * @param lEntityIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getEntitiesByIds")
    @WebResult(name = "getEntitiesByIdsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getEntitiesByIds", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetEntitiesByIds")
    @ResponseWrapper(localName = "getEntitiesByIdsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetEntitiesByIdsResponse")
    public String getEntitiesByIds(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "lEntityIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString lEntityIds);

    /**
     * 
     * @param lOrganismIds
     * @param sSessionToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getOrganismsByIds")
    @WebResult(name = "getOrganismsByIdsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getOrganismsByIds", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetOrganismsByIds")
    @ResponseWrapper(localName = "getOrganismsByIdsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetOrganismsByIdsResponse")
    public String getOrganismsByIds(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "lOrganismIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString lOrganismIds);

    /**
     * 
     * @param sSessionToken
     * @param lDepartmentIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getDepartmentsByIds")
    @WebResult(name = "getDepartmentsByIdsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getDepartmentsByIds", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDepartmentsByIds")
    @ResponseWrapper(localName = "getDepartmentsByIdsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetDepartmentsByIdsResponse")
    public String getDepartmentsByIds(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "lDepartmentIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString lDepartmentIds);

    /**
     * 
     * @param sSessionToken
     * @param lManagingUnitIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.openuri.org/getManagingUnitsByIds")
    @WebResult(name = "getManagingUnitsByIdsResult", targetNamespace = "http://www.openuri.org/")
    @RequestWrapper(localName = "getManagingUnitsByIds", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetManagingUnitsByIds")
    @ResponseWrapper(localName = "getManagingUnitsByIdsResponse", targetNamespace = "http://www.openuri.org/", className = "com.ejie.aa79b.webservices.cp.GetManagingUnitsByIdsResponse")
    public String getManagingUnitsByIds(
        @WebParam(name = "sSessionToken", targetNamespace = "http://www.openuri.org/")
        String sSessionToken,
        @WebParam(name = "lManagingUnitIds", targetNamespace = "http://www.openuri.org/")
        ArrayOfString lManagingUnitIds);

}
