<%--  
 -- Copyright 2012 E.J.I.E., S.A.
 -- Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
 -- Solo podrá usarse esta obra si se respeta la Licencia.
 -- Puede obtenerse una copia de la Licencia en
 -- 
 -- http://ec.europa.eu/idabc/eupl.html
 -- 
 -- Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
 -- el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
 -- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 -- Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
 -- que establece la Licencia. 
 --%>
 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- BASE (sub-productos para patrones) -->
<link href="${staticsUrl}/rup/basic-theme/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />

<!-- jQuery UI (custom-theme) -->
<link href="${staticsUrl}/rup/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />

<!-- Patrones (basic-theme) -->
<link href="${staticsUrl}/rup/basic-theme/theme.rup.base-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.accordion-1.0.0.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.autocomplete-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.breadCrumb-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.combo-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.date-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.feedback-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.grid-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.lang-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.maint-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.menu-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.messages-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tabs-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.time-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.toolbar-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tooltip-1.2.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.upload-1.2.1.css" rel="stylesheet" type="text/css" />
	