package com.ejie.aa79b.control;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DBConstants;
import com.ejie.aa79b.model.DocumentoTarea;
import com.ejie.aa79b.model.DocumentoTareaAdjunto;
import com.ejie.aa79b.model.DocumentosAlinear;
import com.ejie.aa79b.model.DocumentosExpediente;
import com.ejie.aa79b.model.DocumentosPostTraduccionBOE;
import com.ejie.aa79b.model.Fichero;
import com.ejie.aa79b.model.FicheroDocExp;
import com.ejie.aa79b.model.SubidaTarea;
import com.ejie.aa79b.service.DocumentosExpedienteService;
import com.ejie.aa79b.service.DocumentosGeneralService;
import com.ejie.aa79b.service.OidsAuxiliarService;
import com.ejie.aa79b.service.TareasGeneralService;
import com.ejie.aa79b.webservices.PIDService;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;

/**
 * TiposRevisionController generated by UDA, 28-nov-2017 15:23:30.
 *
 * @author UDA
 */

@Controller
@RequestMapping(value = "/documentosgeneral")

public class DocumentosGeneralController {

	private static final Logger LOGGER = LoggerFactory.getLogger(DocumentosGeneralController.class);
	public static final String ERROR_PIF = "mensaje.fichero.errorPIF";

	@Autowired
	private DocumentosGeneralService documentosGeneralService;
	@Autowired
	private TareasGeneralService tareasGeneralService;
	@Autowired()
	private PIDService pidService;
	@Autowired()
	private ReloadableResourceBundleMessageSource appMessageSource;
	@Autowired()
	private DocumentosExpedienteService documentosExpedienteService;
	@Autowired()
	private OidsAuxiliarService oidsAuxiliarService;

	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 *
	 */

	/**
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 *
	 * @param idFichero088
	 *            Long
	 * @return DocumentoTareaAdjunto Objeto correspondiente al identificador
	 *         indicado.
	 */
	@RequestMapping(value = "/{idFichero088}", method = RequestMethod.GET)
	public @ResponseBody DocumentoTareaAdjunto get(@PathVariable BigDecimal idFichero088) {
		DocumentoTareaAdjunto documentoTareaAdjunto = new DocumentoTareaAdjunto();
		documentoTareaAdjunto.setIdFichero(idFichero088);
		documentoTareaAdjunto = this.documentosGeneralService.find(documentoTareaAdjunto);
		DocumentosGeneralController.LOGGER.info("[GET - findBy_PK] : Obtener DocumentoTareaAdjunto por PK");
		return documentoTareaAdjunto;
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param documentoTareaAdjunto
	 *            DocumentoTareaAdjunto Bean que contiene la informacion a
	 *            modificar.
	 * @return DocumentoTareaAdjunto Bean resultante de la modificacion.
	 */
	@RequestMapping(method = RequestMethod.PUT)
	public @ResponseBody DocumentoTareaAdjunto edit(@RequestBody DocumentoTareaAdjunto documentoTareaAdjunto) {
		DocumentoTareaAdjunto docTareaAdjuntoAux = this.documentosGeneralService.update(documentoTareaAdjunto);
		DocumentosGeneralController.LOGGER.info("[PUT] : DocumentoTareaAdjunto actualizado correctamente");
		return docTareaAdjuntoAux;
	}

	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param documentoTareaAdjunto
	 *            DocumentoTareaAdjunto Bean que contiene la informacion con la
	 *            que se va a crear el nuevo registro.
	 * @return DocumentoTareaAdjunto Bean resultante del proceso de creacion.
	 */
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody DocumentoTareaAdjunto add(@RequestBody DocumentoTareaAdjunto documentoTareaAdjunto) {
		DocumentoTareaAdjunto docTareaAdjuntoAux = this.documentosGeneralService.add(documentoTareaAdjunto);
		DocumentosGeneralController.LOGGER.info("[POST] : DocumentoTareaAdjunto insertado correctamente");
		return docTareaAdjuntoAux;
	}

	@RequestMapping(value = "/eliminarDocFinal/{idTarea}/{elIdDocOriginal}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
	public void removeDocFinal(@PathVariable BigDecimal idTarea, @PathVariable BigDecimal elIdDocOriginal) {
		DocumentosGeneralController.LOGGER.info(
				"[DELETE - eliminarDocFinal] : Eliminar doc original, adjunto, ficheros del PID  y tablas intemedias");
		this.documentosGeneralService.eliminarDocFinal(idTarea, elIdDocOriginal);
	}

	@RequestMapping(value = "/eliminarDocXliff/{idTarea}/{elIdDocXliff}/{elOid}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
	public void removeDocXliff(@PathVariable BigDecimal idTarea, @PathVariable BigDecimal elIdDocXliff,
			@PathVariable String elOid) {
		DocumentosGeneralController.LOGGER.info(
				"[DELETE - eliminarDocFinal] : Eliminar doc elIdDocXliff, adjunto, ficheros del PID  y tablas intemedias");
		this.documentosGeneralService.eliminarDocXliff(idTarea, elIdDocXliff, elOid);
	}

	/**
	 * PIF / PID
	 *
	 * @param fichero
	 *            MultipartFile.
	 * @param request
	 *            HttpServletRequest.
	 * @param idioma
	 *            Locale.
	 * @return Fichero Bean Fichero.
	 */

	@RequestMapping(value = "/subidaFicheroFinal", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto subidaFicheroFinal(@RequestBody SubidaTarea subidaTarea) {
		DocumentosGeneralController.LOGGER.info("DocumentosGeneral : subidaFichero");
		Locale locale = LocaleContextHolder.getLocale();

		DocumentoTareaAdjunto bean = new DocumentoTareaAdjunto();
		DocumentoTarea docTarea = subidaFicheroMontajeObjeto(subidaTarea, bean);
		this.addUpdateUploadDocFinal(subidaTarea.getFichero(), subidaTarea.getIdTablaIntermedia(), locale, docTarea,
				bean, subidaTarea.getFichero().getNombre(), subidaTarea.getOidDocRevisado());

		return bean;
	}

	@RequestMapping(value = "/subidaFicheroOriginal", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto subidaFicheroOriginal(@RequestBody SubidaTarea subidaTarea) {
		DocumentosGeneralController.LOGGER.info("DocumentosGeneral : subidaFichero");
		Locale locale = LocaleContextHolder.getLocale();

		DocumentoTareaAdjunto bean = new DocumentoTareaAdjunto();
		DocumentoTarea docTarea = subidaFicheroMontajeObjeto(subidaTarea, bean);
		this.addUpdateUploadDocOriginal(subidaTarea.getFichero(), subidaTarea.getIdTablaIntermedia(), locale, docTarea,
				bean, subidaTarea.getFichero().getNombre(), subidaTarea.getOidDocRevisado());

		return bean;
	}


	private DocumentoTarea subidaFicheroMontajeObjeto(SubidaTarea subidaTarea, DocumentoTareaAdjunto bean) {
		DocumentoTarea filterDocumentoTarea = new DocumentoTarea();
		filterDocumentoTarea.setIdTarea(subidaTarea.getIdTarea());
		DocumentosExpediente docOriginal = new DocumentosExpediente();
		docOriginal.setIdDoc(subidaTarea.getIdDocOriginal());
		filterDocumentoTarea.setDocumentoOriginal(docOriginal);

		// obtenemos documentos originales de tarea y si lo tiene el fichero de
		// tarea
		DocumentoTarea docTarea = null;
		switch (subidaTarea.getIdTablaIntermedia()) {
		case 87:
			docTarea = this.tareasGeneralService.findRegTraduccionRevision(filterDocumentoTarea);
			break;
		case 92:
			docTarea = this.tareasGeneralService.findRegCorredaccion(filterDocumentoTarea);
			break;
		case 93:
			docTarea = this.tareasGeneralService.findRegJustificante(filterDocumentoTarea);
			break;
		default:
			break;
		}
		bean.setNombre(subidaTarea.getFichero().getNombre());
		int elPunto = subidaTarea.getFichero().getNombre().lastIndexOf('.');
		bean.setExtension(subidaTarea.getFichero().getNombre().substring(elPunto + 1,
				subidaTarea.getFichero().getNombre().length()));
		bean.setTamano(subidaTarea.getFichero().getTamano());
		bean.setContentType(subidaTarea.getFichero().getContentType());
		bean.setIdTarea(subidaTarea.getIdTarea());
		bean.setEncriptado(subidaTarea.getFichero().getEncriptado());
		bean.setOid(subidaTarea.getFichero().getOid());
		bean.setIdDocOriginal(subidaTarea.getIdDocOriginal());
		// si tiene fichero de tarea lo inserta. Se comprueba si es nulo en
		// aadUpdate para saber si insertar uno nuevo en 88 o actualizar el que
		// esta
		if (docTarea.getDocumentoFinalOriginal() != null) {
			bean.setIdDocOriginalFinal(docTarea.getDocumentoFinalOriginal().getIdFichero());
		}
		bean.setIdFichero(docTarea.getDocumentoAdjunto().getIdFichero());
		if (subidaTarea.isDocOriginal()) {
			bean.setTitulo(docTarea.getDocumentoOriginal().getTitulo());
		} else {
			bean.setTitulo(docTarea.getDocumentoOriginal().getTitulo() + "_" + subidaTarea.getIdIdiomaDest());
		}
		bean.setIndVisible(docTarea.getDocumentoAdjunto().getIndVisible());
		bean.setReqEncriptadoOriginal((docTarea.getDocumentoOriginal().getFicheros()).get(0).getEncriptado());
		return docTarea;
	}

	@RequestMapping(value = "/subidaFicheroLerrokoa", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto subidaFicheroLerrokoa(@RequestBody SubidaTarea subidaTarea) {
		Locale locale = LocaleContextHolder.getLocale();
		DocumentosGeneralController.LOGGER.info("DocumentosGeneral : subidaFichero");
		DocumentoTareaAdjunto bean = new DocumentoTareaAdjunto();
		bean.setNombre(subidaTarea.getFichero().getNombre());
		bean.setExtension(subidaTarea.getFichero().getExtension());
		bean.setEncriptado(subidaTarea.getFichero().getEncriptado());
		bean.setTamano(subidaTarea.getFichero().getTamano());
		bean.setContentType(subidaTarea.getFichero().getContentType());
		bean.setIdTarea(subidaTarea.getIdTarea());
		bean.setTitulo(subidaTarea.getFichero().getNombre() + "_" + locale.getLanguage());
		bean.setOid(subidaTarea.getFichero().getOid());
		// anyadir a 88
		DocumentoTareaAdjunto docuAdd = this.documentosGeneralService.add(bean);
		// borrar oid nuevo de tabla A0
		this.oidsAuxiliarService.remove(bean.getOid());
		DocumentosAlinear docInsertado = this.documentosGeneralService
				.consultaFicherosAlinear(subidaTarea.getIdTarea());

		if (docInsertado != null && docInsertado.getIdTarea() != null) {
			// insertar informe
			docInsertado.setIdFicheroLerroko(docuAdd.getIdFichero());
			docInsertado.setFechaAltaLerroko(new Date());
			docInsertado.setIdFicheroLerroko(docInsertado.getFicheroLerroko().getIdFichero());
			this.documentosGeneralService.updateB6(docInsertado);
		} else {
			docInsertado = new DocumentosAlinear();
			docInsertado.setIdTarea(subidaTarea.getIdTarea());
			docInsertado.setIndCorreciones(subidaTarea.getIndCorrecciones());
			// insertar informe (obligatorio)
			docInsertado.setIdFicheroLerroko(docuAdd.getIdFichero());
			docInsertado.setFechaAltaLerroko(new Date());
			this.documentosGeneralService.addB6(docInsertado);
		}

		return bean;
	}

	@RequestMapping(value = "/consultaFicherosAlinear/{idTarea}", method = RequestMethod.GET)
	public @ResponseBody DocumentosAlinear consultaFicherosAlinear(@PathVariable() BigDecimal idTarea) {
		DocumentosGeneralController.LOGGER.info("[POST - filter] : Obtener fichero alinear");
		DocumentosAlinear documentosAlinear = this.documentosGeneralService.consultaFicherosAlinear(idTarea);
		return documentosAlinear;
	}

	@RequestMapping(value = "/actualizarValorIndCorreccionesAlinear/{idTarea}/{indCorrecciones}", method = RequestMethod.POST)
	public @ResponseBody Integer actualizarValorIndCorreccionesAlinear(@PathVariable() BigDecimal idTarea,
			@PathVariable String indCorrecciones) {
		DocumentosGeneralController.LOGGER
				.info("[POST - actualizarValorIndCorreccionesAlinear] : actualizar valor ind correcciones");
		return this.documentosGeneralService.actualizarValorIndCorreccionesAlinear(idTarea, indCorrecciones);

	}

	// TITULO Y ReqEncriptadoOriginal?
	@RequestMapping(value = "/subidaFicheroBOE", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto subidaFicheroBOE(@RequestBody SubidaTarea subidaTarea) {
		Locale locale = LocaleContextHolder.getLocale();
		DocumentosGeneralController.LOGGER.info("DocumentosGeneral : subidaFichero");
		DocumentoTareaAdjunto bean = new DocumentoTareaAdjunto();
		bean.setNombre(subidaTarea.getFichero().getNombre());
		bean.setExtension(subidaTarea.getFichero().getExtension());
		bean.setEncriptado(subidaTarea.getFichero().getEncriptado());
		bean.setTamano(subidaTarea.getFichero().getTamano());
		bean.setContentType(subidaTarea.getFichero().getContentType());
		bean.setIdTarea(subidaTarea.getIdTarea());
		bean.setTitulo(subidaTarea.getFichero().getNombre() + "_" + locale.getLanguage());
		bean.setOid(subidaTarea.getFichero().getOid());
		// anyadir a 88
		DocumentoTareaAdjunto docuAdd = this.documentosGeneralService.add(bean);
		// borrar oid nuevo de tabla A0
		this.oidsAuxiliarService.remove(bean.getOid());
		DocumentosPostTraduccionBOE docInsertado = this.documentosGeneralService
				.consultaFicherosBOE(subidaTarea.getIdTarea());

		if (docInsertado != null && docInsertado.getIdTarea() != null) {
			if (Constants.UNO == subidaTarea.getDestinoUpload()) {
				// insertar informe
				docInsertado.setIdFicheroInforme(docuAdd.getIdFichero());
				docInsertado.setFechaAltaInforme(new Date());
				docInsertado.setIdFicheroDoc(docInsertado.getFicheroDoc().getIdFichero());

			} else {
				// insertar documento
				docInsertado.setIdFicheroDoc(docuAdd.getIdFichero());
				docInsertado.setFechaAltaDoc(new Date());
				docInsertado.setIdFicheroInforme(docInsertado.getFicheroInforme().getIdFichero());
			}
			this.documentosGeneralService.update86(docInsertado, subidaTarea.getDestinoUpload());
		} else {
			docInsertado = new DocumentosPostTraduccionBOE();
			docInsertado.setIdTarea(subidaTarea.getIdTarea());
			docInsertado.setIndCorreciones(subidaTarea.getIndCorrecciones());
			if (Constants.UNO == subidaTarea.getDestinoUpload()) {
				// insertar informe (obligatorio)
				docInsertado.setIdFicheroInforme(docuAdd.getIdFichero());
				docInsertado.setFechaAltaInforme(new Date());
			} else {
				// insertar documento
				docInsertado.setIdFicheroDoc(docuAdd.getIdFichero());
				docInsertado.setFechaAltaDoc(new Date());
			}
			this.documentosGeneralService.add86(docInsertado);
		}

		return bean;
	}

	@RequestMapping(value = "/consultaFicherosBOE/{idTarea}", method = RequestMethod.GET)
	public @ResponseBody DocumentosPostTraduccionBOE consultaFicherosBOE(@PathVariable() BigDecimal idTarea) {
		DocumentosGeneralController.LOGGER.info("[POST - filter] : Obtener findTarea");
		DocumentosPostTraduccionBOE docusPostTraduccionBOE = this.documentosGeneralService.consultaFicherosBOE(idTarea);
		return docusPostTraduccionBOE;
	}

	@RequestMapping(value = "/actualizarValorIndCorreccionesBOE/{idTarea}/{indCorrecciones}", method = RequestMethod.POST)
	public @ResponseBody Integer actualizarValorIndCorreccionesBOE(@PathVariable() BigDecimal idTarea,
			@PathVariable String indCorrecciones) {
		DocumentosGeneralController.LOGGER
				.info("[POST - actualizarValorIndCorreccionesBOE] : actualizar valor ind correcciones");
		return this.documentosGeneralService.actualizarValorIndCorreccionesBOE(idTarea, indCorrecciones);

	}

	/**
	 * @param fichero
	 * @param idTablaIntermedia
	 * @param locale
	 * @param docTarea
	 * @param bean
	 * @param nombreFichero
	 * @param oidDocRevisado
	 */
	public void addUpdateUploadDocFinal(Fichero fichero, Integer idTablaIntermedia, Locale locale,
			DocumentoTarea docTarea, DocumentoTareaAdjunto bean, String nombreFichero, String oidDocRevisado) {
		try {

			if (bean.getIdFichero() != null) {
				// guardar 88 y tabla intermedia
				this.documentosGeneralService.updateCondicional(bean, idTablaIntermedia);
				// comprobamos si hay mas ficheros en la 88 con ese oid, por si
				// lo hay, para no anyadirlo a la A0
				Boolean esta = this.documentosGeneralService.oidEstaEn88OEn56(docTarea.getDocumentoAdjunto().getOid());
				// comprobamos si el oidDoc revisado no es de un documento de la
				// 56 y si ese oid no lo tiene otro archivo de la 88 para,
				// en los dos casos, no borrarlo
				if (!esta) {
					// anyadir oid del viejo a la tabla A0
					this.oidsAuxiliarService.add(docTarea.getDocumentoAdjunto().getOid());
				}
			} else {
				if (StringUtils.isNotEmpty(bean.getOid())) {
					// crear 88 y tabla intermedia
					boolean existeEntrada = this.documentosGeneralService.isRowCreated(bean.getIdTarea(), bean.getIdDocOriginal(), idTablaIntermedia);
					if (!existeEntrada) {
						this.documentosGeneralService.addCondicional(bean, idTablaIntermedia);
					} else {
						DocumentoTareaAdjunto ficheroFinal = this.documentosGeneralService.add(bean);
						bean.setIdFichero(ficheroFinal.getIdFichero());
						this.documentosGeneralService.update92(bean);
					}

				} else {
					DocumentosGeneralController.LOGGER
							.error("DocumentosGeneralController: - addUpdateUploadDocFinal al PID Error");
					bean.setError(
							this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
				}
			}
			// borrar oid nuevo de tabla A0
			this.oidsAuxiliarService.remove(bean.getOid());
		} catch (Exception e) {
			DocumentosGeneralController.LOGGER.error("DocumentosGeneralController: - addUpdateUploadDocFinal Error: ",
					e);
			bean.setError(this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
		}
	}

	public void addUpdateUploadDocOriginal(Fichero fichero, Integer idTablaIntermedia, Locale locale,
			DocumentoTarea docTarea, DocumentoTareaAdjunto bean, String nombreFichero, String oidDocRevisado) {
		try {

			if (bean.getIdDocOriginalFinal() != null) {
				// guardar 88 y tabla intermedia
				bean.setIdFichero(bean.getIdDocOriginalFinal());
				this.documentosGeneralService.update(bean);
				this.documentosGeneralService.updateDocOriginalFinal(bean);
				// comprobamos si hay mas ficheros en la 88 con ese oid, por si
				// lo hay, para no anyadirlo a la A0
				Boolean esta = this.documentosGeneralService.oidEstaEn88OEn56(docTarea.getDocumentoFinalOriginal().getOid());
				// comprobamos si el oidDoc revisado no es de un documento de la
				// 56 y si ese oid no lo tiene otro archivo de la 88 para,
				// en los dos casos, no borrarlo
				if (!esta) {
					// anyadir oid del viejo a la tabla A0
					this.oidsAuxiliarService.add(docTarea.getDocumentoFinalOriginal().getOid());
				}
			} else {
				if (StringUtils.isNotEmpty(bean.getOid())) {
					// crear 88 y tabla intermedia
					if (bean.getIdDocOriginalFinal() == null) {
						DocumentoTareaAdjunto originalFinal = this.documentosGeneralService.add(bean);
						bean.setIdDocOriginalFinal(originalFinal.getIdFichero());
					}
					int existe = this.documentosGeneralService.updateDocOriginalFinal(bean);
					if (existe == 0) {
						bean.setIdFichero(null);
						this.documentosGeneralService.add92(bean);
					}

				} else {
					DocumentosGeneralController.LOGGER
							.error("DocumentosGeneralController: - addUpdateUploadDocFinal al PID Error");
					bean.setError(
							this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
				}
			}
			// borrar oid nuevo de tabla A0
			this.oidsAuxiliarService.remove(bean.getOid());
		} catch (Exception e) {
			DocumentosGeneralController.LOGGER.error("DocumentosGeneralController: - addUpdateUploadDocFinal Error: ",
					e);
			bean.setError(this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
		}
	}

	/**
	 * descarga un fichero por su id.
	 *
	 * @param idDoc
	 *            MoBigDecimaldel
	 * @param response
	 *            HttpServletResponse
	 */
	@RequestMapping(value = "/descargarDocumento/{idDoc}", method = RequestMethod.GET)
	public void getDocumento(@PathVariable() BigDecimal idDoc, HttpServletResponse response) {

		DocumentoTareaAdjunto documentoTareaAdjunto = new DocumentoTareaAdjunto();
		documentoTareaAdjunto.setIdFichero(idDoc);
		documentoTareaAdjunto = this.documentosGeneralService.find(documentoTareaAdjunto);

		// Se abre el documento
		response.setContentType(documentoTareaAdjunto.getContentType());
		response.setHeader("Content-Disposition", "attachment; filename=\"" + documentoTareaAdjunto.getNombre() + "\"");
		response.setHeader("Pragma", "cache");
		response.setHeader("Expires", "0");
		response.setHeader("Cache-Control", "private");

		if (StringUtils.isNotBlank(documentoTareaAdjunto.getOid())) {
			try {
				byte[] bytes = this.pidService.getDocument(documentoTareaAdjunto.getOid());
				ByteArrayOutputStream baos = new ByteArrayOutputStream(bytes.length);
				baos.write(bytes, 0, bytes.length);
				response.setContentLength(bytes.length);
				OutputStream os;
				os = response.getOutputStream();
				baos.writeTo(os);
				os.flush();
				os.close();
			} catch (Exception e) {
				DocumentosGeneralController.LOGGER.error("ERROR documentoTareaAdjunto descargando documento del PID: ",
						e);
			}
		} else {
			try {
				OutputStream out = response.getOutputStream();
				InputStream servicioGetDelPifInput = this.pidService
						.servicioGetDelPifInput(documentoTareaAdjunto.getRutaPif());
				byte[] outputByte = new byte[4096];
				while (servicioGetDelPifInput.read(outputByte, 0, 4096) != -1) {
					out.write(outputByte, 0, 4096);
				}
				servicioGetDelPifInput.close();
				out.close();
				response.flushBuffer();

			} catch (Exception e) {
				DocumentosGeneralController.LOGGER.error("ERROR descargando documento del PID: ", e);
			}

		}
	}

	@RequestMapping(value = "/cambiarvisibilidad92", method = RequestMethod.POST)
	public @ResponseBody DocumentoTareaAdjunto cambiarvisibilidad92(
			@RequestJsonBody DocumentoTareaAdjunto documentoTareaAdjunto) {
		DocumentosGeneralController.LOGGER.info("[POST - cambiarvisibilidad92]");
		this.documentosGeneralService.cambiarvisibilidad(documentoTareaAdjunto, DBConstants.TABLA_DOCS_FINALES_TAREA);
		return documentoTareaAdjunto;
	}

	@RequestMapping(value = "/cambiarvisibilidad93", method = RequestMethod.POST)
	public @ResponseBody DocumentoTareaAdjunto cambiarvisibilidad93(
			@RequestJsonBody DocumentoTareaAdjunto documentoTareaAdjunto) {
		DocumentosGeneralController.LOGGER.info("[POST - cambiarvisibilidad93]");
		this.documentosGeneralService.cambiarvisibilidad(documentoTareaAdjunto,
				DBConstants.TABLA_JUSTIFICANTES_REVISION);
		return documentoTareaAdjunto;
	}

	/**
	 *
	 *
	 * @param documentosExpediente
	 *            DocumentosExpediente Bean que contiene la informacion con la
	 *            que se va a crear el nuevo registro.
	 * @return DocumentosExpediente Bean resultante del proceso de creacion.
	 */
	@RequestMapping(value = "/docoriginal/{idTarea}", method = RequestMethod.POST)
	public @ResponseBody DocumentosExpediente add(@RequestBody DocumentosExpediente documentosExpediente,
			@PathVariable BigDecimal idTarea) {

		DocumentosGeneralController.LOGGER.info("[POST] : DocumentoTareaAdjunto insertado correctamente");
		return this.documentosGeneralService.addOriginal(documentosExpediente, Constants.PLANIFICACION, idTarea);
	}

	/**
	 * PIF / PID
	 *
	 * @param subidaTarea
	 *            MultipartFile.
	 * @param request
	 *            HttpServletRequest.
	 * @param idioma
	 *            Locale.
	 * @return Fichero Bean Fichero.
	 */

	// TITULO Y ReqEncriptadoOriginal?
	@RequestMapping(value = "/subidaFicheroXliff", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto subidaFicheroXliff(@RequestBody() SubidaTarea subidaTarea) {
		DocumentosGeneralController.LOGGER.info("DocumentosGeneral : subidaFicheroXLIFF");
		Locale locale = LocaleContextHolder.getLocale();

		DocumentoTareaAdjunto bean = new DocumentoTareaAdjunto();

		int elPunto = subidaTarea.getFichero().getNombre().lastIndexOf('.');
		bean.setNombre(subidaTarea.getFichero().getNombre());
		bean.setExtension(subidaTarea.getFichero().getNombre().substring(elPunto + 1,
				subidaTarea.getFichero().getNombre().length()));
		bean.setTamano(subidaTarea.getFichero().getTamano());
		bean.setContentType(subidaTarea.getFichero().getContentType());
		bean.setIdTarea(subidaTarea.getIdTarea());
		bean.setOid(subidaTarea.getFichero().getOid());
		bean.setTitulo(subidaTarea.getFichero().getNombre());
		bean.setEncriptado(subidaTarea.getFichero().getEncriptado());
		bean.setReqEncriptadoOriginal(subidaTarea.getFichero().getEncriptado());
		try {
			// guardar 88
			if (StringUtils.isNotEmpty(bean.getOid())) {
				this.documentosGeneralService.addXliff(bean);
				// borrar oid nuevo de tabla A0
				this.oidsAuxiliarService.remove(bean.getOid());
			} else {
				DocumentosGeneralController.LOGGER
						.error("DocumentosGeneralController: - subidaFicheroXLIFF al PID Error");
				bean.setError(this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
			}
			// guardar 96
		} catch (Exception e) {
			DocumentosGeneralController.LOGGER.error("DocumentosGeneralController: - subidaFichero Error: ", e);
			bean.setError(this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
		}

		return bean;
	}

	/**
	 * Obtiene los documentos asociados a una tarea
	 *
	 * @param idTarea
	 *            BigDecimal
	 * @return List<DocumentoTareaAdjunto>
	 */

	@RequestMapping(value = "/pasarDocumentoARevisarAFinal/{idDocOriginal}/{idDocRevisado}/{idTarea}/{idiomaDest}", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto pasarDocumentoARevisarAFinal(@PathVariable() BigDecimal idDocOriginal,
			@PathVariable() BigDecimal idDocRevisado, @PathVariable() BigDecimal idTarea,
			@PathVariable() String idiomaDest) {
		return this.pasarDocumentoARevisionFinal(idDocOriginal, idDocRevisado, idTarea, idiomaDest,
				DBConstants.INTVALUE_TABLA_87, true);
	}

	/**
	 * Obtiene los documentos asociados a una tarea
	 *
	 * @param idTarea
	 *            BigDecimal
	 * @return List<DocumentoTareaAdjunto>
	 */
	@RequestMapping(value = "/pasarDocARevisarAFinal/{idDocOriginal}/{idDocRevisado}/{idTarea}/{idiomaDest}", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto pasarDocARevisarAFinal(@PathVariable() BigDecimal idDocOriginal,
			@PathVariable() BigDecimal idDocRevisado, @PathVariable() BigDecimal idTarea,
			@PathVariable() String idiomaDest) {
		return this.pasarDocumentoARevisionFinal(idDocOriginal, idDocRevisado, idTarea, idiomaDest,
				DBConstants.INTVALUE_TABLA_92, true);
	}

	/**
	 * Pasar un documento a final
	 *
	 * @param idDocOriginal
	 *            BigDecimal
	 * @param idDocRevisado
	 *            BigDecimal
	 * @param idTarea
	 *            BigDecimal
	 * @param idiomaDest
	 *            String
	 * @return DocumentoTareaAdjunto
	 */
	@RequestMapping(value = "/pasarDocAFinal/{idDocOriginal}/{idDocRevisado}/{idTarea}/{idiomaDest}", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto pasarDocAFinal(@PathVariable() BigDecimal idDocOriginal,
			@PathVariable() BigDecimal idDocRevisado, @PathVariable() BigDecimal idTarea,
			@PathVariable() String idiomaDest) {
		return this.pasarDocumentoARevisionFinal(idDocOriginal, idDocRevisado, idTarea, idiomaDest,
				DBConstants.INTVALUE_TABLA_92, false);
	}

	@RequestMapping(value = "/pasarDocATraduccionAFinal/{idDocOriginal}/{idDocRevisado}/{idTarea}/{idiomaDest}", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto pasarDocATraduccionAFinal(@PathVariable() BigDecimal idDocOriginal,
			@PathVariable() BigDecimal idDocRevisado, @PathVariable() BigDecimal idTarea,
			@PathVariable() String idiomaDest) {
		return this.pasarDocumentoARevisionFinal(idDocOriginal, idDocRevisado, idTarea, idiomaDest,
				DBConstants.INTVALUE_TABLA_92, false);
	}

	@RequestMapping(value = "/pasarDocOriginalAFinal/{idDocOriginal}/{idTarea}/{idiomaDest}", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto pasarDocOriginalAFinal(@PathVariable() BigDecimal idDocOriginal, @PathVariable() BigDecimal idTarea,
			@PathVariable() String idiomaDest) {
		return this.procesoDocOriginalAFinal(idDocOriginal, idTarea, idiomaDest);
	}

	public DocumentoTareaAdjunto procesoDocOriginalAFinal(BigDecimal idDocOriginal,
			BigDecimal idTarea, String idiomaDest) {
		DocumentoTareaAdjunto documentoInsertar = new DocumentoTareaAdjunto();
		DocumentosExpediente documentoAux = new DocumentosExpediente();
		documentoAux.setIdDoc(idDocOriginal);
		// obtenemos los datos del documento original de 56
		DocumentosExpediente documentoRevisado = this.documentosExpedienteService.find(documentoAux);
		FicheroDocExp fichero = documentoRevisado.getFicheros().get(0);
		// iddoc rel a pasar a final
		DocumentosExpediente docExp = new DocumentosExpediente();
		docExp.setIdDoc(idDocOriginal);
		DocumentosExpediente documentoInsertado = new DocumentosExpediente();

		boolean existeEntrada = this.documentosGeneralService.isRowCreated(idTarea, idDocOriginal, DBConstants.INTVALUE_TABLA_92);
		// introducimos el documento rel en la 88 si no hay entrada en la 88
		if (documentoInsertado != null) {
			documentoInsertar.setNombre(documentoRevisado.getFicheros().get(Constants.CERO).getNombre());
			documentoInsertar.setTitulo(documentoRevisado.getTitulo());
			documentoInsertar.setExtension(documentoRevisado.getFicheros().get(Constants.CERO).getExtension());
			documentoInsertar.setContentType(documentoRevisado.getFicheros().get(Constants.CERO).getContentType());
			documentoInsertar.setTamano(documentoRevisado.getFicheros().get(Constants.CERO).getTamano());
			documentoInsertar.setEncriptado(fichero.getEncriptado());
			documentoInsertar.setOid(documentoRevisado.getFicheros().get(Constants.CERO).getOid());
			if (!existeEntrada) {
				// obtenemos el id fichero de la 88
				documentoInsertar = this.documentosGeneralService.add(documentoInsertar);
			}
		}
		documentoInsertar.setIdTarea(idTarea);
		documentoInsertar.setIdDocOriginal(idDocOriginal);

		if (!existeEntrada) {
			if (documentoInsertar.getIdFichero() == null) {
				DocumentoTareaAdjunto ficheroNew = this.documentosGeneralService.add(documentoInsertar);
				documentoInsertar.setIdFichero(ficheroNew.getIdFichero());
			}
			documentoInsertar.setIdDocOriginalFinal(documentoInsertar.getIdFichero());
			documentoInsertar.setIdFichero(null);
			this.documentosGeneralService.add92(documentoInsertar);
		} else {
			DocumentoTarea filterDocumentoTarea = new DocumentoTarea();
			filterDocumentoTarea.setIdTarea(idTarea);
			DocumentosExpediente docOriginal = new DocumentosExpediente();
			docOriginal.setIdDoc(idDocOriginal);
			filterDocumentoTarea.setDocumentoOriginal(docOriginal);
			DocumentoTarea docTarea = this.tareasGeneralService.findRegCorredaccion(filterDocumentoTarea);
			if (docTarea != null) {
				// obtenemos el idFichero del fichero a reemplazar de la 88
				if (docTarea.getDocumentoFinalOriginal().getIdFichero() == null) {
					DocumentoTareaAdjunto ficheroNew = this.documentosGeneralService.add(documentoInsertar);
					documentoInsertar.setIdDocOriginalFinal(ficheroNew.getIdFichero());
					documentoInsertar.setIdFichero(null);
					this.documentosGeneralService.updateDocOriginalFinal(documentoInsertar);
					return documentoInsertar;
				}
				// actualizamos la tabla intermedia y la tabla 88 con el oid
				// nuevo
				documentoInsertar.setIdFichero(docTarea.getDocumentoFinalOriginal().getIdFichero());
				this.documentosGeneralService.update(documentoInsertar);

				documentoInsertar.setIdDocOriginalFinal(documentoInsertar.getIdFichero());
				this.documentosGeneralService.updateDocOriginalFinal(documentoInsertar);
				// comprobamos que si ese oid lo tiene otro fichero en la 88
				boolean esta = this.documentosGeneralService.oidEstaEn88OEn56(docTarea.getDocumentoFinalOriginal().getOid());
				// comprobamos que el oid no sea del docRevOriginal y que no
				// este en la 88. Si no esta anyadir a la tabla A0
				if (!esta) {
					this.oidsAuxiliarService.add(docTarea.getDocumentoFinalOriginal().getOid());
				}
			} else {
				documentoInsertar.setError(Constants.SI);
			}
		}

		return documentoInsertar;
	}

	/**
	 * @param idDocOriginal
	 * @param idDocRevisado
	 * @param idTarea
	 * @return
	 */
	public DocumentoTareaAdjunto pasarDocumentoARevisionFinal(BigDecimal idDocOriginal, BigDecimal idDocRevisado,
			BigDecimal idTarea, String idiomaDest, int numeroTabla, boolean esDocOriginal) {
		DocumentoTareaAdjunto documentoInsertar = new DocumentoTareaAdjunto();
		DocumentosExpediente documentoAux = new DocumentosExpediente();
		documentoAux.setIdDoc(idDocOriginal);
		// obtenemos los datos del documento original de 56
		DocumentosExpediente documentoRevisado = this.documentosExpedienteService.find(documentoAux);
		FicheroDocExp fichero = documentoRevisado.getFicheros().get(0);
		// iddoc rel a pasar a final
		DocumentosExpediente docExp = new DocumentosExpediente();
		docExp.setIdDoc(idDocRevisado);
		DocumentosExpediente documentoInsertado = new DocumentosExpediente();
		if (esDocOriginal) {
			// lo obtenemos de la 56
			documentoInsertado = this.documentosExpedienteService.find(docExp);
		} else {
			// lo obtenemos de la 88
			DocumentoTareaAdjunto documentoTarea = new DocumentoTareaAdjunto();
			documentoTarea.setIdFichero(idDocRevisado);
			DocumentoTareaAdjunto ficheroAInsertar = this.documentosGeneralService.find(documentoTarea);
			FicheroDocExp ficheroTarea = new FicheroDocExp();
			ficheroTarea.setOid(ficheroAInsertar.getOid());
			ficheroTarea.setContentType(ficheroAInsertar.getContentType());
			ficheroTarea.setExtension(ficheroAInsertar.getExtension());
			ficheroTarea.setTamano(ficheroAInsertar.getTamano());
			ficheroTarea.setEncriptado(ficheroAInsertar.getEncriptado());
			ficheroTarea.setNombre(ficheroAInsertar.getNombre());
			List<FicheroDocExp> listaFicheros = new ArrayList<FicheroDocExp>();
			listaFicheros.add(ficheroTarea);
			documentoInsertado.setFicheros(listaFicheros);
		}
		// comprobamos si ya esta creada la fila para la tarea - iddocoriginal
		boolean existeEntrada = this.documentosGeneralService.isRowCreated(idTarea, idDocOriginal, numeroTabla);
		// introducimos el documento rel en la 88 si no hay entrada en la 88
		if (documentoInsertado != null) {
			documentoInsertar.setNombre(documentoInsertado.getFicheros().get(Constants.CERO).getNombre());
			documentoInsertar.setTitulo(documentoRevisado.getTitulo() + "_" + idiomaDest);
			documentoInsertar.setExtension(documentoInsertado.getFicheros().get(Constants.CERO).getExtension());
			documentoInsertar.setContentType(documentoInsertado.getFicheros().get(Constants.CERO).getContentType());
			documentoInsertar.setTamano(documentoInsertado.getFicheros().get(Constants.CERO).getTamano());
			documentoInsertar.setEncriptado(fichero.getEncriptado());
			documentoInsertar.setOid(documentoInsertado.getFicheros().get(Constants.CERO).getOid());
			if (!existeEntrada) {
				// obtenemos el id fichero de la 88
				documentoInsertar = this.documentosGeneralService.add(documentoInsertar);
			}
		}
		documentoInsertar.setIdTarea(idTarea);
		documentoInsertar.setIdDocOriginal(idDocOriginal);

		// si no habia entrada en la tabla intermedia hemos introducido el
		// fichero en la 88 o si estaba
		// creada la actualizamos en la intermedia y en la 88
		if (!existeEntrada) {
			// actualizamos las tablas intermedias (la insert en la 88 no la
			// hace porque le pasamos el id fichero)
			this.documentosGeneralService.addCondicional(documentoInsertar, numeroTabla);
		} else {
			// si esta creada actualizamos el fichero de 88 al que esta
			// relacionado en la 87 o 92
			DocumentoTarea filterDocumentoTarea = new DocumentoTarea();
			filterDocumentoTarea.setIdTarea(idTarea);
			DocumentosExpediente docOriginal = new DocumentosExpediente();
			docOriginal.setIdDoc(idDocOriginal);
			filterDocumentoTarea.setDocumentoOriginal(docOriginal);
			DocumentoTarea docTarea = null;
			// obtenemos el fichero final de la tarea que vamos a reemplazar
			switch (numeroTabla) {
			case 87:
				docTarea = this.tareasGeneralService.findRegTraduccionRevision(filterDocumentoTarea);
				break;
			case 92:
				docTarea = this.tareasGeneralService.findRegCorredaccion(filterDocumentoTarea);
				break;
			default:
				break;
			}
			if (docTarea != null) {
				// obtenemos el idFichero del fichero a reemplazar de la 88
				documentoInsertar.setIdFichero(docTarea.getDocumentoAdjunto().getIdFichero());
				if (documentoInsertar.getIdFichero() == null) {
					this.documentosGeneralService.add(documentoInsertar);
					this.documentosGeneralService.update92(documentoInsertar);
					return documentoInsertar;
				}

				// actualizamos la tabla intermedia y la tabla 88 con el oid
				// nuevo
				this.documentosGeneralService.updateCondicional(documentoInsertar, numeroTabla);
				// comprobamos que si ese oid lo tiene otro fichero en la 88
				boolean esta = this.documentosGeneralService.oidEstaEn88OEn56(docTarea.getDocumentoAdjunto().getOid());
				// comprobamos que el oid no sea del docRevOriginal y que no
				// este en la 88. Si no esta anyadir a la tabla A0
				if (!esta) {
					this.oidsAuxiliarService.add(docTarea.getDocumentoAdjunto().getOid());
				}
			} else {
				documentoInsertar.setError(Constants.SI);
			}
		}

		return documentoInsertar;
	}

	/**
	 *
	 * @param idDocOriginal
	 *            BigDecimal
	 * @param idTarea
	 *            BigDecimal
	 * @return Integer
	 */
	@RequestMapping(value = "/eliminarJustificante/{idDocOriginal}/{idTarea}", method = RequestMethod.POST)
	public @ResponseBody() Integer eliminarJustificante(@PathVariable() BigDecimal idDocOriginal,
			@PathVariable() BigDecimal idTarea) {
		return this.documentosGeneralService.eliminarJustificante(idDocOriginal, idTarea);
	}

	/**
	 * Obtiene los documentos asociados a una tarea
	 *
	 * @param idTarea
	 *            BigDecimal
	 * @return List<DocumentoTareaAdjunto>
	 */
	@RequestMapping(value = "/findDocumentosTarea/{idTarea}", method = RequestMethod.GET)
	public @ResponseBody() List<DocumentoTareaAdjunto> findDocumentosTarea(@PathVariable BigDecimal idTarea) {
		DocumentoTareaAdjunto docTarea = new DocumentoTareaAdjunto();
		docTarea.setIdTarea(idTarea);

		return this.documentosGeneralService.findAllDocumentosTarea(docTarea);
	}

	/**
	 *
	 * @param idDocOriginal
	 *            BigDecimal
	 * @param idTarea
	 *            BigDecimal
	 * @return Integer
	 */
	@RequestMapping(value = "/eliminarSoloFicheroFinal/{idDocOriginal}/{idTarea}", method = RequestMethod.POST)
	public @ResponseBody() Integer eliminarSoloFicheroFinal(@PathVariable() BigDecimal idDocOriginal,
			@PathVariable() BigDecimal idTarea) {
		return this.documentosGeneralService.eliminarSoloFicheroFinal(idDocOriginal, idTarea);
	}

	/**
	 *
	 * @param subidaTarea SubidaTarea
	 * @return DocumentoTareaAdjunto
	 */
	@RequestMapping(value = "/subidaDocumentoSalidaTareaTrabajo", method = RequestMethod.POST)
	public @ResponseBody() DocumentoTareaAdjunto subidaDocumentoSalidaTareaTrabajo(@RequestBody SubidaTarea subidaTarea) {
		DocumentosGeneralController.LOGGER.info("DocumentosGeneral : subidaDocumentoSalidaTareaTrabajo");
		Locale locale = LocaleContextHolder.getLocale();
		return this.addUpdateUploadDocumentoSalidaTareaTrabajo(subidaTarea, locale);
	}

	/**
	 *
	 * @param idDocOriginal
	 *            BigDecimal
	 * @param idTarea
	 *            BigDecimal
	 * @return Integer
	 */
	@RequestMapping(value = "/eliminarDocumentoSalidaTareaTrabajo/{idFichero}/{idTarea}/{oid}", method = RequestMethod.POST)
	public @ResponseBody() Integer eliminarDocumentoSalidaTareaTrabajo(@PathVariable() BigDecimal idFichero,
			@PathVariable() BigDecimal idTarea, @PathVariable() String oid) {
		return this.documentosGeneralService.eliminarDocumentoSalidaTareaTrabajo(idFichero, idTarea, oid);
	}

	/**
	 *
	 * @param subidaTarea SubidaTarea
	 * @param locale
	 * @return SubidaTarea
	 */
	private DocumentoTareaAdjunto addUpdateUploadDocumentoSalidaTareaTrabajo(SubidaTarea subidaTarea, Locale locale) {
		DocumentoTareaAdjunto docTarea = new DocumentoTareaAdjunto();
		docTarea.setIdTarea(subidaTarea.getIdTarea());
		docTarea.setIdFichero(subidaTarea.getIdDocOriginal());
		docTarea.setOid(subidaTarea.getFichero().getOid());
		docTarea.setContentType(subidaTarea.getFichero().getContentType());
		docTarea.setEncriptado(subidaTarea.getFichero().getEncriptado());
		docTarea.setExtension(subidaTarea.getFichero().getExtension());
		docTarea.setNombre(subidaTarea.getFichero().getNombre());
		docTarea.setTamano(subidaTarea.getFichero().getTamano());
		try {
			if (docTarea.getIdDocOriginal() != null) {

				// obtener el documento anterior para eliminar su oid
				DocumentoTareaAdjunto documentoAnterior = this.documentosGeneralService.find(docTarea);
				// guardar 88
				this.documentosGeneralService.update(docTarea);

				// guardar en tabla aa79bdd1s01 si hay posibilidad de eliminar documento, hacer esta comprobacion
				this.documentosGeneralService.updateD1(docTarea);

				// comprobamos si hay mas ficheros en la 88 con ese oid, por si
				// lo hay, para no anyadirlo a la A0
				Boolean esta = this.documentosGeneralService.oidEstaEn88OEn56(documentoAnterior.getOid());
				// comprobamos si el oidDoc revisado no es de un documento de la
				// 56 y si ese oid no lo tiene otro archivo de la 88 para,
				// en los dos casos, no borrarlo
				if (!esta) {
					// anyadir oid del viejo a la tabla A0
					this.oidsAuxiliarService.add(documentoAnterior.getOid());
				}
			} else {
				if (StringUtils.isNotEmpty(docTarea.getOid())) {
					// anyadir  fichero a tabla 88
					docTarea = this.documentosGeneralService.add(docTarea);
					// comprobar si tiene entrada en la tabla aa79bdd1s01
					boolean existeEntrada = this.documentosGeneralService.isRowCreatedD1(docTarea.getIdTarea());
					if (!existeEntrada) {
						// anyadir entrada a aa79bdd1s01
						this.documentosGeneralService.addD1(docTarea);
					} else {
						// actualizar entrada de aa79bdd1s01
						this.documentosGeneralService.updateD1(docTarea);
					}

				} else {
					DocumentosGeneralController.LOGGER
							.error("DocumentosGeneralController: - addUpdateUploadDocumentoSalidaTareaTrabajo al PID Error");
					docTarea.setError(
							this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
				}
			}
			// borrar oid nuevo de tabla A0
			this.oidsAuxiliarService.remove(docTarea.getOid());
		} catch (Exception e) {
			DocumentosGeneralController.LOGGER.error("DocumentosGeneralController: - addUpdateUploadDocFinal Error: ",
					e);
			docTarea.setError(this.appMessageSource.getMessage(DocumentosGeneralController.ERROR_PIF, null, locale));
		}
		return docTarea;
	}

}