package com.ejie.aa79b.control;

import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.model.ExpedienteTradRev;
import com.ejie.aa79b.service.ExcelReportService;
import com.ejie.aa79b.service.ExpedienteTradRevService;
import com.ejie.aa79b.service.PdfReportService;
import com.ejie.aa79b.utils.DateUtils;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * ExpedienteTradRevController generated by UDA, 31-ene-2018 15:08:53.
 * 
 * @author UDA
 */

@Controller
@RequestMapping(value = "/tramitacionexpedientes/gestionexpedientes/estudioexpedientes/expedientetradrev")

public class ExpedienteTradRevController {

	private static final Logger LOGGER = LoggerFactory.getLogger(ExpedienteTradRevController.class);

	@Autowired
	private ExcelReportService aa79bExcelReportService;
	@Autowired()
	private PdfReportService aa79bPdfReportService;

	@Autowired
	private ExpedienteTradRevService expedienteTradRevService;
	@Autowired()
	private ReloadableResourceBundleMessageSource appMessageSource;

	private static final String LITERAL_LABEL = "titulo.expedienteTradRev";

	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 * 
	 */

	/**
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 * 
	 * @param expedienteAnyo
	 *            Long
	 * @param expedienteNumExp
	 *            Integer
	 * @return ExpedienteTradRev Objeto correspondiente al identificador
	 *         indicado.
	 */
	@RequestMapping(value = "/{expedienteAnyo}/{expedienteNumExp}", method = RequestMethod.GET)
	public @ResponseBody() ExpedienteTradRev get(@PathVariable Long expedienteAnyo,
			@PathVariable Integer expedienteNumExp) {
		ExpedienteTradRev expedienteTradRev = new ExpedienteTradRev(expedienteAnyo, expedienteNumExp);
		expedienteTradRev = this.expedienteTradRevService.find(expedienteTradRev);
		ExpedienteTradRevController.LOGGER.info("[GET - findBy_PK] : Obtener ExpedienteTradRev por PK");
		return expedienteTradRev;
	}

	/**
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 * 
	 * @param expedienteAnyo
	 *            Long
	 * @param expedienteNumExp
	 *            Integer
	 * @return ExpedienteTradRev Objeto correspondiente al identificador
	 *         indicado.
	 */
	@RequestMapping(value = "/planificacion/{expedienteAnyo}/{expedienteNumExp}", method = RequestMethod.GET)
	public @ResponseBody() ExpedienteTradRev findConDatosFacturacion(@PathVariable Long expedienteAnyo,
			@PathVariable Integer expedienteNumExp) {

		ExpedienteTradRev expedienteTradRev = new ExpedienteTradRev(expedienteAnyo, expedienteNumExp);
		expedienteTradRev = this.expedienteTradRevService.findConDatosFacturacion(expedienteTradRev);

		ExpedienteTradRevController.LOGGER.info("[GET - findBy_PK] : Obtener ExpedienteTradRev por PK");
		return expedienteTradRev;
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterExpedienteTradRev
	 *            ExpedienteTradRev Objeto que contiene los parametros de
	 *            filtrado utilizados en la busqueda.
	 * @return List<ExpedienteTradRev> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody List<ExpedienteTradRev> getAll(@ModelAttribute ExpedienteTradRev filterExpedienteTradRev) {
		ExpedienteTradRevController.LOGGER.info("[GET - find_ALL] : Obtener ExpedienteTradRev por filtro");
		return this.expedienteTradRevService.findAll(filterExpedienteTradRev, null);
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param expedienteTradRev
	 *            ExpedienteTradRev Bean que contiene la informacion a
	 *            modificar.
	 * @return ExpedienteTradRev Bean resultante de la modificacion.
	 */
	@RequestMapping(method = RequestMethod.PUT)
	public @ResponseBody ExpedienteTradRev edit(@RequestBody ExpedienteTradRev expedienteTradRev) {
		ExpedienteTradRev expedienteTradRevAux = this.expedienteTradRevService.update(expedienteTradRev);
		ExpedienteTradRevController.LOGGER.info("[PUT] : ExpedienteTradRev actualizado correctamente");
		return expedienteTradRevAux;
	}

	/**
	 * Operacion CRUD Edit. guardarParcial: Modificacion parcial del bean
	 * indicado.
	 *
	 * @param expedienteTradRev
	 *            ExpedienteTradRev Bean que contiene la informacion a
	 *            modificar.
	 * @return ExpedienteTradRev Bean resultante de la modificacion.
	 */
	@RequestMapping(value = "/guardarParcial", method = RequestMethod.PUT)
	public @ResponseBody ExpedienteTradRev guardarParcial(@RequestBody ExpedienteTradRev expedienteTradRev) {
		ExpedienteTradRev expedienteTradRevAux = this.expedienteTradRevService.guardarParcial(expedienteTradRev);
		ExpedienteTradRevController.LOGGER.info("[PUT] : ExpedienteTradRev guardarParcial actualizado correctamente");
		return expedienteTradRevAux;
	}

	/**
	 * Operacion CRUD Edit. guardarParcial: Modificacion parcial del bean
	 * indicado para la parte de planificacion Con datos de facturacion del
	 * expediente
	 *
	 * @param expedienteTradRev
	 *            ExpedienteTradRev Bean que contiene la informacion a
	 *            modificar.
	 * @return ExpedienteTradRev Bean resultante de la modificacion.
	 */
	@RequestMapping(value = "/planificacion/guardarParcial", method = RequestMethod.PUT)
	public @ResponseBody ExpedienteTradRev guardarParcialPlanificacion(
			@RequestBody ExpedienteTradRev expedienteTradRev) {
		Locale locale = LocaleContextHolder.getLocale();
		ExpedienteTradRev expedienteTradRevAux = this.expedienteTradRevService
				.guardarParcialPlanificacion(expedienteTradRev, locale.toString());
		ExpedienteTradRevController.LOGGER
				.info("[PUT] : ExpedienteTradRev guardarParcial en la planificacion actualizado correctamente");
		return expedienteTradRevAux;
	}

	/**
	 * Operacion CRUD Edit. guardarFFinalIzo: Modificacion de la fecha y hora
	 * final izo
	 *
	 * @param expedienteTradRev
	 *            ExpedienteTradRev Bean que contiene la informacion a
	 *            modificar.
	 * @return ExpedienteTradRev Bean resultante de la modificacion.
	 */
	@RequestMapping(value = "/guardarFFinalIzo", method = RequestMethod.PUT)
	public @ResponseBody ExpedienteTradRev guardarFFinalIzo(@RequestBody ExpedienteTradRev expedienteTradRev) {
		ExpedienteTradRev expedienteTradRevAux = this.expedienteTradRevService.guardarFFinalIzo(expedienteTradRev);
		ExpedienteTradRevController.LOGGER
				.info("[PUT] : ExpedienteTradRev guardarFFinalIzo en la planificacion actualizado correctamente");
		return expedienteTradRevAux;
	}

	
	@RequestMapping(value = "/calcularFechaPropuesta", method = RequestMethod.GET)
	public @ResponseBody String calcularFechaPropuesta(@RequestParam(value = "tipoExp", required = true) String tipoExp, @RequestParam(value = "numPalIzo", required = true) Integer numPalIzo, @RequestParam(value = "indPresupuesto", required = true) String indPresupuesto, @RequestParam(value = "indVip", required = true) String indVip) {
		
		Date fechaFinPropuesta = this.expedienteTradRevService.calcularFechaPropuesta(tipoExp, numPalIzo, indPresupuesto, indVip);
		ExpedienteTradRevController.LOGGER.info("[PUT] : ExpedienteTradRev calcularFechaPropuesta");
		
		Locale locale = LocaleContextHolder.getLocale();
		return DateUtils.obtFechaHoraLargaFormateada(fechaFinPropuesta, locale);
	}
	
	
	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param expedienteTradRev
	 *            ExpedienteTradRev Bean que contiene la informacion con la que
	 *            se va a crear el nuevo registro.
	 * @return ExpedienteTradRev Bean resultante del proceso de creacion.
	 */
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody ExpedienteTradRev add(@RequestBody ExpedienteTradRev expedienteTradRev) {
		ExpedienteTradRev expedienteTradRevAux = this.expedienteTradRevService.add(expedienteTradRev);
		ExpedienteTradRevController.LOGGER.info("[POST] : ExpedienteTradRev insertado correctamente");
		return expedienteTradRevAux;
	}

	/**
	 * Operacion CRUD Delete. Borrado del registro correspondiente al
	 * identificador especificado.
	 *
	 * @param expedienteAnyo
	 *            Long
	 * @param expedienteNumExp
	 *            Integer Identificador del objeto que se desea eliminar.
	 * @return ExpedienteTradRev Bean eliminado.
	 */
	@RequestMapping(value = "/{expedienteAnyo}/{expedienteNumExp}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody ExpedienteTradRev remove(@PathVariable Long expedienteAnyo,
			@PathVariable Integer expedienteNumExp) {
		ExpedienteTradRev expedienteTradRev = new ExpedienteTradRev(expedienteAnyo, expedienteNumExp);
		this.expedienteTradRevService.remove(expedienteTradRev);
		ExpedienteTradRevController.LOGGER.info("[DELETE] : ExpedienteTradRev borrado correctamente");
		return expedienteTradRev;
	}

	/*
	 * METODOS COMPONENTE RUP_TABLE
	 * 
	 */

	/**
	 * Metodo de presentacion del RUP_TABLE.
	 * 
	 * @param model
	 *            Model
	 * @return String
	 */
	@RequestMapping(value = "/maint", method = RequestMethod.GET)
	public String getFormEdit() {
		ExpedienteTradRevController.LOGGER.info("[GET - View] : expedientetradrev");
		return "expedientetradrev";
	}

	/**
	 * Operacion de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterExpedienteTradRev
	 *            ExpedienteTradRev Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return JQGridResponseDto<ExpedienteTradRev> Dto que contiene el
	 *         resultado del filtrado realizado por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/filter", method = RequestMethod.POST)
	public @ResponseBody JQGridResponseDto<ExpedienteTradRev> filter(
			@RequestJsonBody(param = "filter") ExpedienteTradRev filterExpedienteTradRev,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ExpedienteTradRevController.LOGGER.info("[POST - filter] : Obtener ExpedienteTradRevs");
		return this.expedienteTradRevService.filter(filterExpedienteTradRev, jqGridRequestDto, false);
	}

	/**
	 * Operacion de busqueda del componente RUP_TABLE.
	 * 
	 * @param filterExpedienteTradRev
	 *            ExpedienteTradRev Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param searchExpedienteTradRev
	 *            ExpedienteTradRev Bean que contiene los parametros de busqueda
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la búsqueda.
	 * @return TableRowDto<ExpedienteTradRev> Dto que contiene el resultado de
	 *         la busqueda realizada por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public @ResponseBody List<TableRowDto<ExpedienteTradRev>> search(
			@RequestJsonBody(param = "filter") ExpedienteTradRev filterExpedienteTradRev,
			@RequestJsonBody(param = "search") ExpedienteTradRev searchExpedienteTradRev,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		ExpedienteTradRevController.LOGGER.info("[POST - search] : Buscar ExpedienteTradRevs");
		return this.expedienteTradRevService.search(filterExpedienteTradRev, searchExpedienteTradRev, jqGridRequestDto,
				false);
	}

	/**
	 * @param columns
	 * @param criterios
	 * @param jqGridRequestDto
	 * @param filterExpedienteTradRev
	 * @param request
	 * @param response
	 * @param model
	 */
	@RequestMapping(value = "/xlsxReport", method = RequestMethod.POST)
	public void xlsxTabla(@RequestParam(value = "columns", required = false) String columns,
			@RequestParam(value = "criterios", required = false) String criterios,
			@ModelAttribute() JQGridRequestDto jqGridRequestDto,
			@ModelAttribute() ExpedienteTradRev filterExpedienteTradRev, HttpServletResponse response) {
		ExpedienteTradRevController.LOGGER.info("[POST - subm]: xlsxTabla ========================================");
		Locale locale = LocaleContextHolder.getLocale();
		JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
				jqGridRequestDto.getSord());
		JQGridResponseDto<ExpedienteTradRev> respuesta = this.expedienteTradRevService.filter(filterExpedienteTradRev,
				jqGridRequestDtoReport, false);

		final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

		this.aa79bExcelReportService.generarExcel("printExcel", response, criterios, columns, respuesta.getRows(),
				locale, LITERAL_LABEL, label);
	}

	/**
	 * @param columns
	 * @param criterios
	 * @param request
	 * @param response
	 * @param jqGridRequestDto
	 * @param filterExpedienteTradRev
	 * @param model
	 */
	@RequestMapping(value = "/pdfReport", method = RequestMethod.POST)
	public void pdfTabla(@RequestParam(value = "columns", required = false) String columns,
			@RequestParam(value = "criterios", required = false) String criterios, HttpServletResponse response,
			@ModelAttribute() JQGridRequestDto jqGridRequestDto,
			@ModelAttribute() ExpedienteTradRev filterExpedienteTradRev) {
		ExpedienteTradRevController.LOGGER.info("[POST - subm]: pdfTabla ========================================");

		JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
				jqGridRequestDto.getSord());

		JQGridResponseDto<ExpedienteTradRev> respuesta = this.expedienteTradRevService.filter(filterExpedienteTradRev,
				jqGridRequestDtoReport, false);

		Locale locale = LocaleContextHolder.getLocale();
		final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

		this.aa79bPdfReportService.generarPdf("defaultPDF", response, criterios, columns, respuesta.getRows(),
				LITERAL_LABEL, locale, label);
	}
}
