package com.ejie.aa79b.control;

import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.model.MotivosAnulacion;
import com.ejie.aa79b.service.ExcelReportService;
import com.ejie.aa79b.service.MotivosAnulacionService;
import com.ejie.aa79b.service.PdfReportService;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * MotivosAnulacionController generated by UDA, 16-nov-2017 12:15:14.
 * 
 * @author UDA
 */

@Controller
@RequestMapping(value = "/administracion/datosmaestros/motivosanulacion")

public class MotivosAnulacionController {

	private static final Logger LOGGER = LoggerFactory.getLogger(MotivosAnulacionController.class);

	@Autowired
	private MotivosAnulacionService motivosAnulacionService;
	@Autowired
	private ExcelReportService aa79bExcelReportService;
	@Autowired()
	private PdfReportService aa79bPdfReportService;

	@Autowired()
	private ReloadableResourceBundleMessageSource appMessageSource;

	private static final String LITERAL_LABEL = "titulo.motivosAnulacion";

	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 * 
	 */

	/**
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 * 
	 * @param id012
	 *            Long
	 * @return MotivosAnulacion Objeto correspondiente al identificador
	 *         indicado.
	 */
	@RequestMapping(value = "/{id012}", method = RequestMethod.GET)
	public @ResponseBody MotivosAnulacion get(@PathVariable Long id012) {
		MotivosAnulacion motivosAnulacion = new MotivosAnulacion();
		motivosAnulacion.setId012(id012);
		motivosAnulacion = this.motivosAnulacionService.find(motivosAnulacion);
		MotivosAnulacionController.LOGGER.info("[GET - findBy_PK] : Obtener MotivosAnulacion por PK");
		return motivosAnulacion;
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterMotivosAnulacion
	 *            MotivosAnulacion Objeto que contiene los parametros de
	 *            filtrado utilizados en la busqueda.
	 * @return List<MotivosAnulacion> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody List<MotivosAnulacion> getAll(@ModelAttribute MotivosAnulacion filterMotivosAnulacion) {
		MotivosAnulacionController.LOGGER.info("[GET - find_ALL] : Obtener MotivosAnulacion por filtro");
		return this.motivosAnulacionService.findAll(filterMotivosAnulacion, null);
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param motivosAnulacion
	 *            MotivosAnulacion Bean que contiene la informacion a modificar.
	 * @return MotivosAnulacion Bean resultante de la modificacion.
	 */
	@RequestMapping(method = RequestMethod.PUT)
	public @ResponseBody MotivosAnulacion edit(@RequestBody MotivosAnulacion motivosAnulacion) {
		MotivosAnulacion motivosAnulacionAux = this.motivosAnulacionService.update(motivosAnulacion);
		MotivosAnulacionController.LOGGER.info("[PUT] : MotivosAnulacion actualizado correctamente");
		return motivosAnulacionAux;
	}

	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param motivosAnulacion
	 *            MotivosAnulacion Bean que contiene la informacion con la que
	 *            se va a crear el nuevo registro.
	 * @return MotivosAnulacion Bean resultante del proceso de creacion.
	 */
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody MotivosAnulacion add(@RequestBody MotivosAnulacion motivosAnulacion) {
		MotivosAnulacion motivosAnulacionAux = this.motivosAnulacionService.add(motivosAnulacion);
		MotivosAnulacionController.LOGGER.info("[POST] : MotivosAnulacion insertado correctamente");
		return motivosAnulacionAux;
	}

	/**
	 * Operacion CRUD Delete. Borrado del registro correspondiente al
	 * identificador especificado.
	 *
	 * @param id012
	 *            Long Identificador del objeto que se desea eliminar.
	 * @return MotivosAnulacion Bean eliminado.
	 */
	@RequestMapping(value = "/{id012}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody MotivosAnulacion remove(@PathVariable Long id012) {
		MotivosAnulacion motivosAnulacion = new MotivosAnulacion();
		motivosAnulacion.setId012(id012);
		this.motivosAnulacionService.remove(motivosAnulacion);
		MotivosAnulacionController.LOGGER.info("[DELETE] : MotivosAnulacion borrado correctamente");
		return motivosAnulacion;
	}

	/*
	 * METODOS COMPONENTE RUP_TABLE
	 * 
	 */

	/**
	 * Metodo de presentacion del RUP_TABLE.
	 * 
	 * @param model
	 *            Model
	 * @return String
	 */
	@RequestMapping(value = "/maint", method = RequestMethod.GET)
	public String getFormEdit(Model model) {
		MotivosAnulacionController.LOGGER.info("[GET - View] : motivosanulacion");
		return "motivosanulacion";
	}

	/**
	 * Operacion de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterMotivosAnulacion
	 *            MotivosAnulacion Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return JQGridResponseDto<MotivosAnulacion> Dto que contiene el resultado
	 *         del filtrado realizado por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/filter", method = RequestMethod.POST)
	public @ResponseBody JQGridResponseDto<MotivosAnulacion> filter(
			@RequestJsonBody(param = "filter") MotivosAnulacion filterMotivosAnulacion,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		MotivosAnulacionController.LOGGER.info("[POST - filter] : Obtener MotivosAnulacions");
		return this.motivosAnulacionService.filter(filterMotivosAnulacion, jqGridRequestDto, false);
	}

	/**
	 * Operacion de busqueda del componente RUP_TABLE.
	 * 
	 * @param filterMotivosAnulacion
	 *            MotivosAnulacion Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param searchMotivosAnulacion
	 *            MotivosAnulacion Bean que contiene los parametros de busqueda
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la búsqueda.
	 * @return TableRowDto<MotivosAnulacion> Dto que contiene el resultado de la
	 *         busqueda realizada por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public @ResponseBody List<TableRowDto<MotivosAnulacion>> search(
			@RequestJsonBody(param = "filter") MotivosAnulacion filterMotivosAnulacion,
			@RequestJsonBody(param = "search") MotivosAnulacion searchMotivosAnulacion,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		MotivosAnulacionController.LOGGER.info("[POST - search] : Buscar MotivosAnulacions");
		return this.motivosAnulacionService.search(filterMotivosAnulacion, searchMotivosAnulacion, jqGridRequestDto,
				false);
	}

	/**
	 * Borrado multiple de registros
	 * 
	 * @param filterMotivosAnulacion
	 *            MotivosAnulacion Bean que contiene los parametros de filtrado
	 *            a emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la busqueda.
	 * @return List<String> Lista de los identificadores de los registros
	 *         eliminados.
	 * 
	 */
	@RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody List<String> removeMultiple(
			@RequestJsonBody(param = "filter") MotivosAnulacion filterMotivosAnulacion,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		MotivosAnulacionController.LOGGER
				.info("[POST - search] : [POST - removeMultiple] : Eliminar multiples MotivosAnulacions");
		this.motivosAnulacionService.removeMultiple(filterMotivosAnulacion, jqGridRequestDto, false);
		MotivosAnulacionController.LOGGER.info("All entities correctly deleted!");

		return jqGridRequestDto.getMultiselection().getSelectedIds();
	}

	@RequestMapping(value = "/xlsxReport", method = RequestMethod.POST)
	public void xlsxTabla(@RequestParam(value = "columns", required = false) String columns,
			@RequestParam(value = "criterios", required = false) String criterios,
			@ModelAttribute() JQGridRequestDto jqGridRequestDto,
			@ModelAttribute() MotivosAnulacion filterMotivosAnulacion, HttpServletRequest request,
			HttpServletResponse response, Model model) {
		MotivosAnulacionController.LOGGER.info("[POST - subm]: xlsxTabla ========================================");
		Locale locale = LocaleContextHolder.getLocale();
		JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
				jqGridRequestDto.getSord());
		JQGridResponseDto<MotivosAnulacion> respuesta = this.motivosAnulacionService.filter(filterMotivosAnulacion,
				jqGridRequestDtoReport, false);

		final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

		this.aa79bExcelReportService.generarExcel("printExcel", response, criterios, columns, respuesta.getRows(),
				locale, LITERAL_LABEL, label);
	}

	/**
	 * @param columns
	 * @param criterios
	 * @param request
	 * @param response
	 * @param jqGridRequestDto
	 * @param filter
	 * @param model
	 * @throws Exception
	 */
	@RequestMapping(value = "/pdfReport", method = RequestMethod.POST)
	public void pdfTabla(@RequestParam(value = "columns", required = false) String columns,
			@RequestParam(value = "criterios", required = false) String criterios, HttpServletRequest request,
			HttpServletResponse response, @ModelAttribute() JQGridRequestDto jqGridRequestDto,
			@ModelAttribute() MotivosAnulacion filterMotivosAnulacion, Model model) {
		MotivosAnulacionController.LOGGER.info("[POST - subm]: pdfTabla ========================================");

		JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
				jqGridRequestDto.getSord());

		JQGridResponseDto<MotivosAnulacion> respuesta = this.motivosAnulacionService.filter(filterMotivosAnulacion,
				jqGridRequestDtoReport, false);

		Locale locale = LocaleContextHolder.getLocale();
		final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

		this.aa79bPdfReportService.generarPdf("defaultPDF", response, criterios, columns, respuesta.getRows(),
				LITERAL_LABEL, locale, label);
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterMotivosAnulacion
	 *            MotivosAnulacion Objeto que contiene los parametros de
	 *            filtrado utilizados en la busqueda.
	 * @return List<MotivosAnulacion> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(value = "/findMotivosAnulacionGestAnul", method = RequestMethod.GET)
	public @ResponseBody List<MotivosAnulacion> getMotivosAnulacionGestAnul(
			@ModelAttribute MotivosAnulacion filterMotivosAnulacion) {
		MotivosAnulacionController.LOGGER
				.info("[GET - getMotivosAnulacionGestAnul] : Obtener MotivosAnulacion por filtro");
		filterMotivosAnulacion.setEstado012(Constants.ALTA);
		return this.motivosAnulacionService.findAllMotivosAnulacion(filterMotivosAnulacion);
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterMotivosAnulacion
	 *            MotivosAnulacion Objeto que contiene los parametros de
	 *            filtrado utilizados en la busqueda.
	 * @return List<MotivosAnulacion> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(value = "/findMotivosAnulacionAlta", method = RequestMethod.GET)
	public @ResponseBody List<MotivosAnulacion> getMotivosAnulacionAlta(
			@ModelAttribute MotivosAnulacion filterMotivosAnulacion) {
		MotivosAnulacionController.LOGGER.info("[GET - getMotivosAnulacionAlta] : Obtener MotivosAnulacion por filtro");
		filterMotivosAnulacion.setEstado012(Constants.ALTA);
		return this.motivosAnulacionService.findAll(filterMotivosAnulacion, null);
	}

}
