package com.ejie.aa79b.control;

import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.model.TiposRevision;
import com.ejie.aa79b.service.ExcelReportService;
import com.ejie.aa79b.service.PdfReportService;
import com.ejie.aa79b.service.TiposRevisionService;
import com.ejie.x38.control.bind.annotation.RequestJsonBody;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;
import com.ejie.x38.dto.TableRowDto;

/**
 * TiposRevisionController generated by UDA, 28-nov-2017 15:23:30.
 * 
 * @author UDA
 */

@Controller
@RequestMapping(value = "/administracion/datosmaestros/tiposrevision")

public class TiposRevisionController {

	private static final Logger LOGGER = LoggerFactory.getLogger(TiposRevisionController.class);

	@Autowired
	private TiposRevisionService tiposRevisionService;
	@Autowired
	private ExcelReportService aa79bExcelReportService;
	@Autowired()
	private PdfReportService aa79bPdfReportService;
	@Autowired()
	private ReloadableResourceBundleMessageSource appMessageSource;

	private static final String LITERAL_LABEL = "titulo.tiposRevision";

	/*
	 * OPERACIONES CRUD (Create, Read, Update, Delete)
	 * 
	 */

	/**
	 * Operacion CRUD Read. Devuelve el bean correspondiente al identificador
	 * indicado.
	 * 
	 * @param id018
	 *            Long
	 * @return TiposRevision Objeto correspondiente al identificador indicado.
	 */
	@RequestMapping(value = "/{id018}", method = RequestMethod.GET)
	public @ResponseBody TiposRevision get(@PathVariable Long id018) {
		TiposRevision tiposRevision = new TiposRevision();
		tiposRevision.setId018(id018);
		tiposRevision = this.tiposRevisionService.find(tiposRevision);
		TiposRevisionController.LOGGER.info("[GET - findBy_PK] : Obtener TiposRevision por PK");
		return tiposRevision;
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterTiposRevision
	 *            TiposRevision Objeto que contiene los parametros de filtrado
	 *            utilizados en la busqueda.
	 * @return List<TiposRevision> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody List<TiposRevision> getAll(@ModelAttribute TiposRevision filterTiposRevision) {
		TiposRevisionController.LOGGER.info("[GET - find_ALL] : Obtener TiposRevision por filtro");
		return this.tiposRevisionService.findAll(filterTiposRevision, null);
	}

	/**
	 * Operacion CRUD Edit. Modificacion del bean indicado.
	 *
	 * @param tiposRevision
	 *            TiposRevision Bean que contiene la informacion a modificar.
	 * @return TiposRevision Bean resultante de la modificacion.
	 */
	@RequestMapping(method = RequestMethod.PUT)
	public @ResponseBody TiposRevision edit(@RequestBody TiposRevision tiposRevision) {
		TiposRevision tiposRevisionAux = this.tiposRevisionService.update(tiposRevision);
		TiposRevisionController.LOGGER.info("[PUT] : TiposRevision actualizado correctamente");
		return tiposRevisionAux;
	}

	/**
	 * Operacion CRUD Create. Creacion de un nuevo registro a partir del bean
	 * indicado.
	 *
	 * @param tiposRevision
	 *            TiposRevision Bean que contiene la informacion con la que se
	 *            va a crear el nuevo registro.
	 * @return TiposRevision Bean resultante del proceso de creacion.
	 */
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody TiposRevision add(@RequestBody TiposRevision tiposRevision) {
		TiposRevision tiposRevisionAux = this.tiposRevisionService.add(tiposRevision);
		TiposRevisionController.LOGGER.info("[POST] : TiposRevision insertado correctamente");
		return tiposRevisionAux;
	}

	/**
	 * Operacion CRUD Delete. Borrado del registro correspondiente al
	 * identificador especificado.
	 *
	 * @param id018
	 *            Long Identificador del objeto que se desea eliminar.
	 * @return TiposRevision Bean eliminado.
	 */
	@RequestMapping(value = "/{id018}", method = RequestMethod.DELETE)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody TiposRevision remove(@PathVariable Long id018) {
		TiposRevision tiposRevision = new TiposRevision();
		tiposRevision.setId018(id018);
		this.tiposRevisionService.remove(tiposRevision);
		TiposRevisionController.LOGGER.info("[DELETE] : TiposRevision borrado correctamente");
		return tiposRevision;
	}

	/*
	 * METODOS COMPONENTE RUP_TABLE
	 * 
	 */

	/**
	 * Metodo de presentacion del RUP_TABLE.
	 * 
	 * @param model
	 *            Model
	 * @return String
	 */
	@RequestMapping(value = "/maint", method = RequestMethod.GET)
	public String getFormEdit() {
		TiposRevisionController.LOGGER.info("[GET - View] : tiposrevision");
		return "tiposrevision";
	}

	/**
	 * Operacion de filtrado del componente RUP_TABLE.
	 * 
	 * @param filterTiposRevision
	 *            TiposRevision Bean que contiene los parametros de filtrado a
	 *            emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en el filtrado.
	 * @return JQGridResponseDto<TiposRevision> Dto que contiene el resultado
	 *         del filtrado realizado por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/filter", method = RequestMethod.POST)
	public @ResponseBody JQGridResponseDto<TiposRevision> filter(
			@RequestJsonBody(param = "filter") TiposRevision filterTiposRevision,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		TiposRevisionController.LOGGER.info("[POST - filter] : Obtener TiposRevisions");
		return this.tiposRevisionService.filter(filterTiposRevision, jqGridRequestDto, false);
	}

	/**
	 * Operacion de busqueda del componente RUP_TABLE.
	 * 
	 * @param filterTiposRevision
	 *            TiposRevision Bean que contiene los parametros de filtrado a
	 *            emplear.
	 * @param searchTiposRevision
	 *            TiposRevision Bean que contiene los parametros de busqueda a
	 *            emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la búsqueda.
	 * @return TableRowDto<TiposRevision> Dto que contiene el resultado de la
	 *         busqueda realizada por el componente RUP_TABLE.
	 */
	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public @ResponseBody List<TableRowDto<TiposRevision>> search(
			@RequestJsonBody(param = "filter") TiposRevision filterTiposRevision,
			@RequestJsonBody(param = "search") TiposRevision searchTiposRevision,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		TiposRevisionController.LOGGER.info("[POST - search] : Buscar TiposRevisions");
		return this.tiposRevisionService.search(filterTiposRevision, searchTiposRevision, jqGridRequestDto, false);
	}

	/**
	 * Borrado multiple de registros
	 * 
	 * @param filterTiposRevision
	 *            TiposRevision Bean que contiene los parametros de filtrado a
	 *            emplear.
	 * @param jqGridRequestDto
	 *            Dto que contiene los parametros de configuracion propios del
	 *            RUP_TABLE a aplicar en la busqueda.
	 * @return List<String> Lista de los identificadores de los registros
	 *         eliminados.
	 * 
	 */
	@RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
	@ResponseStatus(value = HttpStatus.OK)
	public @ResponseBody List<String> removeMultiple(
			@RequestJsonBody(param = "filter") TiposRevision filterTiposRevision,
			@RequestJsonBody JQGridRequestDto jqGridRequestDto) {
		TiposRevisionController.LOGGER
				.info("[POST - search] : [POST - removeMultiple] : Eliminar multiples TiposRevisions");
		this.tiposRevisionService.removeMultiple(filterTiposRevision, jqGridRequestDto, false);
		TiposRevisionController.LOGGER.info("All entities correctly deleted!");

		return jqGridRequestDto.getMultiselection().getSelectedIds();
	}

	/**
	 * @param columns
	 * @param criterios
	 * @param jqGridRequestDto
	 * @param filter
	 * @param response
	 * @param locale
	 * @throws Exception
	 */
	@RequestMapping(value = "/xlsxReport", method = RequestMethod.POST)
	public void xlsxTabla(@RequestParam(value = "columns", required = false) String columns,
			@RequestParam(value = "criterios", required = false) String criterios,
			@ModelAttribute() JQGridRequestDto jqGridRequestDto, @ModelAttribute() TiposRevision filterTiposRevision,
			HttpServletResponse response){
		TiposRevisionController.LOGGER.info("[POST - subm]: xlsxTabla ========================================");
		Locale locale = LocaleContextHolder.getLocale();
		JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
				jqGridRequestDto.getSord());
		JQGridResponseDto<TiposRevision> respuesta = this.tiposRevisionService.filter(filterTiposRevision,
				jqGridRequestDtoReport, false);

		final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

		this.aa79bExcelReportService.generarExcel("printExcel", response, criterios, columns, respuesta.getRows(),
				locale, LITERAL_LABEL, label);
	}

	/**
	 * @param columns
	 * @param criterios
	 * @param response
	 * @param jqGridRequestDto
	 * @param filter
	 * @param model
	 * @throws Exception
	 */
	@RequestMapping(value = "/pdfReport", method = RequestMethod.POST)
	public void pdfTabla(@RequestParam(value = "columns", required = false) String columns,
			@RequestParam(value = "criterios", required = false) String criterios, HttpServletResponse response,
			@ModelAttribute() JQGridRequestDto jqGridRequestDto, @ModelAttribute() TiposRevision filterTiposRevision) {
		TiposRevisionController.LOGGER.info("[POST - subm]: pdfTabla ========================================");

		JQGridRequestDto jqGridRequestDtoReport = new JQGridRequestDto(null, null, jqGridRequestDto.getSidx(),
				jqGridRequestDto.getSord());

		JQGridResponseDto<TiposRevision> respuesta = this.tiposRevisionService.filter(filterTiposRevision,
				jqGridRequestDtoReport, false);

		Locale locale = LocaleContextHolder.getLocale();
		final String label = this.appMessageSource.getMessage(LITERAL_LABEL, new Object[] {}, locale);

		this.aa79bPdfReportService.generarPdf("defaultPDF", response, criterios, columns, respuesta.getRows(),
				LITERAL_LABEL, locale, label);
	}

	/**
	 * Devuelve una lista de beans correspondientes a los valores de filtrados
	 * indicados en el objeto pasado como parametro.
	 *
	 * @param filterTiposRevision
	 *            TiposRevision Objeto que contiene los parametros de filtrado
	 *            utilizados en la busqueda.
	 * @return List<TiposRevision> Lista de objetos correspondientes a la
	 *         busqueda realizada.
	 */
	@RequestMapping(value = "/findTiposRevisionAlta", method = RequestMethod.GET)
	public @ResponseBody List<TiposRevision> getTiposRevisionAlta(@ModelAttribute TiposRevision filterTiposRevision) {
		TiposRevisionController.LOGGER.info("[GET - getTiposRevisionAlta] : Obtener TiposRevision por filtro");
		filterTiposRevision.setEstado018(Constants.ALTA);
		return this.tiposRevisionService.findAll(filterTiposRevision, null);
	}

}
