CREATE OR REPLACE FUNCTION HORAS_ENTRE_FECHAS_ATENCION(FECHA_INI IN DATE, FECHA_FIN IN DATE) RETURN NUMBER IS

RETORNO NUMBER:=0;

BEGIN

WITH FECHAS AS
    (SELECT DIA
    , T10_COD_TIPO_JORNADA TIPO_JORNADA
    FROM (SELECT TRUNC(FECHA_INI) + level - 1 AS DIA
            FROM DUAL
            CONNECT BY LEVEL <= (TRUNC(FECHA_FIN) - TRUNC(FECHA_INI) + 1))
    JOIN R7510T00 ON DIA = T10_FEC_FECHA
    WHERE MOD(TO_CHAR(DIA, 'J'), 7)+1 NOT IN (6, 7)
    AND T10_COD_TIPO_JORNADA != 'F'
    )
, HORARIOS AS
    (SELECT TIPO_JORNADA, TIPO
    , CASE WHEN TIPO = 'M' THEN DECODE(TIPO_JORNADA, 'N1', HORA_DESDE_M, HORA_DESDE_V) ELSE DECODE(TIPO_JORNADA, 'N1', HORA_DESDE_T, NULL) END AS HORA_INI
    , CASE WHEN TIPO = 'M' THEN DECODE(TIPO_JORNADA, 'N1', HORA_HASTA_M, HORA_HASTA_V) ELSE DECODE(TIPO_JORNADA, 'N1', HORA_HASTA_T, NULL) END AS HORA_FIN
    FROM (select * from (select T60_COD_CONFIG, T60_CONFIGURACION from R7560T00 t)
            pivot (
               MAX(T60_CONFIGURACION)
               for T60_COD_CONFIG in (5 as "HORA_DESDE_M", 10 AS "HORA_HASTA_M", 11 AS "HORA_DESDE_T", 8 AS "HORA_HASTA_T", 7 AS "HORA_DESDE_V", 9 AS "HORA_HASTA_V")
            ) order by 1)
    , (SELECT REGEXP_SUBSTR('N1,N2,I,E', '[^,]+', 1, LEVEL) TIPO_JORNADA FROM DUAL CONNECT BY REGEXP_SUBSTR('N1,N2,I,E', '[^,]+', 1, LEVEL) IS NOT NULL)
    , (SELECT REGEXP_SUBSTR('M,T', '[^,]+', 1, LEVEL) TIPO FROM DUAL CONNECT BY REGEXP_SUBSTR('M,T', '[^,]+', 1, LEVEL) IS NOT NULL)
    )
, CALENDARIO AS
    (SELECT F.DIA
    , GREATEST(TO_DATE(TO_CHAR(F.DIA, 'DD/MM/YYYY') || HORA_INI, 'DD/MM/YYYYHH24:MI'), FECHA_INI) INICIO
    , LEAST(TO_DATE(TO_CHAR(F.DIA, 'DD/MM/YYYY') || HORA_FIN, 'DD/MM/YYYYHH24:MI'), FECHA_FIN) FIN
    FROM FECHAS F
    JOIN HORARIOS H ON F.TIPO_JORNADA = H.TIPO_JORNADA
    ORDER BY DIA)
SELECT NVL(SUM( ROUND((FIN-INICIO) * 24, 2)),0)
INTO RETORNO
FROM CALENDARIO
WHERE FIN >= FECHA_INI AND INICIO <= FECHA_FIN
ORDER BY INICIO;

RETURN RETORNO;

END;
/