<%--  
 -- Copyright 2012 E.J.I.E., S.A.
 -- Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
 -- Solo podrá usarse esta obra si se respeta la Licencia.
 -- Puede obtenerse una copia de la Licencia en
 -- 
 -- http://ec.europa.eu/idabc/eupl.html
 -- 
 -- Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
 -- el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
 -- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 -- Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
 -- que establece la Licencia. 
 --%>
 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/prototype.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/firebug/firebugx.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/scriptaculous.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/widgets.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/dynamic_form_functions3.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/t17-i18n.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/language.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/window.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/sidl-dynamic-form.js"></script>
<script src="http://www1.geo.jakina.ejiedes.net/sidl/lib/sidl-base-api-absurl.js" 
	type="text/javascript"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/openlayers/OpenLayers.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/openlayers/ArcGISCache.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/sidl-gis-base-api-absurl.js"></script>
<script type="text/javascript"
	src="http://www1.geo.jakina.ejiedes.net/sidl/lib/nora-openlayers-controls.js"></script>
	

