CREATE OR REPLACE VIEW AA79B_SOLICITANTES_P43 AS
SELECT
    TIPIDEN,
    PREDNI,
    DNI,
    SUFDNI,
    NOMBRE,
    APEL1,
    APEL2,
    TIPO_ENTIDAD,
    COD_ENTIDAD,
    DESC_ES,
    DESC_EU,
    CIF
FROM
    AA79B.X54JAPI_SOLICITANTES
WHERE
    ESTADO = 'V' AND GESTOR_EXPEDIENTES_TRAMITAGUNE = 'N';
/