package com.ejie.x21a.service;

import java.util.List;

import com.ejie.x21a.model.Expediente;



/**
 *  * AlumnoService generated by UDA, 01-mar-2012 9:33:10.
 * @author UDA
 */

public interface ExpedienteService {

	
	Boolean putFase (Expediente expediente);
	
	List<Expediente> getAll();
	
}


