// variable para branch/tag seleccionados para preparar la entrega
def branch2compile = ''
def version = ''

//variables para el SVN EJIE
def urlSvnEJIE = 'svn://cvs.ejiedes.net/'+app
def folderSvnEJIE = app+'Svn'

def log = []

def deliveredToSvnEJIE = false

try {

    stage('Setup'){
        println 'Preparando entorno'
        //meter aquí lo que haga falta
    }
    
    
    stage('Branch selection') {
        if (branch == '') {
            
            // En esta fase hacemos un checkout del repositorio en master
            // Este checkout se usara para que el usuario pueda elegir de que
            // branch/tag se desea hacer la entrega
            // Stage para descargar el codigo a entregar
            node (jenkinsNode) {
                println 'Checkout de master para poder ofrecer branch/tags sobre las que preparar la entrega'
                // Descargamos lo ultimo del repositorio
                git branch:'master', credentialsId: 'bitbucket_sistemas', url: 'git@bitbucket.org:grupo-teknei/'+app+'.git'

                // Mostramos al usuario un combo con los branch disponibles en el repositorio
                // Se le solicita que elija un branch
                println 'Seleccionar branch para preparar la entrega'
                // Obtenemos la lista de branches
                def branchList = sh ( script: "git branch --remote --list '*release*' ", returnStdout: true)
                branchList = branchList.trim() + "\n" + sh ( script: "git branch --remote --list '*hotfix*' ", returnStdout: true)
                branchList = branchList.replace("origin/", "").trim()
                println 'branchList: '+ branchList
                def tagList = "master/" + sh ( script: 'git tag', returnStdout: true)
                tagList = tagList.trim().replace("\n", "\nmaster/")
                println 'tagList: '+ tagList
                
                def opciones = branchList + "\n" + tagList
                opcions = opciones.trim()
                
                // Mostramos un combo mostrando la lista de branches
                branch2compile = input message:'¿Qué branch vamos a utilizar?', parameters: [choice(name: 'branch', choices: opciones)]
                def valores = branch2compile.split('/')
                branch = valores[0]
                version = valores[1]
                
                if (branch == 'master') {
                    branch2compile = branch
                }
            }
        } else {
            node (jenkinsNode) {
                branch = branch.trim()
                
                if (branch.startsWith("origin/")) {
                    branch = branch.replace("origin/", "")
                    branch2compile = branch
                    def valores = branch.split("/")
                    branch = valores[0]
                    version = valores[1]
                } else {
                    version = branch
                    branch = "master"
                    branch2compile = branch
                }
            }
        }
    }

    println 'Branch seleccionado: ' + branch + '/' + version
    currentBuild.displayName = currentBuild.displayName + " - " + version + " (" + branch +")"
    currentBuild.description = 'Branch seleccionado: ' + branch + '/' + version
    
    node(nodo) {
    
        // Descargamos en el jenkins esclavo el branch/tag que se va a usar para
        // realizar la entrega
        stage('Checkout from Bitbucket') {
            println 'Descargamos en el jenkins Windows 8.1 el branch/tag que se va a usar: ' + version
            // Descargamos la rama del repositorio desde la que se va a realizar la entrega
            git branch:branch2compile, credentialsId: 'bitbucket_sistemas', url: 'git@bitbucket.org:grupo-teknei/'+app+'.git'

            // Si tenemos tag nos posicionamos sobre el tag
            if (branch == 'master') {
                bat 'git checkout tags/' + version + ' -b ' + version
                bat 'git branch'
            }
        }

        // En esta fase se genera el entregable desde el branch/tag seleccionado
        stage('Git2EJIE') {
            println 'Se prepara estructura SVN EJIE desde branch/tag: '+ branch + ' / ' + version
            dir(app+'2ejie') {
                bat 'ant '+app+'2ejie'
            }
        }

        // En esta fase se crea un directorio sincronizado con el SVN de EJIE
        // El codigo se descarga solo si no se ha descargado antes
        stage('Checkout from SVN EJIE') {
            // Mira si existe el directorio v85ju
            def svnExists = fileExists folderSvnEJIE

            // Si no existe el directorio lo creamos
            if (!svnExists) {
                println 'Se crea un directorio sincronizado con el SVN de EJIE. No existía.'

                // Creamos el directorio de descarga de SVN y descargamos lo ultimo
                // del repositorio
                bat 'mkdir '+ folderSvnEJIE

                dir(folderSvnEJIE) {
                    bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/backend/trunk backend'
                    bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/codigo/trunk codigo'
                    bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/config/trunk config'
                    bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/datos/trunk datos'
                    bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/documentacion/trunk documentacion'
                    bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/estatico/trunk estatico'
                    
                    // bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/codigo/branches/weblogic14 codigo14'
                    // bat 'svn checkout --username '+ userSvnEJIE +' --password '+ passSvnEJIE +' '+ urlSvnEJIE +'/config/branches/weblogic14 config14'
                    
                }
            }else{
                println 'Se actualiza el directorio sincronizado con el SVN de EJIE'

                dir(folderSvnEJIE) {
                    bat 'svn update backend'
                    bat 'svn update codigo'
                    bat 'svn update config'
                    bat 'svn update datos'
                    bat 'svn update documentacion'
                    bat 'svn update estatico'
                    
                    // bat 'svn update codigo14'
                    // bat 'svn update config14'
                }
            }
        }


        // En esta fase se crea un directorio sincronizado con el SVN de EJIE
        // El codigo se descarga solo si no se ha descargado antes
        stage('Svn EJIE structure preparation') {
            println 'Se prepara la estructura borrando todo (por si han desaparecido ficheros) y copiando'
            dir(app+'2ejie') {
                bat 'ant deliver'
            }
            dir(folderSvnEJIE) {
                log << 'Cambios en backend:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status backend/cade backend/scripts backend/lib').trim()
                log << ''
                log << 'Cambios en código backend:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status backend/java').trim()
                log << ''
                log << 'Cambios en datos backend:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status datos/backend').trim()
                log << ''
                log << 'Cambios en config backend:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status config/backend').trim()
                log << ''
                log << 'Cambios en estático:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status estatico').trim()
                log << ''
                log << 'Cambios en código:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status codigo').trim()
                log << ''
                log << 'Cambios en datos:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status datos/serapp').trim()
                log << ''
                log << 'Cambios en config:'
                log << '========================================================='
                log << bat(returnStdout: true, script: '@svn status config/serapp').trim()
            }
        }

        stage('Anthill') {
            println log.join("\r\n")
            }

        stage('Commit?') {

            if (commitChanges == '') {
                commitChanges = input message:'Ejecutar commit contra SVN EJIE', parameters: [choice(name: 'Quieres hacer commit a SVN EJIE?', choices: 'No\nSí')]
            }
            
            def mensajeCommit = 'Cambios realizados para implementar la '+version
            
            if(commitChanges.startsWith('S')){
                println 'Subimos a SVN EJIE los cambios'

                dir(folderSvnEJIE) {
                    bat 'svn add backend --force'
                    bat 'svn commit backend -m "'+ mensajeCommit +'"'
                    bat 'svn add codigo --force'
                    bat 'svn commit codigo -m "'+ mensajeCommit +'"'
                    bat 'svn add config --force'
                    bat 'svn commit config -m "'+ mensajeCommit +'"'
                    bat 'svn add datos --force'
                    bat 'svn commit datos -m "'+ mensajeCommit +'"'
                    bat 'svn add documentacion --force'
                    bat 'svn commit documentacion -m "'+ mensajeCommit +'"'
                    bat 'svn add estatico --force'
                    bat 'svn commit estatico -m "'+ mensajeCommit +'"'

                    // bat 'svn add codigo14 --force'
                    // bat 'svn commit codigo14 -m "'+ mensajeCommit +'"'
                    // bat 'svn add config14 --force'
                    // bat 'svn commit config14 -m "'+ mensajeCommit +'"'
                }

                deliveredToSvnEJIE = true
            }else{
                println 'No se suben a SVN EJIE los cambios'
                deliveredToSvnEJIE = false
            }
        }

        if(deliveredToSvnEJIE){
            stage('Tag creation'){
                if (tagCreation == '') {
                    tagCreation = input message:'Crear etiqueta en SVN EJIE', parameters: [choice(name: 'Quieres crear etiqueta en SVN EJIE?', choices: 'No\nSí')]
                }
                def mensajeTag = 'Cambios para crear el tag '+ version
                def mensajeTagBorrado = 'Cambios para borrar el tag '+ version

                if(tagCreation.startsWith('S')){
                    try{
                        bat 'svn rm '+ urlSvnEJIE +'/backend/tags/'+ version +' -m "'+ mensajeTagBorrado +'"'
                    }catch(err){
                        println 'No existe el tag '+ version +' en backend. Se crea.'
                    }
                    bat 'svn copy '+ urlSvnEJIE +'/backend/trunk '+ urlSvnEJIE +'/backend/tags/'+version +' -m "'+ mensajeTag +'"'
                    try{
                        bat 'svn rm '+ urlSvnEJIE +'/codigo/tags/'+ version +' -m "'+ mensajeTagBorrado +'"'
                    }catch(err){
                        println 'No existe el tag '+ version +' en codigo. Se crea.'
                    }
                    bat 'svn copy '+ urlSvnEJIE +'/codigo/trunk '+ urlSvnEJIE +'/codigo/tags/'+version +' -m "'+ mensajeTag +'"'
                    try{
                        bat 'svn rm '+ urlSvnEJIE +'/config/tags/'+ version +' -m "'+ mensajeTagBorrado +'"'
                    }catch(err){
                        println 'No existe el tag '+ version +' en config. Se crea.'
                    }
                    bat 'svn copy '+ urlSvnEJIE +'/config/trunk '+ urlSvnEJIE +'/config/tags/'+version +' -m "'+ mensajeTag +'"'
                    try{
                        bat 'svn rm '+ urlSvnEJIE +'/datos/tags/'+ version +' -m "'+ mensajeTagBorrado +'"'
                    }catch(err){
                        println 'No existe el tag '+ version +' en datos. Se crea.'
                    }
                    bat 'svn copy '+ urlSvnEJIE +'/datos/trunk '+ urlSvnEJIE +'/datos/tags/'+version +' -m "'+ mensajeTag +'"'
                    try{
                        bat 'svn rm '+ urlSvnEJIE +'/documentacion/tags/'+ version +' -m "'+ mensajeTagBorrado +'"'
                    }catch(err){
                        println 'No existe el tag '+ version +' en documentacion. Se crea.'
                    }
                    bat 'svn copy '+ urlSvnEJIE +'/documentacion/trunk '+ urlSvnEJIE +'/documentacion/tags/'+version +' -m "'+ mensajeTag +'"'
                    try{
                        bat 'svn rm '+ urlSvnEJIE +'/estatico/tags/'+ version +' -m "'+ mensajeTagBorrado +'"'
                    }catch(err){
                        println 'No existe el tag '+ version +' en estatico. Se crea.'
                    }
                    bat 'svn copy '+ urlSvnEJIE +'/estatico/trunk '+ urlSvnEJIE +'/estatico/tags/'+version +' -m "'+ mensajeTag +'"'
                
                    // try{
                    //     bat 'svn rm '+ urlSvnEJIE +'/codigo/tags/'+ version +'_wl14 -m "'+ mensajeTagBorrado +'"'
                    // }catch(err){
                    //     println 'No existe el tag '+ version +' en codigo. Se crea.'
                    // }
                    // bat 'svn copy '+ urlSvnEJIE +'/codigo/branches/weblogic14 '+ urlSvnEJIE +'/codigo/tags/'+version +'_wl14 -m "'+ mensajeTag +'"'
                    // try{
                    //     bat 'svn rm '+ urlSvnEJIE +'/config/tags/'+ version +'_wl14 -m "'+ mensajeTagBorrado +'"'
                    // }catch(err){
                    //     println 'No existe el tag '+ version +' en config. Se crea.'
                    // }
                    // bat 'svn copy '+ urlSvnEJIE +'/config/branches/weblogic14 '+ urlSvnEJIE +'/config/tags/'+version +'_wl14 -m "'+ mensajeTag +'"'
                }
            }
        }
    }
    
    // Esta fase pasa las reglas de calidad del sonar
    stage('sonarQube') {
        node (jenkinsNode){
            println 'Se comprueban reglas de calidad en SonarQube'
            // Descargamos el branch/tag de entraga para pasar la calidad de codigo
            git branch:branch2compile, credentialsId: 'bitbucket_sistemas', url: 'git@bitbucket.org:grupo-teknei/'+app+'.git'
            if (branch == 'master') {
                sh 'git checkout tags/' + version + ' -b ' + version
                sh 'git branch'
            }

            println 'Preparing sonar properties...'
            writeFile encoding: 'UTF-8', file: 'sonar-project.properties', text: """
                # Required metadata
                sonar.projectKey=com.ejie.""" + app + """
                sonar.projectName=IVAP - """ + app.toUpperCase() + """
                sonar.projectVersion=""" + version + """

                # Comma-separated paths to directories with sources (required)
                # Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
                sonar.sources=""" + sources + """

                # Exclusions
                sonar.exclusions=""" + exclusions + """
                sonar.java.binaries=.

                # Encoding of the source code
                sonar.sourceEncoding=UTF-8

                # Language
                sonar.language=java
            """

            println 'Executing sonar analysis...'
            def scannerHome = tool 'SonarQube-Scanner';
            withSonarQubeEnv('SonarQube') {
                sh "${scannerHome}/bin/sonar-scanner"
            }
            
        }
    }
} catch (err) {
    // Si se produce un error se envia un mail a los responsables para que comprueben la ejecución
    stage ('Failure notification') {
        node (jenkinsNode) {
            /*mail (
                to: 'soporteivap@euro-help.es',
                from: 'soporteivap@euro-help.es',
                replyTo: 'soporteivap@euro-help.es',
                subject: "El proceso '${env.JOB_NAME}' (${env.BUILD_NUMBER}) ha fallado.", 
                body: 'Se ha producido un error durante el proceso de IVAP - V85JU - Delivery. Por favor, compruebe su ejecucion.', 
                mimeType:'text/html'
            );*/
        }
        currentBuild.result = 'FAILURE' 
    }
} finally {
    stage('Clean') {
        node(nodo) {
            if (branch == 'master') {
                bat 'git checkout master'
                bat 'git branch -D '+ version
            }
        }
        node {
            if (branch == 'master') {
                sh 'git checkout master'
                sh 'git branch -D '+ version
            }
        }
    }
}