<%--  
 -- Copyright 2012 E.J.I.E., S.A.
 -- Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
 -- Solo podrá usarse esta obra si se respeta la Licencia.
 -- Puede obtenerse una copia de la Licencia en
 -- 
 -- http://ec.europa.eu/idabc/eupl.html
 -- 
 -- Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
 -- el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
 -- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 -- Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
 -- que establece la Licencia. 
 --%>
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- jQuery 1.6.1 -->
<script src="${staticsUrl}/rup/scripts/core/jquery-1.6.2.js" type="text/javascript"></script>

<!-- RUP-CORE -->
<script src="${staticsUrl}/rup/scripts/rup.utils-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.base-1.2.1.js" type="text/javascript"></script>

<!-- jQuery UI 1.8.14 (+ patrones subyacentes) -->
<script src="${staticsUrl}/rup/scripts/core/jquery.blockUI.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/xbreadcrumbs.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui-1.8.16.custom.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.autocomplete.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui.multidatespicker.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.selectmenu.js" type="text/javascript"></script><!-- combo -->
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui.timepicker.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.jqGrid.fluid.js" type="text/javascript"></script>


<script src="${staticsUrl}/rup/scripts/core/jquery.fileupload.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.fileupload-ui.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.iframe-transport.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.xdr-transport.js" type="text/javascript"></script>


<!-- jqGrid 4.3.1 -->
<script src="${staticsUrl}/rup/scripts/core/jqGrid-4.3.1.js" type="text/javascript"></script>

<!-- Utilidades adicionales -->
<script src="${staticsUrl}/rup/scripts/core/jquery.form.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.json-2.2.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/form2object.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.numeric.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jquery.url.js" type="text/javascript"></script>

<!-- Patrones RUP -->
<script src="${staticsUrl}/rup/scripts/rup.accordion-1.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.autocomplete-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.breadCrumb-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.combo-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.date-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.dialog-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.feedback-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.grid-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.lang-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.maint-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.menu-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.message-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tabs-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.time-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.toolbar-1.1.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tooltip-1.2.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.upload-1.2.1.js" type="text/javascript"></script>