package com.ejie.aa79b.service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;

import com.ejie.aa79b.model.ExpTareasResumen;
import com.ejie.aa79b.model.Gantt;
import com.ejie.aa79b.model.Tareas;
import com.ejie.aa79b.model.TareasTrabajo;
import com.ejie.x38.dto.JQGridRequestDto;
import com.ejie.x38.dto.JQGridResponseDto;

/**
 * CargaTrabajoService generated by UDA, 05-dic-2017 10:05:03.
 *
 * @author UDA
 */

public interface CargaTrabajoService extends GenericoService<ExpTareasResumen> {

	/**
	 * @param expTareasResumenFilter
	 * @param jqGridRequestDto
	 * @param b
	 * @return
	 */
	JQGridResponseDto<ExpTareasResumen> filtroExpTareas(ExpTareasResumen expTareasResumenFilter,
			JQGridRequestDto jqGridRequestDto, boolean b);

	Integer procComprobarEstadoTareasDependientes(final BigDecimal idTarea, final Long anyo, final Integer numExp);

	ExpTareasResumen findTarea(BigDecimal idTarea, String idioma);

	JQGridResponseDto<ExpTareasResumen> filtroTareasDependiente(ExpTareasResumen expTareasResumenFilter,
			JQGridRequestDto jqGridRequestDto, boolean startsWith);

	ExpTareasResumen updateEstadoAceptacion(ExpTareasResumen expTareasResumen);

	void insertObsrvRechazo(BigDecimal idTarea, String motivoRechazo);

	List<Gantt> getExpTareasGantt(ExpTareasResumen expTareasResumen, Locale locale);

	List<Gantt> getExpGantt(ExpTareasResumen expTareasResumen, Boolean tareas, Locale locale);

	List<Tareas> obtenerDatosTareas(String tareasSeleccionados);

	Long comprobarConflictoFechas(String[] listaIdTareas);

	/**
	 * Operacion de obtencion de ids de elementos seleccionados de RUP_TABLE.
	 *
	 * @param expTareasResumenFilter
	 *            ExpTareasResumen
	 * @param tableData
	 *            JQGridRequestDto
	 * @return List<ExpTareasResumen>
	 */
	List<ExpTareasResumen> filtroExpTareasGetSelectedIds(ExpTareasResumen expTareasResumenFilter,
			JQGridRequestDto tableData);

	/**
	 *
	 * @param expTareasResumenFilter ExpTareasResumen
	 * @param jqGridRequestDto JQGridRequestDto
	 * @param startsWith boolean
	 * @return JQGridResponseDto<ExpTareasResumen>
	 */
	JQGridResponseDto<ExpTareasResumen> filtroExpTareasTrabajo(ExpTareasResumen expTareasResumenFilter,
			JQGridRequestDto jqGridRequestDto, boolean startsWith);

	/**
	 *
	 * @param expTareasResumenFilter ExpTareasResumen
	 * @param jqGridRequestDto JQGridRequestDto
	 * @return List<ExpTareasResumen>
	 */
	List<ExpTareasResumen> filtroTareasTrabajoGetSelectedIds(ExpTareasResumen expTareasResumenFilter,
			JQGridRequestDto jqGridRequestDto);

	/**
	 *
	 * @param tareas TareasTrabajo
	 * @return Integer
	 */
	Integer updateEstadoAceptacionTareaTrabajo(TareasTrabajo tareas);

	/**
	 *
	 * @param idTarea BigDecimal
	 * @param motivoRechazo String
	 * @return Integer
	 */
	Integer insertObsrvRechazoTareaTrabajo(BigDecimal idTarea, String motivoRechazo);

	/**
	 *
	 * @param tareasSeleccionados String
	 * @return List<TareasTrabajo>
	 */
	List<TareasTrabajo> obtenerDatosTareasTrabajo(String tareasSeleccionados);


	String tieneTareasPendientes();

	String tieneTareasPendientesAsignador(ExpTareasResumen expTareasResumen);
}