package com.ejie.aa79b.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.common.DaoConstants;
import com.ejie.aa79b.dao.CategExpDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.RegistroAccionesDao;
import com.ejie.aa79b.model.CategExp;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.ListaCategExp;
import com.ejie.aa79b.model.ListaExpediente;
import com.ejie.aa79b.model.MetadatosExpedientes;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.model.enums.PuntosMenuEnum;
import com.ejie.aa79b.utils.ConsultaExpedienteUtils;

/**
 * CategExpServiceImpl generated by UDA, 08-mar-2018 10:51:54.
 *
 * @author UDA
 */

@Service(value = "categExpService")
public class CategExpServiceImpl extends GenericoServiceImpl<CategExp> implements CategExpService {

	@Autowired
	private CategExpDao categExpDao;
	@Autowired
	private RegistroAccionesDao registroAccionesDao;
	@Autowired()
	private ReloadableResourceBundleMessageSource msg;

	@Override
	protected GenericoDao<CategExp> getDao() {
		return this.categExpDao;
	}

	@Override
	public ListaCategExp comprobarYGuardarOEliminar(ListaCategExp listaCategExp) {
		// copiamos la lista pasada para modificarla
		List<CategExp> lista = new ArrayList<CategExp>();
		lista = listaCategExp.getListaCategExp();
		// Obtenemos los objetos guardados en BBDD del expediente
		CategExp categExpFilter = new CategExp();
		categExpFilter.setAnyo(listaCategExp.getListaCategExp().get(0).getAnyo());
		categExpFilter.setNumExp(listaCategExp.getListaCategExp().get(0).getNumExp());
		List<CategExp> listaBBDD = this.categExpDao.findAll(categExpFilter, null);
		// Recorremos la lista de BBDD
		for (CategExp categExpAuxBBDD : listaBBDD) {
			// si objeto a insertar esta en BBDD no hace falta guardarlo y lo
			// eliminamos de la lista de objetos a insertar
			if (estaEnLista(categExpAuxBBDD, lista)) {
				lista.remove(categExpAuxBBDD);
			} else {
				// Si hay objetos en BBDD que no estan en la lista a insertar
				// los eliminamos
				this.categExpDao.remove(categExpAuxBBDD);
			}
		}
		// Recorremos la lista a insertar. Como hemos eliminado los que ya
		// estaban en BBDD solo estaran los que hay que insertar
		for (CategExp categExpLista : lista) {
			this.categExpDao.add(categExpLista);
		}
		return listaCategExp;
	}

	public boolean estaEnLista(CategExp categExp, List<CategExp> lista) {
		for (CategExp categExpAux : lista) {
			if (categExp.getAnyo() == categExpAux.getAnyo() && categExp.getNumExp() == categExpAux.getNumExp()
					&& categExp.getIdMetadato() == categExpAux.getIdMetadato()) {
				return true;
			}
		}
		return false;
	}

	@Override
	public ListaCategExp eliminarAllCategExp(ListaCategExp listaCategExp) {
		CategExp categExpFilter = new CategExp();
		if (listaCategExp != null && !listaCategExp.getListaCategExp().isEmpty()) {
			categExpFilter.setAnyo(listaCategExp.getListaCategExp().get(0).getAnyo());
			categExpFilter.setNumExp(listaCategExp.getListaCategExp().get(0).getNumExp());
			this.categExpDao.eliminarAllCategExp(categExpFilter);
		}
		return listaCategExp;
	}

	@Override
	public Integer eliminarMetadatosDeExpedientes(ListaExpediente listaExpedientes) {
		return this.categExpDao.eliminarMetadatosDeExpedientes(listaExpedientes);
	}

	@Override
	public Integer eliminarMetadatosSeleccionadosDeExpedientes(MetadatosExpedientes metadatosExpedientes) {
		return this.categExpDao.eliminarMetadatosSeleccionadosDeExpedientes(metadatosExpedientes);
	}

	@Override
	public Integer guardarYOEliminarMetadatos(MetadatosExpedientes metadatosExpedientes) {
		Integer resul = this.categExpDao.guardarYOEliminarMetadatos(metadatosExpedientes);
		// Registro de acciones...
		List<RegistroAcciones> listaRegistro = new ArrayList<RegistroAcciones>();
		if (ConsultaExpedienteUtils.listaExpedientesValida(metadatosExpedientes.getListaExpedientes())) {

			Locale locale = new Locale(Constants.LANG_EUSKERA);
			for (Expediente expediente : metadatosExpedientes.getListaExpedientes().getListaExpediente()) {
				RegistroAcciones regAcciones = new RegistroAcciones();
				regAcciones.setIdPuntoMenu(PuntosMenuEnum.CATEGORIZACION_EXPEDIENTES.getValue());
				regAcciones.setIdAccion(Constants.ACCION_MODIFICACION);
				regAcciones.setAnyo(expediente.getAnyo());
				regAcciones.setNumExp(expediente.getNumExp());
				StringBuilder observ = new StringBuilder();
				observ.append(this.msg.getMessage("label.categorizacionExpediente.observaciones", null, locale));
				if (ConsultaExpedienteUtils.listaMetadatosValida(metadatosExpedientes.getListaMetadatos())) {
					boolean esPrimero = true;
					for (CategExp categExp : metadatosExpedientes.getListaMetadatos().getListaCategExp()) {
						if (!esPrimero) {
							observ.append(DaoConstants.SIGNO_COMA);
						} else {
							esPrimero = false;
						}
						observ.append(categExp.getIdMetadato());
					}
				}
				regAcciones.setObserv(observ.toString());
				listaRegistro.add(regAcciones);

			}
			this.registroAccionesDao.addBatch(listaRegistro);
		}
		return resul;
	}

}
