package com.ejie.aa79b.service;

import com.ejie.aa79b.model.DocumentoTarea;
import com.ejie.aa79b.model.DocumentosCorreccion;

/**
 * DocumentosCorreccionService generated by UDA, 01-abr-2019 15:51:21.
 * 
 * @author UDA
 */

public interface DocumentosCorreccionService extends GenericoService<DocumentosCorreccion> {

	/**
	 * obtiene el idFichero y los datos relativos al documento de correccion
	 * 
	 * @param docCorreccion
	 *            DocumentosCorreccion
	 * @return DocumentoTarea
	 */
	DocumentoTarea getDocumentoCorreccion(DocumentosCorreccion docCorreccion);

}
