package com.ejie.aa79b.service;

import java.util.List;

import com.ejie.aa79b.model.EstadosExpediente;

/**
 * EstadosExpedienteService generated by UDA, 02-feb-2018 10:27:12.
 * 
 * @author UDA
 */

public interface EstadosExpedienteService extends GenericoService<EstadosExpediente> {

	/**
	 * Obtiene el listado de estados del expediente
	 * 
	 * @return List<EstadosExpediente>
	 */
	List<EstadosExpediente> findAllEstadosExp(Long idEstadoExp, String tipoExp);

	/**
	 * Obtiene el listado de estados del expediente, excepto el estado alta de
	 * expediente.
	 * 
	 * @return List<EstadosExpediente>
	 */
	List<EstadosExpediente> findAllSinAltaExp();

	/**
	 * obtiene los estados de expediente que coincidan con los ids pasados como
	 * parametro
	 * 
	 * @param listaEstados List<Integer>
	 * @return List<EstadosExpediente>
	 */
	List<EstadosExpediente> getEstados(List<Integer> listaEstados);

	/**
	 * Obtiene el listado de estados del expediente
	 * 
	 * @param idEstadoExp Long
	 * @param idfaseExp   Long
	 * @param tipoExp     String
	 * @return List<EstadosExpediente>
	 */
	List<EstadosExpediente> findAllEstadosExp(Long idEstadoExp, Long idfaseExp, String tipoExp);

}