package com.ejie.aa79b.service;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;

import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.dao.DatosContactoDao;
import com.ejie.aa79b.dao.DatosFacturacionExpedienteDao;
import com.ejie.aa79b.dao.ExpedienteDao;
import com.ejie.aa79b.dao.ExpedienteTradRevDao;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.GestorExpedienteDao;
import com.ejie.aa79b.mail.MailService;
import com.ejie.aa79b.model.DatosContacto;
import com.ejie.aa79b.model.EntradaFechaFinalizacion;
import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.ExpedienteTradRev;
import com.ejie.aa79b.model.GestorExpediente;
import com.ejie.aa79b.model.ParametrosEmail;
import com.ejie.aa79b.model.SubsanacionExpediente;
import com.ejie.aa79b.model.enums.TipoAvisoEnum;
import com.ejie.aa79b.webservices.EventosService;


/**
 * ExpedienteTradRevServiceImpl generated by UDA, 31-ene-2018 15:08:48.
 *
 * @author UDA
 */

@Service(value = "expedienteTradRevService")
public class ExpedienteTradRevServiceImpl extends GenericoServiceImpl<ExpedienteTradRev>
		implements ExpedienteTradRevService {

	@Autowired
	private ExpedienteTradRevDao expedienteTradRevDao;

	@Autowired
	private DatosFacturacionExpedienteDao datosFacturacionExpedienteDao;

	@Autowired
	private ExpedienteDao expedienteDao;

	@Autowired
	private GestorExpedienteDao gestorExpedienteDao;

	@Autowired
	private DatosContactoDao datosContactoDao;

	@Autowired()
	private Properties appConfiguration;

	@Autowired()
	private ReloadableResourceBundleMessageSource appMessageSource;

	@Autowired()
	private MailService mailService;

	@Autowired()
	private EventosService eventosService;

	private static final Logger LOGGER = LoggerFactory.getLogger(ExpedienteTradRevServiceImpl.class);

	private static final String WSDL = "webservice.evento.wsdl";
	private static final String NAME_SPACE_URI = "qname.evento.namespaceURI";
	private static final String LOCAL_PART = "qname.evento.localpart";

	@Override
	protected GenericoDao<ExpedienteTradRev> getDao() {
		return this.expedienteTradRevDao;
	}

	@Override
	@Transactional(rollbackFor = Throwable.class)
	public void actualizarNumPalSolicConIzo(Long anyo, Integer numExp) {
		this.expedienteTradRevDao.actualizarNumPalSolicConIzo(anyo, numExp);
	}

	@Override
	@Transactional(rollbackFor = Throwable.class)
	public void actualizarSumaNumTotalPalIzo(Long anyo, Integer numExp) {
		this.expedienteTradRevDao.actualizarSumaNumTotalPalIzo(anyo, numExp);
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public void procRecalcularCamposDocumentacionPL(Long anyo, Integer numExp) {
		this.expedienteTradRevDao.procRecalcularCamposDocumentacionPL(anyo, numExp);
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public void procAsociarDocAEntregaPL(Long anyo, Integer numExp, BigDecimal idDoc) {
		this.expedienteTradRevDao.procAsociarDocAEntregaPL(anyo, numExp, idDoc);
	}

	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ExpedienteTradRev guardarParcial(ExpedienteTradRev expedienteTradRev) {
		ExpedienteTradRev expedTradRevAux = this.expedienteTradRevDao.getFechaIzo(expedienteTradRev);
		if (this.compararFechaHoraIzo(expedienteTradRev, expedTradRevAux)
        		&& this.appConfiguration.getProperty(Constants.APP_ENTORNO) != null) {
			Expediente exp = new Expediente();
			exp.setAnyo(expedienteTradRev.getAnyo());
			exp.setNumExp(expedienteTradRev.getNumExp());
			exp = this.expedienteDao.getOrigenExpediente(exp);
			if(StringUtils.isNotBlank(exp.getOrigen()) && exp.getOrigen().equals("W")) {
				ExpedienteTradRevServiceImpl.LOGGER.info("ExpedienteTradRevServiceImpl.createInvoiceCambioFecha");
				expedTradRevAux = this.expedienteTradRevDao.find(expedienteTradRev);
    			expedienteTradRev.setRefTramitagune(expedTradRevAux.getRefTramitagune());
				this.eventosService.createInvoiceCambioFecha(expedienteTradRev, exp);
			}
		}
		return this.expedienteTradRevDao.guardarParcial(expedienteTradRev);
	}

	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ExpedienteTradRev guardarFFinalIzo(ExpedienteTradRev expedienteTradRev) {
		return this.expedienteTradRevDao.guardarFFinalIzo(expedienteTradRev);
	}

	@Override
	@Transactional(rollbackFor = Throwable.class)
	public ExpedienteTradRev guardarParcialPlanificacion(ExpedienteTradRev expedienteTradRev, String idioma) {
        ExpedienteTradRev expedTradRevAux = this.expedienteTradRevDao.getFechaIzo(expedienteTradRev);
		// Update tabla 53
		this.expedienteTradRevDao.guardarParcial(expedienteTradRev);
		if (expedienteTradRev.getAceptacionPresupuesto() != null
				&& expedienteTradRev.getAceptacionPresupuesto().getFechaLimite() != null) {
			// Update tabla 64 y adicion en bitacora
			this.expedienteTradRevDao.updateDatosAceptacionPpto(expedienteTradRev, idioma);
		}
		if (expedienteTradRev.getAceptacionFechaHora() != null
				&& expedienteTradRev.getAceptacionFechaHora().getFechaLimite() != null) {
			// Update tabla 64 y adicion en bitacora
			this.expedienteTradRevDao.updateDatosAceptacionFechaHora(expedienteTradRev, idioma);
		}
        if (this.compararFechaHoraIzo(expedienteTradRev, expedTradRevAux)
        		&& this.appConfiguration.getProperty(Constants.APP_ENTORNO) != null) {

        	//  enviar email
        	ExpedienteTradRevServiceImpl.LOGGER.info("************************** Proceso de envio de email - INICIO **************************");
       		List<String> listaDestinatarios = new ArrayList<String>();
       		DatosContacto datosContacto = new DatosContacto();
       		GestorExpediente gestorExpediente = this.gestorExpedienteDao.getDniSolicitante(expedienteTradRev);
        	datosContacto.setDni031(gestorExpediente.getSolicitante().getDni());
        	datosContacto = this.datosContactoDao.findDatosContacto(datosContacto);
        	if (datosContacto != null && StringUtils.isNotBlank(datosContacto.getEmail031())) {
        		listaDestinatarios.add(datosContacto.getEmail031());
        		ExpedienteTradRevServiceImpl.LOGGER.info("entorno: " + this.appConfiguration.getProperty(Constants.APP_ENTORNO));
        		ParametrosEmail parametrosEmail = new ParametrosEmail();
        		Locale localeEu = new Locale(Constants.LANG_EUSKERA);
        		Map<String, String> infoEu = new LinkedHashMap<String, String>();
        		Locale localeEs = new Locale(Constants.LANG_CASTELLANO);
        		Map<String, String> infoEs = new LinkedHashMap<String, String>();
        		parametrosEmail.setAnyoNumExpediente(expedienteTradRev.getAnyoNumExpConcatenado());
        		infoEu.put(this.appMessageSource.getMessage(Constants.LABEL_NUM_EXP, null, localeEu),
        				Constants.ESPACIO + expedienteTradRev.getAnyoNumExpConcatenado() + Constants.ESPACIO);
        		infoEu.put(this.appMessageSource.getMessage(Constants.LABEL_FECHA_FIN_IZO_NUEVA, null, localeEu),
        				Constants.ESPACIO + expedienteTradRev.getFechaHoraFinalIZO());
        		infoEs.put(this.appMessageSource.getMessage(Constants.LABEL_NUM_EXP, null, localeEs),
        				 Constants.ESPACIO + expedienteTradRev.getAnyoNumExpConcatenado() + Constants.ESPACIO);
        		infoEs.put(this.appMessageSource.getMessage(Constants.LABEL_FECHA_FIN_IZO_NUEVA, null, localeEs),
        				Constants.ESPACIO + expedienteTradRev.getFechaHoraFinalIZOEs());
        		parametrosEmail.setInfoEu(infoEu);
        		parametrosEmail.setInfoEs(infoEs);
        		try {
        			this.mailService.sendMailWithParameters(TipoAvisoEnum.CAMBIO_FECHA_FINALIZACION_IZO.getValue(),
        				listaDestinatarios, parametrosEmail);
        		} catch (Exception e) {
        			ExpedienteTradRevServiceImpl.LOGGER.info("Error en el envío de email", e);
        		}
        	} else {
        		ExpedienteTradRevServiceImpl.LOGGER.info("No hay destinatarios", listaDestinatarios);
        	}
        	ExpedienteTradRevServiceImpl.LOGGER.info("************************** Proceso de envio de email - FIN **************************");
        	Expediente exp = new Expediente();
    		exp.setAnyo(expedienteTradRev.getAnyo());
    		exp.setNumExp(expedienteTradRev.getNumExp());
    		exp = this.expedienteDao.getOrigenExpediente(exp);
    		if(StringUtils.isNotBlank(exp.getOrigen()) && exp.getOrigen().equals("W")) {
    			ExpedienteTradRevServiceImpl.LOGGER.info("ExpedienteTradRevServiceImpl.createInvoiceCambioFecha");
    			expedTradRevAux = this.expedienteTradRevDao.find(expedienteTradRev);
    			expedienteTradRev.setRefTramitagune(expedTradRevAux.getRefTramitagune());
    			this.eventosService.createInvoiceCambioFecha(expedienteTradRev, exp);
    		}
        }

		return expedienteTradRev;
	}

	private boolean compararFechaHoraIzo(ExpedienteTradRev expedienteTradRev, ExpedienteTradRev expedTradRevAux) {
		SimpleDateFormat formato;
		formato = new SimpleDateFormat(Constants.JAVA_DATE_FORMAT_ES);
        if (expedTradRevAux.getFechaFinalIzo() != null &&
                expedienteTradRev.getFechaFinalIzo() != null &&
                StringUtils.isNotBlank(expedTradRevAux.getHoraFinalIzo()) &&
                StringUtils.isNotBlank(expedienteTradRev.getHoraFinalIzo())) {
            return !formato.format(expedTradRevAux.getFechaFinalIzo()).equals(formato.format(expedienteTradRev.getFechaFinalIzo())) ||
                    !expedTradRevAux.getHoraFinalIzo().equals(expedienteTradRev.getHoraFinalIzo());
        }
        return false;
	}

	@Override()
	public ExpedienteTradRev findConDatosFacturacion(ExpedienteTradRev expedienteTradRev) {

		ExpedienteTradRev expedienteTradRevAux = this.expedienteTradRevDao.find(expedienteTradRev);
		ExpedienteTradRev expedienteTradRevAux2 = this.datosFacturacionExpedienteDao.find(expedienteTradRev);
		if (expedienteTradRevAux2 != null) {
			expedienteTradRevAux.setDatosFacturacionExpediente(expedienteTradRevAux2.getDatosFacturacionExpediente());
		}

		// acept rechazo de ppto y f entrega
		SubsanacionExpediente subsanacionExpediente = this.expedienteTradRevDao
				.findDatosEstadoPresupuesto(expedienteTradRev);
		if (subsanacionExpediente != null) {
			expedienteTradRevAux.setAceptacionPresupuesto(subsanacionExpediente);
		}
		// Negociación nueva fecha/hora entrega
		SubsanacionExpediente subsanacionExpedienteNegociarFecha = this.expedienteTradRevDao
				.findDatosNegociacionFecha(expedienteTradRev);
		if (subsanacionExpedienteNegociarFecha != null) {
			expedienteTradRevAux.setAceptacionFechaHora(subsanacionExpedienteNegociarFecha);
		}

		return expedienteTradRevAux;
	}

	@Override
	@Transactional(rollbackFor = Throwable.class)
	public void actualizarT53ConfidencialSI(Long anyo, Integer numExp) {
		this.expedienteTradRevDao.actualizarT53ConfidencialSI(anyo, numExp);
	}

	@Override
	public Date calcularFechaPropuesta(String tipoExp, Integer numPalIzo, String indPresupuesto, String indVip) {
		EntradaFechaFinalizacion entradaFechaFinalizacion = new EntradaFechaFinalizacion();
		entradaFechaFinalizacion.setTipoExpediente(tipoExp);
		entradaFechaFinalizacion.setNumPalabras(numPalIzo);
		entradaFechaFinalizacion.setIndPresupuesto(indPresupuesto);
		return this.expedienteDao.llamadaFncObtenerPlazoMinEntrega(entradaFechaFinalizacion, indVip);
	}
}