package com.ejie.aa79b.service;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.common.Constants;
import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.GruposTrabajoDao;
import com.ejie.aa79b.dao.PersonalIZODao;
import com.ejie.aa79b.dao.RegistroAccionesDao;
import com.ejie.aa79b.model.GruposTrabajo;
import com.ejie.aa79b.model.RegistroAcciones;
import com.ejie.aa79b.utils.Utils;

/**
 * GruposTrabajoServiceImpl generated by UDA, 24-nov-2017 10:10:29.
 * @author UDA
 */

@Service(value = "gruposTrabajoService")
public class GruposTrabajoServiceImpl extends GenericoServiceImpl<GruposTrabajo> implements GruposTrabajoService {

	@Autowired()
	private GruposTrabajoDao gruposTrabajoDao;

	@Autowired()
	private RegistroAccionesDao registroAccionesDao;
    @Autowired()
    private ReloadableResourceBundleMessageSource msg;
    @Autowired()
    private PersonalIZODao personalIZODao;

	@Override()
	protected GenericoDao<GruposTrabajo> getDao() {
		return this.gruposTrabajoDao;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public GruposTrabajo add(GruposTrabajo bean) {
		this.gruposTrabajoDao.add(bean);
		bean.setResponsable(this.personalIZODao.find(bean.getResponsable()));
		this.personalIZODao.guardarFoto(bean.getResponsable());
		
		RegistroAcciones regGruposTrabajo = new RegistroAcciones();
		regGruposTrabajo.setIdPuntoMenu(Constants.PUNTO_MENU_GESTION_GRUPOS);
		regGruposTrabajo.setIdAccion(Constants.ACCION_ALTA);
		Map<String, String> paramGruposTrabajoAlta = new LinkedHashMap<String, String>();
		paramGruposTrabajoAlta.put("tipoExpedienteDesc", "label.tipoExpediente");
		paramGruposTrabajoAlta.put("descEu", "label.descripcionEus");
		paramGruposTrabajoAlta.put("responsable.nombreCompleto", "label.responsable");
		paramGruposTrabajoAlta.put("bopvDesc", "label.bopv");
		paramGruposTrabajoAlta.put("previstoBopvDesc", "label.previstoBopv");
		paramGruposTrabajoAlta.put("palabrasDesde", "label.rangoPalabrasDesde");
		paramGruposTrabajoAlta.put("palabrasHasta", "label.rangoPalabrasHasta");
		paramGruposTrabajoAlta.put("estadoDesc", "label.estado");
		Locale locale = new Locale(Constants.LANG_EUSKERA);
		this.rellenarDescripciones(bean, locale);
		String aux = Utils.observacionesRegistro(bean, null, paramGruposTrabajoAlta, this.msg, locale);
		if (StringUtils.isNotBlank(aux)) {
			regGruposTrabajo.setObserv(aux);
			this.registroAccionesDao.add(regGruposTrabajo);
		}
		return bean;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public GruposTrabajo update(GruposTrabajo bean) {
		GruposTrabajo original = this.gruposTrabajoDao.find(bean);
		this.gruposTrabajoDao.update(bean);
		bean.setResponsable(this.personalIZODao.find(bean.getResponsable()));
		this.personalIZODao.guardarFoto(bean.getResponsable());
		
		if (Constants.SI.equals(bean.getIndBopv()) || Constants.SI.equals(bean.getIndPrevistoBopv())) {
			this.gruposTrabajoDao.borrarEntidadesAsociadas(bean);
		}
		
		RegistroAcciones regGruposTrabajo = new RegistroAcciones();
		regGruposTrabajo.setIdPuntoMenu(Constants.PUNTO_MENU_GESTION_GRUPOS);
		regGruposTrabajo.setIdAccion(Constants.ACCION_MODIFICACION);
		Map<String, String> paramGruposTrabajo = new LinkedHashMap<String, String>();
		paramGruposTrabajo.put("tipoExpedienteDesc", "label.tipoExpediente");
		paramGruposTrabajo.put("descEu", "label.descripcionEus");
		paramGruposTrabajo.put("responsable.nombreCompleto", "label.responsable");
		paramGruposTrabajo.put("bopvDesc", "label.bopv");
		paramGruposTrabajo.put("previstoBopvDesc", "label.previstoBopv");
		paramGruposTrabajo.put("palabrasDesde", "label.rangoPalabrasDesde");
		paramGruposTrabajo.put("palabrasHasta", "label.rangoPalabrasHasta");
		paramGruposTrabajo.put("estadoDesc", "label.estado");
		Locale locale = new Locale(Constants.LANG_EUSKERA);
		this.rellenarDescripciones(bean, locale);
		this.rellenarDescripciones(original, locale);
		String aux = Utils.observacionesRegistro(bean, original, paramGruposTrabajo, this.msg, locale);
		if (StringUtils.isNotBlank(aux)) {
			regGruposTrabajo.setObserv(aux);
			this.registroAccionesDao.add(regGruposTrabajo);
		}
		return bean;
	}
	
	private void rellenarDescripciones(GruposTrabajo bean, Locale locale) {
		bean.setTipoExpedienteDesc(Utils.literalTipoExpediente(this.msg, bean.getIdTipoExpediente(), locale));
		bean.setBopvDesc(Utils.literalSiNo(this.msg, bean.getIndBopv(), locale));
		bean.setPrevistoBopvDesc(Utils.literalSiNo(this.msg, bean.getIndPrevistoBopv(), locale));
		bean.setEstadoDesc(Utils.literalEstado(this.msg, bean.getEstado(), locale));
	}

	@Override()
	public List<GruposTrabajo> findAllLikeResponsable(GruposTrabajo filter) {
		return this.gruposTrabajoDao.findAllLikeResponsable(filter);
	}
	
	@Override()
	public List<GruposTrabajo> findAllLikeEntidad(GruposTrabajo filter) {
		return this.gruposTrabajoDao.findAllLikeEntidades(filter);
	}
	
	@Override()
	public Long countExiste(GruposTrabajo gruposTrabajo) {
		return this.gruposTrabajoDao.countExiste(gruposTrabajo);
	}

	@Override
	public GruposTrabajo informarCamposGrupoTrabajo(GruposTrabajo gruposTrabajo) {
		return this.gruposTrabajoDao.informarCamposGrupoTrabajo(gruposTrabajo);
	}

	@Override
	public List<GruposTrabajo> findAllLikeGruposTrabajo(GruposTrabajo gruposTrabajo) {
		return this.gruposTrabajoDao.findAllLikeGruposTrabajo(gruposTrabajo);
	}
	
}

