package com.ejie.aa79b.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.MotivosrechazoDao;
import com.ejie.aa79b.model.Motivosrechazo;

/**
 * MotivosrechazoServiceImpl generated by UDA, 16-nov-2017 12:15:13.
 * @author UDA
 */

@Service(value = "motivosrechazoService")
public class MotivosrechazoServiceImpl extends GenericoServiceImpl<Motivosrechazo> implements MotivosrechazoService {

	@Autowired
	private MotivosrechazoDao motivosrechazoDao;

	@Override
	protected GenericoDao<Motivosrechazo> getDao(){
		return this.motivosrechazoDao;
	}

}

