package com.ejie.aa79b.service;

import java.util.List;

import com.ejie.aa79b.model.NivelesDeCalidad;

/**
 * NivelesDeCalidadService generated by UDA, 24-nov-2017 13:50:22.
 * 
 * @author UDA
 */

public interface NivelesDeCalidadService extends GenericoService<NivelesDeCalidad> {

	public boolean comprobarRango(NivelesDeCalidad bean);

	public List<NivelesDeCalidad> getAllOrdered(NivelesDeCalidad bean);

	public boolean comprobarNivel(NivelesDeCalidad bean);

}
