package com.ejie.aa79b.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ejie.aa79b.dao.GenericoDao;
import com.ejie.aa79b.dao.NivelesDeCalidadDao;
import com.ejie.aa79b.model.NivelesDeCalidad;

/**
 * TiposInterpretacionServiceImpl generated by UDA, 24-nov-2017 13:50:22.
 * 
 * @author UDA
 */

@Service(value = "nivelesDeCalidadService")
public class NivelesDeCalidadServiceImpl extends GenericoServiceImpl<NivelesDeCalidad>
		implements NivelesDeCalidadService {

	@Autowired
	private NivelesDeCalidadDao nivelesDeCalidadDao;

	@Override
	protected GenericoDao<NivelesDeCalidad> getDao() {
		// TODO Auto-generated method stub
		return this.nivelesDeCalidadDao;
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public NivelesDeCalidad update(NivelesDeCalidad bean) {
		return this.nivelesDeCalidadDao.update(bean);
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public boolean comprobarRango(NivelesDeCalidad bean) {
		return this.nivelesDeCalidadDao.comprobarRango(bean);
	}

	@Override()
	@Transactional(rollbackFor = Throwable.class)
	public List<NivelesDeCalidad> getAllOrdered(NivelesDeCalidad bean) {
		return this.nivelesDeCalidadDao.getAllOrdered(bean);
	}

	public boolean comprobarNivel(NivelesDeCalidad bean) {
		return this.nivelesDeCalidadDao.comprobarNivel(bean);
	}
}
