package com.ejie.aa79b.service;

import com.ejie.aa79b.model.Expediente;
import com.ejie.aa79b.model.ObservacionesExpediente;

/**
 * ObservacionesExpedienteService generated by UDA, 06-feb-2018 8:28:55.
 * @author UDA
 */

public interface ObservacionesExpedienteService extends GenericoService<Expediente> {
    /**
     * busca las observaciones de un expediente
     *
     * @param Expediente
     *            expediente
     * @return ObservacionesExpediente
     */
    ObservacionesExpediente observacionesFind(Expediente expediente);

}


